### ISSUE TITLE
Conky 1.10.0 fails to compile without these patches, please commit...

### ISSUE THREAD

**Issue by ghost** [brndnmtthws/conky#100]
Hi,

I found these patches from Arch, but noticed on my distro I can't compile conky also unless I use these patches;

https://projects.archlinux.org/svntogit/packages.git/tree/trunk/ascii.patch?h=packages/conky

https://projects.archlinux.org/svntogit/packages.git/tree/trunk/lua53.patch?h=packages/conky

I hope you'll please commit these, otherwise conky fails to compile on some distros.

On my system without the `ascii.patch` I'll get this error at compile time;

[  6%] Proccessing man page for docs
/usr/bin/iconv: illegal input sequence at position 7845
/usr/bin/db2x_manxml: program in pipeline exited with an error
make[2]: **\* [../doc/docs.html] Error 1
make[1]: **\* [doc/CMakeFiles/docs.dir/all] Error 2
make: **\* [all] Error 2

On my system without the `lua53.patch` I'll get this error at compile time;

[ 58%] Building CXX object src/CMakeFiles/conky.dir/luamm.cc.o
In file included from /usr/include/lua.hpp:6:0,
                 from /tmp/foo/conky-1.10.0/src/luamm.hh:30,
                 from /tmp/foo/conky-1.10.0/src/luamm.cc:24:
/tmp/foo/conky-1.10.0/src/luamm.cc: In member function ‘void lua::state::gettable(int)’:
/tmp/foo/conky-1.10.0/src/luamm.cc:370:3: error: no matches converting function ‘safe_misc_trampoline’ to type ‘lua_CFunction {aka int (_)(struct lua_State_)}’
   lua_pushcfunction(cobj.get(), (&safe_misc_trampoline<&lua_gettable, 1>));
   ^
/tmp/foo/conky-1.10.0/src/luamm.cc:168:7: note: candidate is: template<void (* misc)(lua_State*, int), int nresults> int lua::{anonymous}::safe_misc_trampoline(lua_State_)
   int safe_misc_trampoline(lua_State *l)
       ^
make[2]: *_\* [src/CMakeFiles/conky.dir/luamm.cc.o] Error 1
make[1]: **\* [src/CMakeFiles/conky.dir/all] Error 2
make: **\* [all] Error 2

**Comment by marcpayne** [comment]
Fixed by #137 and #138, so this issue can be closed.
