### ISSUE TITLE
Display html/css rendered page/snippet in Conky

### ISSUE THREAD

**Issue by wakatara** [brndnmtthws/conky#1000]
**Issue**

I am trying to coax Conky into "simply" using the root X window to displaying a html/css rendered file/output at all times (basically a desktop overlay).

**Information**

Conky version 1.10.8
POPOS 20.04 running gnome (but would also like it to work on i3)

I am finding it difficult ot determine how to do this (and also was trying to understand what happened to gtk-python-info since it seems that that package did this but was then incorporated into Conky.at some point.).

Apologies if this is an easy question to answer. I spent quite a bit of time googling, and while my google-fu may not be Master level, it was almost impossible after hunting for quite a hour or so how someone may accomplish this with Conky (though there are other unmaintained projects that purport to be able to do this.).

For more context, I am trying to accomplish in Conky in Linux what I accmplished with Ubersicht in OSX as outlined in this blog post of mine:
https://daryl.wakatara.com/productivity-buckets-reviews-and-visibility

*(head to bottom of post for screenshot, but effectively, take an org file, export it through pandoc to html and then display that on the desktop.).*

![Desktop effect](https://daryl.wakatara.com/images/2020-05-19-001-ubersicht-7+1-desktop.7c510cb739c9c44d117021b9f1ed20ec72cd9f8016b280eb1e02bb39fac86332.png)

**Comment by su8** [comment]
U cant do it in conky
