### ISSUE TITLE
Conky CPU usage rises with time reaching 10% in 36 hours

### ISSUE THREAD

**Issue by vexillia** [brndnmtthws/conky#1006]
**Issue**

Conky CPU usage rises with time reaching 10% in 36 hours.  CPU usage can be lowered by switching script off and restarting.

**Information**

Xubuntu 20.04 with xcfe 4.14

Please delete all descriptions, unused headers, notes, sections, etc too. Thank you.

**Comment by rizlaw** [comment]
I've noticed similar behavior with Ubuntu 20.04LTS, but only when using the built-in Conky "Audacious" music player variables. I never got to 10% CPU usage, but I've seen 3 - 4 %. Without "Audacious" code, Conky stays below 1% much of the time.
