### ISSUE TITLE
[Question] How to have conky on all kde workspaces ?

### ISSUE THREAD

**Issue by sebma** [brndnmtthws/conky#1008]
How to have conky on all kde workspaces ?

**Comment by su8** [comment]
Làúñçh çóñkÿ fróm thé térmíñàl íñ thé deßíréd wórkßpàçé

**Comment by sebma** [comment]
The `own_window_type = 'desktop'` should be the answer but that doesn't see issue #665

**Comment by whtyger** [comment]
In my case the next code works and places Conky on every workspace:

    own_window_type = 'normal',
    own_window_hints = 'undecorated,below,skip_taskbar,sticky',

`sticky` hint is the one which is responsible for that.

**Comment by sebma** [comment]
> own_window_type = 'normal',
> own_window_hints = 'undecorated,below,skip_taskbar,sticky',

@whtyger That does not work on all workspaces. I use `conky-all` package from Ubuntu 20.04 LTS.

**Comment by whtyger** [comment]
@sebma Package type shouldn't be the cause of this issue.  
These lines were taken from working Conky v1.10.8 configuration. I was using `conky-std` package from Kubuntu 20.04.  
What is the output of the command `xprop _NET_WM_STATE` when you run it in the terminal and click on conky's window? Does it show all prescribed hints?
In my configuration it shows:
> _NET_WM_STATE(ATOM) = _NET_WM_STATE_BELOW, _NET_WM_STATE_STICKY, _NET_WM_STATE_SKIP_TASKBAR

I.e. all hints are applied properly.

**Comment by sebma** [comment]
@whtyger I use `conky-all` `v1.10.8-1build3` on KUbuntu 20.04.5 and I get this `xprop` output : 
```shell
$ xprop _NET_WM_STATE
_NET_WM_STATE(ATOM) = _NET_WM_STATE_BELOW, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_SKIP_PAGER
$
```

**Comment by whtyger** [comment]
@sebma As you can see, in your case _NET_WM_STATE_STICKY is missing from the list of applied hints. If it isn't a typo in your config, you can try to force sticky position to Conky window using KWin.
Run `System Settings`, select `Window Management | Window Rules`. Press <kbd>New...</kbd> to add new rule, on the first tab "Window matching" set `Window class | Exact Match: conky`. Fill in `Description` field.
On the second tab "Size & Position" activate `Desktop` checkmark, choose `Force` action and select `All Desktops`. Press <kbd>OK</kbd> to close the window, then <kbd>Apply</kbd> to activate the new rule.

**Comment by mmuman** [comment]
For the record, I have this in my Conky config and it does display on all workspaces in KDE, and I don't have any specific KWin setup:

```
conky.config = {
	--lua_load = 'sgtest.lua',
    alignment = 'bottom_left',
    background = false,
    border_width = 1,
    cpu_avg_samples = 2,
	default_color = '409090',--'lightgrey',
    default_outline_color = 'white',
    default_shade_color = 'darkcyan',
    color0 = 'a0c0c0',--'lightcyan',
    color1 = '429286',--'darkcyan',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = true,
    use_xft = true,
	--xftalpha = 0.5,
    -- misses : and , : font = 'Times New Ancient:size=16',
    --font = 'Anquietas:size=14',
    font = 'Ancient G Modern:size=14',
    default_bar_height = 12,
    gap_x = 100,
    --gap_x = 1980,
    gap_y = 60,
    minimum_height = 5,
	minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_stderr = false,
    extra_newline = false,
    -- -- This Works in Gnome-shell
    --own_window = true,
    --own_window_class = 'Conky',
    --own_window_type = 'desktop',
    ----own_window_transparent = true,
    ---- fixes issue with Metacity with compositing
    ---- cf. https://wenlong.wordpress.com/2011/05/03/conky-true-transparency/
    --own_window_argb_visual = true,
    --own_window_argb_value = 0,
    -- Works in KDE Plasma with transparency
    own_window = true,
    own_window_class = 'default',
    own_window_type = 'default',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 0,
    own_window_hints = 'undecorated,below,skip_taskbar,skip_pager,sticky',
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    show_graph_scale = false,
    show_graph_range = false
}
```
