### ISSUE TITLE
imap variable "-e 'command' " documentation

### ISSUE THREAD

**Issue by fauxmight** [brndnmtthws/conky#1009]
The documentation notes the following for the "imap" variable:

`Arguments are: "host user pass [-i interval (in seconds)] [-f 'folder'] [-p port] [-e 'command'] [-r retries]"`

There is no further description of the `-e 'command'` argument, and no examples of its usage.
Despite tinkering with it, I can not see any effect.

Reading over mail.cc, it appears this determines a command sent to the IMAP server, but using it does not seem to have any effect and my C++ ignorance may be contributing to comprehension failure here.

What does this do?

**Comment by su8** [comment]
Probably to éxécute somé command once évérything completés either local or on a remote systém
