### ISSUE TITLE
1.10.0 Double buffer not working, screen flicker

### ISSUE THREAD

**Issue by Geyup** [brndnmtthws/conky#101]
Hi,

I have Nvidia GTX 660M GPU, using  nvidia-driver-346.59 and in 1.9.0 conky works good, but I noticed in 1.10.0 the double buffer does not seem to work, conky flickers every few seconds.

This is my config;

conky.config = {
override_utf8_locale = false,
background = true,
use_xft = true,
font = 'aller:size=9',
xftalpha = 0.8,
out_to_console = false,
update_interval = 3.0,
total_run_times = 0,
draw_shades = false,

own_window = true,
own_window_class = 'Conky',
own_window_type = 'desktop',    -- normal /override /desktop /dock
own_window_transparent = true,
own_window_hints = 'undecorated,sticky,skip_taskbar,skip_pager,below',

-- Prevent Conky refresh over itslef in tile wms 
-- true - true transparency with compton 
-- false - pseudo-transparency without compton
own_window_argb_visual = true,

minimum_size = 1920,
maximum_width = 1920,

double_buffer = true,
default_color = 'e3412c',
color1 = 'e0cdc3',

alignment = 'top_middle',
gap_y = 5, --vertical
--gap_x = 0, --horizontal
no_buffers = true
}

conky.text = [[
${alignc}${color}CPU1: ${color1}${cpu cpu0}%   \
${color}CPU2: ${color1}${cpu cpu1}%   \
${color}CPU3: ${color1}${cpu cpu2}%   \
${color}CPU4: ${color1}${cpu cpu3}% - ${freq}MHz - ${hwmon 0 temp 1} °C   \
${color}GPU: ${color1}${execi 100 nvidia-settings -q gpucoretemp -t | head -1} °C   \
${color}RAM: ${color1}${mem} - $memperc%   \
${color}SSD: ${color1}${fs_free /} free   \
${color}LAN: ${color1}${addr eth0} - ${downspeed eth0} kb/s down - ${upspeed eth0} kb/s up   \
${color}POWER: ${color1}${acpiacadapter AC0}  -  ${color}BATTERY: ${color1}${execi 1 ~/.conky/scripts/battery.sh}  \
${color}UP: ${color1}$uptime_short
${execi 70 ~/.conky/scripts/battery_notify.sh}
]]

**Comment by marcpayne** [comment]
Double buffering is disabled by default in 1.10.0, it seems. You might have to file a packaging bug with your distro and ask for the cmake option `BUILD_XDBE` to be enabled.

**Comment by Geyup** [comment]
Sorry for any misunderstanding, I'm saying I have it enabled at compile time.

These are my compile flags;

```
mkdir build
cd build
cmake .. \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_CURL=ON \
    -DBUILD_XDBE=ON \
    -DBUILD_IMLIB2=ON \
    -DBUILD_RSS=ON \
    -DBUILD_WEATHER_METAR=ON \
    -DBUILD_WEATHER_XOAP=ON \
    -DBUILD_WLAN=ON \
    -DBUILD_IPV6=OFF \
    -DMAINTAINER_MODE=ON \
    -DCMAKE_BUILD_TYPE=Release \

  make
  make install DESTDIR=$PKG
```

Now with ```double_buffer yes``` in my conky config, when I run conky, it flickers, this is what I mean by it not working. :)

**Comment by Geyup** [comment]
Any thoughts here from the developers, on how to get the flickering to stop, or is there a bug anyone is aware about, regarding this problem?

As I mentioned, 1.9.0 works, only this problem in 1.10.0

**Comment by Geyup** [comment]
This works ok now in 1.10.1
