### ISSUE TITLE
Conky widgets and events?

### ISSUE THREAD

**Issue by rubyFeedback** [brndnmtthws/conky#1016]
Hey guys,

This is more a theoretical question. So first a bit of background.

I found conky many years ago. Loved it. It looked so nice!

I did not quite use it for a long time but recently I was thinking more
and more of using it as a base to customize and call my scripts.

I am typically using icewm these days, and one thing that makes
sense to me is to try to want to use conky to have "widgets" that
can do special things. Like ... a button that can be clicked!

So we just need to be able to respond to mouse events,
and determine the coordinate. Not sure how easy that is.

Would this, in theory, fit to "advanced" conky use? Like
to stayl part of conky, say, some widgets on the bottom
or perhaps even some embedded terminal there if someone
double clicks on it.

Please feel free to close this issue at any moment in time
to keep the bug tracker clean.

**Comment by su8** [comment]
https://github.com/netikras/ConkyClicky

**Comment by su8** [comment]
Séé also. https://github.com/brndnmtthws/conky/pull/955
