### ISSUE TITLE
1.10.0 Unusual README appears after compiling

### ISSUE THREAD

**Issue by ghost** [brndnmtthws/conky#102]
Hi,

These are my compile flags for conky;

```
mkdir build
cd build
cmake .. \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_CURL=ON \
    -DBUILD_XDBE=ON \
    -DBUILD_IMLIB2=ON \
    -DBUILD_RSS=ON \
    -DBUILD_WEATHER_METAR=ON \
    -DBUILD_WEATHER_XOAP=ON \
    -DBUILD_WLAN=ON \
    -DBUILD_IPV6=OFF \
    -DMAINTAINER_MODE=ON \
    -DCMAKE_BUILD_TYPE=Release \

  make
  make install DESTDIR=$PKG
cd -
```

After conky is done compilng, I noticed in the source directory a new README file appear, which seems to look formatted like a man page, somehow created by mistake.

Here's the contents of ``/tmp/foo/conky-1.10.0` after compiling;

```
AUTHORS COPYING INSTALL LICENSE.GPL README README.md  /build 
check_docs.py  /data  extras  /src CMakeLists.txt  ChangeLog  LICENSE.BSD
NEWS README.cmak changelog2html.py  /cmake /doc /lua text2c.sh
```

I copied the README here;

http://pastebin.ca/3042872

**Comment by lasers** [comment]
@su8 I assume this does not happen anymore, but can you check this?

**Comment by su8** [comment]
Same here, nothing new appears.
