### ISSUE TITLE
How to remove extra whitespace caused by ${voffset -N}?

### ISSUE THREAD

**Issue by AlbinoGeek** [brndnmtthws/conky#1020]
## Summary

If I create a dense style (such as underlined headers, etc.) involving a lot of the following formula, the resulting window draws with a lot of extra space (all the added up voffset values) after the last contentful item.

## Screenshot

![image](https://user-images.githubusercontent.com/1910461/95703394-d3a25b00-0c03-11eb-99f8-7252b80d32ba.png)

## Details

Conky Version: `1.11.7_pre`

## Config

```lua
conky.config = {
	use_xft = true,
	xftalpha = 0.6,
	text_buffer_size = 2048,
	override_utf8_locale = true,
	background = false,
	update_interval = 60,
	total_run_times = 0,
	own_window = true,
	own_window_class = 'Conky',
	own_window_colour = '2D2D2D',
	own_window_hints = 'undecorated,above,skip_taskbar,skip_pager,sticky',
	own_window_title = 'Conky',
	own_window_argb_visual = true,
	own_window_argb_value = 70,
	own_window_transparent = false,
	own_window_type = 'normal',
	double_buffer = true,
	draw_outline = true,
	default_outline_color = '424242',
	draw_shades = false,
	default_shade_color = '000000',
	extra_newline = false,
	use_spacer = "none",
	out_to_console = false,
	out_to_ncurses = false,
	out_to_stderr = false,
	out_to_x = true,
	default_color = 'DAC79C',
	font = 'Liberation Mono:regular:size=16',
	alignment = 'bottom_left',
	gap_x = 60,
	gap_y = 420,
	uppercase = false,
	border_inner_margin = 2,
	border_outer_margin = 2,
	border_width = 0,
	draw_borders = false,
	draw_graph_borders = false,
	stippled_borders = 0,
	show_graph_range = false,
	show_graph_scale = false,
	imlib_cache_size = 0,
	max_user_text = 5120,
};

conky.text = [[${font FreeMono:bold:size=24}Some Header${font}
${voffset -20}${goto 2}${hr 1}
${voffset -12}${font FreeMono:regular:size=12}Some Paragraph Text${font}]]
```

**Comment by kanyck** [comment]
I've the same issue. Still no remedy?

**Comment by sbirl** [comment]
Have you tried wrapping it inside of `${rstrip}`?  Maybe:
`${rstrip${font FreeMono:bold:size=24}Some Header${font}
${voffset -20}${goto 2}${hr 1}
${voffset -12}${font FreeMono:regular:size=12}Some Paragraph Text${font}}`

or

${rstrip${font FreeMono:bold:size=24}Some Header${font}}
${rstrip${voffset -20}${goto 2}${hr 1}}
${rstrip${voffset -12}${font FreeMono:regular:size=12}Some Paragraph Text${font}}

**Comment by plikhari** [comment]
@AlbinoGeek 

At the **end** of the line, place the # character - it will do what you desire...

cheers

**Comment by AlbinoGeek** [comment]
Ultimately I had to switch to a different font (really not sure why.)
