### ISSUE TITLE
MPRIS (music player API) support

### ISSUE THREAD

**Issue by allo-** [brndnmtthws/conky#1023]
**Issue**

Many music players support an API, that allows desktops like Plasma to use an unified music player control. I do not know what the API is called, but I think it uses dbus.

It would be nice, if conky could use the songtitle/artist/time/progress information in a similar way as it already support it for MPD. This would both allow supporting unknown music players like for example spotify and seamless switching between music players without changing the conky configuration.

**Comment by taigrr** [comment]
Are you referring to mpris?

https://specifications.freedesktop.org/mpris-spec/latest/

**Comment by Egocentrix** [comment]
MPRIS support would very useful I think

**Comment by allo-** [comment]
Someone wrote [a script](https://mein-neues-blog.de/2013/07/05/guayadeque-conky-integration-via-mpris-daemon/), but using a daemon looks like a too complicated approach.

**Comment by Egocentrix** [comment]
There is also this set of scripts that get the artist/title info from DBUS. Haven't tested it yet.
https://github.com/gvc14/NowPlaying

I think MPRIS is 'standard' enough that it can be part of conky itself, only I don't have enough DBUS experience (yet, but I can do c++) to write a patch.

**Comment by 20NE** [comment]
Feature needed!

**Comment by t0m5k1** [comment]
you could use:

```${execi xx playerctl metadata --format '{{artist}}: {{lc(title)}} '\}
change xx for the seconds you want this to update
