### ISSUE TITLE
conky: can't load font 'PizzaDude Bullets:size=9'

### ISSUE THREAD

**Issue by corro69** [brndnmtthws/conky#1032]
**Issue**

After update to 1.10 and converted to lua...font that I have been using previously will not load. 
conky: can't load font 'PizzaDude Bullets:size=9'

I attempted to use other bullet fonts and received the same error.

**Information**

Debian 10, conky 1.10

conky.config = {

	use_xft=yes,
	font = '=DejaVu Sans:size=9',
	xftalpha = 0.8,
	text_buffer_size = 2048,

-- Update interval in seconds
	update_interval = 1,
-- This is the number of times Conky will update before quitting.
-- Set to zero to run forever.
	total_run_times = 0,

-- Create own window instead of using desktop (required in nautilus)
	own_window = false,
	own_window_transparent = false,
--own_window_type root
--own_window_type override
	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

-- Use double buffering (reduces flicker, may not work for everyone)
	double_buffer = true,

-- Minimum size of text area
	minimum_width = 100, minimum_height = 0,

-- Draw shades?
	draw_shades = false,

-- Draw outlines?
	draw_outline = false,

-- Draw borders around text
	draw_borders = false,

-- Stippled borders?
	stippled_borders = 0,

-- border margins
--border_margin 5

-- border width
--border_width 1

-- Default colors and also border colors
	default_color = '#00579E',
--default_shade_color black
--default_outline_color 00579E
	own_window_colour = '#00579E',

-- Text alignment, other possible values are commented
--alignment top_left
--alignment top_right
--alignment bottom_left
	alignment = 'bottom_right',

-- Gap between borders of screen and text
-- same thing as passing -x at command line
	gap_x = 10,
	gap_y = 10,

-- Subtract file system buffers from used memory?
	no_buffers = true,

-- set to yes if you atht all text to be in uppercase
	uppercase = false,

-- number of cpu samples to average
-- set to 1 to disable averaging
	cpu_avg_samples = 2,

-- number of net samples to average
-- set to 1 to disable averaging
	net_avg_samples = 2,

-- Force UTF8? note that UTF8 support requi911C91 XFT
	override_utf8_locale = true,

-- Add spaces to keep things from moving about?  This only affects certain objects.
	use_spacer = 'none',

-- Network Options
	if_up_strictness = 'address',

};

conky.text = [[
$alignc Hostname: $nodename
$alignc Kernel: $kernel
$alignc Uptime: $uptime
${font DejaVuSans:Condensed:Bold:size=10} $alignc ${time %c}${font Bitstream Vera Sans:size=8}

${color 929292} SYSTEM ${hr 2}
${color 00579E}#${voffset 4}${font PizzaDude Bullets:size=9}A${font} intel-i5 ${voffset -2}${alignr} ${alignr}${freq}MHz 
${voffset 4}${font PizzaDude Bullets:size=9}A${font} CPU1: ${cpu cpu0}% ${alignr}${cpubar cpu0 8,80}
${voffset -2}${alignr} ${alignr}${freq}MHz   
${voffset 4}${font PizzaDude Bullets:size=9}A${font} CPU2: ${cpu cpu1}% ${alignr}${cpubar cpu1 8,80}
${voffset -2}${alignr} ${alignr}${freq}MHz  
${voffset 4}${font PizzaDude Bullets:size=9}A${font} CPU3: ${cpu cpu2}% ${alignr}${cpubar cpu2 8,80}
${voffset -2}${alignr} ${alignr}${freq}MHz  
${voffset 4}${font PizzaDude Bullets:size=9}A${font} CPU4: ${cpu cpu3}% ${alignr}${cpubar cpu3 8,80}
${voffset -2}${alignr} ${alignr}${freq}MHz 
${color 929292} MEMORY ${hr 2}${color 00579E}
${voffset 0}${font PizzaDude Bullets:size=9}A${font} RAM: $memperc% ${alignr}${membar 8,80}
#${voffset -2}${alignr} ${alignr}${fs_size (swap)}
${voffset 4}${font PizzaDude Bullets:size=9}A${font} SWAP: $swapperc% ${alignr}${swapbar 8,80}

${color 929292} TEMPS ${hr 2}${color 00579E}
${voffset 4}${font PizzaDude Bullets:size=9}A${font} TEMP 1: ${hwmon 1 temp 1}°C ${alignr}       ${voffset 4}${font PizzaDude Bullets:size=9}A${font} TEMP 2: ${hwmon 1 temp 2}°C
${voffset 4}${font PizzaDude Bullets:size=9}A${font} TEMP 3: ${hwmon 1 temp 3}°C ${alignr}       ${voffset 4}${font PizzaDude Bullets:size=9}A${font} TEMP 4: ${hwmon 1 temp 4}°C

${color 929292} PROCESSES ${hr 2}
		${alignr}CPU%	MEM%
${color 00579E}${voffset 2}${font PizzaDude Bullets:size=9}t${font} ${top name 1}${alignr}${top cpu 1}   ${top mem 1}
${voffset 2}${font PizzaDude Bullets:size=9}t${font} ${top name 2}${alignr}${top cpu 2}   ${top mem 2}
${voffset 2}${font PizzaDude Bullets:size=9}t${font} ${top name 3}${alignr}${top cpu 3}   ${top mem 3}
${voffset 2}${font PizzaDude Bullets:size=9}t${font} ${top name 4}${alignr}${top cpu 4}   ${top mem 4}
${voffset 2}${font PizzaDude Bullets:size=9}t${font} ${top name 5}${alignr}${top cpu 5}   ${top mem 5}

${color 929292} STORAGE ${hr 2}
${color 00579E}${voffset 4}${font PizzaDude Bullets:size=9}e${font} ${voffset 0}ROOT:${alignr}${fs_free_perc /}%
	${voffset 2} ${fs_free /}/${fs_size /} ${alignr}${fs_bar 8,80 /}
${voffset 4}${font PizzaDude Bullets:size=9}e${font} ${voffset 0}STEAM${alignr}${fs_free_perc /media/STEAM}%
	${voffset 2}${fs_free /media/STEAM}/${fs_size /media/STEAM} ${alignr}${fs_bar 8,80 /media/STEAM}
${voffset 4}${font PizzaDude Bullets:size=9}e${font}${voffset 0} MEDIA:${alignr}${fs_free_perc //media/MEDIA}%
	${voffset 2}${fs_free /media/MEDIA}/${fs_size /media/MEDIA} ${alignr}${fs_bar 8,80 /media/MEDIA}
${voffset 4}${font PizzaDude Bullets:size=9}e${font} ${voffset 0}HOME:${alignr}${fs_free_perc /home}%
	${voffset 2}${fs_free /home}/${fs_size /home} ${alignr}${fs_bar 8,80 /home}
${voffset 4}${font PizzaDude Bullets:size=9}e${font} ${voffset 0}EXTRA:${alignr}${fs_free_perc /media/EXTRA}%
	${voffset 2}${fs_free  /media/EXTRA}/${fs_size  /media/EXTRA} ${alignr}${fs_bar 8,80  /media/EXTRA}
${color 00579E}${voffset 4}${font PizzaDude Bullets:size=9}e${font} ${voffset 0}TOSHIBA:${alignr}${fs_free_perc /media/dustin/TOSHIBA EXT}%
	${voffset 2} ${fs_free /media/dustin/TOSHIBA}/${fs_size /media/dustin/TOSHIBA EXT} ${alignr}${fs_bar 8,80 /media/dustin/TOSHIBA EXT}

${color 00579E}HDD Read-> ${alignc}${color 91C591}${diskio_read}/s ${alignr}${color 911C91}${diskio_write}/s ${color 00579E}<-HDD Write
${color 91C591}${diskiograph_read 20,150} ${alignr}${color 911C91}${diskiograph_write 20,150}
    ${if_up eno1}
${color 929292} NETWORK ${hr 2}
${color 00579E}LAN:${alignr}IP: ${addr eno1}
${color 00579E}${font PizzaDude Bullets:size=9}T${font} ${downspeed eno1}kb/s${alignr}${font PizzaDude Bullets:size=9}N${font} ${alignr}${upspeed eno1}kb/s
${color 91C591}${downspeedgraph eno1 20,150} ${alignr}${color 911C91}${upspeedgraph eno1 20,150}
${color 91C591}Total:${color 00579E}${totaldown eno1}  ${alignr}${color 911C91}Total:${color 00579E}${totalup eno1}
 ${endif}
 
   #${if_up wlan0}
#${color #B8FF00}WIFI:${color 00579E} ${alignr}IP: ${addr wlan0} #${alignr}${color 00579E}
#Link quality: ${color orange}${wireless_link_qual_perc wlan0}%#${color 00579E}  #${alignr}Rate:${color orange}${wireless_bitrate #wlan0}
#ESSID: ${color orange}${wireless_essid wlan0}${color 00579E}${alignr}#${wireless_link_bar 8,80 wlan0}
#${color 00579E}${font PizzaDude Bullets:size=9}T${font} ${downspeed #wlan0}kb/s${alignr}${font PizzaDude Bullets:size=9}N${font} ${alignr}#${upspeed wlan0}kb/s
#${color 91C591}${downspeedgraph wlan0 20,150} ${alignr}${color 911C91}${upspeedgraph wlan0 20,150}
#${color 91C591}Total:${totaldown wlan0}  ${alignr}${color 911C91}Total:${totalup wlan0}
#${color 00579E}AP Mode: ${wireless_mode wlan1} ${alignr}AP MAC: ${wireless_ap wlan1}
]];

**Comment by su8** [comment]
Is it fixed in thé latést conky ¿

**Comment by su8** [comment]
No résponsé for twélve days, closing it féel freé to réopén it if thé issué is not fixed
