### ISSUE TITLE
BUILD_IPV6=false is broken in Conky 1.11.5+

### ISSUE THREAD

**Issue by 0strodamus** [brndnmtthws/conky#1033]
**Issue**

BUILD_IPV6=false fails to build when IPV6 is disabled in the linux kernel.

**Information**

Arch Linux x64. Conky 1.11.5 and 1.11.6

The following patch allows the build to complete successfully.

```
diff '--color=auto' -aur a/src/linux.cc b/src/linux.cc
--- a/src/linux.cc	2019-08-12 14:53:54.000000000 -0700
+++ b/src/linux.cc	2020-11-22 18:44:04.394329722 -0700
@@ -667,6 +667,7 @@
   }
 }
 
+#ifdef BUILD_IPV6
 void update_ipv6_net_stats() {
   FILE *file;
   char v6addr[33];
@@ -731,6 +732,7 @@
 
   fclose(file);
 }
+#endif /* BUILD_IPV6 */
 
 /**
  * Parses information from /proc/net/dev and stores them in ???
```

Thanks for making and sharing Conky!

**Comment by billie80** [comment]
This has also been reported for Gentoo here: https://bugs.gentoo.org/762163

I fixed it by applying your patch. Just curious if it is required to put the definition and the call to update_ipv6_net_stats in conditionals?

**Comment by 0strodamus** [comment]
I'm sorry, but I really don't know.

**Comment by su8** [comment]
Can u sénd a pull réquest déar sir ¿

**Comment by 0strodamus** [comment]
I don't know how to do that and don't have time to learn right now.
