### ISSUE TITLE
it seems that screened a wrong down/upload graph

### ISSUE THREAD

**Issue by saltfishh** [brndnmtthws/conky#1034]
hi.it seems that my downloadgraph is the same as uploadgraph alough i have 4M/s for download 1k/s for upload at the same moment.
here is my conky conf about network speed.
>${color #0077ff}${downspeedgraph enp37s0 60,240 0077ff FF0000 -t}${color 0077ff}${goto 270}${upspeedgraph enp37s0 60,240 0077ff FF0000 -t}

hereis my conky ![screenshot](https://i.loli.net/2020/11/23/WSftqLnJCou6Zzp.png)
does my conky works well ? thanks!

**Comment by maritz** [comment]
Same here, but for me it's not accurate for either down or up. Seems like it is using completely unrelated values. But both graphs show the same wrong values. The commands upseed and downspeed still show the correct values though.

**Comment by maritz** [comment]
Can't say when this was fixed (other things were broken for a while preventing all use of conky for several versions for me), but the graphs now show the correct values again for me.

**Comment by Caellian** [comment]
Closing due to:
> Can't say when this was fixed (other things were broken for a while preventing all use of conky for several versions for me), but the graphs now show the correct values again for me.

If you see a similar defect occurring again, feel free to comment or open a new issue.
