### ISSUE TITLE
No reference images in wiki

### ISSUE THREAD

**Issue by chahak13** [brndnmtthws/conky#1035]
Hi,
I was going through the wiki and it seems that there are no reference images in the wiki/the image links are broken. For example:
https://github.com/brndnmtthws/conky/extras/wiki/LuaTut/fill.png on the page [Using Lua scripts (Part 04): Drawing rectangles, circles and arcs](https://github.com/brndnmtthws/conky/wiki/Using-Lua-scripts-(Part-04)%3A-Drawing-rectangles,-circles-and-arcs)
and http://en.zimagez.com/miniature/screenshotd1385fb1f682885980eb5c32de2d92db.png link on the page [Using Lua scripts (Part 03): Drawing lines](https://github.com/brndnmtthws/conky/wiki/Using-Lua-scripts-(Part-03):-Drawing-lines) are broken.

Edit: I thought I'd list down other such instances as I come across them:
- https://github.com/brndnmtthws/conky/extras/wiki/LuaTut/stroke.png on [Using Lua scripts (Part 06): Borders and if statements](https://github.com/brndnmtthws/conky/wiki/Using-Lua-scripts-(Part-06)%3A-Borders-and-if-statements)

**Comment by brndnmtthws** [comment]
Hmm yeah I wonder if those were ever ported over properly. Let me see if I can figure it out.

**Comment by Caellian** [comment]
This is resolved - the wiki pages related to Lua were just rewritten from tutorial form to documentation form.

No diagrams atm but they will be added soon.
