### ISSUE TITLE
graph inside template using execpi not scrolling

### ISSUE THREAD

**Issue by sstickel** [brndnmtthws/conky#1039]
Good morning everybody. 

**Issue**
Please take a look into the attached conkyrc file. This is a stripped down version of one of my conkys.
None of my graphs which are packed inside templates and run via execpi work any longer. Only the rightmost pixel column gets updated, no **scrolling happens.**

**Information**
The issue appeared after updating from Ubuntu 20.04 to 20.10.
20.04 ships conky v1.10.8
20.10 ships conky v1.11.6
(https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=conky)

I also ran the conky file against self compiled versions of conky:
Works without problems on v1.10.8.
No scrolling on v1.11.6

This also happens in my network graphs which use a similar construct to automagically find all interfaces. I played around a lot with this issue but was not really able to track the root cause down.

[conkyrc_test.tar.gz](https://github.com/brndnmtthws/conky/files/5714131/conkyrc_test.tar.gz)

**Comment by renbag** [comment]
More details are given on issue #1109

**Comment by natmey** [comment]
I put a couple more examples of reproducing this [in a comment on the above mentioned issue](https://github.com/brndnmtthws/conky/issues/1109#issuecomment-1028275155). This is definitely still an active issue.

**Comment by johalaoui** [comment]
Hello,
This bug was introduced with 594d0c85baff7e930ec4c9568690bb53d3cd5d2a.
