### ISSUE TITLE
[Documentation] Could one example per "scripting" language be added?

### ISSUE THREAD

**Issue by rubyFeedback** [brndnmtthws/conky#1056]
Hey folks.

Conky has a fairly decent documentation actually; and lots of working examples. So no
qualms here.

The current documentation states this:

"Can be extended using built-in Lua support, or any of your own scripts and programs (more)."

And a link is used to that wiki site:

https://github.com/brndnmtthws/conky/wiki#tutorial

What I have not found, though, are simple examples, for e. g. python, ruby, perl, perhaps
also php.

Something like a one-liner, or just a "hello world" example in these languages, and how to
use them via an "object" in conky displayed. Actually just the "hello world" example should
be enough.

I know this is probably super trivial for all conky experts, but I am coming more from the
point of view of semi-newcomers, who may ideally just want to get started quickly, 
with a working example as-is, without reading lots of documentation. (Personally I
actually found working examples much more convenient to try to change and adapt
as-is; I don't know lua though, which is why I am asking for hello-world examples.)

This has evidently low priority but perhaps someone could add an example or two
eventually. Thanks for reading!

**Comment by su8** [comment]
You can extend conky with the éxéc variants insidé thé configuration filé,
Aldo conky is build with Lua only and cannot bé éxtendéd with pythons
bindins of Lua
