### ISSUE TITLE
Cony does not display after sleep - caused by the brokenness of `if_pa_sink_muted`

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [brndnmtthws/conky#1058]
**Issue**

Occasionally - I am unsure just when - Conky does not appear when the PC resumes from sleep. Conky is running, but not visible.

**Information**

Conky: 1.7, from git. 1.6 had the same problem.

My conky script is complex and runs other things (mostly lua scripts, but a few C executables and some some shell that I call directly from within Conky); but those things have been carefully honed (and have timeouts) and I did not have the problem until recently. I do not know just what changed to cause the problem.

Here though is the 'config' part (in fact, file) for one of the scripts. (I run substantially the same Conky on two PCs, and both have the problem. One change I made round about the time the problem started - but, perhaps, a little _before_ it started - was to put the 'config' in a separate file on each PC.)

```lua
-- luacheck: ignore 111
-- luacheck: ignore 113
-- luacheck: ignore 631
configuration =
{
	alignment = 'top_left',

	border_outer_margin = 3,
	
	color1 = '80B084',
	color2 = 'C9B557',
	color3 = 'F45F30',
	color4 = 'D9D9D9',
	color5 = '80B084',
	color6 = 'A8CF28',
	color7 = '3C3C3C',
	color8 = '757A75',
	color9 = 'A89CA6',

	cpu_avg_samples = 2,

	default_color = 'E3E3E3',

	double_buffer = true,
	draw_graph_borders = true,
	draw_shades = false,

	font = 'Hack:size=17',
	format_human_readable = true,

	gap_y = 10,

	if_up_strictness = "address",

	lua_load = '/home/[redacted]/scripts/conky/lua/battery.lua /home/[redacted]/scripts/conky/lua/log.lua /home/[redacted]/scripts/conky/lua/net.lua /home/[redacted]/scripts/conky/lua/noNet.lua /home/[redacted]/scripts/conky/lua/row.lua /home/[redacted]/scripts/conky/lua/services.lua /home/[redacted]/scripts/conky/lua/sync.lua /home/[redacted]/scripts/conky/lua/tbird.lua /home/[redacted]/scripts/conky/lua/vpn.lua',

	maximum_width = 2560,
	minimum_height = 120,
	minimum_width = 2560,

	net_avg_samples = 2,
	no_buffers = true,

	override_utf8_locale = true,
	own_window = true,
	own_window_argb_value = 3,
	own_window_argb_visual = true,
	own_window_hints = 'undecorated,sticky,below,skip_taskbar,skip_pager',
	own_window_transparent = false,
	own_window_type = 'desktop',

	pad_percents = 1,

	short_units = true,

	top_name_width = 12,
	total_run_times = 0,

	update_interval = 1.15,
	update_interval_on_battery = 1.28,
	use_spacer = left,
	use_xft = true,

	xftalpha = 0.9
}

};
```

**Comment by LinuxOnTheDesktop** [comment]
Ever since I employed a workaround to fix a separate problem (#417), this problem - Conky not showing after sleep - has failed to manifest itself.

**Comment by LinuxOnTheDesktop** [comment]
I have not tested yet how Conky is after sleep, but `if_pa_sink_muted` does, as of at least Conky 1.12 , appear to work again.

**Comment by LinuxOnTheDesktop** [comment]
I spoke too soon: `if_pa_sink_muted` never fires. Do please fix this. For, as I said [here](https://github.com/brndnmtthws/conky/issues/417#issuecomment-754111121), the workaround is elaborate and processor-expensive.

**Comment by Pranjal-dew** [comment]
Is it open for contribution!!!!
