### ISSUE TITLE
Can I tell conky which shell to use for $exec*?

### ISSUE THREAD

**Issue by ohnonot** [brndnmtthws/conky#1059]
The documentation says:

>exec command
Executes a shell command and displays the output in conky. Warning: this takes a lot more resources than other variables. I'd recommend coding wanted behaviour in C/C++ and posting a patch. 

And all other `exec*` vars start with "Same as exec, etc."

The way I see it, conky simply executes "sh command" for all these vars (I assume [this is the code](https://github.com/brndnmtthws/conky/blob/e4fad17dc0bb69745236f1425ccf88c998a95c6c/src/exec.cc#L125) in question. I don't fully understand it tbh).

### ISSUE

On my system, `$(which sh)` is a symlink to /bin/bash - and I don't want to change that. But I'd like conky to use a lighter shell for recurring executions, such as dash.

Is it possible to tell conky to do that?

If I put `#!/bin/dash` at the top of my script, then `sh command` will still invoke `bash` first, then change to `dash`, as far as I understand. So that isn't enough.

**Comment by su8** [comment]
Simply compilé conky with dash.  https://github.com/brndnmtthws/conky/blob/88fce68a7cbb721e683bf158dec5f18ae554c160/src/exec.cc#L125 éxchange it dash

**Comment by ohnonot** [comment]
Thanks.
Instead I decided to [permanently symlink /bin/sh to dash](https://wiki.archlinux.org/index.php/Dash#Use_Dash_as_/bin/sh) because it makes a lot of sense; not only wrt conky.
