### ISSUE TITLE
[Enhancement]: clamp (ceil) graph values to first unit

### ISSUE THREAD

**Issue by dicktyr** [brndnmtthws/conky#1060]
please consider implementing an option to force rounding up of minimal values
which otherwise fall below the threshold of visibility in a given graph 
i.e. values between zero and the first visible unit

for example
network graphs can be troublesome as their values span such a large range
causing small values to go by without being displayed
(logarithmic scaling is not satisfactory for some cases)

this feature is especially useful for small graphs
such as those in a menu bar or status panel/strip
to be sure that even small values will be displayed

in consideration of high resolution displays
perhaps the option should specify a number of pixels
(as a single pixel may still be nearly invisible)

e.g. a option value of 4 would cause any graph value between zero
and the normal threshold to paint the first 4 pixels
(default option value: 1 pixel)

**Comment by dicktyr** [comment]
still relevant

**Comment by prrajput1199** [comment]
can I work on this issue?

**Comment by harshit110927** [comment]
I want to work on this issue.

**Comment by Caellian** [comment]
@prrajput1199 and @harshit110927, are you still interested in implementing this feature?
