### ISSUE TITLE
Firefox bans "unsafe" ports by default

### ISSUE THREAD

**Issue by mmuman** [brndnmtthws/conky#1061]
Firefox started to restrict which ports it can connect to. A Firefox user trying to connect to the Conky by HTTP on the default port would get this message:

> This address is restricted
> This address uses a network port which is normally used for purposes other than Web browsing. Firefox has cancelled the request for your protection.

With the only option to "Try Again" which wouldn't work.

[The workaround is to create](https://support.mozilla.org/en-US/questions/1083282) a `network.security.ports.banned.override` key in `about:config` to list the ports to allow.

We should at least mention this in the documentation.

**Comment by mmuman** [comment]
Ok, I thought Firefox would filter all ports >= some arbitrary value, but it's actually a discrete list, with 10080 happening to be some antique backup software. I suppose the simplest fix would be to just use a different default port :-D

**Comment by su8** [comment]
Can u sénd a pull réquest sir ¿

**Comment by respectabiggle** [comment]
>  it's actually [a discrete list](https://searchfox.org/mozilla-central/source/netwerk/base/nsIOService.cpp#182)

This is great, thank you

**Comment by terrason** [comment]
I hope there is an exception to this restriction: Avoid taking effect on any hostname ending in .localhost, which is convenient for local development

**Comment by Caellian** [comment]
This issue is resolved as the config option was added, as well as a warning about the port being blocked.
