### ISSUE TITLE
IT IS NOT ISSUE

### ISSUE THREAD

**Issue by 3BD-R** [brndnmtthws/conky#1062]
sorry for disturbing but i just being curious about "is there anyway to show or run conky in gnome overview 'not in desktop' ? 
because i am using ' just perfection ' gnome extension and I'm thinking to making conky appear in it as a panel. 

![Screenshot from 2021-02-16 22-23-34](https://user-images.githubusercontent.com/33579200/108118998-cd3b5880-70a7-11eb-9afc-ac1f6e67e840.png)

**Comment by su8** [comment]
@lasers can u run gnomé and séé what u can do ¿

**Comment by 3BD-R** [comment]
@su8 what do you mean ?

**Comment by 3BD-R** [comment]
> @lasers can u run gnomé and séé what u can do ¿

@su8 what do you mean ?

**Comment by lasers** [comment]
@su8 I hadn't touched conky and GNOME for long time. :fearful: 

@3BD-R I'd try changing `own_window_type` --> `normal, desktop, dock, panel, override` and see what works. Also, try messing with `own_window_hints` too --> `undecorated,below,sticky,skip_taskbar,skip_pager`.

Following GNOME tradition... If you want a panel, you should use `GNOME Flashback` (Session) or `Cinnamon` (Desktop Env) instead. Alternatively, use different software... such as `GNOME System Monitor`, `glances` in your terminal, etc so they all get shown in Gnome Overview. 

I think the solution for GNOME those days might be to always stick with random GNOME extensions too.

* Random extensions like `Dash to Dock` with settings to customize your panel.
* Random extensions like this one. https://extensions.gnome.org/extension/1154/top-bar-script-executor/
* Random tools like `Gnome Tweak` tool (just in case).

**Comment by 3BD-R** [comment]
> @su8 I hadn't touched conky and GNOME for long time. fearful
> 
> @3BD-R I'd try changing `own_window_type` --> `normal, desktop, dock, panel, override` and see what works. Also, try messing with `own_window_hints` too --> `undecorated,below,sticky,skip_taskbar,skip_pager`.
> 
> Following GNOME tradition... If you want a panel, you should use `GNOME Flashback` (Session) or `Cinnamon` (Desktop Env) instead. Alternatively, use different software... such as `GNOME System Monitor`, `glances` in your terminal, etc so they all get shown in Gnome Overview.
> 
> I think the solution for GNOME those days might be to always stick with random GNOME extensions too.
> 
>     * Random extensions like `Dash to Dock` with settings to customize your panel.
> 
>     * Random extensions like this one. https://extensions.gnome.org/extension/1154/top-bar-script-executor/
> 
>     * Random tools like `Gnome Tweak` tool (just in case).

@lasers thanks for hints .. i tried it but no difference to normal behavior seems like `own_window_hints` does not effect.
