### ISSUE TITLE
appimage compiled features

### ISSUE THREAD

**Issue by dmidecodes** [brndnmtthws/conky#1064]
i try to autostart a conkyrc with conky-x86_64.AppImage.

the first run in konsole coredumped, because of an unknown variable **'$wireless_essid'**, so for testing purposes, i deactivated the related section in the configfile. unfortunately, the problem still persists.

```
./conky-x86_64.AppImage -c "/home/user/.config/conky/conky_gen.conkyrc" --daemonize --pause=5
conky: desktop window (2400015) is subwindow of root window (157)
conky: window type - dock
conky: drawing to created window (0x3a00002)
conky: drawing to double buffer
conky: forked to background, pid is 11089


systemd-coredump[11112]: Process 11089 (AppRun) of user 1000 dumped core.

Stack trace of thread 11089:
#0  0x00007f1e23dd2fb3 n/a (n/a + 0x0)
```

i'm not sure, but think it has to do with missing compiled features, since the config needs lua and cairo & works with conky installed from the aur.

```
./conky-x86_64.AppImage -v
conky 1.11.6 compiled Mon Jul 27 12:12:12 UTC 2020 for Linux 4.15.0-1077-gcp x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky


 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * Weather (METAR)
  * support for IBM/Lenovo notebooks
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * OSS mixer support
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * Xshape extension (click through)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * CMUS
  * MPD
  * MOC

 Default values:
  * Netdevice: eno1
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 256
  * Maximum text size: 16384
  * Size text buffer: 256
```

is there anything speaking against including all conky features in the appimage build, so any config can be run without issues?

**Comment by su8** [comment]
Inclùdìng all featurés in bsd wont work as thé wiréléss variablés only work
in Linux and they use old architécturé

**Comment by dmidecodes** [comment]
ok, that's understandable.

now, in this case, would it make sense to offer an extra variant featuring all the bells and whistles besides the standard appimage?

**Comment by brndnmtthws** [comment]
Fixed with:

* 9bc0302934ecf2d69287d5164d4f2cc93b07fb48
* b27944af559253983c4d07d514a56f6c32518950
* d75a1468896b05ffe154d4df320872390b90d61e

**Comment by brndnmtthws** [comment]
Note: this won't go out until the next release, but you can grab the latest builds from here: https://github.com/brndnmtthws/conky/actions/workflows/publish-appimage.yml
