### ISSUE TITLE
missing rule for uninstalling conky installed from source

### ISSUE THREAD

**Issue by freddii** [brndnmtthws/conky#1068]
**Issue**

i am trying to uninstall my previous installed conky from source with:
sudo make uninstall
but make is complaining that there is no rule for uninstalling.

**Comment by brndnmtthws** [comment]
This is a limitation of CMake (though it is possible to add a custom uninstall target):

https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake
