### ISSUE TITLE
Is it possible to have dynamic items within conky.config{ ... }?

### ISSUE THREAD

**Issue by MostHated** [brndnmtthws/conky#1069]
Hello there,
    I had a more general usage question which I have not been able to locate an answer via google, prior issues, or browsing other peoples config files. I was wondering if there is a way to have aspects of the actual conky.config section be variable/dynamic based on some of the available conditional commands?

Basically, I am wanting to do something like this, which basically would try and make it so that if I am using remmina to RDP into my work laptop, move Conky over to my other monitor:

```lua
conky.config ={
  alignment = ${if_running remmina} 'top_right' ${else} 'top_left',
  gap_x = ${if_running remmina} 2580  ${else} 30,
  gap_y = 0
}
```

Would this work, or do I need to simply have two separate conky configs, one with each set of settings, and do the check outside of Conky and then switch between them by stopping and restarting the application?

**Comment by brndnmtthws** [comment]
I am not sure if I understand your question entirely, but perhaps I can try to answer it.

The config itself is Lua code, so you can quite pretty much do anything you want with the configuration. There are some limitations, such as the fact that the config is only evaluated once when it's loaded. You can, however, generate the conky config however you want using Lua.

I hope that helps!

**Comment by MostHated** [comment]
So, the conky.config = {} portion is only evaluated once, but then conky.text = "" is evaluated repeatedly? I was mostly just looking for a way to dynamically change the position of conky at runtime, but it sounds like that may not be possible. At least, not without doing something external to change the value then restart the process so that the config is evaluated again?
