### ISSUE TITLE
Is it possible? Set Conky's window icon & taskbar icon

### ISSUE THREAD

**Issue by Botspot** [brndnmtthws/conky#1075]
**Issue**

1. I'm using Conky to graph the performance of various file copy operations.
2. It would be awesome if conky's window icon could be customized. Right now, it's blank:

![2021-03-04-134355_1920x1080_scrot](https://user-images.githubusercontent.com/54716352/110021045-e2db8f80-7cef-11eb-9884-15fe63653456.png)

No this is not Windows, it's Linux trying to look like Windows. ;)

**Information**

Conky version `1.10.8-1 armhf`

**Comment by Botspot** [comment]
Anyone? @brndnmtthws @labath @ngaro

**Comment by ohnonot** [comment]
If you're under Xorg, you can use `xseticon`.  
Also try playing with `own_window_class` - not sure it has an impact, but it might.  
Or start it from a .desktop file - on some DEs that's enough I believe.

**Comment by Botspot** [comment]
> If you're under Xorg, you can use `xseticon`.

I'm hesitant to add another dependency to the software I'm going to distribute. `xseticon` will be a last resort.

> Or start it from a .desktop file - on some DEs that's enough I believe.

Could you help me with that? I'm using LXDE, and here's the desktop file I made for it:
```
[Desktop Entry]
Version=1.0
Terminal=false
Type=Application
Name=conky
Exec=conky -c /home/pi/ultiflash/config/conky-rsync.config
Icon=gparted
StartupWMClass=conky
Categories=Graphics;
StartupNotify=true
```
The file is located at `/home/pi/.local/share/applications/conky.desktop`

Expected behavior: Conky launches with the gparted icon.  
Actual behavior: Conky launches with the same blank icon.

@ohnonot Do you see anything wrong with my desktop file? Or must I conclude that LXDE is not capable?

**Comment by Botspot** [comment]
Any updates on this?
