### ISSUE TITLE
Using AppImage, the process shows up as "AppRun" instead of Conky

### ISSUE THREAD

**Issue by MostHated** [brndnmtthws/conky#1079]
Hello,
    I decided to try out the AppImage as the `apt install conky-all` install is an older version. I have noticed though, that when running conky the process name is now "AppRun". Then when I have multiple instances running, each one is called AppRun without a way to differentiate them. Is there a way to assign a new name to the process at launch in order to keep track and identify them, or am I best off just cloning and building conky in order to make sure I have the most recent version while retaining a proper process name?

Thanks,
-MH

**Comment by MostHated** [comment]
If anyone wants a way to pretty decently find the processes for the running appimage, this should do the trick, though. There are probably better ways, that is just what I came up with.

```sh
ps aux | grep -v grep | grep -i -e VSZ -e conky | awk '{print $2}' | sed -e 1d | xargs kill -9 $1
```

It is still a big enough pain to work with over the standard executable that I just went and built from source anyways.

**Comment by brndnmtthws** [comment]
I believe the name comes from here: https://github.com/AppImage/AppImageKit/blob/master/resources/AppRun
