### ISSUE TITLE
Freenode's irc channel #conky topic has wrong conky version.

### ISSUE THREAD

**Issue by lockywolf** [brndnmtthws/conky#1080]
**Issue**

On the "official" conky freenode channel #conky, the topic says 
```
 Topic for #conky is: http://conky.sf.net - Conky 1.9.0 is the latest | Let us know if you find bugs or need help  (or file a bug on sf.net). | Wiki: http://conky.be/ | IRC stats: http://diddyinc.com/conkystats.html
```
In fact, almost all of that information is obsolete: it's been 1.10 for quite a while, conky.sf now redirects to github, the wiki is no more, and the irc stats service seems to be offline.

**Information**

This is not a "software-related" issue, but if the changed is not used any more, perhaps it is worth marking it as closed, or something.

**Comment by brndnmtthws** [comment]
I lost the registration for the nickname I used on freenode back in the day, and also lost registration for #conky as a result. If there's a way to get it back, that would be cool.
