### ISSUE TITLE
Syntax changed or bug in v1.12.1 vs v1.11.6? (When object/attribute width is set to 0 AND color gradient is used)

### ISSUE THREAD

**Issue by gc-user** [brndnmtthws/conky#1082]
**Issue**

After updating from v1.11.6 to v1.11.6 conky fails to start with custom conf file. Error message: double free or corruption (out)

The culprit within the custom config seems to be the following line:

${cpugraph 12,0 404040 bfbfbf}

When deleting either one of the color codes OR setting the width to >=2 conky starts normally.

Did anything change from v1.11.6 regarding the syntax or was a bug introduced?

man shows
cpugraph (cpuN) (height),(width) (gradient colour 1) (gradient colour 2) (scale) (-t) (-l)

Also, changelog doesn't mention any change in syntax.
So, no hint as to why the "old" line shouldn't work anymore.

**Comment by brndnmtthws** [comment]
Do you have the HSV gradient build switch enabled?

This might be related (although I think it _should_ be fixed): https://github.com/brndnmtthws/conky/issues/1070

**Comment by gc-user** [comment]
@brndnmtthws, thank you for your reply!

#1070 sure reads like the same issue. Sorry I missed that one.

I assume, that switch is a build(ing) switch.
If it is enabled by default, I guess it's enabled, if I read the build template correctly (it's not mentioned, i.e. not disabled):

https://github.com/void-linux/void-packages/blob/master/srcpkgs/conky/template

Either way, the issue seems to be known and fixed. So, I just wait for the next release.

And thank you again!

**Comment by gc-user** [comment]
The distro I'm using just updated to v1.24.2 (from 1.22.3) and somewhat looked different - until I realized that the gradient is working again for me!
Because of all the version skipped by the distro I use, I can't tell for sure, but the changelog suggests that [this](https://github.com/brndnmtthws/conky/pull/2336) is most probably the fix that fixed this issue for me.

Thank you (although a bit late)!
