### ISSUE TITLE
1.10.0 segfault after several munutes if RSS feed is used

### ISSUE THREAD

**Issue by MaxKh** [brndnmtthws/conky#109]
subj

version:
conky 1.10.0 compiled Tue Jun 30 06:56:49 TAHT 2015 for Linux 4.0.6-1-ARCH x86_64

journalctl log:
kernel: conky[4378]: segfault at 0 ip 00007f9f19217243 sp 00007f9f147fea98 error 4 in libcurl.so.4.3.0[7f9f191d5000+70000]

Archlinux BSS discussion thread:
https://bbs.archlinux.org/viewtopic.php?pid=1542372#p1542372

**Comment by marcpayne** [comment]
This issue is also being discussed on the Arch bug tracker. It *might* be an upstream problem in curl. Just FYI.

https://bugs.archlinux.org/task/45569

**Comment by vesath** [comment]
jay has posted a patch that fixes the segfault in https://github.com/bagder/curl/issues/342#issuecomment-120579447

**Comment by marcpayne** [comment]
@MaxKh Is this issue fixed for you in 1.10.1?

**Comment by MaxKh** [comment]
@marcpayne I used 10.0.1 during last week. Looks stable now. Thanks

**Comment by lasers** [comment]
Solved by #134 and https://github.com/curl/curl/issues/342. One less issue to worry about. Thanks.
