### ISSUE TITLE
regression: conky 1.12.0 intentionally broke Linux memory reporting

### ISSUE THREAD

**Issue by ChrisCheney** [brndnmtthws/conky#1090]
**Issue**

As of Conky 1.12.0 intentionally broke Linux memory reporting

**Information**

Memory reporting in Conky under Linux was finally fixed with issue #859 in git commit https://github.com/brndnmtthws/conky/commit/11695b076abf72d797879c7c3b16fe89f3b68ca9 , after many (7) years of doing it incorrectly and so distributions dropped their patches fixing it themselves.

However then for largely unknown reasons Conky later intentionally broke memory reporting again under Linux in Feb 2021.
See git commits https://github.com/brndnmtthws/conky/commit/91a3f2ed871b7200fcf7a53f284bcd98f1fc49aa and https://github.com/brndnmtthws/conky/commit/c2c9e07afc7ac27e348ce12879f3b1e1b7382ce6 .

As is explained in detail in this kernel [git commit](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=34e431b0ae398fc54ea69ff85ec700722c9da773)  the proper way to report used memory is:

`curmem = info.memmax - memavail`

which was how it was being done in Conky before being reverted.

Sidenote: curmem is used as 'mem' in Conky which is defined as "Amount of memory in use." which fits this definition exactly.

The only explanation in the Conly source for why it was broken again is:

_**"* People think they will find the same amount of used RAM with the free program."**_

So Conky was doing it correctly then intentionally broke it supposedly because some people don't know how to read 'free' output correctly, yet didn't mention an opened issue by this group of people who don't know how memory actually works under Linux.

However nearly every other program, besides free, have already fixed memory reporting in a released version or in their next release (for example: htop, inxi, neofetch, screenfetch, etc) to match how it should be done with modern Linux.

In addition to the above mentioned fact that conky is now reporting the data incorrectly it also actually makes a **HUGE** difference as the numbers themselves are nowhere even close to each other.

Currently Conky is reporting my system is only using 8.16 GiB of ram while every other memory reporting program shows the real usage is nearly double that at 15.83 GiB.

**In addition Conky currently has no way to actually report the correct memory usage at all.**

**Perhaps the best solution to this problem is to have 'mem' report the correct memory usage, like prior to 1.12.0, and add a separate 'memused' variable to show the incorrect numbers like 'free' does if users still want to see the old bad data. Or maybe just add in the 'mem' variable documentation that 'free' reports used memory incorrectly.**

**Comment by brndnmtthws** [comment]
Thanks for the report. Let me try and figure out what's going on here and get back to you.

**Comment by brndnmtthws** [comment]
I believe #1092 will provide the behaviour everyone is looking for. If people want the old calculation, they can just use `legacymem` and get the old value. Otherwise, it should return the new value as expected elsewhere.
