### ISSUE TITLE
Scaling goes strange after commit ≈ 7f84662c and including in today's git version

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [brndnmtthws/conky#1097]
**Issue**

I build Conky from git, on a machine with HiDPI and the OS set to scale everything to x2. Everything works until the commit immediately previous to 7f84662c. (I do not know the number of that previous, problematic commit. My git skills are very limited even though I build Conky via it! And the problematic commit might not be _exactly_ the one _immediately_ before 7f84662c.)

After the problematic commit, things look like this:

![image](https://user-images.githubusercontent.com/47056543/116798768-07cf6180-aaeb-11eb-918d-7b0dcfa0048a.png)

Before that commit, they look, as they should, like this:

![image](https://user-images.githubusercontent.com/47056543/116798820-5da40980-aaeb-11eb-9a01-deca17a15d8b.png)

There was a problem like this a while back and it got fixed; I would not mention the current problem were it not that I see you are heading for a release (and I do want the Intel backlight support that the new release will add - though I am unsure one is to use it).

**Information**

Linux Mint 20.1 x 64 Cinnamon

I can give my Conky config files but they are large.

**Comment by genes1122** [comment]
I have the same issue.  I have used the DPI setting in MATE for years to scale the display for high resolution monitors.  Conky has ignored this setting until very recently.  I'm not sure about the commit number, I'm using conkyn from the openSUSE Tumbleweed repository.  Here are the openSUSE verfsions bracketing the issue.

`
Update that broke things.
2021-04-30 09:56:59 | install | conky | 1.12.2-1.1

Revert that fixed things.
2021-04-30 11:38:43 | install | conky | 1.12.1-1.3

Update now works with **modified** .conkyrc file.
2021-05-02 15:56:09 | install | conky | 1.12.2-1.1
`

Diff between the .conkyrc files:

`
> diff -s conkyrc.old conkyrc.new
48,50c48,50
<     gap_y = 5,
<     maximum_width = 1920,
<     minimum_width = 1920,
---
>     gap_y = 3,
>     maximum_width = 1536,
>     minimum_width = 1536,
72,79c72,79
< ${goto 8}${color0}BAT:$color ${battery_short BAT1} ${battery_time BAT1}\
< ${goto 445}${color0}CPU:$color $cpu%\
< ${goto 555}${color0}CPU:$color ${hwmon k10temp temp 1}°C\
< ${goto 675}${color0}Fan:$color ${hwmon dell_smm fan 1}rpm\
< ${goto 830}${color0}NVMe:$color ${hwmon nvme temp 1}°C\
< ${goto 970}${color0}SSD:$color ${hddtemp /dev/sda}°C\
< ${goto 1095}${color0}RAM:$color $memperc%\
< ${goto 1205}${color0}Down:$color ${downspeedf wlp3s0}KB/s\
---
> ${goto 6}${color0}BAT:$color ${battery_short BAT1} ${battery_time BAT1}\
> ${goto 355}${color0}CPU:$color $cpu%\
> ${goto 445}${color0}CPU:$color ${hwmon k10temp temp 1}°C\
> ${goto 540}${color0}Fan:$color ${hwmon dell_smm fan 1}rpm\
> ${goto 665}${color0}NVMe:$color ${hwmon nvme temp 1}°C\
> ${goto 775}${color0}SSD:$color ${hddtemp /dev/sda}°C\
> ${goto 875}${color0}RAM:$color $memperc%\
> ${goto 965}${color0}Down:$color ${downspeedf wlp3s0}KB/s\
`
Please ignore the system DPI when moving to pixel locations.

Gene

**Comment by LinuxOnTheDesktop** [comment]
There has no been a release involve the commit at issue - and, still (to my knowledge) no documentation.

**Comment by LinuxOnTheDesktop** [comment]
Let me myself provide some rough documentation. (In so doing I build upon what @genes1122 wrote above.)

_Users need to adjust these values:_

- `gap_<whatever>`
- `maximum_<whatever>`
- `minumum_<whatever>`
- `goto` statements
- `offsets` and `voffsets`
- graph sizes

_Users should **not** adjust the following:_

- font sizes
- manually entered lines of space

I use 200% DPI scaling. Thus one might think that _halving_ various values in Conky would do the trick; and, if I remember correctly, I think that so doing did indeed work.
