### ISSUE TITLE
Window disappears when I click on desktop

### ISSUE THREAD

**Issue by blakemcbride** [brndnmtthws/conky#1107]
**Issue**

When I run conky I get the expected informational window.  If I click on the disktop, it disappears but the conky process does not exit.  I'd prefer if it didn't disappear when I click on the desktop.  However, if it does disappear, how do I make it reappear?

**Information**

I am using 64-bit LinuxMint 19.3 MATE

I am trying the default conky config.

**Comment by chenssgit** [comment]
I ran into the same issue on xubuntu20.04. conky just buggy

**Comment by hanscees** [comment]
Same issue here on ubuntu 21



some info that might help?? 
conky: received SIGHUP, SIGINT, or SIGTERM to terminate. bye!
$ DEBUG(0) [/build/conky-QmM1tH/conky-1.11.6/src/x11.cc:437]: deinit_X11

conky -v
conky 1.11.6 compiled 2020-08-17 for Linux x86_64

ps waux | egrep -i xo
root        1292  7.0  0.8 690248 68192 tty7     Rsl+ 13:52   1:55 /usr/lib/xorg/Xorg -core :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch



my .conkyrc
`
conky.config = {
    alignment = 'top_right',
    background = true,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'Droid Sans:size=10',
    gap_x = 10,
    gap_y = 50,
    minimum_height = 140,
    minimum_width = 20,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_transparent = false,
    own_window_argb_visual = true,
    own_window_argb_value = 90,
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
    xftalpha = 0.1,
    color0 = 'white',
    color1 = 'EAEAEA',
    color2 = 'FFA300',
    color3 = 'grey',
}

conky.text = [[
${color slate grey}Info: $sysname $nodename $kernel $machine
Uptime:$color $uptime

${cpugraph cpu1 50,150}${cpugraph cpu2 50,150}${voffset -19}
${cpugraph cpu3 50,150}${cpugraph cpu4 50,150}
${font Ubuntu:size=10}${voffset -110}${color3}${goto 10}1 ${goto 160}2 ${goto 0} ${voffset 50} ${goto 10}3 ${goto 160}4
${font Ubuntu:size=8}${voffset -67}${color3}${goto 108}${freq_g (1)}GHz ${goto 258}${freq_g (2)}GHz ${goto 0}${voffset 50}${goto 108}${freq_g (3)}GHz ${goto 258}${freq_g (4)}GHz 


$hr
${color2}CPU ${color red}${alignr}${cpu cpu0}%
${cpubar cpu0 5,}
${color red}${font Ubuntu Mono:size=12}${top name 1} $alignr ${top cpu 1}%
${top name 2} $alignr ${top cpu 2}%
${top name 3} $alignr ${top cpu 3}%
${top name 4} $alignr ${top cpu 4}%
${top name 5} $alignr ${top cpu 5}%
 
${color2}RAM ${color0}${alignr}${mem}
${membar 5,}
${top_mem name 1} $alignr ${top_mem mem_res 1}
${top_mem name 2} $alignr ${top_mem mem_res 2}
${top_mem name 3} $alignr ${top_mem mem_res 3}
${top_mem name 4} $alignr ${top_mem mem_res 4}
${top_mem name 5} $alignr ${top_mem mem_res 5}
$hr


${color2}Download ${color red}${alignr}${downspeedf enp3s0} KiB/s
${downspeedgraph enp3s0 80,}
${color2}Upload ${color0}${alignr}${upspeedf enp3s0} KiB/s 
${upspeedgraph enp3s0 80,} 
$hr
${color Tan2}ESTABLISHED Connections${color DarkSlateGray}${hr 2}

${offset 10}${color lightgrey}Inbound: ${color white}${tcp_portmon 1 32767 count}    ${color lightgrey}Outbound: ${color white}${tcp_portmon 32768 61000 count}${alignr}${color lightgrey}Total: ${color white}${tcp_portmon 1 65535 count}

${color slate grey}Process                 ${color slate grey}Remote Host                     ${color slate grey}L-Port ${alignr}${color slate grey}R-Port${color lightgrey}

${color red}${font Ubuntu Mono:size=10}${texeci 30 netstat -ap | grep 'ESTABLISHED'  | awk '{print $1, " ",  $4, " ",  $5, " ", $7}'


]]`

**Comment by hanscees** [comment]
I have checked several things (lsof and ps and so on) but I see no way to detect (other than my eyes) that conky has stopped displaying on my display. 

workaround
Only way to restart conky easily is to change the config file. 

So for instance I could write a sceript to replace color4 = 'grey', with color4 = 'red',

like so:
sed -i 's/# color4/color5/' ~/.conkyrc

**Comment by GeneMosher** [comment]
background false
double_buffer
use_xft yes
own_window yes
own_window_class Conky
won_window_type normal
own_window_transparent yes
update interval 2

**Comment by blakemcbride** [comment]
Gene, please fill in the blank for your previous post:  

The following config does ________________________________.

Thank you.

**Comment by whtyger** [comment]
Replacing the line

    own_window_type = 'desktop',

with

    own_window_type = 'normal',
    own_window_hints = 'undecorated,below,skip_taskbar,sticky',

in the `conky.config` section may help.

**Comment by ferdnyc** [comment]
As I mentioned in a comment on #399, personally with OpenBox (now in LXQT, previously I used LXDE) I use the `dock` window type, since I find it's the most compatible with OpenBox's window management. But to use that, you have to  configure the placement/management in _both_ Conky and OpenBox. This is the windowing section of my `conky-config.lua`:

```lua
        own_window = true,
        own_window_class = 'Conky',
        own_window_type = 'dock',
        own_window_hints = 'sticky,skip_taskbar,skip_pager,undecorated,below',
        own_window_transparent = false,
        own_window_colour = 'black',
```

And I combine that with these Dock configs in the OpenBox Configuration Manager:

![image](https://github.com/brndnmtthws/conky/assets/538020/8c9eafa1-5c56-4d80-ad22-31e782b23175)

**Comment by Caellian** [comment]
This can't be fixed:

- MATE uses caja for drawing desktop icons and menus.
- caja shows these as a fullscreen window in the background.
- both caja and conky are subject to same window ordering rules
  - they both show in background
  - last clicked window is displayed on top

The only workaround for this is changing the window type (as whtyger noted):
```
own_window_type = 'normal',
own_window_hints = 'undecorated,below,skip_taskbar,sticky',
```

Adding WM specific code to conky is a never-ending battle and not worth it IMO.

Future wanderers, see [Window Configuration](https://github.com/brndnmtthws/conky/wiki/Window-Configuration) for more details.

Closing this issue.
