### ISSUE TITLE
fs_usage and fs_used_perc return incorrect values for zfs mount point

### ISSUE THREAD

**Issue by rbrdvr** [brndnmtthws/conky#1119]
fs_usage with the path to a zfs mount point (pool created using raidz2) returns incorrect value
(in my case it reports 256K used instead of 700G), so is fs_used_perc.
fs_size returns correct value

conky version 1.11.6, I haven't tested this in 1.12.2, sorry

usage in rc file:
${fs_used /path_to_zfs_pool} / ${fs_size /path_to_zfs_pool} ${alignr} ${fs_used_perc /path_to_zfs_pool}%

**Comment by rbrdvr** [comment]
one more thing, if I specify subvolume in the path, fs_used and fs_used_perc return correct values, but fs_size returns value larger than available

for example:
zfs list output
NAME                  USED   AVAIL     REFER   MOUNTPOINT
zfs_pool              806G     9.46T      140K      /path_to_zfs_pool
zfs_pool/subvol   806G     9.46T      806G     /path_to_zfs_pool/subvol

using zfs_pool as path in conky returns
fs_usage 256K
fs_size 9.46T
fs_used_perc 0%

using zfs_pool/subvol as path in conky returns
fs_usage 806G (correct)
fs_size 10.2T (larger than exists)
fs_used 8% (correct based on first two values, incorrect based on actual usage, should be larger number)

**Comment by rbrdvr** [comment]
er.. I meant to say "using /path_to_zfs_pool and /path_to_zfs_pool/subvol

**Comment by idanka** [comment]
ext4 used:
#${font sans-serif:normal:size=10}SSD $alignc ${fs_used /} / ${fs_size /} $alignr ${fs_used_perc /}%
#${fs_bar /}

But zfs used / free
exec zpool iostat -v rpool | grep G | cut -c 40-45
exec zpool iostat -v rpool | grep G | cut -c 49-52

and missing used %
