### ISSUE TITLE
catp truncates after X characters

### ISSUE THREAD

**Issue by sbirl** [brndnmtthws/conky#1137]
**Issue**
Conky v1.11.6 from Debian 11.

`${catp}` truncates after _X_ characters.  Unaffected by value increases to `max_user_text` and/or `max_text_width`.  Problem does **not** exist with `${execp}` or `${execpi}`.

**Information**

I have a sort of template `~/.config/conky.conf` file where it uses `${catp}` to pull in a local file.   This file is only partially parsed, causing conky to throw "Missing endif" errors.

```
conky.config = {
    max_text_width = 0,
    max_user_text = 32767,
}

conky.text = [[
${if_existing /home/sbirl/.config/conky/networks-wireless.conf}${catp /home/sbirl/.config/conky/networks-wireless.conf}${endif}
]]
```

```
  ${color 55F}wlp2s0 ${color AAF}${wireless_mode wlp2s0} ${color}${if_up wlp2s0}${addrs wlp2s0} ${alignr}${color FA0}▲${color}${upspeed wlp2s0} ${color 0F0}▼${color}${downspeed wlp2s0}
    ${color AAF}${wireless_essid wlp2s0} ${rstrip ${wireless_link_qual_perc wlp2s0}}%
    ${color AAF}${wireless_freq  wlp2s0} ${wireless_bitrate wlp2s0}${color}${else}${color F00}No wireless${color}${endif}
```

The data is truncated around right after the SSID is displayed.

**Comment by plikhari** [comment]
Increase `text_buffer_size` , depending on the size of your rc file - you can increase this value to 2000 or 20000 - the value is in bytes...

**Comment by sbirl** [comment]
Simply doubling it to 512 was sufficient.  Thanks!
