### ISSUE TITLE
Widgets with transparency overlapping menu

### ISSUE THREAD

**Issue by mirkojovanovic** [brndnmtthws/conky#114]
I'm using conky on Arch Linux with Awesome Window Manager. When I enable some transparent conky widget it jumps to top left even if it's not aligned there. It's positioned with x and y gap, even I can see it's border there but the actual widget is in top left. I couldn't find this as known bug. Why is it happening?
![screen](https://cloud.githubusercontent.com/assets/8415436/8789286/7e1c737c-2f41-11e5-9404-ed1703464aa8.png)

**Comment by mirkojovanovic** [comment]
This fixed the issue https://wiki.archlinux.org/index.php/Conky#Universal_method_to_enable_true_transparency

**Comment by lasers** [comment]
That anchor does not exist anymore.
* Old archive. https://archive.fo/I14TP
* Current: https://wiki.archlinux.org/index.php/Conky#Transparency

Thanks. Closing.
