### ISSUE TITLE
cmake error on macos

### ISSUE THREAD

**Issue by notyz77** [brndnmtthws/conky#1143]
i watch your youtube video on conky in macos.....thank you for conky

i try  'cmake ..' but it give me error and i also try cmake with those FLAGS which are you used in your video still same error.

btw i try this in my ....MacBook-Air9,1 which is running Big Sur macOS 11.5.2 (20G95)
[error.txt](https://github.com/brndnmtthws/conky/files/7230222/error.txt)

-- INCLUDE_DIRECTORIES = /usr/local/include;/Users/halflifeprince/Downloads/temp/conky/3rdparty/toluapp/include;/Users/halflifeprince/Downloads/temp/conky/build;/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/include;/usr/local/include;/usr/local/include/freetype2;/usr/local/include/lua;/usr/local/Cellar/imlib2/1.7.4/include;/Users/halflifeprince/Downloads/temp/conky/build/data
-- LINK_LIBRARIES = /usr/local/lib/libintl.dylib;-lncurses;-lm;/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/lib/libncurses.tbd;/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr/lib/libform.tbd;/usr/local/lib/libX11.dylib;/usr/local/lib/libXext.dylib;/usr/local/lib/libXft.dylib;/usr/local/lib/libXext.dylib;lua;m;-L/usr/local/Cellar/imlib2/1.7.4/lib;-lImlib2;curl;toluapp_lib_static;Xinerama_LIBRARIES-NOTFOUND
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Xinerama_LIBRARIES (ADVANCED)
    linked by target "conky" in directory /Users/halflifeprince/Downloads/temp/conky/src

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
halflifeprince@HalfLifePrinces-MacBook-Air build %

**Comment by notyz77** [comment]
edit:
it is dependency problem to solve it run

brew install libxinerama

**Comment by ferdnyc** [comment]
@notyz77 While I'm sure installing libxinerama from Homebrew _worked_ to fix the build, it's not clear to me how useful Xinerama really would be on a macOS device, because according to its man page:
> **Xinerama** is a simple library designed to interface the Xinerama  Extension for retrieving information about physical output devices which may be combined into a single logical X screen.

If it's _not_ useful to build a macOS Conky with Xinerama support, then it can be disabled as a requirement by adding `-DBUILD_XINERAMA=0` to the `cmake` command when you generate the initial build system.
