### ISSUE TITLE
Conky + Cinnamon + Workspaces

### ISSUE THREAD

**Issue by Davetheraveuk** [brndnmtthws/conky#1145]
OS: Arch
Desktop Environment: Cinnamon

I would like to display my conky on a single workspace (Workspace 2).
I have already looked on google for a workaround - but none was forthcoming.

First is the output of wmctl:

```
[dave@ArcoLinuxB ~]$ wmctrl -d
0  * DG: 1920x1080  VP: 0,0  WA: 0,0 1920x1050  Workspace 1
1  - DG: 1920x1080  VP: N/A  WA: 0,0 1920x1050  Workspace 2
2  - DG: 1920x1080  VP: N/A  WA: 0,0 1920x1050  Workspace 3
3  - DG: 1920x1080  VP: N/A  WA: 0,0 1920x1050  Workspace 4
```

..and here is my conky config file:

```
conky.config={
alignment = 'top_left',
background = false,
color1 = '1793D1',
color2 = '4D4D4D',
double_buffer = true,
draw_borders = false,
draw_graph_borders = false,
draw_outline = false,
draw_shades = false,
font = 'Source Code Pro Light:size=10',
format_human_readable = true,
gap_x = 150,
gap_y = 0,
minimum_height = 5,
minimum_width = 5,
net_avg_samples = 4,
no_buffers = true,
own_window = true,
own_window_argb_visual = true,
own_window_class = "Conky",
own_window_hints = 'undecorated, below, skip_taskbar, skip_pager',
own_window_transparent = false,
own_window_type = normal,
--own_window_type = 'override',
--own_window_type = 'desktop',
--own_window_type = 'normal',
--own_window_type = 'dock',
--own_window_type = 'panel',
show_graph_range = false,
show_graph_scale = false,
temperature_unit = 'celsius',
total_run_times = 0,
update_interval = 1,
use_spacer = 'left',
use_spacer = 'right',
use_xft = true
};


conky.text = [[
${color2} │
${color2} ├───${color1} system
${color2} │     ├───${color1} date	      ${color2}     [${color1} ${time %A %d %B %Y} ${color2}]
${color2} │     ├───${color1} distro          ${color2}[${color1} $distribution ${color2}]
${color2} │     ├───${color1} kernel          ${color2}[${color1} $kernel ${color2}]
${color2} │     ├───${color1} uptime          ${color2}[${color1} $uptime ${color2}]
${color2} │     └───${color1} packages
${color2} │           ├─${color1} installed   ${color2}[${color1} ${execi 3600 pacman -Q | wc -l} ${color2}]
${color2} │           └─${color1} to update   ${color2}[${color1} ${execi 3600 checkupdates | wc -l} ${color2}]
${color2} └───${color1} network
${color2}       ├───${color1} state           ${color2}[${color1} ${if_gw}${color 00CC00}ONLINE${else}${color CC0000}OFFLINE${endif} ${color2}]
${color2}       ├───${color1} ethernet        ${color2}[${color1} ${if_up enp4s0}${color 00CC00}UP${else}${color CC0000}DOWN${endif} ${color2}]
${color2}       └───${color1} ipv4
${color2}             ├─${color1} local       ${color2}[${color1} ${texeci 3600 ip addr show enp4s0 | grep "inet " | awk '{print $2}'} ${color2}]
${color2}             ├─${color1} public      ${color2}[${color1} ${texeci 3600 curl -4 icanhazip.com} ${color2}]
${color2}             ├─${color1} latency     ${color2}[${color1} ${texeci 3600 ping archlinux.org -c 1 | grep time= | rev | cut -c -6 | rev} ${color2}]
${color2}             ├─${color1} downloaded  ${color2}[${color1} ${totaldown enp4s0} ${color2}]
${color2}             ├─${color1} uploaded    ${color2}[${color1} ${totalup enp4s0} ${color2}]
${color2}             ├─${color1} down        ${color2}[${color1} ${downspeed enp4s0} ${color2}]
${color2}             │  ${downspeedgraph enp4s0 14, 180 4D4D4D 1793D1}
${color2}             └─${color1} upload      ${color2}[${color1} ${upspeed enp4s0} ${color2}]
${color2}                ${upspeedgraph enp4s0 14, 180 4D4D4D 1793D1}
]]

```

Hope you can help.
David.

**Comment by ajgringo619** [comment]
What is happening now - all workspaces, or just the wrong one?

**Comment by Davetheraveuk** [comment]
Hi "brndnmtthws",
The conky is appearing on *all workspaces*.
I want conky to appear on *ONLY workspace 2*.

Thanks.
David.

**Comment by ajgringo619** [comment]
On my full-screen window, which was only in (1) workspace, my window settings were these:
```
own_window_hints = 'skip_taskbar,undecorated',
own_window_title = 'Conky Fullscreen',
own_window_type = 'normal'
```
Since yours are basically the same, I can't say why it's not working. I've tested this with XFCE and Cinnamon.

**Comment by Davetheraveuk** [comment]
Nevermind, I'll leave the conky on workspace 1 and do everything else on
workspace 2.
thanks.

**Comment by ajgringo619** [comment]
OK, you're confusing me. In one post you say that your conky is displaying on all workspaces, but your last one implies that it's only displaying on workspace 1. If this is the case, just add `wmctrl -s 1` before starting your conky.

**Comment by Davetheraveuk** [comment]
Okay, let me explain this again.
I use ArcoLinuxB (Arch Linux) with the Cinnamon Desktop Environment.
I also have the cinnamon applet called "Workspaces" attached/installed to
the taskbar at the bottom of the screen.
These "workspaces" are numbered 1, 2 , 3 and 4.
Now, when the system starts the conky loads (by default) on to workspace 1.
I would like conky to load at startup on workspace 2, 3 or 4. NOT workspace
1.

Thanks.
David.

**Comment by plikhari** [comment]
@Davetheraveuk 

It is beyond the purview of conky to be launched on a specific desktop/workspace.

However - the program was mentioned above `wmctrl` - you will need to install that to get a control of the level you desire - on Arch - it is in the community repos.

Here is a link to a website which has the solution for your query - [How to start an application on a different workspace?](https://unix.stackexchange.com/questions/27050/how-to-start-an-application-on-a-different-workspace)

If this has answered your query - perhaps you can mark this thread as solved.

cheers

**Comment by Davetheraveuk** [comment]
I found what I needed:

#!/bin/sh
sleep 20
#Move left conky:
wmctrl -r "Conky Fullscreen Left" -t 1
#Move right conky:
wmctrl -r "Conky Fullscreen Right" -t 1
