### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by Dash-gr** [brndnmtthws/conky#1155]
**Issue**

How to uninstall Conky?
Here's a screenshot: https://u.cubeupload.com/jabin/Screenshotfrom202112.png

I'm new to Linux so keep it simple please!

**Information**
OS: Linux Mint 20.2 Uma Cinnamon

**Comment by humanoid2050** [comment]
If you built it yourself from source, which usually looks something roughly like
```
mkdir build
cd build 
cmake ..
make
sudo make install
```

then you should also be able to run `make uninstall` and it looks like conky will do its best to remove all the files it installed previously. I'm not 100% sure, but you probably will need `sudo` to do the uninstall.

If you installed it via a linux package manager (like apt, aptitude, yum, etc.) then you will need to go back to the package manager.

**Comment by Dash-gr** [comment]
I just reinstalled the operating system 🤣 thanks anyway.
