### ISSUE TITLE
Conky 1.12.2 uses tolua++ from 3rdparty?

### ISSUE THREAD

**Issue by 0pLuS0** [brndnmtthws/conky#1181]
Hello,

In older Conky versions, if memory serves me correctly, we had to compile tolua++ in the past.

I noticed in 1.12.2 the 3rdparty directory with the toluapp directory.

So 1.12.2 still uses tolua++, it's just now included?

Thanks

**Comment by plikhari** [comment]
Yes that is correct - you do not need to install tolua++ separately.

Please close the issue, as it really is not, but a query - thanks

**Comment by 0pLuS0** [comment]
THANKS
