### ISSUE TITLE
Conky 1.10.8 to 1.15 - hwmon: Factor and offset do not work

### ISSUE THREAD

**Issue by rdschmidt** [brndnmtthws/conky#1187]
**Issue**

{hwmon 1 temp 1 1.0 20.0} do not work. Result is the same without factor and offset: {hwmon 1 temp 1}

conky.text = [[
1: ${hwmon 1 temp 1 1.0 20.0}
2: ${hwmon 1 temp 1}
]]
On Screen:
1: 40
2: 40

**Information**

OS testet: Linux Mint 20.03, Conky Version 1.10.8

Edit: also testet; Linux Mint 21, Conky Version 1.12.2

**Comment by hmeiser2000** [comment]
Also with Version: conky 1.11.3_pre compiled Do 28. Apr 08:07:17 CEST 2022 for Linux 5.17.4-arch1-1 x86_64

**Comment by rdschmidt** [comment]
Same behavior: conky 1.11.3_pre compiled Do 28. Apr 08:07:17 CEST 2022 for Linux 5.17.4-arch1-1 x86_64

**Comment by rdschmidt** [comment]
Same behavior with Conky 1.12.2 compiled 2021-04-25 for Linux x86_64.
Testet with latest conky Appimage.

**Comment by rdschmidt** [comment]
conky-x86_64.AppImage --version
conky 1.15.0 compiled 2022-10-16 for Linux x86_64

Factor and Offset still not working

**Comment by launacorp** [comment]
the factor must be given with a decimal comma "," not a decimal dot "."

it´s like ${hwmon 1 freq 1 0,001 0,0}

**Comment by rdschmidt** [comment]
I should have tried that myself :/
Thanks launacorp!

**Comment by rdschmidt** [comment]
Thanks to launacorp this is solved. 
As so often, the problem was sitting in front of the screen again
