### ISSUE TITLE
QUESTION: surely conky has a way of checking the username?

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [brndnmtthws/conky#1188]
Am I right in thinking that, strangely, it is impossible (without calling an external program) to do something like the following?

`${if_match "${username"=="susan"}\`

I know that one could have separate conkies for separate users. However: there can be call for running one and the same conky for all users and yet executing some commands only for some users.

Thanks.

**Comment by rdschmidt** [comment]
${if_match "${exec whoami}" == "username"}
   do something
${endif}

**Comment by LinuxOnTheDesktop** [comment]
Right, thanks; but I did write (did I not?)

> without calling an external program

- and that `exec` looks a little expensive for a Conky that updates approximately every second.

**Comment by rdschmidt** [comment]
But you have to use really old hardware to notice an additional load.

**Comment by LinuxOnTheDesktop** [comment]
Well, OK (though I have not done any benchmarks), but: (1) there is such hardware; (2) as a matter of principle efficiency is desirable.

**Comment by rdschmidt** [comment]
use LUA...

**Comment by LinuxOnTheDesktop** [comment]
Well, alright, though my `lua_load` file is now some six hundred characters long. I really think that an efficient username retrieval method ought to be built-into Conky. 'Pull requests welcome', I suppose . .

**Comment by rdschmidt** [comment]
function conky_currentuser ()
    local handle = io.popen("whoami")
    local user = handle:read("*a")
    handle:close()
    return (user)
end
____________________________
${lua currentuser}

**Comment by rdschmidt** [comment]
just noticed you have to truncate a trailing newline:
```
function conky_currentuser ()
    local handle = io.popen("whoami | tr -d '\n'")
    local user = handle:read("*a")
    handle:close()
    return (user)
end
```

**Comment by rdschmidt** [comment]
even easier:
```
function conky_currentuser()
    local result = os.getenv("USER")
    return (result)
end
```

**Comment by LinuxOnTheDesktop** [comment]
Thanks. Are you saying that one can place (all of) that stuff _in-line_ within Conky? If so then, how does one invoke it within Conky?

In my own use case I have come to find the following. I can adapt one of my existing lua files - invoked via `lua_load` - to do what I want to do with the username.
