### ISSUE TITLE
Error message doesn't say which script

### ISSUE THREAD

**Issue by Lowrida** [brndnmtthws/conky#1189]
When there pops an error in xsession-errors it only says "conky: blabla warning error danger", but not which window/script is creating this error? I have about 45 conky scripts running and an aditional 40 bash scripts.. and it is a pain in the ass to find which script creates which error!

I tried
own_window_class = with unique name
own_window_type = with unique name
own_window_name = with unique name

But none of them adds the name of the script to the error message.
Is this actually possible? To add a windowname or scriptname or some kind of name in the message? If not, maybe an idea to use own_window_name for that?

OS: Mint 20.3 with kernel 5.14
Conky: 1.10.8

**Comment by Lowrida** [comment]
Is this still alive?

**Comment by Lowrida** [comment]
I guess this is a dead end...

**Comment by su8** [comment]
You can use "echo" to number each script to find out which script is failing

**Comment by Lowrida** [comment]
I don't get it. In which way do i use echo?

**Comment by rubyFeedback** [comment]
I don't have an immediate solution but an indirect solution may be to add timestamped logs to each script and then check which ones create log messages; store the name of the file path too. And then deselect perhaps a batch of 5 and try anew.

Not the best solution but could help you find out which script is the faulty one.
