### ISSUE TITLE
master branch fails when "border_inner_margin = 0, border_outer_margin = 0, and border_width = 0".

### ISSUE THREAD

**Issue by arclance** [brndnmtthws/conky#12]
The master branch fails with
```
conky: desktop window (201) is root window
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  1 (X_CreateWindow)
  Value in failed request:  0x0
  Serial number of failed request:  1303
  Current serial number in output stream:  1308
```
when 
```
border_width = 0 
```
is used in conky.config.

I believe this is because it is trying to create the initial window with dimensions of 0x0 which is not allowed by X.

**Comment by arclance** [comment]
I have been told by someone who uses one of my Lua scripts that this affects Conky v1.10.x (the newly released version).

**Comment by Nooby4Ever** [comment]
I can confirm this still exists in the current master branch

**Comment by arclance** [comment]
I probably just needs a sanity check (are we trying to make a invalid window size window?) to handle this possibility (
I would guess you would just make it use 1x1 instead of 0x0 if 0x0 is asked for.
I don't know the language so I can't do it either.

**Comment by marcpayne** [comment]
@arclance Is this fixed for you in 1.10.1?

**Comment by arclance** [comment]
I can't configure it to build it so I can't test it.
```
CMake Error at cmake/ConkyPlatformChecks.cmake:144 (check_include_file):
   Unknown CMake command "check_include_file".
 Call Stack (most recent call first):
   CMakeLists.txt:37 (include)
```
Judging by #169 you need some kind of fallback behavior for cmake versions older than 3.4.0.
That is currently in Experimental in Debian and I am not installing any compiler from Experimental.

**Comment by arclance** [comment]
I figured out why it would not configure (missing include in "ConkyPlatformCheck.cmake") but I am now getting a linking failure (#174) so I still can't test it.

**Comment by arclance** [comment]
I was able to get it to build and can confirm that this fix worked.
