### ISSUE TITLE
Translating? Where?

### ISSUE THREAD

**Issue by heidiwenger** [brndnmtthws/conky#1206]
Where to translate? Is it this, yes? https://explore.transifex.com/almasa/conky-manager/ 

The project name doesn't match though and there is no description on that particular Transifex instance at all.

Thanks.

**Comment by brndnmtthws** [comment]
I'm guessing that project is for one of these: https://github.com/teejee2008/conky-manager or https://github.com/zcot/conky-manager2

Conky itself doesn't have any i18n support, but if someone wants to take that on I'd be happy to accept that PR.
