### ISSUE TITLE
Conky crash with malloc error + high bars in graph

### ISSUE THREAD

**Issue by Pip0une** [brndnmtthws/conky#1211]
**Issue**
Conky crash with this error : 

malloc(): smallbin double linked list corrupted 
aborted (core dumped)

And I have big bars from graph that shows memory leaks as per this previous issue : https://github.com/brndnmtthws/conky/issues/856

**Information**

POP_OS!
config : https://pastebin.com/ape1LaKE

the gdb is ongoing.

**Comment by brndnmtthws** [comment]
Can you try the latest build from git?

Here's a link to the appimage: https://github.com/brndnmtthws/conky/suites/8275774754/artifacts/362366347

Or just go to https://github.com/brndnmtthws/conky/actions/workflows/publish-appimage.yml and fetch the artifact from one of the most recent builds.

**Comment by brndnmtthws** [comment]
I also just published a release so you can grab that here: https://github.com/brndnmtthws/conky/releases/tag/v1.13.1
