### ISSUE TITLE
audacious add buttons (Play, Pause, Stop, Previous Track and Nex Track) in conky

### ISSUE THREAD

**Issue by visious25** [brndnmtthws/conky#1225]
Hi, is it posibole to setup buttons in conky without using lua scripts?

lua_load ~/.conky/lua/image.lua

template1 ${lua rc_button {btype=3,bname="button1",blx_off=160,bly_off=196,bw_off=20,bh_off=20}}
template2 ${lua rc_button {btype=3,bname="button2",blx_off=185,bly_off=196,bw_off=20,bh_off=20}}
template3 ${lua rc_button {btype=3,bname="button3",blx_off=210,bly_off=196,bw_off=20,bh_off=20}}
template4 ${lua rc_button {btype=3,bname="button4",blx_off=235,bly_off=196,bw_off=20,bh_off=20}}
template5 ${lua rc_button {btype=3,bname="button5",blx_off=257,bly_off=196,bw_off=20,bh_off=20}}

I found this guide here:
https://forums.bunsenlabs.org/viewtopic.php?id=3158

**Comment by brndnmtthws** [comment]
Conky does not currently support mouse interactions.

**Comment by visious25** [comment]
Hi all, I have one more question for you. Audacious doesn't display all track numbers of all tracks. Test the below command:

${color6}Track Number: ${color9}${alignr}${exec audtool --current-song-tuple-data track-number}

**Comment by Caellian** [comment]
[Mouse event support](https://github.com/brndnmtthws/conky/pull/955) has been implemented in the meantime. Though it might have [some bugs and quirks](https://github.com/brndnmtthws/conky/issues/1495). Simple buttons should definitely work though and is preferable (more performant and portable) than relying on externals scripts for same functionality.

Something like [widgets](https://github.com/brndnmtthws/conky/issues/1587) would be a good addition, but conky can now handle stuff that was previously handled externally (e.g. [ConkyClicky](https://github.com/netikras/ConkyClicky)) in a somewhat simpler way.

**Comment by Caellian** [comment]
Mouse events have been added, most issues that arose from that addition have been fixed. This allows adding buttons to conky. There are still some improvements when it comes to passing these events through on the way.

Wayland support will be added in the future.
