### ISSUE TITLE
own_window argb + imlib2 fails to render images properly (${image })

### ISSUE THREAD

**Issue by ghost** [brndnmtthws/conky#123]
I know this is a wide know problem which has been around for a while.
An attempt to fix is was made but not sufficient: https://github.com/brndnmtthws/conky/pull/84 from http://sourceforge.net/p/conky/bugs/317/ and was already mentioned in https://github.com/brndnmtthws/conky/issues/51

There exists a work around where the drawing is done in through Lua which works fine but since many people complain about this issue and it's rather old i tried to work towards an solution.

---

The solution from: https://github.com/brndnmtthws/conky/pull/84 works for some png files but not all, as mentioned by @ghost.

I've found a commit from another program (tint2) which had the same issue and solved the problem; their mention in the log file:

```
 - some launcher icons (PNG files saved with an indexed colormap and alpha mask) were sometimes rendered with white instead of transparency;
```

Which is pretty much the same issue Conky has with https://github.com/brndnmtthws/conky/pull/84 applied (I've tested it on the current master branch). 
This is what they did to solve it: https://gitlab.com/o9000/tint2/commit/e7c3f99e28d28539178679c4b3d1b46e793ec248

I have no knowledge of the imlib2 and next to none C/C++ but maybe some one with some insights in imlib2/Conky could port the solution to Conky, considering the changes they made were not very big and many people are experiencing  this issue.

---

I'm sorry for making another Issue for the same Issue but it thought this could lead towards a solution.

**Comment by mzpsh** [comment]
me too, latest on Arch Linux

**Comment by killua99** [comment]
bump

**Comment by D4void** [comment]
I encounter this problem with my conky meteo and png image. (with gnome shell)

Someone can tell me what is the work around with lua ?

**Comment by BrozzSama** [comment]
This issue is still present even in the latest release of conky, and it's more relevant than ever since now fake transparency suddenly stopped working on GNOME.

This is how a "dark" widget shows with transparency (without transparency it's just drawn with a black box around it)

![screenshot from 2017-05-03 00-08-54](https://cloud.githubusercontent.com/assets/10326497/25641518/cc0c70f0-2f94-11e7-925d-d38672afb4d8.png)

**Comment by Aaahh** [comment]
conky 1.10.7_pre compiled Thu Nov 16 23:54:34 EST 2017 for Linux 4.10.0-38-generic x86_64
affected

**Comment by lasers** [comment]
Closed via #682. Thank you very much for adding this! @dmccombs :slightly_smiling_face:

**Comment by dmccombs** [comment]
I'll be interested to hear from GNOME users if setting `draw_blended` to `false` corrects their transparency issues with ARGB now, in addition to the image transparency issues I had been having (on Enlightenment).

**Comment by xVanjaZ** [comment]
Oh my thank you so much! 
The documentation on Sourceforge (http://conky.sourceforge.net/config_settings.html) is not updated. `draw_blended` is not documented. I've been looking for HOURS.

Is there any way how we can update the docs?

**Comment by ArmoryFou** [comment]
Hey guys, if I render a png above another, the transparency goes through and it's not shown correctly, any idea how to fix it?

![image](https://github.com/brndnmtthws/conky/assets/104171628/e09c8215-6c0e-4751-b2ea-8137d86449f7)
