### ISSUE TITLE
Building docs without pandoc

### ISSUE THREAD

**Issue by kekePower** [brndnmtthws/conky#1247]
### What happened?

Building version 1.14.0 on Mageia Cauldron, which doesn't have pandoc, the build fails.

Is there a way to make building the docs configurable and use another program?

Build log: https://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20221012183555.kekepower.duvel.4064171/log/conky-1.14.0-1.mga9/build.x86_64.0.20221012183604.log

### Version

1.14.0

### Which OS/distro are you seeing the problem on?

Linux (other)

### Conky config

```Lua
N/A
```

### Stack trace

```GDB
N/A
```

### Relevant log output

```Shell
N/A
```

**Comment by brndnmtthws** [comment]
Pass `-DBUILD_DOCS=OFF` to CMake to disable the pandoc check.
