### ISSUE TITLE
Please remove pandoc

### ISSUE THREAD

**Issue by 0pLuS0** [brndnmtthws/conky#1254]
### What happened?

I'm running Slackware 15.0 and when I tried to compile 1.14.0 and I get this message at the term;

CMake Error at cmake/ConkyPlatformChecks.cmake:485 (message):
  Unable to find program 'pandoc'
Call Stack (most recent call first):
  CMakeLists.txt:35 (include)

I see in the doc README.md, pandoc listed.

So I'm not looking Slackware biased here, look at Arch Linux for pandoc; (Dependencies (74))

https://archlinux.org/packages/community/x86_64/pandoc/

74 dependencies needed for pandoc.

I guess for now I'm going to have to use -DBUILD_DOCS=OFF if I want to use this version, but I would like to have docs installed.

Can we please get this changed, since pandoc has an extreme amount of Haskell dependencies. I don't understand why from version 1.13.1 to 1.14.0 this had to change and now include this extreme amount of Haskell dependency just for docs.

THANKS

### Version

1.14.0

### Which OS/distro are you seeing the problem on?

Slackware 15.0

```P.S. Didn't mean to post this as an actual bug report, sorry.```

**Comment by brndnmtthws** [comment]
Pandoc is only used for generating the man page. If you're building from source, and you want the man page, then it requires Pandoc. If you don't need the man page, you can disable the docs.

I understand it's a bit annoying to pull all those dependencies, but I haven't found tool better than Pandoc for dealing with doc generation. Docbook (which was what we used before) leaves much to be desired, although admittedly it's much lighter than Pandoc.

**Comment by 0pLuS0** [comment]
I know Pandoc is for the man pages, but this is so extreme, there has to be a better solution then this.

I thought there are a lot of good alternatives out there, and I thought Docutils is still very commonly used...

What about these?

docbook-to-man
http://manpages.ubuntu.com/manpages/bionic/man1/docbook-to-man.1.html

AsciiDoc
https://docs.asciidoctor.org/asciidoctor/latest/manpage-backend/

GNU Troff
https://www.gnu.org/software/groff/

Sphinx
https://www.sphinx-doc.org/en/master/

Docutils
https://pypi.org/project/docutils/#files

**Comment by brndnmtthws** [comment]
Of those, I think the only tool close to being good is AsciiDoctor, but it's not nearly as good as Pandoc.

I want to keep the documentation sources in Markdown, so whatever tool/pipeline is used needs to be able to go from markdown -> man. AsciiDoc is its own thing that looks similar to but isn't quite markdown. Markdown is preferred because it's pretty ubiquitous at this point, relatively easy to use/write, and supported by a lot of different tooling.

**Comment by 0pLuS0** [comment]
It's been a while since I really played around with man.

Can't you simply convert it on your end, and just place in the source directories as an example man.1 and we simply gzip it on our end and be done with it?

THANKS

**Comment by brndnmtthws** [comment]
It sounds like you found a way. The warning at the end can be ignored.

**Comment by brndnmtthws** [comment]
> Here's the contents of my tar file, could you please tell me if this is all the docs and man?
> 
> ```
> usr/bin/conky
> usr/doc/
> usr/doc/conky-1.14.0/
> usr/doc/conky-1.14.0/AUTHORS
> usr/doc/conky-1.14.0/COPYING
> usr/doc/conky-1.14.0/LICENSE
> usr/doc/conky-1.14.0/LICENSE.BSD
> usr/doc/conky-1.14.0/README
> usr/doc/conky-1.14.0/README.cmake
> usr/doc/conky-1.14.0/README.docker
> usr/doc/conky-1.14.0/doc/
> usr/doc/conky-1.14.0/doc/.gitignore
> usr/doc/conky-1.14.0/doc/CMakeLists.txt
> usr/doc/conky-1.14.0/doc/README.md
> usr/doc/conky-1.14.0/doc/config_settings.yaml
> usr/doc/conky-1.14.0/doc/lua.yaml
> usr/doc/conky-1.14.0/doc/man.md.j2
> usr/doc/conky-1.14.0/doc/render.py
> usr/doc/conky-1.14.0/doc/variables.yaml
> usr/doc/conky-1.14.0/extras/
> usr/doc/conky-1.14.0/extras/CMakeLists.txt
> usr/doc/conky-1.14.0/extras/convert.lua
> usr/doc/conky-1.14.0/extras/gedit/
> usr/doc/conky-1.14.0/extras/gedit/README.md
> usr/doc/conky-1.14.0/extras/gedit/conky.lang
> usr/doc/conky-1.14.0/extras/nano/
> usr/doc/conky-1.14.0/extras/nano/README
> usr/doc/conky-1.14.0/extras/nano/conky.nanorc.j2
> usr/doc/conky-1.14.0/extras/vim/
> usr/doc/conky-1.14.0/extras/vim/README
> usr/doc/conky-1.14.0/extras/vim/ftdetect/
> usr/doc/conky-1.14.0/extras/vim/ftdetect/conkyrc.vim
> usr/doc/conky-1.14.0/extras/vim/syntax/
> usr/doc/conky-1.14.0/extras/vim/syntax/conkyrc.vim.j2
> usr/lib/
> usr/lib/libconky_core.a
> usr/man/
> usr/man/man1/
> usr/man/man1/conky.1.gz
> ```

What is this file listing from exactly? Most of the files under `usr/doc/conky-1.14.0` shouldn't be included in the package.

**Comment by 0pLuS0** [comment]
I just mentioned that is the contents of the tar file after I compiled conky.

My mistake, I added in the /doc & /extras directories by mistake.

Is there a -DCMAKE compile flag I can use that will look for pandoc in another path besides /usr? Since I'm going to use the precompiled binary and I'll just keep it with tthe conky source.

THANKS

**Comment by 0pLuS0** [comment]
Here's the contents of 1.14.0 now, after correcting my /doc mistake.
```
usr/bin/conky
usr/doc/conky-1.14.0/
usr/doc/conky-1.14.0/AUTHORS
usr/doc/conky-1.14.0/COPYING
usr/doc/conky-1.14.0/LICENSE
usr/doc/conky-1.14.0/LICENSE.BSD
usr/doc/conky-1.14.0/README
usr/doc/conky-1.14.0/README.cmake
usr/doc/conky-1.14.0/README.docker
usr/doc/conky-1.14.0/TODO
usr/lib/libconky_core.a
usr/man/man1/conky.1.gz
```
THANKS
