### ISSUE TITLE
{patch} conky crashes with a SEGV in a CPU hotplug environment

### ISSUE THREAD

**Issue by devsk** [brndnmtthws/conky#127]
There is a bug in conky code where it gets the number of CPUs at the startup and if the CPUs are added with hotplug, it SEGVs.

I noticed this because I hotplug remove the hyper-threaded CPUs (I can't disable HT at the BIOS level, its a Macbook). On resume from sleep, temporarily, all CPUs are enabled by kernel. So, conky tries to write for 8 CPUs to an array which it allocated only for 4 CPUs.

The attached patch just stops after the cpu_count, thereby fixing the SEGV.

**Comment by devsk** [comment]
--- src/linux.c.orig	2015-08-01 10:09:22.325049220 -0700
+++ src/linux.c	2015-08-01 10:24:11.775309236 -0700
@@ -738,6 +738,9 @@
 			} else {
 				idx = 0;
 			}
+			if (idx >= info.cpu_count) {
+				continue;
+			}
 			sscanf(buf, stat_template, &(cpu[idx].cpu_user),
 				&(cpu[idx].cpu_nice), &(cpu[idx].cpu_system),
 				&(cpu[idx].cpu_idle), &(cpu[idx].cpu_iowait),

**Comment by Nooby4Ever** [comment]
Why don't you make a pull request?

**Comment by brndnmtthws** [comment]
Please submit patches as pull requests.

**Comment by selurvedu** [comment]
@devsk Ping
