### ISSUE TITLE
[pointer] Proper UTF-8 support for scroller (no hacks)

### ISSUE THREAD

**Issue by andreas--e** [brndnmtthws/conky#129]
As this project has very much come back to life again (after a long (sort of) hiatus), I've decided to (re)open this old issue here because SF is the past and the great part of issues reported there will most likely remain unnoticed for the time being...
Original bug report here:
https://sourceforge.net/p/conky/bugs/341/

Yes, aidecoe's patch plus my dirty hack (which tackles the freeze-up issue) do work. But as all this is still very **experimental**, I'm hoping for someone of you gurus here to finally implement a proper fix so users may also use scroll texts in Cyrillic, Chinese or Japanese scripts. Thank you in advance.

**Comment by lasers** [comment]
Reportedly fixed by referenced pull requests.
