### ISSUE TITLE
[Bug]: Downspeedgraph and upspeedgraph are not working in a LUA file

### ISSUE THREAD

**Issue by johnvranos** [brndnmtthws/conky#1307]
### Possible bug of Conky 1.11 - 1.15

Good evening,

Congratulations for Conky, it is a very nice tool.

I have been using a Conky widget, named Lean Conky:

https://github.com/jxai/lean-conky-config

It is using downspeedgraph and upspeedgraph in a file named main.lua.

These two features work well up to version 1.10 of Conky. In versions 1.11 and later these features do not work.

downspeedgraph and upspeedgraph work OK in conky.conf, but not when used in that LUA source code file.

So I thought, perhaps it is a bug of the latest versions of Conky.

### Version

1.11 - 1.15 have the bug, so I am using version 1.10

### Which OS/distro are you seeing the problem on?

Linux (other)

**Comment by johalaoui** [comment]
Hello,

This will help you https://github.com/brndnmtthws/conky/pull/1315. You will need to build conky from main and set `store_graph_data_explicitly = false` in conky.conf.

**Comment by johnvranos** [comment]
I added the statement:

store_graph_data_explicitly = false

in the conky.conf file, of Lean Conky widget, and the widget works OK now indeed.

I added a comment, in the relevant bug report I had made, at Lean Conky site.

So, I close this bug report here.

**Comment by johnvranos** [comment]
My bad, adding the statement:

store_graph_data_explicitly = false

does not solve the issue with Conky 1.15.

The *graphs* still do not work.

**Comment by johnvranos** [comment]
I added the statement:

store_graph_data_explicitly = false,

in the:

conky.config = {

inside conky.conf file, of Lean Conky widget, and the widget works OK now indeed.

I added a comment with the solution, in the relevant bug report I had made, at Lean Conky site.

So I close this bug report here.

**Comment by johnvranos** [comment]
Not working with Conky 1.15.

I use Manjaro Linux, a rolling release, so I am waiting for Conky version 1.16 to become available in it soon.

**Comment by johnvranos** [comment]
> Hello,
> 
> This will help you #1315. You will need to build conky from main and set `store_graph_data_explicitly = false` in conky.conf.

I tested it with Conky 1.17, and it works.

Thank you very much.
