### ISSUE TITLE
[Bug]: changing scaling on wayland doesnt always re-scale conky correctly

### ISSUE THREAD

**Issue by stacyharper** [brndnmtthws/conky#1355]
### What happened?

I generally have a scale value to 1.6.

If I change it to 1 while conky runs, it overflow the output.
If I set it to 1 and then start conky, it got the expected dimensions.
Re-scaling from 1 to 1.6 seems to be okay.
So, down-scaling seems to be broken.

![](https://dav.missbanal.net/16ff9f9f-790b-444b-a920-aa70ef30a87e.png)

![](https://dav.missbanal.net/18da1b0c-78f3-4c31-9dfe-3ece4d2f5998.png)

![](https://dav.missbanal.net/ea54ba12-68b5-4e69-ac46-20ef9e251d26.png)

![](https://dav.missbanal.net/d7a86eaf-8cf2-45bd-9683-041ecb61aa10.png)

### Version

1.16.1

### Which OS/distro are you seeing the problem on?

Ubuntu

**Comment by brndnmtthws** [comment]
paging @bi4k8

**Comment by bi4k8** [comment]
The Wayland display backend does attempt to respond correctly to output scale events, but those correspond to the stable, non-fractional scaling protocol. I'm not sure how compositors (Sway here, it looks like) handle fractional scales for clients that don't support the new fractional scale protocol. It isn't a huge amount of work to implement fractional scale support in Conky, but I haven't looked into it yet, so any bug here right now is presumably related to support for non-fractional scaling.

I'll try poking at this in Sway with different starting scales and dynamic scale changes when I get a chance.

**Comment by stacyharper** [comment]
Client just receive a scaling rounded to the highest value. Here I think
conky receive "2".

**Comment by bi4k8** [comment]
It looks like we weren't actually resizing the window in response to dynamic scale changes. PR incoming.
