### ISSUE TITLE
[Bug]: changing own_window_argb_value setting has no effect

### ISSUE THREAD

**Issue by oldrust** [brndnmtthws/conky#1416]
### What happened?

In Conky 1.18 (with X11 backend) changing own_window_argb_value doesn't have any effect, the window is always transparent. Version 1.17 works fine. 

### Version

1.18.0

### Which OS/distro are you seeing the problem on?

Arch Linux

### Conky config

```Lua
        own_window = true,
        own_window_type = 'normal',
	own_window_class = 'conky_panel',
--  own_window_colour = '302424',
	own_window_transparent = false,
	own_window_hints = 'undecorated,below,skip_taskbar',
	own_window_title = 'Panel',
	own_window_argb_visual = true,
	own_window_argb_value = 144,
```

**Comment by tecnosegugio** [comment]
Same here.

Using Debian Sid, GNOME 43.3, Xorg 7.7, conky 1.18.0.

If I set:
own_window_colour = 'FFFFFF' 
own_window_argb_value = <any value>
the background become white with no trasparency.

With 
own_window_colour = '000000' 
own_window_argb_value = <any value>
I was expecting the background to become black but instead I got a full transparent background regardless the argb value.

**Comment by brndnmtthws** [comment]
Likely a regression introduced by #1390, cc @bi4k8.
