### ISSUE TITLE
[Bug]: The colors of up/down speedgraphs is  now locked in to the default_color rather than the configured colors. Perhaps something changed that I didn't catch?

### ISSUE THREAD

**Issue by brndnmtthws** [brndnmtthws/conky#1417]
The colors of up/down speedgraphs is  now locked in to the default_color rather than the configured colors. Perhaps something changed that I didn't catch?

_Originally posted by @johnmc98683 in https://github.com/brndnmtthws/conky/discussions/1409#discussioncomment-5064962_

**Comment by misterhsp** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1031736

**Comment by brndnmtthws** [comment]
Possibly a regression due to #1390.

**Comment by sej7278** [comment]
ah, i was just about to raise a debian bug myself.

downgrading to 0.17 gives the gradient behaviour back (its not a wayland thing as i assumed, tried x11 to no avail)

**Comment by iestynapmwg** [comment]
Came here looking for a solution to the same bug... up/down and CPU graphs are all white for me now, too. So far, all i've found is similar bug reports. Is there a fix?

**Comment by bi4k8** [comment]
Should be fixed in #1418; testers welcome.

**Comment by misterhsp** [comment]
works, thank you

...
