### ISSUE TITLE
[Bug]: cpugraph/memgraph colour is always red

### ISSUE THREAD

**Issue by loshz** [brndnmtthws/conky#1424]
### What happened?

I noticed that after upgrading from 1.17 -> 1.18.1 that my `cpugraph` and `memgpaph` always render in red regardless of how I change the colour settings. I haven't changed my config in a while, and I noticed a refactor to the colour implementation, however I'm not seeing a config setting I'm missing.

### Version

1.18.1

### Which OS/distro are you seeing the problem on?

Arch Linux

### Conky config

```Lua
conky.config = {
    alignment = 'top_left',
    background = true,
    border_width = 0,
    cpu_avg_samples = 8,
    default_graph_height = 30,
    default_graph_width = 0,
    default_color = '#121212',
    default_outline_color = '#121212',
    default_shade_color = '#121212',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'Hack:size=11',
    gap_x = 15,
    gap_y = 45,
    if_up_strictness = 'address',
    minimum_height = 0,
    minimum_width = 400,
    maximum_width = 400,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    own_window = true,
    own_window_transparent = true,
    own_window_class = 'Conky',
    own_window_type = 'override',
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    top_name_width = 10,
    update_interval = 3,
    update_interval_on_battery = 5,
    uppercase = false, 
    use_spacer = 'none',
    use_xft = true,
}
```

**Comment by brndnmtthws** [comment]
Can you provide an example of your graph colour configuration?

**Comment by brndnmtthws** [comment]
While it doesn't solve the problem, I've created https://github.com/brndnmtthws/conky/pull/1426 so we can add some tests around this once we figure out what's going on.

Perhaps @bi4k8 knows where the issue is.

**Comment by loshz** [comment]
> Can you provide an example of your graph colour configuration?

I have no other settings. I just use `${cpugraph -l -t}` in my conky.text block.

**Comment by frankspace** [comment]
I also just upgraded from 1.17 to 1.18.1, and I am encountering the exact same problem with diskiograph.

My previous configuration was just `${diskiograph /dev/nvme0n1 7 -l}`, and that worked fine, the color was black as expected and the height was correct.  It looked like this:

![diskiograph_old](https://user-images.githubusercontent.com/13141709/221367123-70b17d31-d753-4340-9039-201f267e4076.png)

After the upgrade, that results in the color being entirely red as reported by loshz, and also the graph becoming weirdly tall.

I tried changing it to `${diskiograph /dev/nvme0n1 10,275 000000 -l}`, which resulted in it looking like this:

![diskiograph](https://user-images.githubusercontent.com/13141709/221366111-a11ad778-c91f-48a5-80f5-6354e4dd39c2.png)

...so now one end is black as it should be, and the height is as specified (yeah, I changed it from 7 to 10), but the other end is still red.

Notes: I tried putting `${color black}` in front of it, that had no effect.  I tried changing the color code to `000000,000000`, that also had no effect.  Omitting the color code entirely results in the graph going back to all red and being improperly tall; it seems to just ignore the height specification entirely or something (probably that's a separate bug entirely, but I figured I'd mention it just in case it's related).

My configuration section has not been updated in a very long time, and it looks like this:

```
conky.config = {
	text_buffer_size = 1536,
	alignment = 'top_left',
	maximum_width = 275,
	minimum_width = 275,
	gap_x = 3,
	gap_y = 3,
	background = true,
	own_window = true,
	own_window_title = 'Conky',
	own_window_type = 'normal',
	own_window_hints = 'undecorated,skip_pager,below,sticky,skip_taskbar',
	own_window_transparent = true,
	own_window_colour = 'gray85',
	draw_borders = false,
	draw_graph_borders = false,
	draw_outline = false,
	draw_shades = false,
	double_buffer = true,
	update_interval = 1.0,
	use_xft = true,
	pad_percents = 2,
	default_color = 'black',
	font = 'Input:size=8.5',
};
```

I also noticed there were some commits changing how color is implemented, but I'm nowhere near a good enough programmer to have the vaguest idea what any of it meant.  Also, if it has any diagnostic worth, I use X11, I do _not_ use Wayland.

**Comment by brndnmtthws** [comment]
@frankspace really appreciate the detailed response, thanks!

Hopefully @bi4k8 can sort it out quickly, but if not I'll get to it when I can.

**Comment by loshz** [comment]
Apologies for my lack of detail. AFK atm and replying from my phone.

Happy to upload some logs or do some debugging when I get back to my machine if that'd be helpful!

For the record, I'm also on X11

**Comment by servimo** [comment]
Maybe this will help you: https://github.com/brndnmtthws/conky/issues/1428

**Comment by frankspace** [comment]
I can confirm that the link posed by servimo works.  When I change my line to the following:

`${diskiograph /dev/nvme0n1 10,275 #000000 #000000 -l}`

I now get the expected all-black color.

I realize it's not my call to make, but I'm not sure at this point that I'd call this a _bug_, because the functionality is all present and accessible (and even expanded on), but I definitely think the documentation needs to be updated to reflect these changes.

**Comment by loshz** [comment]
I also used the solution outlined in #1428 and can confirm this works.

However, after re-reading the docs I think 1.18.1 _is_ working as expected. I noticed I was passing the `-t` flag without specifying colours. I don't actually use the temperature flag, so if I remove it and just use `${cpugraph -l}` then the graph uses the `default_color` settings as expected.

Happy to close this as user error, but feel free to re-open if needed.
