### ISSUE TITLE
pre_exec doesn't work. Is there an alternative?

### ISSUE THREAD

**Issue by txtsd** [brndnmtthws/conky#146]
I need this to work `${pre_exec lscpu | grep -i "model name" | cut -c 24-}` but only once. It does not change so I need it to run once at the beginning.

**Comment by maxiwell** [comment]
In conky 1.9, I used ``$(pre_exec lsb_release}`` too. Why the ``pre_exec`` was removed in 1.10?

**Comment by Nooby4Ever** [comment]
This was already discussed here: #62 (2.0pre is the current 1.10) So maybe you can close this one and continue the discussion there.
Basically, there is no replacement and you should use Lua or use a very large interval and execi.

I'm not sure why it was removed either.

**Comment by lasers** [comment]
Duplicate #62. Closing.
