### ISSUE TITLE
out_to_console / out_to_x ineffectual; always outputs to X

### ISSUE THREAD

**Issue by AlexArendsen** [brndnmtthws/conky#147]
With these settings:

    conky.conky = {
    ...
    out_to_console = true,
    out_to_x = false,
    ...
    }

Conky text is still written to X display, the following is written to to stdout:

    conky: desktop window (1200003) is subwindow of root window (d4)
    conky: drawing to desktop window

(Tested on XFCE (xfwm) and i3)

**Comment by marcpayne** [comment]
There is a typo in the first line of your config. It should be `conky.config = {`.

**Comment by AlexArendsen** [comment]
Oh shoot-- yup, that was the issue. Sorry about that + thanks!
