### ISSUE TITLE
[Bug]: out_to_x = false causes startup failure

### ISSUE THREAD

**Issue by philer** [brndnmtthws/conky#1479]
There are two parts to this issue, that I assume are related.

### 1.
When setting `out_to_x = false` with no other output related settings, conky fails to start and logs the following error:
```
conky: invalid setting of type 'table'
Unable to find a usable display output.
conky: initialize_display_outputs() failed.
```
Example config:
```Lua
conky.config = { out_to_x = false }
conky.text = "foo"
```

Evidently conky is not happy that it's not allowed to output anywhere.

You may argue that there is no point in running conky like this.
I do however use it to run tests for my lua widget library [polycore](https://github.com/philer/polycore). The test files are conky configs that are rendered to image files, rather than outputting anything. See [this example](https://github.com/philer/polycore/blob/master/test/test_layout.lua)

### 2.
When adding `out_to_console = true` conky starts successfully but still logs the first line of the error above:
```
conky: invalid setting of type 'table'
```
Example config:
```Lua
conky.config = {
    out_to_x = false,
    out_to_console = true,
}
conky.text = "foo"
```
### Version

1.18.3

### Which OS/distro are you seeing the problem on?

Linux Mint 21.1

**Comment by bi4k8** [comment]
I think this bug would be clearer if named "out_to_x = _false_ causes startup failure".
