### ISSUE TITLE
Lua functions in .conkyrc

### ISSUE THREAD

**Issue by chneukirchen** [brndnmtthws/conky#149]
Since 1.10 .conkyrc is a lua file, but it seems custom functions still need to be defined in a seperate file and loaded with lua_load, wouldn't it make sense to define them in .conkyrc already?

**Comment by lasers** [comment]
@plikhari may be able to answer this question. He's a black belt in using Lua scripts in conky. :crossed_swords:

**Comment by plikhari** [comment]
>  it seems custom functions still need to be defined in a seperate file and loaded with lua_load, wouldn't it make sense to define them in .conkyrc already?

It is simply not a good idea to imbed LUA scripts inside a configuration section as this will most likely make the config section in `.conkyrc` file very difficult to parse.

`lua_load` is like an import statement within the config section.

Trust this answers your query.

**Comment by lasers** [comment]
@plikhari Thanks for the good explanation.

@chneukirchen I'm here to close issues. The person who implemented nice Lua support in conky hasn't been active on GitHub. I don't know the reasons, but I'll ping @labath to see if we can get a response and/or a pull request to remedy this issue. If nothing, we can close this in a month.

Trust this satisfies your question.
