### ISSUE TITLE
[Docs] Graph scale format

### ISSUE THREAD

**Issue by maxsupermanhd** [brndnmtthws/conky#1493]
Documentation lacks (essential) information about built-in graph scale format. Are values in bytes, kilobytes or some other format?

**Comment by Caellian** [comment]
`show_graph_scale` value is a float representing a ratio. So a value of `1` means no scaling, `1.5` is 1.5× the size, etc.

A lot of functionality could make use of better documentation, but it's a lot of work. It's also best to do in bulk or while adding new features. That being said, I think "scale" in the name reflects the meaning/purpose well enough, even though the description:
> Shows the maximum value in scaled 

is a bit misleading.

**Comment by Caellian** [comment]
Closing in favor of #1800.
