### ISSUE TITLE
conky doesn't set hints on override_redirect windows

### ISSUE THREAD

**Issue by Airblader** [brndnmtthws/conky#150]
When using `own_window_type = "override"`, conky doesn't set any window hints (deliberately). This can be seen [here](https://github.com/brndnmtthws/conky/blob/master/src/x11.cc#L654).

There is no reason why conky should not set these hints and in fact it is an obstacle in certain situations. The window may not be managed, but tools such as xdotool or compton should still have a way of identifying the window. Hints such as WM_CLASS should be set either way. In fact I don't think setting all the same hints would hurt, even if it may contain unnecessary information.

**Comment by Airblader** [comment]
From the EWMH spec:

> Override-redirect windows are ignored by traditional window managers, but not by compositing managers. Compositing managers are responsible for painting all windows to the screen, including override-redirect windows.

> To enable compositing managers to decorate override-redirect window properly, for example by making them translucent or by changing the shape of the windows, this spec allows clients to set properties on override-redirect windows indicating the function of the windows.

**Comment by lasers** [comment]
I don't know C/C++ and I'm here to close issues. Do you want to make a PR to address this? Thx. :-)

**Comment by Airblader** [comment]
I don't have time to work on this (and also no longer use conky), but it should be a relatively simple fix, so it'd be a good beginner issue!

**Comment by phenixia2003** [comment]
Hello,

In attachment a patch that (only) sets WM_CLASS hint when own_window_type=override. 

Can be usefull for anyone who use conky (with own_window_type=override) and compton and want to exclude shadow on conky with the simple rule "class_g ?= 'conky'".

[conky-set-wmclass-on-override.patch.txt](https://github.com/brndnmtthws/conky/files/4428204/conky-set-wmclass-on-override.patch.txt)

-- 
SeB
