### ISSUE TITLE
Add vertical scroll

### ISSUE THREAD

**Issue by murrayf** [brndnmtthws/conky#151]
Hello,

I find conky very useful, but there's one variable I'm not sure if exists... I'd like developers to implement vertical scroll for text, because sometimes can save space, and text sometimes overlaps other widgets, it could make also  widgets more productive. A scrolling text from bottom to top of the selected area would be very appreciated.

Thanks a lot,

Alberto.

:)

**Comment by kaptoxic** [comment]
+1 for this, it would be a good addition

**Comment by psilogroup** [comment]
+1 for this stuff
