### ISSUE TITLE
[feature request] support for atom rss feeds...

### ISSUE THREAD

**Issue by murrayf** [brndnmtthws/conky#152]
Thanks,

Alberto.

:)

**Comment by mswanson-me** [comment]
Marked as an 'enhancement'. 

You may also consider alternative methods for displaying Atom feeds by way of a shell script, for instance.

**Comment by murrayf** [comment]
OK. Thanx.Alberto.-------- Mensaje original --------Asunto: Re: [brndnmtthws/conky] [feature request] support for atom rss feeds... (#152)De: Michael Swanson Para: brndnmtthws/conky CC: Alberto Segura ,Author Marked as an 'enhancement'.
You may also consider alternative methods for displaying Atom feeds by way of a shell script, for instance.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/brndnmtthws/conky","title":"brndnmtthws/conky","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/brndnmtthws/conky"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mswanson-me in #152: Marked as an 'enhancement'. \r\n\r\nYou may also consider alternative methods for displaying Atom feeds by way of a shell script, for instance."}],"action":{"name":"View Issue","url":"https://github.com/brndnmtthws/conky/issues/152#issuecomment-368696270"}}}

**Comment by lasers** [comment]
Two years 10 months 1 week passed. Do you still require this feature? Let us know. Many thanks.

**Comment by murrayf** [comment]
I don't need it now. It was only an idea. Thanks.
-- Alberto --

**Comment by lasers** [comment]
It is a great idea. I leave this to @su8 to decide what he want to do here.

_To atom, or not to atom: that's the question._  :atom_symbol:

**Comment by murrayf** [comment]
Ok. Thank you.
-- Alberto --

**Comment by plikhari** [comment]
You are looking for this - RSS in [smooth scrolling conky window](https://image.ibb.co/guA7se/Screenshot_2018_08_18_18_26_05.png) this is done in LUA+Cairo. With LUA as the scripting language for conky - it opens a whole new vista for people to be creative.

**Comment by murrayf** [comment]
Thank you too, Paramvir...
:)
-- Alberto --

**Comment by su8** [comment]
@lasers It's much more easier to do parsing in scripting languages such python/perl/ruby/lua than in C.

Just for reference there are [161 python repositories](https://github.com/search?l=Python&o=desc&q=rss+parse&s=stars&type=Repositories) that do rss parsing.

Just look at the table to the left how many languages do rss parsing and their repositories, pick the language that you are most familiar with and go with it. Most repos provide usage examples so even if @murrayf doesn't know any scripting language he can use the examples in the repos as starting point.

**Comment by lasers** [comment]
@su8 Right you are. That's a great idea. I see you console heart some of the atom tools too. Wink, wink.

@murrayf It is most likely better to `execi 1800` scripts and/or atom polished tools as @su8 suggested... instead of having him implement something very basic and/or poor atom support in conky.

Also, the users can control feed output better by not depending on small number of atom variables and/or objects. Thank you for this great idea too. :-)
