### ISSUE TITLE
conky ubuntu fix

### ISSUE THREAD

**Issue by skypce** [brndnmtthws/conky#159]
Hello i want contribute with a little guide for ubuntu 14.04. 
https://sites.google.com/site/conkyfixforubuntu/

**Comment by lasers** [comment]
I don't know what you're trying to fix, but the page looks nice. If you want to contribute more, you can help out with the [wiki](https://github.com/brndnmtthws/conky/wiki) and/or report bugs. Thanks. Also, we're on Ubuntu 18.04.1 LTS now. :-)
