### ISSUE TITLE
[Bug]: Problems building with 'ccmake ..' on MacOS

### ISSUE THREAD

**Issue by Lssg97** [brndnmtthws/conky#1600]
### What happened?

Hi guys,

I've seen the content in #1348, but the information I searched on the Internet is too little to solve this problem independently.

I also got the "Unable to find freetype library" error. I'm using a 2020 MacBook Pro with M1 (Ventura 13.4.1). All dependencies have been installed according to the method introduced in the wiki. But this error still occurs when executing `ccmake ..`.

The following shows the screenshots of the errors I encountered, as well as the versions of the dependent software:
<img width="1082" alt="屏幕快照 2023-07-13 22 56 15" src="https://github.com/brndnmtthws/conky/assets/47817993/639bfa14-335f-4b6e-aad1-4028c1f59ec0">
<img width="1082" alt="屏幕快照 2023-07-13 23 01 24" src="https://github.com/brndnmtthws/conky/assets/47817993/1eda2746-4e6e-4bf2-808d-32e07b9998da">
PS: The information I found on the Internet is that this library is related to PHP, but there is freetype in the installed dependencies, so I guess these messages may have nothing to do with the problems I encountered.

### Version

v1.19.2

### Which OS/distro are you seeing the problem on?

macOS

**Comment by brndnmtthws** [comment]
Can you paste the result of `grep -i 'freetype\|fontconfig' CMakeCache.txt` from the build dir?

**Comment by Lssg97** [comment]
Thanks for your reply, the results I got after running this string of commands are as follows:
`//Build Xft (freetype fonts) support`

**Comment by Lssg97** [comment]
> What if you run `pkg-config --libs freetype2`?

I got this：`-L/opt/homebrew/opt/freetype/lib -lfreetype`

**Comment by brndnmtthws** [comment]
Try setting [`CMAKE_PREFIX_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html#variable:CMAKE_PREFIX_PATH) to `/opt/homebrew`, i.e., `ccmake -DCMAKE_PREFIX_PATH=/opt/homebrew`, then hopefully cmake will pick it up.

**Comment by Lssg97** [comment]
> Try setting [`CMAKE_PREFIX_PATH`](https://cmake.org/cmake/help/latest/variable/CMAKE_PREFIX_PATH.html#variable:CMAKE_PREFIX_PATH) to `/opt/homebrew`, i.e., `ccmake -DCMAKE_PREFIX_PATH=/opt/homebrew ..`, then hopefully cmake will pick it up.

I noticed that the command you gave seemed to miss a space. I fixed it, but unfortunately the miracle didn't happen, and the build still showed the same error. 
The content given by CMakeCache.txt has not changed.

**Comment by Lssg97** [comment]
A little progress:

I found some information in [this webpage](https://qa.1r1g.com/sf/ask/1112874941/), combining the directory address returned by `pkg-config --libs freetype2` and the variables given in the "**ConkyPlatformChecks.cmake**" file , I used `cmake -DFREETYPE_INCLUDE_DIR_freetype2=/opt/homebrew/opt/freetype/include/freetype2 ..` command, and finally passed the *freetype* library check, but encountered the next library missing problem...
<img width="1082" alt="截屏2023-07-29 12 11 51" src="https://github.com/brndnmtthws/conky/assets/47817993/5f495425-955b-4aaf-a18c-0fecbea5ef7b">
Now I have two questions are:
1. What command should I use to find this library file called *Xft*?
2. Is it feasible to directly define the variables from the .cmake file, and will there be problems during construction? I noticed a change in the log related to "freetype": 
```
//Build Xft (freetype fonts) support
FREETYPE_INCLUDE_DIR_freetype2:UNINITIALIZED=/opt/homebrew/opt/freetype/include/freetype2
```

**Comment by Lssg97** [comment]
I used Homebrew to install two libraries not mentioned in the **Wiki**: `brew install libxft libxinerama`. After this I was able to build directly with `cmake ..` without setting any variables. The subsequent installation also went smoothly. Currently it shows:

<img width="607" alt="截屏2023-07-31 12 48 30" src="https://github.com/brndnmtthws/conky/assets/47817993/ce5d4c27-f710-4467-a950-f5267fb57e17">

My Mac is just bought and not used for a long time, the system is still very clean. So I think the content in the **Wiki** should be updated.

One more thing: I cannot build using `ccmake..` but only `cmake..`. Only in this way can the correct *Makefile* be generated in the build directory, and the former has two files less than the latter.

<img width="1305" alt="截屏2023-07-31 12 43 49" src="https://github.com/brndnmtthws/conky/assets/47817993/d8286169-22e6-421c-a603-d4a64796f20d">

Anyway, I can now finally start trying to configure it. ヾ(✿ﾟ▽ﾟ)ノ

**Comment by Lssg97** [comment]
I have solved the last problem: `conky: can't open display:`

At this point, I have probably solved all the problems of building Conky on MacOS.

If you want to build Conky on a fresh Mac, at least the following dependencies need to be installed:

`brew install cmake freetype gettext lua imlib2 pkg-config libxft libxinerama xquartz`

I finally saw the default configuration displayed on my desktop, it was a long process...

<img width="1440" alt="截屏2023-08-06 21 09 57" src="https://github.com/brndnmtthws/conky/assets/47817993/9985bbac-bcfd-4379-a6bf-33ba3954050f">
