### ISSUE TITLE
problem with syntax

### ISSUE THREAD

**Issue by t0m5k1** [brndnmtthws/conky#164]
I have been running conky for god knows how long & now I upgrade to 1.10 & it appears my config is incorrect:

conky -c .conkyrc-i3 -D  
DEBUG(0) [/build/conky/src/conky-1.10.0/src/conky.cc:2671]: reading contents from config file '.conkyrc-i3'
conky: Syntax error (.conkyrc-i3:18: ']' expected near ':') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: [string "..."]:138: attempt to index a nil value (local 'settings')

line 18:
{"full_text":" ${scroll 25 5 ${mpd_smart}} ${mpd_percent}%/${mpd_length} ${mpd_bar 5,5} ${mpd_bitrate}kbps  ${mpd_vol}  " , "color" : "#ff7c01"}  ,

here is my fill config:
out_to_x = no
own_window = no
out_to_console = yes
double_buffer = no
background = no
update_interval = 1
total_run_times = 0
short_units = no
if_up_strictness = address
use_spacer = right
override_utf8_locale = yes
use_xft = yes
cpu_avg_samples = 2
pad_percents = 2

TEXT
[
{"full_text":" ${scroll 25 5 ${mpd_smart}} ${mpd_percent}%/${mpd_length} ${mpd_bar 5,5} ${mpd_bitrate}kbps  ${mpd_vol}  " , "color" : "#ff7c01"}  ,
{"full_text":" ${execpi 180 ~/.conky/scripts/gmail.sh}  " , "color" : ${if_match ${execpi 180 ~/.conky/scripts/gmail.sh}>0}"#FF0000"${else}"#ffffff"${endif} }  ,
{"full_text":" ${downspeed eth0}:${totaldown eth0}  ", "color" : "#0ffd00" }  ,
{"full_text":" ${upspeed eth0}:${totalup eth0}  ", "color" : "#fd0000" }  ,
{"full_text":" ${fs_free /}  ", "color" : ${if_match ${fs_used_perc /}>75}"#FF0000"${else}"#769ebb"${endif} }  ,
{"full_text":" ${if_mounted /home}${fs_free /home}  ", "color" : ${if_match ${fs_used_perc /home}>75}"#FF0000"${else}"#769ebb"${endif}$endif }  ,
{"full_text":" ${if_mounted /public}${fs_free /public}  ", "color" : ${if_match ${fs_used_perc /public}>75}"#FF0000"${else}"#769ebb"${endif}$endif }  ,
{"full_text":" ${cpu}% @${exec sensors | grep 'Core0' | cut -c16-19 | sed '/^$/d' }°C  " , "color" : ${if_match ${exec sensors | grep 'Core0' | cut -c16-19 | sed '/^$/d' }>70}"#FF0000"${else}"#ffec01"${endif} }  ,
{"full_text":" ${memperc}% ${mem}  " , "color" : ${if_match ${memperc}>50}"#bf3f34"${else}"#ffec01"${endif} }  ,
{"full_text":" ${loadavg}  ", "color" : "#ffec01"}
],

It has worked for ages as my i3 status bar but now it is not & I can't find any reference page to help me convert to the new syntax ...I'm lost & can't downgrade.
Please help

**Comment by txtsd** [comment]
1.10 has a new config format
https://github.com/brndnmtthws/conky/wiki/Configuration-Settings
https://github.com/brndnmtthws/conky/wiki/Configuration-Variables

**Comment by lasers** [comment]
Presumably, this problem was solved years ago. Closing.
