### ISSUE TITLE
[Bug]: general protection fault in liblua5.3.so.0.0.0

### ISSUE THREAD

**Issue by babiulep** [brndnmtthws/conky#1645]
### What happened?

Succesfully compiled conky 1.19.5 with GCC 12.3.1 on Ubuntu 20.04.6 LTS.

But when running it I get the following error: see Relevant log output
Conky does not start with a lua_load in it's config, otherwise it runs fine.

This does not occur with version 1.19.4.

I've checked some of the changes between the 2 releases and 'decided' to revert commit 68ac284 (3rdparty/toluapp/src/bin/lua/package.lua) on the 1.19.5 source.

After that conky also compiles AND runs OK with lua_load in it's config...

### Version

1.19.5

### Which OS/distro are you seeing the problem on?

Ubuntu

### Relevant log output

```Shell
traps: conky[858118] general protection fault ip:7f30a8b7446f sp:7ffe21cbc8a0 error:0 in liblua5.3.so.0.0.0[7f30a8b64000+24000]
```

**Comment by brndnmtthws** [comment]
Could you test #1646? It should be a more robust fix that doesn't break build reproducibility.

**Comment by babiulep** [comment]
Yes! This seems to work fine... No general protection fault and running OK!

**Comment by jjgomera** [comment]
with 1.19.5 I had to change config file to lua version, with 1.19.6 i can run again lua script but cairo must be realocated using the fixing from [here](https://github.com/brndnmtthws/conky/issues/1389#issuecomment-1751578600)
