### ISSUE TITLE
[Web] High CPU usage by LineChart component

### ISSUE THREAD

**Issue by elamperti** [brndnmtthws/conky#1669]
The LineChart component of the website looks nice but it consumes _a lot_ of CPU. Replacing it with a simple image or a gif should be enough to solve this.

Fixing this issue should not only reduce the CPU usage to normal levels, but also decrease the bundle size, since the D3 library wouldn't be necessary anymore.

**Comment by brndnmtthws** [comment]
Yeah it's a bit of a gimmick, though I hadn't noticed an issue with CPU usage (it may be somewhat dependent on browser/settings/GPU/etc). If it's annoying people then I will just remove it.

**Comment by elamperti** [comment]
I'm using Firefox with a Ryzen 9 processor, enough RAM (no swap) and a Nvidia RTX 3080 card. It's not CPU-blocking, but I definitely see some cores fire up.

Sadly I don't have the time to setup the site locally and try to fix this myself at the moment, but here are a few things I've noticed in the component that could be improved:
- The usage of `localStorage` + `JSON.stringify()` on each `doIt()` call is probably hurting performance a lot. I'd recommend just not using localStorage for this, let the data generate from scratch
- I'm not familiar with D3, but using transitions could be resource intensive. From what I can see on the page, it seems to shrink/grow the bars after they shift to the left, which is a very subtle change. Perhaps this transition can be removed without too much impact on the result
- The recursive call to `doIt()` using `setTimeout` could be simplified using `setInterval()` (I don't think this will make noticeable improvements in perf though)

Hope this helps :)
