### ISSUE TITLE
Conky fails to build with ncurses if ncurses itself is built with the terminfo option

### ISSUE THREAD

**Issue by billie80** [brndnmtthws/conky#167]
This is because if ncurses is built with the terminfo option the curses library (libncurses) is built separately from the low-level terminfo library (libtinfo) and stdscr is defined in libtinfo but conky does not link against it.

I opened a bug about this at sourceforge already. This was: http://sourceforge.net/p/conky/bugs/446/. However the patch provided there was for autotools. The build failure is still there with the cmake build system.

**Comment by lasers** [comment]
Resolved by #254.
