### ISSUE TITLE
painting images from imlib2 with cairo

### ISSUE THREAD

**Issue by wujek-srujek** [brndnmtthws/conky#17]
I noticed there is some new functionality to paint images from imlib2 with cairo. I build conky today from master and it seems not to work properly, or I'm doing things wrong. When I scale an image down, the transparency in png or gif does not work and the background is black. If I scale a png up, I get quite a few funny artifacts.
Also, the new function as of now just allows to paint an image with full opacity, I think. It would be much better to allow users to set custom transparency as well. Actually, the best thing would be to allow the call:
local surface = cairo_image_surface_create_for_data(imlib_image_get_data_for_reading_only(), ..
to work fine. Currently I always get the errors that argument #1 is userdata but should be string - I guess that's because the cairo functions takes unsigned char\* and tolua++ needs a string there? (I guess that's the main reason for the function, but I am not sure.) As I have little idea about c or c++, even less about lua and don't know nothing about tolua++, I am not sure if this is doable.

**Comment by mswanson-me** [comment]
Is this issue still outstanding in the current version of Conky? If so, please update this issue. Otherwise, the issue will be closed in 2 weeks.

**Comment by zcot** [comment]
As far as I can tell the aforementioned example doesn't work. See random sample here: https://gist.github.com/wxg4net/7210517

It is possible to use the imlib2 stuff but I'm not aware of being able to intermix it with cairo like that exactly. You can do transparency with imlib but are limited once you don't have png specifically, and I'm not aware of any cairo transparency image function directly, so you need to mix them, and it may not be possible.

Is there any documentation on that issue directly?

If someone wants a non-png watermark, is it possible? Can you directly use a jpg as a transparent image?

**Comment by lasers** [comment]
@plikhari Are you able to help here?

**Comment by plikhari** [comment]
From what I have understood - `cairo` does not use `imlib2` - and `cairo` needs to interact with `lua` - and so far the support is only for `png` images. 

Most people look at `cairo` with `python` or `c` bindings and get all excited - but here we have cairo with lua bindings - to put things into perspective.

So if we have images that are non `png` - I use `Imagemagick` to manipulate and display it with lua + cairo.

We can close this as it is beyond the scope of `conky + lua + cairo` at present time.
