### ISSUE TITLE
old text remains under new refresh

### ISSUE THREAD

**Issue by john-walsh** [brndnmtthws/conky#171]
Here is a screen shot of the problem:

http://snag.gy/jqh7j.jpg

Seams that the text from the 'previous' update remains and is drawn over by the new update.

It does not happen on every screen update, but it is quite often. I can't quite figure out the exact circumstances of when/how/what causes it.

I did at first think: when conky 'reads' the background to apply it's own transparancy, when a background is an image, the current 'conky' window is included in that image, so when it re-draws itself, the now previous conky text is present and 'fades' away with each new re-fresh...

But it also happens with just a plain 'color' background.

Setting the update interval to 5 seconds, then see that each refresh seams to happen in 2 phases, about 1/4 second apart. You kind of see it happening over the 2 drawings, when it happens.

I'm using Arch, xfce, conky-1.10.1-1.

My config file:

    alignment = 'top_right',
    background = false,
    border_width = 2,
    border_inner_margin = 2,
    border_outer_margin = 2,
    gap_x = 10,
    gap_y = 10,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    use_xft = true,
    font = 'DejaVu Sans Mono:size=12',
    minimum_height = 5,
    minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_stderr = false,
    extra_newline = false,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    own_window_argb_visual = true,
    own_window_argb_value = 64,
    double_buffer = true,
    stippled_borders = 0,
    update_interval = 5.0,
    uppercase = false,
    use_spacer = 'none',
    show_graph_scale = false,
    show_graph_range = false

My X does have 'dbe' loaded, and compositing is on.

**Comment by plikhari** [comment]
In Settings - "Session and Startup" - disable "Automatically save session on logout"
clean existing session rm ~/.cache/sessions/*
Unless this is already done - but this is one of the most common issues with xfce sessions and conky

**Comment by john-walsh** [comment]
Thank you, that worked.
Not that I really care about 'saving my session', but does that mean I can't use saved sessions any more?
I tried it once and the problem did come back.

ps. if this is a 'most common issue', I think it's worth putting in the FAQ.

**Comment by plikhari** [comment]
One way could be that you do not create any autostart for conky - and since it is being saved as part of a session - things should work out - they did not work for me though :-))
The other way is you create a list of applications in a script file and then you can choose if you want that list application script to run on startup or like - I let the session start and then click on an icon link to trigger that file to run if I want to else do what ever you want.
cheers

**Comment by john-walsh** [comment]
Yes - I've also had this problem with 'cairo-dock': both the auto-start APP.desktop starts an instance and the xfce 'saved session' starts an instance. So you get 2 conkys running.

Thanks for reminding me about that.

**Comment by john-walsh** [comment]
Note to anyone else finding this: my preferred method now is to disable and not use 'save session', and to have my own startup script for any apps that I want.

To do that, see: /etc/xdg/autostart/
