### ISSUE TITLE
bottom alignments bug on multiple monitors with different height

### ISSUE THREAD

**Issue by Francesco149** [brndnmtthws/conky#172]
on multiple monitor set-ups where not all monitors are the same height, conky assumes that the height is the highest monitor's height, which results in the window being off-screen with bottom_* alignments.

steps to reproduce:
* set up xinerama with multiple monitor that have different heights or rotate one of your monitors left or right (which is my case)
* set conky's alignment to bottom_left (or any bottom_ alignment)
* set gap_x so that conky is on a monitor that doesn't have the largest height
* start conky. the window will be off screen
* set gap_x so that conky is on the highest monitor
* start conky. the window will be visible

this should be easily fixable by checking which head or display conky is on and obtaining the height for that particular display by using XineramaQueryScreens if the user is using xinerama. If the user is not using xinerama, then we can just get the display's height normally.

EDIT: I'm using conky 1.9.0 by the way

**Comment by Francesco149** [comment]
Compiled the latest upstream version and I can confirm the bug is still present.

```
loli@memes ~/wdtan/coding/cpp/conky/build/src $ ./conky --version
conky 1.10.2_pre compiled Wed Nov 25 09:57:08 CET 2015 for Linux 4.1.6-ck-weeb x86_64
```

**Comment by Francesco149** [comment]
I made a pull request where I fix this bug, feel free to review it and consider merging it :)

**Comment by Nooby4Ever** [comment]
@Francesco149 your fix has been merged, I think you can close this issue?
