### ISSUE TITLE
[Bug]: Conky uses 30% CPU when run via i3's config

### ISSUE THREAD

**Issue by siliconsniffer** [brndnmtthws/conky#1765]
### What happened?

I am using i3 as my window manager. It allows me to "auto-start" programs via the config using "exec". E.g. I can use it to run a script with ```exec --no-startup-id path/to/script``` or packages with ```exec --no-startup-id package```, trying this with conky like this ```exec_always --no-startup-id conky -c ~/.config/conky/config.lua``` results, in it freezing and using 30% of the CPU. I already tried it with no config with the same result.

I'm unsure about how to provide log output or stacktraces as running it from the terminal resutls in no problems.

### Version

conky 1.19.7_pre compiled 2024-02-26

### Which OS/distro are you seeing the problem on?

Arch Linux

**Comment by siliconsniffer** [comment]
Killing the process and reloading i3's config works, so there must be something wrong when it runs for the first time. I think conky also doesn't get killed when closing the X session, as terminating and starting it again resulted in multiple instances.

**Comment by Caellian** [comment]
Give a try to stating conky with `exec conky -DD >> /var/log/conky` from i3 script and see whether that does the trick.

**Comment by Caellian** [comment]
Related to #1476.

**Comment by Caellian** [comment]
@siliconsniffer  Can you send me your i3 config and conky config files?

I need first one ~~so I don't have to write it from scratch~~ to faithfully recreate your environment, and the second one so I know if it's some option/variable that's causing issues.

**Comment by Caellian** [comment]
It's hard to tell what's wrong - newer version _does_ use a bit more CPU as it listens for global cursor events. I'll be improving that soon so that builds without `BUILD_MOUSE_EVENTS` are more performant.

I'm closing this for now as resolved (as it will be in a few days, with proper build flags). Let me know if you need this issue reopened.
