### ISSUE TITLE
[Bug]: llua_load: specified script file doesn't exist

### ISSUE THREAD

**Issue by IfGremlinThen** [brndnmtthws/conky#1778]
### What happened?

It seems that recent versions of conky have prevented relative pathing from the home folder with ~/.config/conky/example.lua.

This makes it harder to share configs without editing filepaths.  Is there a workaround for this or is it possible to restore pathing from the home folder with ~/ ?

```
conky: desktop window (2200010) is subwindow of root window (6bd)
conky: window type - desktop
conky: drawing to created window (0x3200002)
conky: drawing to double buffer
conky: llua_load: specified script file '~/.config/conky/draw_bg.lua' doesn't exist
```

### Version

1.19.8

### Which OS/distro are you seeing the problem on?

Ubuntu

### Conky config

```Lua
conky.config = {
    -- TRANSPARENCY & ROUNDED CORNERS
    -- lua_load = 'draw_bg.lua',                         -- WORKS
    -- lua_load = '~/test/draw_bg.lua',                  -- DOESN'T WORK
    -- lua_load = '/home/user/test/draw_bg.lua',        -- WORKS
    -- lua_load = '~/.config/conky/draw_bg.lua',         -- DOESN'T WORK
    lua_load = '/home/user/.config/conky/draw_bg.lua',  -- WORKS
```

**Comment by brndnmtthws** [comment]
Want to try https://github.com/brndnmtthws/conky/pull/1779? That should fix it.
