### ISSUE TITLE
[Bug]: Regression issue after a4ac632db7c76bde63b8e50a0541bbd0cd6a192b - $desktop variable does not update any longer

### ISSUE THREAD

**Issue by lervag** [brndnmtthws/conky#1792]
### What happened?

I use the following text in a Conky config:

```lua
conky.text = [[
$font1${color1}WORKSPACE ${color2}${hr 2}${color}$font
$font2$alignr\
${if_match ${desktop}==1}${color1}${endif}⚫${color} \
${if_match ${desktop}==2}${color1}${endif}⚫${color} \
${if_match ${desktop}==3}${color1}${endif}⚫${color} \
${if_match ${desktop}==4}${color1}${endif}⚫$font
]]
```

After a4ac632db7c76bde63b8e50a0541bbd0cd6a192b, this stopped working. In particular, the `${desktop}` variable no longer updates after Conky starts. It gets the value it has during startup but it never changes.

I found the guilty commit by Git bisection; here's the bisect log:

```
git bisect start
# status: waiting for both good and bad commits
# bad: [647c05c55c2be56ea5139e6e82f9ac95f80e2da7] Update README.md
git bisect bad 647c05c55c2be56ea5139e6e82f9ac95f80e2da7
# status: waiting for good commit(s), bad commit known
# good: [bbdc7081aec27daafca07fc40523335a2ea0a992] Preserve ordering of generated Lua code (#1646)
git bisect good bbdc7081aec27daafca07fc40523335a2ea0a992
# bad: [e4a9cb5a0b04334db36a58fe594b4ecc713c19b5] Add out_to_wayland to default config
git bisect bad e4a9cb5a0b04334db36a58fe594b4ecc713c19b5
# skip: [cbfdb13f506bca506d7fde0fbd4bd973a661bac6] Hide Nvidia on non-linux OSs
git bisect skip cbfdb13f506bca506d7fde0fbd4bd973a661bac6
# skip: [02a75b20bf75696d273544b5fe378eeb0ecf47c4] build(deps): bump actions/upload-artifact from 3 to 4
git bisect skip 02a75b20bf75696d273544b5fe378eeb0ecf47c4
# bad: [56a81ef4fd1b9a994b6157bb94a69a660a27b684] Fix build for imlib2 <1.10.0
git bisect bad 56a81ef4fd1b9a994b6157bb94a69a660a27b684
# skip: [20f9f60c6a6f758af4f24496c88e2c037d068dd6] Fix build & cleanup
git bisect skip 20f9f60c6a6f758af4f24496c88e2c037d068dd6
# good: [f52c5cbd7b11ac36678dcd2b87016fbe8477290e] Run npm audit fix
git bisect good f52c5cbd7b11ac36678dcd2b87016fbe8477290e
# skip: [1b45d95e269e9783f5d49a62480ded09334e70d2] Use core X11 events when Xinput is enabled
git bisect skip 1b45d95e269e9783f5d49a62480ded09334e70d2
# skip: [c43582e917fa124a2a9bc3a8224f74b2bf4b4160] build(deps): bump actions/labeler from 4 to 5
git bisect skip c43582e917fa124a2a9bc3a8224f74b2bf4b4160
# bad: [90472292b3c41e5dd2b0f6e277e271e3d2d79a3b] Bump web deps, improve mdx handling
git bisect bad 90472292b3c41e5dd2b0f6e277e271e3d2d79a3b
# skip: [f6d42c5a69fed134a8b4ed0602c892f6f7b6e242] Fix issues building without BUILD_ARGB flag
git bisect skip f6d42c5a69fed134a8b4ed0602c892f6f7b6e242
# bad: [5e6db91b6d4608865d84cc83b16cad7bd7c8884c] build(deps): bump github/codeql-action from 2 to 3
git bisect bad 5e6db91b6d4608865d84cc83b16cad7bd7c8884c
# bad: [965d7dc0a4053036989057f41403d4e84370e58f] Simplify cursor checking
git bisect bad 965d7dc0a4053036989057f41403d4e84370e58f
# good: [b4fa9b8ad9e2aa9e6810b9c630d849518be67d1e] Remove duplicate BUILD_MOUSE_EVENTS includes (again)
git bisect good b4fa9b8ad9e2aa9e6810b9c630d849518be67d1e
# good: [c4ef5f5e8ca3db11176ee9c19aab781b28b0fefd] Use SFINAE to collapse numeric pust_table_value impls
git bisect good c4ef5f5e8ca3db11176ee9c19aab781b28b0fefd
# bad: [a4ac632db7c76bde63b8e50a0541bbd0cd6a192b] Fix X11 area enter & leave bug
git bisect bad a4ac632db7c76bde63b8e50a0541bbd0cd6a192b
# skip: [5d5e235467f44e5164f5a0bd14b86e4a500e14bf] Cleanup display-x11 includes
git bisect skip 5d5e235467f44e5164f5a0bd14b86e4a500e14bf
# good: [bf900545c0d2ccc94afb7f031bc7abd877b5f4ac] Debug X11 enter & leave events
git bisect good bf900545c0d2ccc94afb7f031bc7abd877b5f4ac
# first bad commit: [a4ac632db7c76bde63b8e50a0541bbd0cd6a192b] Fix X11 area enter & leave bug
```

### Version

Conky from Arch repos (currently version 1.19.7)

### Which OS/distro are you seeing the problem on?

Arch Linux

**Comment by lervag** [comment]
I'll be glad to provide more info if necessary. It didn't feel like it was relevant to give more conky config or stack trace here. It may be useful to state that I use Xorg (with Fluxbox).

And in the mean time I can revert to an older version that works.

**Comment by brndnmtthws** [comment]
Definitely requires a little deeper investigation. Perhaps @Caellian knows what happened here, but I'm guessing it has to do with X event handling.

**Comment by lervag** [comment]
I don't know the Conky source code at all, but [this stood out to me](https://github.com/brndnmtthws/conky/commit/a4ac632db7c76bde63b8e50a0541bbd0cd6a192b#diff-c9ac161ed259f39c83ac37ec6b483503331c4c57d081322d1c373c9ff938b9d6R1372-R1375):

```c
  if (false && ev.type == ButtonPress) {
    XSetInputFocus(display, window.desktop, RevertToNone, i_ev->common.time);
  } else if (false && ev.type == MotionNotify) {
    XSetInputFocus(display, window.window, RevertToParent, i_ev->common.time);
```

Why the `false` here?

**Comment by brndnmtthws** [comment]
That is indeed odd, but I'm not sure it's related. You could rule it out by testing v1.19.6, which doesn't have the Xinput code: https://github.com/brndnmtthws/conky/blob/v1.19.6/src/x11.cc

**Comment by lervag** [comment]
> That is indeed odd, but I'm not sure it's related. You could test it out by comparing to v1.19.6, which doesn't have the Xinput code: https://github.com/brndnmtthws/conky/blob/v1.19.6/src/x11.cc

While bisecting I started with v1.19.6 as the first good commit. I also found that everything worked as expected until and including bf900545c0d2ccc94afb7f031bc7abd877b5f4ac, i.e. that the first commit where it stopped working for me was a4ac632db7c76bde63b8e50a0541bbd0cd6a192b: https://github.com/brndnmtthws/conky/compare/bf900545c0d2ccc94afb7f031bc7abd877b5f4ac...a4ac632db7c76bde63b8e50a0541bbd0cd6a192b

> I guess that won't really tell us whether the Xinput code is the issue, but the value itself comes from here (which should be totally unrelated to Xinput):
> 
> https://github.com/brndnmtthws/conky/blob/bbdc7081aec27daafca07fc40523335a2ea0a992/src/x11.cc#L1029

That's interesting; it seems that the mentioned commit does not really change any nearby lines, and the `get_x11_desktop_current` also seems unchanged. So it seems there is some "implicit" thing going on here?

**Comment by Caellian** [comment]
> I don't know the Conky source code at all, but [this stood out to me](https://github.com/brndnmtthws/conky/commit/a4ac632db7c76bde63b8e50a0541bbd0cd6a192b#diff-c9ac161ed259f39c83ac37ec6b483503331c4c57d081322d1c373c9ff938b9d6R1372-R1375):
> 
> ```c
>   if (false && ev.type == ButtonPress) {
>     XSetInputFocus(display, window.desktop, RevertToNone, i_ev->common.time);
>   } else if (false && ev.type == MotionNotify) {
>     XSetInputFocus(display, window.window, RevertToParent, i_ev->common.time);
> ```
> 
> Why the `false` here?

I accidentally left this while testing things during development. Enabling these statements in some cases took the keyboard and/or mouse (clicking) focus for me on Plasma in some unexpected cases. It's not related though.

<hr/>

Could you build the [debug-desktop-atom](https://github.com/Caellian/conky/tree/dev/debug-desktop-atom) branch and use check the value of `desktop` with something like:
```
conky.text = [[
$font1${color1}WORKSPACE ${color2}${hr 2}${color}$font
$font2$alignr\
Desktop is: ${desktop}
]]
```

Also, does the first bad commit work if `BUILD_XINPUT` is disabled?

I checked some of the changed includes in files that I believed could affect the existing code, but nothing really jumps out. I did call `xcb_connect` which might be doing something unexpected with atoms.

**Comment by lervag** [comment]
> > Why the `false` here?
> 
> I accidentally left this while testing things during development. Enabling these statements in some cases took the keyboard and/or mouse (clicking) focus for me on Plasma in some unexpected cases. It's not related though.

Ok! :)

> Could you build the [debug-desktop-atom](https://github.com/Caellian/conky/tree/dev/debug-desktop-atom) branch and use check the value of `desktop` with something like:

I did `make clean`, then I checked out the branch and built things, then I ran `src/conky -c test.conky` with the following conky config:

```lua
conky.config = {
  own_window = true,
  own_window_type = "desktop",
  update_interval = 0.5,
}

conky.text = [[
Desktop is: ${desktop}
]]
```

On my end, it only draws a black box near the bottom left of my screen. With conky 1.18 packaged with Arch Linux it looks like this:

![image](https://github.com/brndnmtthws/conky/assets/998898/f0941cc6-c9ab-49b5-89b2-2b809f264f1c)

> Also, does the first bad commit work if `BUILD_XINPUT` is disabled?

Sorry, stupid question: how do I disable it?

**Comment by lervag** [comment]
And just to be clear: With the same `test.conky` file, the desktop number will change when it works as expected. But for the versions after https://github.com/brndnmtthws/conky/commit/a4ac632db7c76bde63b8e50a0541bbd0cd6a192b it stays "stuck" at the number it has when I launch conky.

**Comment by Caellian** [comment]
Ok, so the atom isn't even checked, which means whatever is calling the function isn't doing so for some reason.

> > Also, does the first bad commit work if `BUILD_XINPUT` is disabled?
>
> Sorry, stupid question: how do I disable it?

Not a stupid question, it can be tricky to figure out when you're not familiarized with the project and/or cmake.

```sh
git clone <conky git>
cd conky
mkdir build && cd build
cmake ..
# use ccmake for a TUI to toggle flags, there's also a gui in Qt available but it comes as a separate package
ccmake .
# find the option and toggle it in the list
# use 'c' key to "configure"
# 'q'/'e' to quit (not sure which, it's listed on the bottom)
# finally, make:
make
```

**Comment by lervag** [comment]
I checked out the latest `main` version (4eecf3b8) and followed your steps. I then ran `src/conky -c test.conky` as before, and it still does not update the desktop variable.

I'm not very sure how to help here. But one thing I _could_ do is to do a sort of manual bisection of the "guilty" commit. I.e., I could introduce the changes from that commit "one at a time". But that will take some time, so I'd rather have it as a last resort method.

**Comment by Caellian** [comment]
> I checked out the latest `main` version ([4eecf3b](https://github.com/brndnmtthws/conky/commit/4eecf3b88febe46140c49e59bbe8f25f4e6fe803)) and followed your steps. I then ran `src/conky -c test.conky` as before, and it still does not update the desktop variable.
> 
> I'm not very sure how to help here. But one thing I _could_ do is to do a sort of manual bisection of the "guilty" commit. I.e., I could introduce the changes from that commit "one at a time". But that will take some time, so I'd rather have it as a last resort method.

No need, I have recreated the issue with the latest version. I'll reply once I have more info.

**Comment by lervag** [comment]
Great, thanks!

**Comment by Caellian** [comment]
Will be fixed once the PR is merged. I ignored events that weren't on Conky window, but `PropertyNotify` was on root, so we didn't get notified when desktop number (or other X11 property) changed.

**Comment by lervag** [comment]
I can confirm that your PR fixes the problem. Thanks!

**Comment by lervag** [comment]
Would it be possible to also make a minor/patch release after the PR is merged? Then I could contact the Arch Linux maintainers and have them update to the latest release.

(In the meantime, I'll stay on the [git nightly](https://aur.archlinux.org/packages/conky-git) package.)

**Comment by Caellian** [comment]
> Would it be possible to also make a minor/patch release after the PR is merged? Then I could contact the Arch Linux maintainers and have them update to the latest release.

I'd like to fix issue 1767 before next version as well as it's related to the same code. I think that's the last bigger issue that cropped up from my contribution. Though it requires a bit more investigation. I'm guessing we could push a new version by the end of the next week.

**Comment by lervag** [comment]
Sounds great; thanks again!
