### ISSUE TITLE
can't build conky with --disable-ncurses

### ISSUE THREAD

**Issue by wujek-srujek** [brndnmtthws/conky#18]
I get the following error, which gets fixed by using --enable-ncurses:

gcc -DHAVE_CONFIG_H -I. -DSYSTEM_CONFIG_FILE=\"/etc/conky/conky.conf\" -DPACKAGE_LIBDIR=\"/usr/lib/conky\"  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -I/usr/include/lua5.1    -I/usr/include/freetype2  -Wall -W -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector --param=ssp-buffer-size=4 -MT conky-conky.o -MD -MP -MF .deps/conky-conky.Tpo -c -o conky-conky.o `test -f 'conky.c' || echo './'`conky.c
conky.c: In function ‘generate_text_internal’:
conky.c:885:7: error: unknown type name ‘bool’
       static bool warned = false;
       ^
conky.c:885:28: error: ‘false’ undeclared (first use in this function)
       static bool warned = false;
                            ^
conky.c:885:28: note: each undeclared identifier is reported only once for each function it appears in
conky.c:890:17: error: ‘true’ undeclared (first use in this function)
        warned = true;
                 ^
make[2]: **\* [conky-conky.o] Error 1
make[2]: Leaving directory `/home/wujek/Playground/src/conky-1.9.0/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory`/home/wujek/Playground/src/conky-1.9.0/src'
make: **\* [all-recursive] Error 1

**Comment by marcpayne** [comment]
This issue is over 2 years old, and a lot has changed since then. I doubt that it is valid anymore since we use a C++ compiler now. Have you tried compiling Conky recently, preferably from git master?

**Comment by wujek-srujek** [comment]
No, sorry, I haven't used conky for a while now, let alone build it myself. I guess it can be closed if so much has changed.
