### ISSUE TITLE
[Enhancement]: make downspeedgraph and upspeedgraph use same scaling

### ISSUE THREAD

**Issue by Caellian** [brndnmtthws/conky#1820]
It might be better to clamp `downspeedgraph` and `upspeedgraph` according to maximum value across both graphs because people assume (#979, #1034) they're using the same vertical step.

**Comment by donutAnees** [comment]
I noticed that the issue is still open, and I would like to contribute to it. Please let me know if it's still available.

**Comment by Caellian** [comment]
Yup, any "good first issue" issues are if they don't have any linked PRs with recent activity.
