### ISSUE TITLE
How to uninstall the compile version conky?

### ISSUE THREAD

**Issue by stardiviner** [brndnmtthws/conky#183]
As the title said.
I compiled latest version Conky on Arch Linux. version: `1.10`.

**Comment by KamranMackey** [comment]
Why do you want to uninstall it?

**Comment by stardiviner** [comment]
I want to try the compiling from source code version Conky. But I found Arch default source conky has new version enough.

**Comment by plikhari** [comment]
Uninstalling programs on Arch linux - refer  ```man pacman```
```sudo pacman -R conky```
Please note that Arch stock conky is compiled with lua 5.3 - which is not compatible with cairo integration

**Comment by stardiviner** [comment]
I see. Looks conky update is very slow on main Linux distributions.

**Comment by mubashir-rehman** [comment]
Kindly open this issue.
Because there is no  documentation on how to uninstall the source compiled version of conky.
Reason: I want to install the latest available build from release page.

**Comment by nurgasemetey** [comment]
@mubashir-rehman if it will help you, you can remove following files:

```
-- Install configuration: "RelWithDebInfo"
-- Installing: /usr/local/share/doc/conky-1.11.7_pre/convert.lua
-- Installing: /usr/local/share/doc/conky-1.11.7_pre/conky_no_x11.conf
-- Installing: /usr/local/share/doc/conky-1.11.7_pre/conky.conf
-- Installing: /usr/local/share/applications/conky.desktop
-- Installing: /usr/local/share/icons/hicolor/scalable/apps/conky-logomark-violet.svg
-- Installing: /usr/local/bin/conky
-- Installing: /usr/local/lib/libtcp-portmon.a
```

A bit manual but can solve your problem
