### ISSUE TITLE
[Bug]: conky doesn't compile on MacOS with default flags

### ISSUE THREAD

**Issue by Caellian** [brndnmtthws/conky#1836]
### Discussed in https://github.com/brndnmtthws/conky/discussions/1835

<div type='discussions-op-text'>

<sup>Originally posted by **Buitragox** April 18, 2024</sup>
I am trying to compile the source code following the [instructions](https://github.com/brndnmtthws/conky/wiki/Installation) page. I managed to make the `cmake ..` step successful, but the `make install` keeps failing.

```
[ 17%] Building CXX object src/CMakeFiles/conky.dir/display-x11.cc.o
/Users/jhbuitrago/Study/conky/src/display-x11.cc:765:14: error: no member named 'xi_opcode' in 'conky_x11_window'
  if (window.xi_opcode != 0) return true;  // handled by mouse_input already
      ~~~~~~ ^
/Users/jhbuitrago/Study/conky/src/display-x11.cc:767:55: error: no member named 'x' in 'conky_x11_window'
  bool not_over_conky = ev.xcrossing.x_root <= window.x ||
                                               ~~~~~~ ^
/Users/jhbuitrago/Study/conky/src/display-x11.cc:768:55: error: no member named 'y' in 'conky_x11_window'
                        ev.xcrossing.y_root <= window.y ||
                                               ~~~~~~ ^
/Users/jhbuitrago/Study/conky/src/display-x11.cc:769:55: error: no member named 'x' in 'conky_x11_window'
                        ev.xcrossing.x_root >= window.x + window.width ||
                                               ~~~~~~ ^
/Users/jhbuitrago/Study/conky/src/display-x11.cc:770:55: error: no member named 'y' in 'conky_x11_window'
                        ev.xcrossing.y_root >= window.y + window.height;
                                               ~~~~~~ ^
/Users/jhbuitrago/Study/conky/src/display-x11.cc:775:44: error: use of undeclared identifier 'mouse_event_t'
        ev.xcrossing.type == EnterNotify ? mouse_event_t::AREA_ENTER
                                           ^
/Users/jhbuitrago/Study/conky/src/display-x11.cc:776:44: error: use of undeclared identifier 'mouse_event_t'
                                         : mouse_event_t::AREA_LEAVE,
                                           ^
/Users/jhbuitrago/Study/conky/src/display-x11.cc:975:10: error: no member named 'x' in 'conky_x11_window'
  window.x = x;
  ~~~~~~ ^
/Users/jhbuitrago/Study/conky/src/display-x11.cc:976:10: error: no member named 'y' in 'conky_x11_window'
  window.y = y;
  ~~~~~~ ^
9 errors generated.
make[2]: *** [src/CMakeFiles/conky.dir/display-x11.cc.o] Error 1
make[1]: *** [src/CMakeFiles/conky.dir/all] Error 2
make: *** [all] Error 2
```

Any ideas are much appreciated.

**System details**
macOS Ventura (13.6.3)
MacBook Pro (Intel based)</div>

**Comment by Caellian** [comment]
Removed high priority as macos build isn't that common.

@Buitragox this issue happens because you're building without `OWN_WINDOW` flag, which also turns of `BUILD_MOUSE_EVENTS` currently. I'll experiment with those on linux and try fixing define guards, though I won't be able to test it on MacOS.

There's some existing [brew formulas](https://github.com/Conky-for-macOS/homebrew-formulae/tree/master) we could maybe move to extras and add a CI that tries building them. The CI shouldn't block PRs and such, but it would be good to have it as an indicator whether the build even works and what's the last good version for brew. Again, I don't have a mac so I could only fix trivial issues and leave it up to community to maintain.

**Comment by Buitragox** [comment]
That's interesting because I only touched the `BUILD_X11` flag with ccmake. 

I managed to build the source with the default flags after deleting the build directory and starting over. The installation wiki links to [this](https://npyl.github.io/emerald/conky-libraries-script) page for which dependencies to install, but I needed to install a few more:
```shell
brew install libxft libxinerama xinput
```

Now I have a new problem, since conky fails to run:
```
» conky
conky: can't open display:
```

I also tried some of the formulas that you linked. `conky-all.rb` failed because of missing formulae, and `conky.rb` failed when building.

**Comment by Caellian** [comment]
> That's interesting because I only touched the BUILD_X11 flag with ccmake.

You disabled it? Disabling `BUILD_X11` automatically disables dependent `OWN_WINDOW` flag which does the same for `BUILD_MOUSE_EVENTS` (currently). That's because neither should do anything without `BUILD_X11`. In future, `OWN_WINDOW` _could_ be added to Wayland, but that's unrelated to MacOS.

So you're trying to build conky for terminal output/https server/... and not X11? I'm asking because `display-x11.cc` that's causing the error shouldn't be built without `BUILD_X11`.

> I also tried some of the formulas that you linked. conky-all.rb failed because of missing formulae, and conky.rb failed when building.

Yeah, those formulas haven't been updated since conky 1.11.

> Now I have a new problem, since conky fails to run

Have you enabled [`out_to_console`](https://conky.cc/config_settings#out_to_console) or some other output?

**Comment by Caellian** [comment]
> That wasn't my intention. I was trying different things to see if it would compile, since it couldn't find X11. I want to use conky on my desktop.

Aah, ok. Yep, X11 is a required dependency for that. We don't support appkit.

>  After installing the dependencies mentioned above, building with default flags, and installing [XQuartz](https://www.xquartz.org/index.html) conky was able to run. X support on MacOS was the problem.

Ok, I'll add that to wiki so others doing the same can see.

> It still has some issues. For example, changing the alignment to anything other than top_left makes a tiny window. I still need to experiment more with it, but it works for now.

That's likely a bug with XQuartz though it's hard to tell, you can emulate other alignments by increasing `gap_x` and `gap_y` properties as a workaround.
