### ISSUE TITLE
update_interval_on_battery does not work

### ISSUE THREAD

**Issue by Dreamsorcerer** [brndnmtthws/conky#190]
I get this error when starting Conky:
conky: can't open /sys/class/power_supply/BAT0/uevent: Document or folder doesn't exist
conky: can't open /proc/acpi/battery/BAT0/state: Document or folder doesn't exist

This is because my old script had "update_interval_on_battery 5.0 BAT1", but in Conky 1.10 this is no longer valid syntax. Now it is "update_interval_on_battery = 5.0," and I cannot find a way to specify the correct device.

Although, it would probably be suitable for conky to detect that BAT0 does not exist, and use BAT1 by default, rather than requiring user configuration.

**Comment by Dreamsorcerer** [comment]
Specifically, selecting the default battery device by doing something like this:
ls /sys/class/power_supply/ | grep BAT | head -n 1

**Comment by rogorido** [comment]
Is there any solution in sight for this?
