### ISSUE TITLE
[feature request] battery_status

### ISSUE THREAD

**Issue by wommel** [brndnmtthws/conky#191]
battery as well as battery_short display the battery status but allways with the percentage.
So if i want to show different colors or icons instead of text there is no simple option.

So i'd like an option to get the battery status.

**Comment by lasers** [comment]
![2018-08-07-005430_229x181_scrot](https://user-images.githubusercontent.com/852504/43756984-d65483be-99dc-11e8-8b2a-a476d7db0812.png)

2 years, 8 months passed. Okay, I understand what you want. You want `{battery_status}` to print `Discharging`, `Charging`, `Full`, `Empty`, `Unknown`. We should add this so you can use this with conky conditionals.

I think we should remove percentages too... in `battery` and `battery_short`. I think I'd remove `{battery_short}` variable too in favor of `{battery_status}` + conky conditionals where users can make it short again (or replace it with icons now).

Conky conditionals. Untested.
```lua
-- replaces ${battery_status} with icons

${if_match ${battery_status}==Discharging}🔋${endif}
${if_match ${battery_status}==Charging}⚡${endif}
${if_match ${battery_status}==Full}☻${endif}
-- ${if_match ${battery_status}==Empty}E${endif}  -- skip empty
${if_match ${battery_status}==Unknown}?${endif}
```
```lua
-- behaves like ${battery_short}

${if_match ${battery_status}==Discharging}D${endif}
${if_match ${battery_status}==Charging}D${endif}
${if_match ${battery_status}==Full}F${endif}
-- ${if_match ${battery_status}==Empty}E${endif}  -- skip empty
${if_match ${battery_status}==Unknown}U${endif}
```
Is this change okay with you? @brndnmtthws

**Comment by lasers** [comment]
@su8 We can close this today. Easy peasy.

**Comment by su8** [comment]
What's about to be changed exactly ?

>So i'd like an option to get the battery status.

So he/she/it would like a new variable called `${battery_status}` to be added ?

**Comment by lasers** [comment]
Yes... So he/she/it want to `if_match` against `discharging`. He/she/it claims he/she/it can't `if_match` because of the percents, but we know that's not true... because technically,  he/she/it can make all 100 `if_match` lines, one for each percent, but no, he/she/it want an easy life... so he/she/it files this issue instead of working his/her/it ass off... So we need to fix this to make him/her/it happy.

I think we should break everything to correct `battery_*` variables for once and all.
* `battery_status`, eg `discharing`
* `battery_bar`, eg `######....`
* `battery_percent`, eg `85`
* `battery_time`, eg `2h 17 10s`
```

**Comment by su8** [comment]
Okay that's easy then.

**Comment by su8** [comment]
With Upper or Lower Case to print the status ?

**Comment by lasers** [comment]
I think leave it as-is, which is Upper.... based on `/sys/class/power_supply/BAT0/status`.

**Comment by su8** [comment]
Can you test this diff since I no longer have laptop:

```diff
diff --git a/src/core.cc b/src/core.cc
index 7a438b2e..725823f8 100644
--- a/src/core.cc
+++ b/src/core.cc
@@ -545,6 +545,10 @@ struct text_object *construct_text_object(char *s, const char *arg, long line,
   obj->data.s = strndup(bat, text_buffer_size.get(*state));
   obj->callbacks.print = &print_battery_short;
   obj->callbacks.free = &gen_free_opaque;
+
+  END OBJ(battery_status, 0) obj->data.s = STRNDUP_ARG;
+  obj->callbacks.print = &print_battery_status;
+  obj->callbacks.free = &gen_free_opaque;
   END OBJ(battery_time, nullptr) char bat[64];
 
   if (arg != nullptr) {
diff --git a/src/linux.cc b/src/linux.cc
index a9c65a86..19cd0dcd 100644
--- a/src/linux.cc
+++ b/src/linux.cc
@@ -2185,6 +2185,23 @@ void get_battery_short_status(char *buffer, unsigned int n, const char *bat) {
   // Otherwise, don't shorten.
 }
 
+void print_battery_status(struct text_object *obj, char *p, unsigned int p_max_size) {
+  get_battery_stuff(p, p_max_size, obj->data.s, BATTERY_STATUS);
+  if (0 == strncmp("charging", p, 8)) {
+    snprintf(p, p_max_size, "%s", "Charging");
+  } else if (0 == strncmp("discharging", p, 11)) {
+    snprintf(p, p_max_size, "%s", "Discharging");
+  } else if (0 == strncmp("charged", p, 7)) {
+    snprintf(p, p_max_size, "%s", "Charged");
+  } else if (0 == strncmp("not present", p, 11)) {
+    snprintf(p, p_max_size, "%s", "Not present");
+  } else if (0 == strncmp("empty", p, 5)) {
+    snprintf(p, p_max_size, "%s", "Empty");
+  } else if (0 == strncmp("unknown", p, 7)) {
+    snprintf(p, p_max_size, "%s", "Unknown");
+  }
+}
+
 int _get_battery_perct(const char *bat) {
   static int rep = 0;
   int idx;
diff --git a/src/linux.h b/src/linux.h
index 6468bcb3..1943cc93 100644
--- a/src/linux.h
+++ b/src/linux.h
@@ -39,6 +39,7 @@ int gateway_exists(struct text_object *);
 void print_gateway_iface(struct text_object *, char *, unsigned int);
 void print_gateway_iface2(struct text_object *, char *, unsigned int);
 void print_gateway_ip(struct text_object *, char *, unsigned int);
+void print_battery_status(struct text_object *, char *, unsigned int);
 
 enum { PB_BATT_STATUS, PB_BATT_PERCENT, PB_BATT_TIME };
 void get_powerbook_batt_info(struct text_object *, char *, unsigned int);
```

**Comment by lasers** [comment]
No more diffs. From now on, link me to your branches. I have rarely used laptop here. Can test. Gotta update system (Idk when last time), install build essentials, install conky, etc.

**Comment by su8** [comment]
https://github.com/su8/conky/tree/su8-fixes-191 , https://github.com/su8/conky/commit/87a39d5e669c8139779ed2fa560603da238a762c

**Comment by lasers** [comment]
This does not seems to remove `battery_short` and other things I wanted to break?

**Comment by lasers** [comment]
Then he/she/it should update their config... to `${battery_status} ${battery_percent}`. In fact, `${battery_short}` looks too damn like `${battery_percent}` so I'm not convinced that it's useful to keep it. Also, our He/she/it want `${battery_status}` to display icons instead. It can be done exactly the same way to display single characters.

**Comment by su8** [comment]
While waiting on your reply to see whether the code is working, I'll be watching a movie :blush:

**Comment by lasers** [comment]
Dusting off old `Manjaro` i3wm.

![2018-08-19-122842_1920x1200_scrot](https://user-images.githubusercontent.com/852504/44311379-e87c5e80-a3ab-11e8-8ed2-6d7630b5e36b.png)

**Comment by lasers** [comment]
Closed via https://github.com/brndnmtthws/conky/pull/631.
