### ISSUE TITLE
High cpu usage and broken position since last update

### ISSUE THREAD

**Issue by sushi2503** [brndnmtthws/conky#1919]
### What happened?

Since the update from 1.19.7-2 -> 1.20.2-1 the positions and windows sizes are broken with a very high cpu usage by moving the mouse around (80 - 90%) on 12 cores desktop machine and over 100% on a laptop.

Reverting to 1.19.7-2 fixes the problem.

Edit : On X11

### Version

1.20.2-1

### Which OS/distro are you seeing the problem on?

Arch Linux

**Comment by Caellian** [comment]
Closing as duplicate of #1917 and #1886.
