### ISSUE TITLE
[Bug]: Fonts are red. Default config file, background is black, X11 environment

### ISSUE THREAD

**Issue by e-Gyi-qO** [brndnmtthws/conky#1922]
### What happened?

After upgrading conky, the color of the fonts turned red. I am not sure from which version it started. I tried downgrading, and the problem persists. It could be I have not noticed the issue earlier enough, and I should have tried downgrading further in the past. Or that it is not conky's fault. I have not noticed color related issues any where else. 

### Version

1.20

### Which OS/distro are you seeing the problem on?

Arch Linux

### Conky config

```Lua
-- Conky, a system monitor https://github.com/brndnmtthws/conky
--
-- This configuration file is Lua code. You can write code in here, and it will
-- execute when Conky loads. You can use it to generate your own advanced
-- configurations.
--
-- Try this (remove the `--`):
--
--   print("Loading Conky config")
--
-- For more on Lua, see:
-- https://www.lua.org/pil/contents.html
--
-- Conky Lua API: https://conky.cc/lua

-- Configuration settings: https://conky.cc/config_settings
conky.config = {
    alignment = 'top_left',
    background = false,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    double_buffer = true,
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'DejaVu Sans Mono:size=12',
    gap_x = 60,
    gap_y = 60,
    minimum_height = 5,
    minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_wayland = false,
    out_to_x = true,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'normal',
    own_window_hints = 'undecorated,sticky,below,skip_taskbar,skip_pager',
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
}

-- Variables: https://conky.cc/variables
conky.text = [[
${color grey}Info:$color ${scroll 32 Conky $conky_version - $sysname $nodename $kernel $machine}
$hr
${color grey}Uptime:$color $uptime
${color grey}Frequency (in MHz):$color $freq
${color grey}Frequency (in GHz):$color $freq_g
${color grey}RAM Usage:$color $mem/$memmax - $memperc% ${membar 4}
${color grey}Swap Usage:$color $swap/$swapmax - $swapperc% ${swapbar 4}
${color grey}CPU Usage:$color $cpu% ${cpubar 4}
${color grey}Processes:$color $processes  ${color grey}Running:$color $running_processes
$hr
${color grey}File systems:
 / $color${fs_used /}/${fs_size /} ${fs_bar 6 /}
${color grey}Networking:
Up:$color ${upspeed} ${color grey} - Down:$color ${downspeed}
$hr
${color grey}Name              PID     CPU%   MEM%
${color lightgrey} ${top name 1} ${top pid 1} ${top cpu 1} ${top mem 1}
${color lightgrey} ${top name 2} ${top pid 2} ${top cpu 2} ${top mem 2}
${color lightgrey} ${top name 3} ${top pid 3} ${top cpu 3} ${top mem 3}
${color lightgrey} ${top name 4} ${top pid 4} ${top cpu 4} ${top mem 4}
]]
```

**Comment by Caellian** [comment]
Are you sure you're running 1.20?

We changed how color names are handled in [v1.20.2](https://github.com/brndnmtthws/conky/releases/tag/v1.20.2).

Let me know whether you can recreate the issue on [v1.21.1](https://github.com/brndnmtthws/conky/releases/tag/v1.21.1) and [v1.19.8
](https://github.com/brndnmtthws/conky/releases/tag/v1.19.8)

**Comment by e-Gyi-qO** [comment]
Tin Švagelj ***@***.***> wrote:

> Are you sure you're running 1.20?
> 
> We changed how color names are handled in [v1.20.2](https://github.com/brndnmtthws/conky/releases/tag/v1.20.2).
> 
> Let me know whether you can recreate the issue on [v1.21.1](https://github.com/brndnmtthws/conky/releases/tag/v1.21.1) and [v1.19.8
> ](https://github.com/brndnmtthws/conky/releases/tag/v1.19.8)
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/brndnmtthws/conky/issues/1922#issuecomment-2119026064
> You are receiving this because you authored the thread.
> 
> Message ID: ***@***.***>

I am sure about the versions as far as stock archlinux packages vesrions 
are as expected.
Issue seems to vanish right now. Not in a way I can fully explain. I upgrade 
frequently, as I am using a rolling distribution. I will keep the report
open for a while. If there will be no furthere meaningful replies I wll 
then close it.

**Comment by servimo** [comment]
conky-1.20-2 in my Manjaro solved this issue.

**Comment by e-Gyi-qO** [comment]
> [servimo](https://github.com/servimo): conky-1.20-2 in my Manjaro solved this issue.

Confirming [servimo](https://github.com/servimo) comment and closing this issue.

**Additional information:**
Stock archlinux 1.20.2-1, which is
```
conky -v | head -1
conky 1.20.2_pre compiled for Linux x86_64
```
has this issue. When started from a terminal, it also regularly spits 
``conky: can't parse hex color 'lightgrey' (9)``
messages to the terminal. I guess it does this for each update of the window. lightgrey is mentioned above at Conky config section.

Stock archlinux 1.20.2-2, which is also
```
conky -v | head -1
conky 1.20.2_pre compiled for Linux x86_64
```
does not have this issue. The difference between stock archlinux 1.20.2-1 and 1.20.2-2 is [fixed color naming](https://gitlab.archlinux.org/archlinux/packaging/packages/conky/-/commit/8cc8352806e123d4310fb9efbad521616127260c). I guess it is the same as [Tin Švagelj ***@***.*** comment from above](https://github.com/brndnmtthws/conky/issues/1922#issuecomment-2119026064), but have not tried to verify my guess.

**Comment by Caellian** [comment]
Right, the binary was built without gperf present. A later version made it a requirement to avoid this issue in the future.
