### ISSUE TITLE
[Bug]: 1.21.1 /usr/share/doc/conky name mistake?

### ISSUE THREAD

**Issue by 0pLuS0** [brndnmtthws/conky#1928]
### What happened?

When I compile Conky from source in Linux 1.21.1 now has the /path named as; ```/usr/share/doc/conky-1.21.1-pre-``` that I copy the doc contents out of.

Previous versions were like this;

```conky-1.19.6_pre```
```conky-1.20.1_pre```

They use to always be as 'Version Number'  _pre

Now in 1.21.1 (dash pre dash)  -pre-

Which this seems a bit of odd naming.

### Version

1.21.1

It would be nice in the next version updates the source compiled it as /usr/share/doc/conky-version 

I never could understand all the _pre stuff...

THANKS

**Comment by brndnmtthws** [comment]
How did you install it? Generally the -pre stuff should be removed from the versioning when `-DRELEASE=ON` with CMake, as shown here: https://github.com/brndnmtthws/conky/blob/7526e7e18d8f5b08f5c8325abd6cf00cf9a46c59/cmake/Conky.cmake#L179-L184

I'm trying to understand if this is a regression, or you just don't like the versioning on the docs dir.

Now that I think about it, it probably doesn't make sense to use the -pre and git sha in the version for the install path, so I might just remove that anyway.

**Comment by 0pLuS0** [comment]
Hi @brndnmtthws 

I am compiling Conky from source in Slackware, with a Slackware build script. I've actually been using this build script maybe for 2 years. DOCS are off; -DBUILD_DOCS=OFF 

I'm manually copying docs from the pre directory and making the /usr/doc/ path.

I'm attaching the build script for you to see, it's actually called conky.SlackBuild

[conky.SlackBuild.txt](https://github.com/brndnmtthws/conky/files/15427141/conky.SlackBuild.txt)
 
THANKS
