### ISSUE TITLE
execpi doesn't execute a command immediately

### ISSUE THREAD

**Issue by alexbel** [brndnmtthws/conky#194]
For example, I need to run a script every hour. 
```
${execpi 3600 ./my_script.sh}
```
As I understand in version 1.10, I have to wait the whole hour to see output of my script.
Is it expected behavior? If yes, is there a way to run command in `execpi` block right after conky started?

**Comment by marcpayne** [comment]
I've made a pull request that fixes this issue: #192. I guess the behavior is expected by now (it's been a known issue for a while :-/), but it is not intended. Over on issue #180, plikhari posted a nice workaround using a lua script that you may use until the changes are merged. Or, if you don't mind compiling conky from source, you could checkout the exec-cb-refactor branch from [my repo](https://github.com/marcpayne/conky).

Let me know if there is anything else I can do to help.

**Comment by alexbel** [comment]
thanks @marcpayne !!!. I should have found your pr.
