### ISSUE TITLE
[Bug]: Tests fail with BUILD_COLOUR_NAME_MAP=OFF

### ISSUE THREAD

**Issue by billie80** [brndnmtthws/conky#1940]
### What happened?

With conky 1.21.0 the build option BUILD_COLOUR_NAME_MAP was introduced. When disabling the colour name map the color related test in test-colours.cc "parse_color correctly parses colours" fails.
Should this test be disabled in this case?

### Version

1.21.1

### Which OS/distro are you seeing the problem on?

Gentoo

**Comment by brndnmtthws** [comment]
In this particular case, the name tests should just be disabled.
