### ISSUE TITLE
[Bug]: Middle not working as second argument in Alignment

### ISSUE THREAD

**Issue by Dany-Dan** [brndnmtthws/conky#1962]
### What happened?

Since version 1.21.1, conky no longer displays anything when using middle as second argument in alignment.
top_middle, middle_middle and bottom_middle don't work. Corresponding aliases don't work either.

### Version

1.21.2

### Which OS/distro are you seeing the problem on?

Arch Linux

### Conky config

```Lua
conky.config = {
alignment = 'middle_middle',
background = false,
border_inner_margin = 0,
border_outer_margin = 0,
border_width = 0,
default_color = '#e4f8fd',
double_buffer = true,
draw_shades = false,
font = 'Sansation:Regular:size=14',
gap_x = 0,
gap_y = 0,
imlib_cache_flush_interval = 0,
maximum_width = 500,
own_window = true,
own_window_argb_value = 0,
own_window_argb_visual = true,
own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
own_window_title = 'Conky Uptime',
own_window_transparent = false,
own_window_type = 'desktop',
update_interval = 2,
use_xft = true,
xftalpha = 1
};

conky.text = [[
####################################################################
# INFO SYSTEM
####################################################################
#
${goto 0}${font}Démarré depuis : ${uptime}${font}\
#
]];
```

**Comment by Caellian** [comment]
Do you mind trying out 1.21.3? I believe this bug was removed with #1963.

**Comment by Dany-Dan** [comment]
I just tested the latest version via the appimage and the bug is fixed.
So I will keep version 1.20.2 until version 1.21.3 is available in the Arch Linux repositories.

Problem solved, thank you.
