### ISSUE TITLE
[Bug]: Conky not sizing its own window properly on KDE Plasma 6 / X11

### ISSUE THREAD

**Issue by carpii** [brndnmtthws/conky#1976]
Since upgrading from KDE Plasma Desktop 5 to Plasma 6, conky is no longer sizing its own window correctly.

Instead it seems to be limited to around 20 pixels in height (indicated by the white border - which conky is drawing, not me). 

Previous issues around this were fixed as part of #1511

### Screenshot when `own_window = false`

![](https://i.imgur.com/lbAfesV.png)

### Screenshot when `own_window = true`

![](https://i.imgur.com/IWNODWm.png)

### Version

1.21.2-pre-8e363634

### Which OS/distro are you seeing the problem on?

Arch Linux

### Conky config

```Lua
conky.config = {
  own_window = true,
  own_window_class = 'Conky',
  own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
  own_window_type = 'dock',
  own_window_colour = '000000',
  own_window_transparent = true,
  own_window_argb_visual = false,
  own_window_argb_value = 0,

  draw_borders = true,
  gap_x = 0,
  gap_y = 300,
  minimum_width = 640,
  minimum_height = 360,
  update_interval = 1
}

conky.text = [[
  ${image ~/bin/binscripts/awesome_cctv/drive.jpg -p 0,0 -n -s 640x360}
]]
```

**Comment by Caellian** [comment]
Can you try 1.21.3 to check whether this is fixed? It might be the same bug as reported in #1925.

**Comment by carpii** [comment]
Thanks, AUR repo was updated with 1.21.3, and fixes the cropping issue
