### ISSUE TITLE
[Bug]: Problem with "new" upspeedgraph / downspeedgraph scaling

### ISSUE THREAD

**Issue by skunktrading** [brndnmtthws/conky#2001]
### What happened?

Pull 1991 introduced a new feature to link the scaling of up/down speed graphs so that a consistent scale is used for both. This is a great new feature.

Unfortunately, the maximum is not linked to the actual data range displayed in the graphs. This means that a spike in usage (which is pretty common) will not roll off the graph as time progresses and persists until conky is restarted. I would have expected the maximum of both graphs to be the maximum of the data points actually displayed, not the maximum ever seen since startup

### Version

1.21.5

### Which OS/distro are you seeing the problem on?

Arch Linux

**Comment by Caellian** [comment]
CC @donutAnees

**Comment by Caellian** [comment]
Related to: #1991

**Comment by donutAnees** [comment]
I’ll fix this issue within the hour! Thanks for letting me know.
