### ISSUE TITLE
-s command line option does nothing

### ISSUE THREAD

**Issue by PlaidShirtPat** [brndnmtthws/conky#203]
```
       -s | --for-scripts TEXT
              Prints TEXT on the standard output and exits.  (This option makes conky  useful  in
              scripts)  TEXT  has to be enclosed by single quotes. Example: conky -s 'Your uptime
              is: $uptime'
```

Running the example `conky -s 'Your uptime is: $uptime'` just starts conky as usual. No text is printed to the console & the GUI starts.

**Comment by ngoonee** [comment]
https://github.com/brndnmtthws/conky/wiki/Command-Line-Options shows there's no such option.

**Comment by Nooby4Ever** [comment]
@PlaidShirtPat the documentation is updated, this option is indeed no longer available. You may consider closing this issue.
