### ISSUE TITLE
[Bug]: transperancy is lost after some time

### ISSUE THREAD

**Issue by nPHYN1T3** [brndnmtthws/conky#2039]
### What happened?

When I start conky everything is as it should be. However after some time passes the background turns light gray (it starts off transparent). Simply resaving the conkyrc fixes it but I can't figure out why/what makes it change.

### Version

1.21.5

### Which OS/distro are you seeing the problem on?

Arch Linux

### Relevant log output

Previously the snippet below was all that was "odd."

```
[xcb] Extra reply data still left in queue
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
conky: xcb_io.c:673: _XReply: Assertion `!xcb_xlib_extra_reply_data_left' failed.
```

Today I caught it turning gray and checked the logs to find nothing.
```
conky: desktop window (0x386) is root window
conky: window type - desktop
conky: drawing to created window (0x5a00002)
conky: drawing to double buffer
conky: forked to background, pid is 28922

conky: FOUND: console
conky: FOUND: ncurses
conky: FOUND: file
conky: FOUND: x11
conky: FOUND: wayland
conky: '(null)' x11 session running 'CTWM' desktop
```

I've now started running with -D so hopefully I can catch something more useful soon.

I restarted my Window manager and it went gray, absolutely nothing turned up in the logs. I've restarted my WM before and it's not done it then. It also does it when the WM has never been restarted.

Window manager is CTWM and I'm not running any compositor. Trying with -DD now.

Caught it with -DD still nothing in the logs to say anything went wrong. Just turns gray and loses any transparency.

**Comment by henning-schild** [comment]
Check how many conky processing you have running. Since some time on my system conky starts up many times, basically a new process with every new login. Seems to be related to restoring previously saved sessions.

Could be something different in your case, but 20 transparent windows layered on top of each other are simply not transparent anymore.

**Comment by nPHYN1T3** [comment]
There is only a single process/instance. I never said anything about logging in more than once. Also if that was the case it would continue to be gray after saving the conf file. More so transparency is like adding 0, 0+0+0=0 so if you somehow get a number other than 0 there is an issue/bug. Be 0*3 or 0*20.

**Comment by LinuxOnTheDesktop** [comment]
Perhaps it is worth adding the following, in the hope of helping out the reporter and others who have similar problems.

I find, on Linux Mint Cinnamon, that Conky does not get terminated - or terminated properly? - upon logoff; thus, logging back in again - without a shutdown - causes problems (though I forget exactly what the problems are). So I added the following to `~/.bash_logout` (and that file might need to be created and, I imagine, set executable).

```
# CONKY
if pidof -nqsx conky; then
    killall -q -u "${USER}" conky >/dev/null 2>&1 || true
fi
```
That seemed to solve the problem.

**Comment by nPHYN1T3** [comment]
Again there is no logging in or out in my report. This has nothing to do with the issue.

**Comment by stele95** [comment]
I have somewhat of the same issue. I'm using three conky instances with three different config files, stacked on top of each other, and the behaviour is weird. This setup worked perfectly the last time I used it (around 6-7 months ago). 
Take a look at the attached video. The background should be semi transparent, but it's actually flickering, and text is all broken like it's being drawn on top of already drawn text/layer without clearing the previous text/layer.

https://github.com/user-attachments/assets/674e728d-1724-4524-a2ad-250d7b197b72

What I've noticed while trying to debug my conf files is that when I remove the following lines of code, I get a black background and text is properly displayed, so I assume it has something to do with how layers are drawn.

```
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 190,
```

Testing with a single instance and a single conf file, after removing `own_window_transparent = true`, the background starts semi transparent and with each update losses transparency until it's completely black.

I use the following code for the `own_window` settings:

```
    own_window_class = 'Conky',
    own_window = true,
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 190,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
```
I'm on EndeavourOS, KDE Wayland, using latest commit from git.

I've also tested with [Conky Gorilla](https://github.com/brndnmtthws/conky/wiki/Configs#conky-gorilla), the same issue with text being drawn over each other is happening. 

This is the `conky.config` from my config file
```
conky.config = {
    background = true,
    use_xft = true,
    xftalpha = 0.8,
    update_interval = 1.0,
    total_run_times = 0,
    temperature_unit = 'celsius',
    
    xinerama_head = 1,

    own_window_class = 'Conky',
    own_window = true,
    own_window_type = 'desktop',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_argb_value = 190,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    alignment = 'middle_middle',

    double_buffer = true,
    minimum_width = 530,

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = false,

    -- stippled_borders = 8,
    -- border_inner_margin = 4,
    -- border_width = 1,

    gap_x = 320,
    gap_y = -50,

    no_buffers = true,
    uppercase = false,

    cpu_avg_samples = 12,
    net_avg_samples = 2,

    use_spacer = 'none',
    text_buffer_size = 256,
    override_utf8_locale = true,

    default_color = 'a8a8a8',
    default_shade_color = 'darkgray',
    default_outline_color = 'darkgray',

    color2 = '4285F4',
    color3 = 'ff7200',
    color4 = 'ff000d'
};
```

**Comment by nPHYN1T3** [comment]
Well the thread jacking continues. Note the X11 tagged in the labels. ;p Wayland is its own set of undercooked issues but honestly your video just looks like the old "you need triple buffering" issue. Either way everyone here has reported their own issue that should be reported separately.

**Comment by stele95** [comment]
> Well the thread jacking continues. Note the X11 tagged in the labels. ;p Wayland is its own set of undercooked issues but honestly your video just looks like the old "you need triple buffering" issue. Either way everyone here has reported their own issue that should be reported separately.

I've missed the label, my bad :sweat_smile:  Thanks for pointing that out. I'll report it as a new issue

**Comment by nPHYN1T3** [comment]
Tis fine, just frustrated and cheeky.

**Comment by stele95** [comment]
I've been testing with older versions of Conky, even going back to 1.18.3, all of them have my issue, and I've used some of those versions back when they were released and they were working correctly. So it would seem that it's also not a Conky issue and it's starting to look like it's related to yours. I'll see if I can gather more info

**Comment by nPHYN1T3** [comment]
Sadly with your issue I suspect it could be a mix of wayland, the KDE compositor, GPU drivers (refresh related redraw stuff) etc. For me everything worked fine for the longest time but I started noticing this "gray" crap. I suspect this started after I ditched my compositor. On the Arch wiki about conky it has a note about the pseudo transparency and conky turning gray if the wallpaper is set above the X root. With the compositor I set my wallpaper with feh, but without it my WM sets it. I suspect my WM is doing something in the background, some type of refresh which conky doesn't like.

I just did some testing (can't sleep) where I remove the wallpaper settings from my WM, set with feh and then restarted my WM, but again gray. I then tried it with picom, still conky goes gray. Oddly when I restart my WM conky does a little restart, just like if you save a change to the settings. Upon coming back up from the restart it's fine, but after about a second it changes from transparent to gray. So now I'm not sure who is the culprate.

My WM rarely gets updates, but there was one not too long ago that might have been around the time of some of the system changes (ditching compositor etc). I'd suspect a change to conky or something in X perhaps has triggered or contributed to this.

For now the only thing I can think of is a cheese cron job touch -m ~/.conkyrc every so often to correct it since saving the rc file resets conky.

**Comment by nPHYN1T3** [comment]
So I suppose if anyone else comes across this switching own_window_type = 'desktop', to own_window_type = 'override', fixes this! HAZA!

**Comment by stele95** [comment]
That also fixed my issue! Thank you!

**Comment by Caellian** [comment]
> That also fixed my issue! Thank you!

`own_window_type` doesn't do anything on Wayland yet.

> So I suppose if anyone else comes across this switching own_window_type = 'desktop', to own_window_type = 'override', fixes this!

Weird, transparent windows need to ask the compositor/WM what's the "image" behind them when things behind them change. It's possible this is when conky turns opaque. It's instantaneous and not gradual loss of transparency?

What's weird is that CTWM default background color for windows is (pure) "white", and not gray.

I'll keep this closed, if anyone experiences a similar issue and `override` window type doesn't work for their case, they should try `normal` with standard `undecorated,below,sticky,skip_taskbar,skip_pager` window hints. If none of that work, bump this issue and I'll reopen it.

**Comment by stele95** [comment]
> own_window_type doesn't do anything on Wayland yet.

Well it fixed the issues I was having. After checking, it seems Conky is running through XWayland for me (with `override` option, have tested others).

**Comment by nPHYN1T3** [comment]
@Caellian yeah it's instantaneous. Everything is cool, then blat! GRAY! Each of my workspaces has its own color so CTWM *in theory* wouldn't report the default color, but that said it also doesn't change to what the color is set to either. So my text is all #CCCCCC and the background color it changes to is something maybe like #C4C4C4.

own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager', is what I've had set for the longest time.

@stele95 XWayland ;p cheater ;) On the plus side that means the X fix...fixes for you. ;)
