### ISSUE TITLE
[Bug]: conky not in fluxbox slit anymore

### ISSUE THREAD

**Issue by sieste** [brndnmtthws/conky#2046]
### What happened?

After full system update of arch linux, the conky window appears on the desktop on top of all other windows, rather than in the fluxbox slit as it used to.

### Version

conky 1.21.5-pre-20091470 compiled for Linux x86_64

### Which OS/distro are you seeing the problem on?

Arch Linux

### Conky config

```Lua
conky.config = {
    alignment = 'top_left',
    background = false,
    border_inner_margin = 10,
    border_width = 5,
    cpu_avg_samples = 2,
    default_color = '#ccbbaa',
    default_outline_color = '#ccbbaa',
    default_shade_color = 'white',
    double_buffer = true,
    draw_borders = true,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    extra_newline = false,
    font = 'Source Code Pro:size=14:antialias=true',
    gap_x = 60,
    gap_y = 60,
    minimum_height = 5,
    minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    out_to_wayland = false,
    own_window_colour = '#112233',
    own_window = true,
    own_window_class = 'Conky',
    own_window_title = '',
    own_window_type = 'dock',
    show_graph_range = false,
    show_graph_scale = false,
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    use_xft = true,
}
```

### Relevant log output

```Shell
conky: desktop window (0x4f3) is root window
conky: window type - dock
conky: drawing to created window (0x800001)
conky: drawing to double buffer
conky: FOUND: console
conky: FOUND: ncurses
conky: FOUND: file
conky: FOUND: x11
conky: FOUND: wayland
```

**Comment by Caellian** [comment]
Likely caused by my changes to [`update_x11_workarea()`](https://github.com/brndnmtthws/conky/blob/b05810d439447666bb7a8c3823d94833cc282033/src/x11.cc#L331), or (less likely) [`set_struts(alignment align)`](https://github.com/brndnmtthws/conky/blob/b05810d439447666bb7a8c3823d94833cc282033/src/x11.cc#L1140).

**Comment by heavyjoost** [comment]
@sieste @Caellian I have the same problem in Openbox. I noticed line 643 in `src/x11.cc` got changed a few months back which breaks it. Changing it from this:
```c
        // wmHint.initial_state = WithdrawnState;
```
To this:
```c
        wmHint.initial_state = WithdrawnState;
```
Fixes it. I'm no expert on dockapps but as far as I know dockapps are required to be in the withdrawn state initially.
