### ISSUE TITLE
Feature Request: nvidiabar and nvidiagraph

### ISSUE THREAD

**Issue by MattSturgeon** [brndnmtthws/conky#207]
I have been trying out the updated nvidia module from 22fe3b1ea4f450061dc8dcff1bf4b8c4b560cd7f and I have found `${nvidia gpuutil}` a vastly superior alternative to `${exec nvidia-settings -t -q '[gpu:0]'/GPUUtilization | tr ',' '
'|grep graphics|sed 's/[^0-9]//g'}` (for example).

However I have one glaring issue. So far as I can tell, there is no way to make a graph or bar out of these internal variables. My config has a lot of `${execgraph "nvidia-settings #...etc"}` in it that I would like to replace with something like `${nvidiabar memutil}` or `${nvidiagraph temp}` for example.

I appreciate this may be more complicated than it appears, but I would appreciate any feedback on the suggestion. :)

**Comment by Nooby4Ever** [comment]
You can always use Lua, you can pretty much design the bar however you want. Depends on your knowledge of programming/Lua. There are examples on DeviantArt on how to do it.

**Comment by MattSturgeon** [comment]
I've never used Lua but I do feel like this is something that should really be built into the nvidia module... If I was to try and hack anything together I'd rather it be built into conky rather than a Lua extension.

Right now I have a working solution using `${execgraph}` and the above shell commands so it's not the end of the world.

**Comment by MattSturgeon** [comment]
From a quick look over the code (I don't know C++ and hardly know C) it looks like we need to define an object like this in core.cc??

    	END OBJ_ARG(nvidiabar, 0, "nvidiabar needs an argument")
		if (set_nvidia_type(obj, arg)) {
			CRIT_ERR(obj, free_at_crash, "nvidiabar: invalid argument"
				 " specified: '%s'\n", arg);
		}
		obj->callbacks.barval = &nvidia_bar_value;
		obj->callbacks.free = &free_nvidia;

and we need to split `print_nvidia_value` into functions that print to buffer and a function to return a float for `barval`.

I'm almost certainly missing something really important but I feel like if I was to work on this that's where I'd start

**Comment by MattSturgeon** [comment]
Fixed in d8c659e7de8f7173ff66161e5bf191f5aa621362

I still need to add docs

**Comment by kgreenek** [comment]
Updating the docs would be very helpful. I scoured the internet for way to long until I came across this PR.

Thanks for this feature btw, it's awesome!
