### ISSUE TITLE
[BUG]: OpenBSD crash when `cpu` variable is used

### ISSUE THREAD

**Issue by Caellian** [brndnmtthws/conky#2088]
@epsheldoni reports a bug with `${cpu}` variable on OpenBSD which causes conky to crash. I'm opening it as a separate issue because it's not related to the [original one](https://github.com/brndnmtthws/conky/issues/2073) which will be fixed once [`fix/openbsd76-build`](https://github.com/g0mb4/conky/tree/fix/openbsd76-build) is merged.

## Conky Version

main (SHA [47ec9f9](https://github.com/brndnmtthws/conky/commit/47ec9f911ccff28d1a632d37b56e318b0e644a6f)), ^v1.21.8

## OS

OpenBSD 7.6

## Conky config

lines that cause conky to crash:
```
CPU 1 usage:$alignr   ${cpu cpu1}%
CPU 2 usage:$alignr   ${cpu cpu2}%
CPU 3 usage:$alignr   ${cpu cpu3}%
...
CPU 15 usage $alignr ${cpu cpu15}%
```

## Logs

<details>
<summary><code>./conky -d</code></summary>
<pre>
conky: desktop window (0x1a00003) is subwindow of root window (0x538)
conky: window type - normal
conky: drawing to created window (0x3000002)
conky: drawing to double buffer
conky: forked to background, pid is 33192
conky: FOUND: console
conky: FOUND: ncurses
conky: FOUND: file
conky: FOUND: x11
conky: '(null)' (null) session running 'XFCE' desktop
conky: Cannot get kern.cp_time
conky: obj->data.i 2 info.cpu_count 1
conky: attempting to use more CPUs than you have!
</pre>
</details>

<details>
<summary><code>sysctl | grep cpu</code></summary>
<pre>
conky: desktop window (0x1a00003) is subwindow of root window (0x538)
conky: window type - normal
conky: drawing to created window (0x3000002)
conky: drawing to double buffer
conky: forked to background, pid is 33192
conky: FOUND: console
conky: FOUND: ncurses
conky: FOUND: file
conky: FOUND: x11
conky: '(null)' (null) session running 'XFCE' desktop
conky: Cannot get kern.cp_time
conky: obj->data.i 2 info.cpu_count 1
conky: attempting to use more CPUs than you have!
</pre>
</details>

The following lines in the terminal output may indicate something OpenBSD specific:
<pre>
conky: Cannot get kern.cp_time
conky: obj->data.i 2 info.cpu_count 1
conky: attempting to use more CPUs than you have!
</pre>

_Originally posted by @epsheldoni in https://github.com/brndnmtthws/conky/issues/2073#issuecomment-2492669414_

**Comment by epsheldoni** [comment]
OS should be OpenBSD 7.6
