### ISSUE TITLE
Add option for selecting nVidia device

### ISSUE THREAD

**Issue by kennyballou** [brndnmtthws/conky#21]
I have a few machines that have multiple GPU's, but conky only queries the first one (device 0). Running a lot of CUDA code and BOINC projects, being able to see the clock speeds and temperatures of both cards would be a lot more helpful.

**Comment by Nooby4Ever** [comment]
I advice to just read the values from nvidia-settings, if you have it available on your system that is (should come by default with the latest drivers).
In Conky just use: ${exec nvidia-settings -q [gpu:0]/GPUCurrentProcessorClockFreqs -t}
The command: nvidia-settings -q all -t lists all possible options to be read out from nvidia-settings. The values are not always nicely formatted though.

**Comment by kennyballou** [comment]
This seems like it would work. I'll take this as the solution and close this issue.
