### ISSUE TITLE
Openweathermap API key

### ISSUE THREAD

**Issue by zagortenay333** [brndnmtthws/conky#210]
The folks at http://openweathermap.org/ allow FOSS projects to get a public API key. I just talked to them and was told that the conky project as a whole can have a key, which then can be used in various themes.

Would you consider registering an API key for conky? https://openweathermap.org/faq#error401

Otherwise, I'll just register one for my theme, but it would be cool to have a global key for various conky themes.

**Comment by plikhari** [comment]
Hey that is good news :-)

Perhaps I shall give it a GOOD shot for conkywx

**Comment by lasers** [comment]
inb4 https://github.com/su8/pinky-bar/blob/master/src/weather.c

**Comment by lasers** [comment]
https://medium.freecodecamp.org/how-to-securely-store-api-keys-4ff3ea19ebda

I'm itching to close this. If we made a API key, we probably would need to figure out how to hide that without requiring users to do anything (ie installing an additional dependency for weather alone)... And what's more, if our API key got invalid, the users without specified API keys will suddenly have no weathers. This is same for other tokens. We keep our hands clean.

It seems like a no-brainer (to me) to let users specify tokens themselves.

@zagortenay333 I looked at https://github.com/zagortenay333/Harmattan. You probably can replace the value inside `template6` with `ADD_YOUR_API_KEY_HERE` in all weather themes and tell users about `sed` command to efficiently update your weather themes with a valid API key.

If you don't agree, I will leave this open and assign this to the `Owner` instead.

**Comment by plikhari** [comment]
I have had a discussion - a few years back - with the people running openweather - yes at the time they were giving out API keys for FOSS projects besides for individual developer.

We can approach them again.

A point that came up was - that you have to be a genuine developer to use an individual API key - and not just to use the website - like many have done as a work around with other sites. So using the line `ADD_YOUR_API_KEY_HERE` will not help.

**Comment by brndnmtthws** [comment]
I'm not opposed, but we don't have a way to include the API key without simply making it available to everyone in plain text. My guess is that is not acceptable to OWM.

**Comment by plikhari** [comment]
Today we have the api key but tomorrow - just like wunderground the API could get an end of service.

Perhaps conky should focus on system information and since we have the magic of LUA - let other applications handle the more esoteric stuff like RSS, weather etc. We definitely could do with mouse interaction.
