### ISSUE TITLE
[Bug]: Conky v 1.21.9 conky: cannot kvm_openfiles: /dev/mem: Permission denied

### ISSUE THREAD

**Issue by epsheldoni** [brndnmtthws/conky#2107]
### What happened?

Down loaded latest version on NetBSD10.0.  Compiles yet after starting it throws the following:

NetBSD-10$ ./conky
conky: desktop window (0x1200028) is subwindow of root window (0x111)
conky: window type - normal
conky: drawing to created window (0x2e00002)
conky: drawing to double buffer
conky: forked to background, pid is 6017
NetBSD-10$ 
conky: FOUND: x11
conky: FOUND: file
conky: FOUND: ncurses
conky: FOUND: console
conky: cannot kvm_openfiles: /dev/mem: Permission denied
conky: maybe you need to setgid kmem this program?

The last two lines repeat until I kill conky.

### Version

1.21.9

### Which OS/distro are you seeing the problem on?

Ubuntu

**Comment by Caellian** [comment]
Closing as duplicate of #2108
