### ISSUE TITLE
Conky folder

### ISSUE THREAD

**Issue by sadalavoaoj** [brndnmtthws/conky#212]
Hi there,

Im trying to set my conky but i have a weird problem.  I can run conky by terminal but i do not see .conky folder in /home.

Where could the file that is running be? I would like to change conkyrc configuration for a nice clock made in words.

Best regards,

**Comment by chepioq** [comment]
How do you launch Conky?

**Comment by sadalavoaoj** [comment]
Hello my friend,

I added in Mint Cinnamon 17.3 conky -d to startup but i only see conky on desktop after i open terminal and write "conky".

I noticed that when i do "Win +D" shortcut the icon stays like minimized again.

Here is a [example.](http://imageshack.com/a/img924/8586/X0nr5n.png)

**Comment by chepioq** [comment]
Ok my friend.
If you launch conky with -d option, you launch the conkyrc default file.
You must use the -c option if you want launch your own conky.
For sample, I have five conky configuration, in a folder .conkyrc I have create in my home :

conky -c /home/dominique/.conkyrc/conky_monitor/conky-monitor
conky -c /home/dominique/conky-meteo/conky-meteo4
conky -c /home/dominique/.conkyrc/conky-saint/.conkyrc10
conky -c /home/dominique/.conkyrc/conky-calendrier/conkyrc15
conky -c /home/dominique/.conkyrc/conky-soleil1/conkyrc

**Comment by lasers** [comment]
@brndnmtthws Should I keep calling your name or you'll check messages? For instance, can we close this? Just a general questions/support. Thanks.

**Comment by brndnmtthws** [comment]
@lasers I just made you a collaborator, so you can close them yourself :)

**Comment by lasers** [comment]
You can read more about it in man page. `$ man conky`
```
       -c | --config= FILE
              Config file to load instead of $HOME/.config/conky/conky.conf
```
