### ISSUE TITLE
compiling from source instructions outdated

### ISSUE THREAD

**Issue by ishankhare07** [brndnmtthws/conky#216]
there appears to be no file `autogen.sh`
cmake doesn't yield any results

**Comment by chepioq** [comment]
Have you read the README.cmake file ?:

```
Hello, there.

Using CMake to build Conky is pretty easy, and here is how I do it:

1. From the top level source dir, create a build working dir, and cd into it
  $ mkdir build
  $ cd build
2. Run the cmake configuration process
  $ cmake ../ # pass the path to the sources to cmake
  OR
  $ ccmake ../ # you can also use the fance curses interface, or try cmake-gui
3. Compile as usual, and enjoy the out-of-source goodness
  $ make
  # make install # if you want

There are a number of build options for Conky, and the best way to discover
them is to use the ccmake (or cmake-gui) CMake tool for browsing them.

Certain Conky build time features (such as doc generation) require third-party
applications, which you should be notified of via CMake.  In the case of doc
generation, you'll need the docbook2X package (available on most
distributions).

```

From the directory of conky 
mkdir build
cd build
ccmake../
make

and after, as root 
make install

**Comment by Corin-EU** [comment]
More than a year later ...

What is the point in continuing to include the INSTALL file in releases when these are the generic instructions for autotools and conky uses cmake?

If the INSTALL file is not going to be updated to show the proper cmake instructions, as kindly provided above by chepioq, please delete it.

**Comment by Corin-EU** [comment]
Also there does not appear to be any documentation concerning the need for specifying which features can be turned on or off via the cmake options, viz

      CMAKE_OPTIONS="\
     -DBUILD_AUDACIOUS=OFF    \
     -DBUILD_CURL=ON          \
     -DBUILD_EVE=ON           \
     -DBUILD_IBM=OFF          \
     -DBUILD_IMLIB2=ON        \
     -DBUILD_LUA_CAIRO=ON     \
     -DBUILD_LUA_IMLIB2=ON    \
     -DBUILD_LUA_RSVG=ON      \
     -DBUILD_NVIDIA=ON        \
     -DBUILD_RSS=ON           \
     -DBUILD_WEATHER_METAR=ON \
     -DBUILD_WEATHER_XOAP=ON  \
     -DBUILD_WLAN=ON          \
     -DBUILD_XDBE=ON          \
     -DBUILD_XMMS2=OFF        \
     "
 
     cd  path_to_temporary_build_directory

     cmake ${CMAKE_OPTIONS}   path_to_conky_source_top_level_directory

Why support for Lenovo laptops is turned on by default (when the majority of users are probably not using a Lenovo laptop) and has to be explicitly turned off, wherase essentail support for LUA has to be turned on, is anybody's guess.

**Comment by mzpqnxow** [comment]
Terrible process to build this. I had a handful of PRs but I'm not sure I'm going to bother at this point. At least some documentation that says "the documentation is wrong" would be nice...
