### ISSUE TITLE
Unable to find ncurses library

### ISSUE THREAD

**Issue by ghost** [brndnmtthws/conky#217]
I'm trying to compile conky from source. But when I enter cmake ../ I get:

CMake Error at cmake/ConkyPlatformChecks.cmake:125 (message):
  Unable to find ncurses library
Call Stack (most recent call first):
  CMakeLists.txt:37 (include)

I know that I don't have the ncurses library and I did a search about installing ncurses so I did:

sudo apt-get install libncurses5-dev libncursesw5-dev

But it still did not work. Can anyone help me? I'm not very experienced at compiling from source.
I am running an ubuntu 32-bit computer.

**Comment by MattSturgeon** [comment]
You can try `ncurses-dev` instead of `libncurses5-dev `.

However, if I recall correctly, when I first built on my fedora machine, I'd run `ccmake` then installed `ncurses` after recieving the error and it kept giving the error until I cleaned my build directory.

You can try running this from your git checkout directory (you will have to reconfigure any options you entered):

    rm -rf build/*

**Comment by aaronTHJ** [comment]
It doesn't work I tried:

'sudo apt-get install ncurses-dev'

it said:

'Note, selecting 'libncurses5-dev' instead of 'ncurses-dev'
libncurses5-dev is already the newest version.`

It seems that my system only recognises `libncurses5-dev`

**Comment by MattSturgeon** [comment]
Did you try deleting `build/*` and starting `ccmake` from scratch?

**Comment by aaronTHJ** [comment]
It works now! I successfully built and installed it. Thanks very much! Just a quick question did I have to build the lua modules? Because currently my conky is just a black window on the left side of my desktop and when I click on my desktop it disappears. Is that normal?

**Comment by MattSturgeon** [comment]
Do you have a conkyrc file? What do you have the window mode set to?

**Comment by aaronTHJ** [comment]
Where do I find the conkyrc file? How do I check what window mode I set it to?

**Comment by MattSturgeon** [comment]
By default you create a file called `~/.conkyrc`

I'm on my phone at the moment so I can't really help. If you just read the docs ([`man conky`][man]) or google ["conky config file"][conkyrc] it should be fairly clear.

[All the settings][settings], [variables for use within the printed text][vars].

[conkyrc]: http://google.com/search?q=conky+config+file
[man]: http://conky.sourceforge.net/docs.html
[settings]: http://conky.sourceforge.net/config_settings.html
[vars]: http://conky.sourceforge.net/variables.html

**Comment by MattSturgeon** [comment]
Heres an example `conkyrc`:

```
conky.config = {
	-- output settings
	own_window = true,
	own_window_type = 'normal', 
		-- options are 'normal', 'desktop', 'dock',
		-- 'panel' or 'override'
	own_window_hints = 'above, skip_taskbar, skip_pager',
		-- options are 'undecorated', 'below', 'above',
		-- 'sticky', 'skip_taskbar', 'skip_pager'
	own_window_title = 'my awesome conky window',

	-- min and max sizes
	maximum_width = 200,
	minimum_width = 100,
	minimum_height = 20,

	-- position (or padding in 'normal' window mode)
	alignment = 'top_left',
	gap_x = 10,
	gap_y = 10,

	-- background and colours
	own_window_argb_visual = true, -- ARGB transparency; wont work well with 'override' mode
	own_window_argb_value = 230, -- opacity value (0-255)
	own_window_colour = '0000ff',
	default_color = '0c0c0c',
	

	-- where to print conky's output
	out_to_console = false,
	out_to_ncurses = false,
	out_to_x = true
}

conky.text = [[
CPU: ${cpubar}

RAM: ${membar}

Put other cool variables here
# you can write text section comments using '#' or options section comments with '--'
\
# You can escape newlines (and some other characters) with '\'
]]
```

**Comment by aaronTHJ** [comment]
I googled conky config file and found a wikihow page on how to configure conky, [http://www.wikihow.com/Configure-Conky](url), it said to install lm-sensors. Should I do that?

**Comment by MattSturgeon** [comment]
It is a good way of configuring your sensors if you want to display things like HDD temps, CPU temps, fan speeds, voltages, etc.

Some of those things may already work correctly on your system.

There's a guide on how to setup `lm-sensors` [here](http://ubuntuforums.org/showthread.php?t=2780) (you can skip step 2) if you want it

**Comment by Stolas** [comment]
Same issue on OpenSuse.

```
-- checking for module 'ncurses'
--   package 'ncurses' not found
CMake Error at cmake/ConkyPlatformChecks.cmake:124 (message):
  Unable to find ncurses library
Call Stack (most recent call first):
  CMakeLists.txt:37 (include)


-- Configuring incomplete, errors occurred!
See also "/home/stolas/code/conky/build/CMakeFiles/CMakeOutput.log".
See also "/home/stolas/code/conky/build/CMakeFiles/CMakeError.log".
stolas@wasp-prime:~/code/conky/build% zypper se ncurses                                                        3s
Loading repository data...
Reading installed packages...

S | Name                     | Summary                                                   | Type
--+--------------------------+-----------------------------------------------------------+--------
i | libncurses5              | The New curses Libraries                                  | package
i | libncurses5-32bit        | The New curses Libraries                                  | package
i | libncurses6              | The New curses Libraries                                  | package
i | libncurses6-32bit        | The New curses Libraries                                  | package
  | libyui-ncurses-devel     | Libyui-ncurses header files                               | package
  | libyui-ncurses-doc       | Libyui-ncurses documentation                              | package
  | libyui-ncurses-pkg-devel | Libyui-ncurses-pkg header files                           | package
  | libyui-ncurses-pkg-doc   | Libyui-ncurses-pkg documentation                          | package
i | libyui-ncurses-pkg7      | Libyui - yast2 package selector widget for the ncurses UI | package
i | libyui-ncurses7          | Libyui - Character Based User Interface                   | package
i | ncurses-devel            | Include Files and Libraries mandatory for Development     | package
  | ncurses-devel-32bit      | Include Files and Libraries mandatory for Development     | package
i | ncurses-utils            | Tools using the new curses libraries                      | package

```

**Comment by MattSturgeon** [comment]
@Stolas could you submit a pull request so that @brndnmtthws can test and review your patch?

**Comment by Stolas** [comment]
I'll setup a decent development system (a non-headless one) and start submitting my Patches (I've got multiple)

**Comment by Vistaus** [comment]
Same issue on Solus. ncurses-devel is installed but Conky says it can't find it. Note that I've had ncurses-devel install prior to cloning the Conky git master repo.

**Comment by arpitjindal97** [comment]
Same issue in Arch Linux

**Comment by plikhari** [comment]
@arpitjindal97 try using [conky-cairo](https://aur.archlinux.org/packages/conky-cairo/) in the AUR

**Comment by arpitjindal97** [comment]
```
CMake Error at cmake/ConkyPlatformChecks.cmake:124 (message):
  Unable to find ncurses library
Call Stack (most recent call first):
  CMakeLists.txt:37 (include)


-- Configuring incomplete, errors occurred!
See also "/tmp/yaourt-tmp-arpit/aur-conky-cairo/src/conky-1.10.6/CMakeFiles/CMakeOutput.log".
See also "/tmp/yaourt-tmp-arpit/aur-conky-cairo/src/conky-1.10.6/CMakeFiles/CMakeError.log".
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Makepkg was unable to build .
```

**Comment by xsoft** [comment]
Ive tried this at Ubuntu 17.04 (64b), 16.10 (32b and 64b) but all ends with this:
(VMbox images)

```
Note, selecting 'libncurses5-dev' instead of 'ncurses-dev'
E: Unable to locate package libqt4-core
E: Unable to locate package libqt4-gui
```

use: apt-get install libncurses5-dev ncurses-dev
will NOT help

Using Ubuntu 12.04 worked (whoa)
```
Install OK!
make[1]: Leaving directory `/tmp/OpenBLAS'
WARNING: Your ipython version is too old.  Type "ipython --version" to see this.  Should be at least version 2
==> Torch7's dependencies have been installed
```
Ive used images from: http://www.osboxes.org/ubuntu/
Note that smallest Amazon Ubuntu image worked also.
