### ISSUE TITLE
random crash resolving top user

### ISSUE THREAD

**Issue by shiroyagi** [brndnmtthws/conky#220]
The return value of getpwuid() is not tested in top.c (1.9.0) or top.cc (current master).

Thread 1 "conky" received signal SIGSEGV, Segmentation fault.
print_top (obj=0x6a43c0, p=0x6a687b "", p_max_size=16149) at top.c:1043
1043                    snprintf(p, width, "%.8s",

I am seeing random crashes, possibly related to slow user look-up on the network.

Removing ${top user 1} from .conkyrc is a workaround.

**Comment by lasers** [comment]
`${top user 1}` worked okay here in console. Always first `root`, then `$USER`. Are you still experiencing this? How long does it generally take to crash due to this variable? Thanks.

**Comment by lasers** [comment]
Closed via 25eac4c.

@su8 Just FYI.
* https://help.github.com/articles/closing-issues-using-keywords/
* https://blog.github.com/2013-01-22-closing-issues-via-commit-messages/
* [https://:heart:](https://wallpapertag.com/wallpaper/full/e/1/a/714497-beautiful-love-wallpaper-1920x1080-hd.jpg)
