### ISSUE TITLE
Can't run conky due to config file!

### ISSUE THREAD

**Issue by cirelli94** [brndnmtthws/conky#222]
I downloaded a theme from here http://blog.icanbeacoder.com/creative/infinity-conky/
I installed everything.
Now, my ~/.conkyrc file is like this: http://pastebin.com/Et69vLax

And when I do in my terminal concky -v I obtain:
conky 1.10.1 compiled Wed Jan  6 17:11:44 UTC 2016 for Linux 3.19.0-43-generic x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky

 General:
- math
- hddtemp
- portmon
- IPv6
- Curl
- RSS
- Weather (METAR)
- Weather (XOAP)
- wireless
- support for IBM/Lenovo notebooks
- nvidia
- eve-online
- builtin default configuration
- old configuration syntax
- Imlib2
- apcupsd
- iostats
- ncurses
- Internationalization support
  
  Lua bindings:
- Cairo
- Imlib2
- RSVG
  X11:
- Xdamage extension
- XDBE (double buffer extension)
- Xft
- ARGB visual
- Own window
  
  Music detection:
- Audacious
- MPD
- MOC
- XMMS2
  
  Default values:
- Netdevice: eth0
- Local configfile: $HOME/.conkyrc
- Localedir: /usr/share/locale
- Maximum netdevices: 64
- Maximum text size: 16384
- Size text buffer: 256

So it's 1.\* version!
But when I try to run it, it said: 
conky: Syntax error (/home/cirelli/.conkyrc:17: unexpected symbol near '#') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: [string "..."]:138: attempt to index local 'settings' (a nil value)

so I remove comments, and then it said:
conky: Syntax error (/home/cirelli/.conkyrc:1: '=' expected near 'yes') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: [string "..."]:138: attempt to index local 'settings' (a nil value)

Why? Only concky v2 needs "=" or am I mistake?

**Comment by mxmlnkn** [comment]
The `unexpected symbol near '#'` is only a warning. Conky will still use the old syntax if it recognizes it. Here is an example with the new syntax: https://github.com/brndnmtthws/conky/issues/218
There also is a converter, although I'm not sure how well it works. It worked for me, though: https://github.com/brndnmtthws/conky/blob/master/extras/convert.lua
The real problem seems to be
`conky: [string "..."]:138: attempt to index local 'settings' (a nil value)`
I'm not sure where this comes from in your conkyrc. Try reducing your conkyrc line by line to see when it starts working again.

**Comment by njkevlani** [comment]
> I'm not sure where this comes from in your conkyrc.
That's coming from that convert.lua script. It looks like every config file is converted to new syntax using this script, if needed and possible.

**Comment by CottonEaster** [comment]
I have similar problems: my Cony won't run and the conversion script gives the error:

```
/usr/bin/lua: ./convert.lua:139: attempt to index local 'settings' (a nil value)
stack traceback:
	./convert.lua:139: in main chunk
	[C]: ?
```

I am not even sure that my Conky config is in the old format. Is there more than one old format? Is, e.g., the following in the newest format?

```
conky.config =
{
	-- // Update & reporting //
		update_interval = 1.1,
```

**Comment by lasers** [comment]
Run `dos2unix` on your new config first before using `convert.lua`. Tested okay.
