### ISSUE TITLE
Conky scroll multibyte character splitting

### ISSUE THREAD

**Issue by Rojikku** [brndnmtthws/conky#223]
I run i3 WM in arch. I feed/pipe conky into my i3bar, which is great. Runs great.
However, when listing the filename of songs, i3bar sometimes gives me:
json lexical error invalid bytes in utf8 string conky
I have found that by removing the scrolling part, I no longer have this issue. However, many of the names are extremely long, so this is inconvenient.
I saw mentioned there was an issue at one point with conky splitting characters mid-byte. Personally, I don't care if the whole name displays perfectly all the time, as long as it doesn't crash my i3 bar.
I'll attach my config.
I honestly assumed this issue would already be on here, but as I don't see it, I'll create one.

[i3conkyrc.txt](https://github.com/brndnmtthws/conky/files/162555/i3conkyrc.txt)

**Comment by darkfeline** [comment]
> I saw mentioned there was an issue at one point with conky splitting characters mid-byte. 

"At one point" [was six years ago](https://sourceforge.net/p/conky/bugs/341/). Unfortunately, rewriting something in C++ doesn't magically fix encoding bugs.

**Comment by plikhari** [comment]
Have a look at iconv - you can modify or strip or what ever - if you pipe the text through this utility and then to where ever you want - like the conky scroll...
