### ISSUE TITLE
conky 1.10 double_buffer issue 

### ISSUE THREAD

**Issue by 2Belette** [brndnmtthws/conky#225]
Hi,
Already see some topics related to this but would like to know if there is any workaround ?
double_buffer is important for me as I refresh every 10 seconds and would lost conky for a couple of second when I switch to another workspace without double_buffer...
Forgot to mention that activating double_buffer makes a black windows as atttached
![screenshot_2016-03-12_15-46-06](https://cloud.githubusercontent.com/assets/2325706/13723570/94498842-e869-11e5-81ab-0efc42a434c6.png)

Any fix planned or any workaround?
many thanks

**Comment by chepioq** [comment]
Can you provide your conky ?

**Comment by benoitne** [comment]
sure:
conky.config = {
own_window=false,
own_window_type='normal',
own_window_hints='undecorated, below, sticky, skip_taskbar, skip_pager',
own_window_transparent=true,
own_window_argb_visual=true,
background=true,
draw_shades=false,
draw_outline=false,
draw_borders=false,
draw_graph_borders=false,
gap_x=5,
gap_y=70,
update_interval=1,
cpu_avg_samples=10,
net_avg_samples=1,
temperature_unit='celsius',
double_buffer=false,
text_buffer_size=4096,
minimum_width=200,
maximum_width=200,
border_inner_margin=0,
border_outer_margin=0,
alignment='top_right',
override_utf8_locale=true,
use_xft=true,
font='caviar dreams:style=Bold:size=8',
xftalpha=1,
uppercase=false,
default_color='D0D0D0',
default_bar_width=180,
default_bar_height=10,
default_graph_width=180,
default_graph_height=10,
}

as soon as I try double_buffer=true I got the issue illustrated by my screenshot

**Comment by chepioq** [comment]
Try that : 

conky.config = {
own_window=true,
own_window_type='normal',
own_window_hints='undecorated, below, sticky, skip_taskbar, skip_pager',
own_window_transparent=true,
own_window_argb_visual=true,
background=false,
draw_shades=false,
draw_outline=false,
draw_borders=false,
draw_graph_borders=false,
gap_x=5,
gap_y=70,
update_interval=1,
cpu_avg_samples=10,
net_avg_samples=1,
temperature_unit='celsius',
double_buffer=true,
text_buffer_size=4096,
minimum_width=200,
maximum_width=200,
border_inner_margin=0,
border_outer_margin=0,
alignment='top_right',
override_utf8_locale=true,
use_xft=true,
font='caviar dreams:style=Bold:size=8',
xftalpha=1,
uppercase=false,
default_color='D0D0D0',
default_bar_width=180,
default_bar_height=10,
default_graph_width=180,
default_graph_height=10,
}

**Comment by benoitne** [comment]
thanks
when I do the changes , conky fails to start with:
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  62 (X_CopyArea)
  Serial number of failed request:  238
  Current serial number in output stream:  241

**Comment by chepioq** [comment]
I think this error is in your conky.text  section, not in the conky.config section I send to you.

Try test line by line in your conky.config

**Comment by benoitne** [comment]
I tried with only one line in my conky.text and same issue : 
conky.config = {
own_window=true,
own_window_type='normal',
own_window_hints='undecorated, below, sticky, skip_taskbar, skip_pager',
own_window_transparent=true,
own_window_argb_visual=true,
background=false,
draw_shades=false,
draw_outline=false,
draw_borders=false,
draw_graph_borders=false,
gap_x=5,
gap_y=70,
update_interval=1,
cpu_avg_samples=10,
net_avg_samples=1,
temperature_unit='celsius',
double_buffer=true,
text_buffer_size=4096,
minimum_width=200,
maximum_width=200,
border_inner_margin=0,
border_outer_margin=0,
alignment='top_right',
override_utf8_locale=true,
use_xft=true,
font='caviar dreams:style=Bold:size=8',
xftalpha=1,
uppercase=false,
default_color='D0D0D0',
default_bar_width=180,
default_bar_height=10,
default_graph_width=180,
default_graph_height=10,
}

conky.text = [[
${offset 20}gw${alignr}test
]]

conky
conky: desktop window (1000003) is subwindow of root window (d4)
conky: window type - normal
conky: drawing to created window (0x1600002)
conky: drawing to double buffer
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  62 (X_CopyArea)
  Serial number of failed request:  160
  Current serial number in output stream:  163

**Comment by benoitne** [comment]
own_window_argb_visual=true is the issue but then impossible to get transparent and it is not very beautifull..
have you succed to get transparency work with double_buffer?
![screenshot_2016-03-12_19-28-58](https://cloud.githubusercontent.com/assets/2325706/13724526/aeb313b4-e888-11e5-921e-ba6be159682c.png)

**Comment by chepioq** [comment]
I have five conky with double_buffer and own_window_argb_visual=true, and they work fine.

own_window_argb_visual=true work only if you have enable desktop effects on your environment (KDE, Gnome, Xfce or other).

**Comment by benoitne** [comment]
thanks chepioq, will test tomorrow, I have a doubt for desktop effects in my Xfce, if you have an idea to check don't hesitate  :)

**Comment by chepioq** [comment]
With Xcfe it'is here (sorry I am french and I don't know how translate in english) : 
right-click on work-space ==> Applications ==> Paramètres ==> Peaufinages des fenêtres ==> onglet "Compositeur" ==> check the case "Activer le compositeur d'affichage"

**Comment by benoitne** [comment]
thanks chepioq (je suis français aussi ;)
As you can see I got the display composing checked
![screenshot_2016-03-14_09-55-42](https://cloud.githubusercontent.com/assets/2325706/13739365/1047dab8-e9cb-11e5-98fa-a87de08f4d5a.png)

**Comment by chepioq** [comment]
In your screen-shot, I cansee that Opacity of windows ... are configured to Opaque.
Try to put them on Transparent

**Comment by benoitne** [comment]
just tested and no change (and it affects all others windows)
anyway this is only when own_window_argb_visual=false which is a workaround but not what I would like to do...
my objective is own_window_argb_visual=true and double_buffer=true...in this cas I got this error message:
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  62 (X_CopyArea)
  Serial number of failed request:  150
  Current serial number in output stream:  153

I search and found some topics speaking about DBE module in X server but I already checked and it is apprently ON by default now...

**Comment by benoitne** [comment]
I think I found a working ocnfiguration: 

own_window=true,
own_window_type='desktop',
own_window_hints='undecorated, below, sticky, skip_taskbar, skip_pager',
own_window_transparent=true,
own_window_argb_visual=true,
background=false,
double_buffer=false,

**Comment by chepioq** [comment]
Here my configuration that work with tranparency and Xfce : 

```
conky.config = {
double_buffer = true,
background = false ,
use_xft = true,
font = "MgOpen Modata L:size=7:bold",
update_interval = 1,
total_run_times = 0,
own_window = true,
own_window_type = 'normal',
own_window_transparent = true,
own_window_argb_visual = true,
own_window_hints = 'undecorated,skip_taskbar,skip_pager,below',

draw_shades = false,
draw_outline = false,
draw_borders = false,
draw_graph_borders = true,
default_color = 'white',
alignment = 'top_right',
gap_x = 12,
gap_y = 250,
no_buffers = true,
uppercase = false,
cpu_avg_samples = 2,
net_avg_samples = 2,
override_utf8_locale = true,
text_buffer_size = 4096,

color1 = '00f5ff',
color2 = 'cd5555',
color3 = '11B3F8',
color4 = '0000ff',
color5 = '176e88',
color6 = 'ff4500',
color7 = '00FF00',
color8 = 'FF8000',
color9 = 'FF0000',

}
```

**Comment by benoitne** [comment]
Thanks
I copied your configuration on my system and got the same error..
It must be something on my system

**Comment by benoitne** [comment]
just a little update, I am now on 1.10.2 and it is like double_buffer is now available again without issue...

**Comment by dbenque** [comment]
@benoitne anything that you could have changed ? because I am running 1.10.2 and I still have the problem:

`
conky: drawing to double buffer
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  62 (X_CopyArea)
  Serial number of failed request:  364
  Current serial number in output stream:  367
`

**Comment by dbenque** [comment]
@benoitne just to let you know that I manage to solve thanks to this other comment:
https://github.com/brndnmtthws/conky/issues/55#issuecomment-48024304

I have recompile conky with XDBE activated. This is required to have the "double buffer" feature working with conky.

I think you can closed this issue.

**Comment by benoitne** [comment]
Thanks I will test this when I'll we reinstall conky as I have multiple things to test on it as well

**Comment by peterfpeterson** [comment]
I was having the same issue with transparency, `own_window_argb_visual = true`, and `double_buffer = true` on fedora 25 with the default desktop (wayland rather than x). Adding `-DBUILD_XDBE` to cmake fixed my issues, but tracking it down was not easy since it is a couple of variables interacting with each other than causes the issue.
