### ISSUE TITLE
Conky keeps drawing every single widget on the left

### ISSUE THREAD

**Issue by SethDusek** [brndnmtthws/conky#228]
For some reason conky completely ignores gap_x and gap_y and just places the widgets on the left. I'm going to paste my .conkyrc but this happens with other conkyrcs too, I've tried conky google now, conky nvidia rings, and so on, and all of them appear on the left no matter what I set gap_x to.

https://gist.github.com/7504a35769384eac4513

**Comment by plikhari** [comment]
You are using the older format for the conkyrc. conky will try and update your old format during run time but that may not work - as in your case.
Perhaps you should use the **convert.lua** utility that ships with conky to convert your conkyrc to the new format and then see what is missing.

**Comment by SethDusek** [comment]
Here is the converted .conkyrc https://gist.github.com/SethDusek/5f39c06593170fbffe446443b6f668e2

Here is the long list of errors its giving: https://gist.github.com/SethDusek/0f60cb99f917cf34b56373ba15ec2618

**Comment by plikhari** [comment]
Change the colors settings from `color1 = '#DCDCDC',`  `to color1 = 'DCDCDC',` - do this for all colour values.

You can also use the templateN format to define your path once in the config section - you can use template0 to template9
```
template1 = '/home/username/harmattan-assets/misc/Numix/God-Mode',
```
later in the text section use it like
```
${image ${template1}/separator-h.png -p 33,269 -s 202x1}
```
See how it goes ...

**Comment by SethDusek** [comment]
Okay, so this is really frustrating and all I want now is for my conkyrc to work. Is there any way I can I revert to the old conky, in which my current .conkyrc will work?

**Comment by Nooby4Ever** [comment]
Your config syntax is for conky versions 1.9.1 and previous so if you do not want to update your config to the new syntax you have to revert back to an older version of conky.

Have you tried the suggestions from  plikhari?

**Comment by SethDusek** [comment]
@Nooby4Ever It seems it's not an issue with the older conky, but it's happening even on newer versions.

https://gist.github.com/6c6af8fce4c5587fe75f5929154d76ca

The widget is still being drawn on the top left

**Comment by plikhari** [comment]
please refer to alignment in the wiki https://github.com/brndnmtthws/conky/wiki/Configuration-Settings
```
Aligned position on screen, may be top_left, top_right, top_middle, bottom_left, bottom_right, bottom_middle, middle_left, middle_middle, middle_right, or none (also can be abreviated as tl, tr, tm, bl, br, bm, ml, mm, mr). See also gap_x and gap_y. 
```
Also compare the variables to get a final check if they are indeed what you want - this way you will learn how things work in conky land :-)

**Comment by SethDusek** [comment]
@plikhari I tried setting align to "bottom_right" to see if it works and it's still in the same position

**Comment by plikhari** [comment]
the word is **alignment**

**Comment by SethDusek** [comment]
@plikhari yup, tried that too

**Comment by plikhari** [comment]
ok remove that first line - conky.config should be there first (you can have comments before that )- nothing shows if I have that line on top. now it may not work for me - but still - remove that first line "metadata" and then see

**Comment by SethDusek** [comment]
@plikhari Tried, didn't make a difference and it shouldn't anyways because it's just a lua script.

Anyways somebody told me it was the "dock" option that was causing it, but I tried setting it to "normal" and now it dissapears whenever I click show desktop, though I think it might have fixed it

**Comment by plikhari** [comment]
yes - you are correct - change that own_window_type - well you have other options - normal, desktop, dock, panel or override (default: normal)

**Comment by SethDusek** [comment]
When I try desktop or override, it dissapears when I click show desktop. If I select panel, it automatically reserves space at the bottom of my screen, and it resizes all of my windows to be smaller.

Also when I select desktop, there's a gap of 5 pixels in between the left of the screen and the widget, but it's still not positioned properly. Is this a bug?

**Comment by plikhari** [comment]
What Desktop Environment are you using??

**Comment by plikhari** [comment]
and the window manager if any :)

**Comment by SethDusek** [comment]
@plikhari Cinnamon 3.0.7

**Comment by Nooby4Ever** [comment]
try (should work for cinnamon):
```
	own_window = true,
	own_window_type = 'normal',
	own_window_transparent = false,
	own_window_hints = 'undecorated,sticky,below,skip_taskbar,skip_pager',
	own_window_argb_visual = true,
	own_window_argb_value = 192,
```
also remove the `#` in `own_window_colour = '#224466',` it is no longer required in conky >1.10 (same for the colors).  Btw i see some of your colors have less then 6 digits i don't know whether or not conky handles these well.

**Comment by SethDusek** [comment]
@Nooby4Ever Okay, well it works but unpredictably. It often ends up in the right position, but sometimes not? Like it's stuck on the top left. And if I click show desktop it dissapears which is still an issue

**Comment by Nooby4Ever** [comment]
Can you post your full (latest) config file again, i will test it on my system (also running cinnamon).

**Comment by SethDusek** [comment]
@Nooby4Ever Ok, here is the full conkyrc with all of the resources and modules http://i.shibe.ml/QmNjT8PPsc2TikWCMj8BX6YpKuYK1hYmRBLisGahbfD7mB.tar

**Comment by Nooby4Ever** [comment]
It runs fine, didn't change anything. Does not change position, show desktop does not make it dissapear or change position. Might be something on your system?

ps: the lua script/ conky config doesn't do anything (just static) but i assume that is because i don't use `playerctl`

**Comment by SethDusek** [comment]
Where does it appear? Top left or is the position correct

**Comment by Nooby4Ever** [comment]
Top middle, to the right. Correct (considering my screen dimensions + bottom_right + the gap_x and gap_y values).

**Comment by SethDusek** [comment]
Can you try the conky from the ubuntu 16 repos? If you're nit on ubuntu then I can give you the unpacked version when I get home

**Comment by SethDusek** [comment]
@Nooby4Ever can you go into cinnamon-settings and take a screenshot of this page? http://i.shibe.ml/QmP3e9AcX9SV3gRMpoqrhJUyV32a6o9onFqE3fYYcEkLyY.png

I want to find out what your settings are, because I'm pretty sure the "location of newly opened windows" is what is causing the issue, since if I change it from automatic, then it isn't stuck in the top left. However, If I select cursor or manual, conky pops up wherever my cursor is which I dont want and center means conky is stuck in the middle

**Comment by Nooby4Ever** [comment]
Since typing is faster:
```
- click
- off
- off
- off
- off

- centre
- alt
- 24
- on
```

(not yet had the time to test on ubuntu)

**Comment by SethDusek** [comment]
@Nooby4Ever Well now I honestly dont know what to do. It's obviously a cinnamon bug, but it might just be an issue with my settings, but I don't know where to start fixing this

**Comment by SethDusek** [comment]
@Nooby4Ever Fixed. https://github.com/linuxmint/Cinnamon/issues/5566#issuecomment-241812831 Was a configuration issue. Hope this can help other people too

**Comment by Nooby4Ever** [comment]
Thanks for further digging into it, should be added to the wiki. (i might do it later if i have time)

**Comment by SethDusek** [comment]
@Nooby4Ever If you are gonna add it then this is the command "gsettings set org.cinnamon.desktop.wm.preferences disable-workarounds false"

**Comment by Nooby4Ever** [comment]
Thanks!
