### ISSUE TITLE
Unknown setting 'xftfont'

### ISSUE THREAD

**Issue by leongm** [brndnmtthws/conky#229]
Hi,
I upgraded to version 1.10.1-2 and the new syntax for config files is now required. I made the changes and my config file has the lines 
`use_xft = true,`
`xftfont= 'bauhaus'`
but conky complains saying `conky: Unknown setting 'xftfont'`

**Comment by plikhari** [comment]
change that to
``` font = 'bauhaus',```
ensure that each line ends with a comma

**Comment by plikhari** [comment]
Please close this issue if it has solved the issue.
cheers

**Comment by lasers** [comment]
@brndnmtthws General question/support. Please close this.

**Comment by lasers** [comment]
You can read more about it in man page. `$ man conky`
```
       -f | --font= FONT
              Font to use. Only available with build flag BUILD_X11 enabled.
```
```
       font   Font name in X, xfontsel can be used to get a nice font

       use_xft
              Use Xft (anti-aliased font and stuff)
```
