### ISSUE TITLE
man page isn't updated for 1.10

### ISSUE THREAD

**Issue by ngoonee** [brndnmtthws/conky#234]
Probably related to https://github.com/brndnmtthws/conky/issues/197 and https://github.com/brndnmtthws/conky/issues/203

I was looking at the man page, specifically wanting to use the --stdin-config option, when conky gave me the error that the option was unrecognized. Indeed https://github.com/brndnmtthws/conky/wiki/Command-Line-Options doesn't list any such option.

Probably some remnant of an old man page somewhere.

**Comment by Nooby4Ever** [comment]
These options are indeed no longer available, I will update the documentation sometime "soon".

**Comment by lasers** [comment]
The `--stdin-config` option is not in man page. I suppose it is okay to close this now. Thanks.
