### ISSUE TITLE
High cpu usage

### ISSUE THREAD

**Issue by kylon** [brndnmtthws/conky#239]
My current setup: Archlinux with openbox
tested with latest conky from Arch repo and latest compiled from github

when update_interval is < 1.0 there s an high cpu usage
my current value is 0.1, two of my four cores are always under load and the cpu usage of conky is stuck at 20% (htop)

Other apps like GkrellM have a normal cpu usage with the same update interval

**Comment by Nooby4Ever** [comment]
Can you post your conky config so I can verify on my system.  I'm currently on Conky 1.10.0 and I can run a Conky config with `update_interval = 0.05` without unusual performance issues aside from updating so frequently is using some extra resources of course (unfortunately a not easy to share config).

**Comment by kylon** [comment]
here
[conky.conf.txt](https://github.com/brndnmtthws/conky/files/244690/conky.conf.txt)

**Comment by Nooby4Ever** [comment]
I have testen on my desktop and laptop running conky 1.10.0 (+commits till https://github.com/brndnmtthws/conky/commit/03a5cc50470b429c73321463b273a97fe5720a2c).

Both run Arch linux with cinnamon (gnome), in both cases i had no cores under constant load nor any unusual performance issues (also used htop). The load from conky on my laptop was noticeable but this is hardware dependent.

Unfortunately I don't have the time to test with the current build or the 1.10.1 build, so may be some one else can give it a go? (it is possible this is caused by a later commit)
***
Note: you might want to use templateN in your config eg. 
```
conky.config = {
...
color0 = '1793d0',
color1 = 'DDDDDD',
color2 = 'AAAAAA',
color3 = '888888',
template0 = [[${goto 50}${color\1}${top name \2}${alignr}${top cpu \2}%]],
...
}}
```
```
conky.text = [[
${template0 1 2}
${template0 2 3}
${template0 3 4}
${template0 3 5}
]];
```

**Comment by mxmlnkn** [comment]
I tested commit `06f87b9c26cf79244e4cde82738694636a48df0` (+nvidiabar) on my PC. I only have 4 cores, so had to to half the config, also hwmon doesn't work for me and of course the battery status.
```
conky: can't open '/sys/class/hwmon/hwmon2/temp1_input': No such file or directory
please check your device or remove this var from conky
```
htop reports a constant load of 5-6% for conky. My normal conky which ran concurrently reported "only" 1.5% load (and Xorg 5%).
When using `update_interval = 0.01` htop reports Xorg at ~30% and also conky at ~30%. Conky itself reports Xorg to be ~9% and conky to be ~7% with an overall CPU load of ~20%. `top` is roughly the same as `htop`, therefore differs from conky. I think conky divides the cpu usage by the core count, remember the sum of all top processes could go up to 400% for my 4-core setup.

I'm using an i3-3220 with 3.30GHz

**Comment by plikhari** [comment]
I understand what @kylon is saying. 
But if you have same items displayed - the CPU usage is very similar.

Another point to note is in `gkrellm` the update interval is fixed - 1 second - so all the graphics is updated per second while the krell and LED updates freakout depending on the how many updates per second you use - while the graphs remain constant. I recall 6 - 7 years back the overall update interval was minimum 5 seconds. So there is perhaps a simulation involved to get a sense of faster update IMO.

Yeah I installed `gkrellm` just to test it out.
I have 4 core system and the values range from 3 to 10 percent.
Personally am quite happy with an update interval of 5 seconds - less distracting ;-)

**Comment by kylon** [comment]
My only displayed item is 1 conky with that config, i prefer a very minimal setup and i like a real time update_interval :P 

seem i'm not able to compile old conky without donwgrading packages or updating code. Can you please share an old bin?


templates are awesome, thanks for the tip

**Comment by Nooby4Ever** [comment]
I doubt that would work since tolua++ (and possibly other libs) have been updated since and it was compiled against the old version, if you still want to try give me your email (or send me a mail, see my profile, if you want to keep your email private). I use build flags like nvidia, xshape, lua, ...
If you know git you can clone the repository, go to a specific commit and build from source.

**Comment by kylon** [comment]
same problem with 1.10-pre

**Comment by lasers** [comment]
2 years 4 months passed. Can you determine if you're still having this problem today on `1.10.9` or preferably `1.10.10_pre` (git)? The older versions are not trustworthy due to too many changes that can be hard to track. Thank you.

**Comment by kylon** [comment]
I will try asap.
The arch package is outdated, i ll compile a new one from git

Thanks

**Comment by su8** [comment]
Can you also compile it with this patch - https://github.com/brndnmtthws/conky/issues/189#issuecomment-411828451

To compile against the master branch:

```bash
git clone https://github.com/brndnmtthws/conky
cd conky
mkdir -p build
cd build
cmake ..
make -j4 # 4 cores to run in parallel
```

**Comment by X0rg** [comment]
>  The arch package is outdated, i ll compile a new one from git

@kylon: You can try [conky-git](https://aur.archlinux.org/packages/conky-git/) package from AUR.  It works like a charm for me. :wink:

**Comment by kylon** [comment]
this is the first time i try 0.1 since when i opened this issue, latest stable on arch (1.10.8) partially fixed the issue.
conky is always on top, 20+% but my cores seem fine.

anyway...

update interval 0.1, git build (master 6c590590a)

with patch (#189 (comment))
lower cpu usage, 12%, the cpu graph is a bit slower even if my value is 0.1 (i think this is why the cpu % is lower)

without patch
same cpu usage as old conky (1.10.8), 20+%, the cpu graph is really fast

+1 for the patched one

**Comment by su8** [comment]
@lasers Can you have a look good sir ?

**Comment by plikhari** [comment]
I made a super smooth scroller with an update_interval of 0.04 to 0.07 - YES ;-)

Please see this image - [conkywx news scroller](https://image.ibb.co/k1DLmU/Screenshot_2018_08_14_16_03_32.png) - scrolling 182 items of news - cpu about 10% to 12 % - it has remained the same with 1.10.8 as well - this test was with 1.11.0_pre.

I frankly have not seen any high cpu usage ...

**Comment by lasers** [comment]
@kylon Is it still a same config after few years?

Out of us all, you (and some others) are in best position to troubleshoot this issue.

Try `ps -C conky -o %cpu,%mem,cmd` from time to time to see how much it roughly used up.

Install `gnome-system-monitor` and/or `ksysguard`. See if you have this pattern too. https://github.com/brndnmtthws/conky/issues/341.

Here's my `ps`, `gnome-system-monitor`, `ksysguard`, etc.

`mate-system-monitor` seems fairly old / limited.

----

My `ps`...

After running your config for an hour, I scored...
```
%CPU %MEM CMD
 5.2  0.2 conky -c /home/chris/conky/kylon-modified.conf
```
Modified to use 12 cores. Run it again every hour or so to see if it builds up.

----

My `gnome-system-monitor`...

![2018-08-14-232251_729x513_scrot](https://user-images.githubusercontent.com/852504/44131621-f4aa0062-a019-11e8-97b4-957f383f9a86.png)

----

My `ksysguard`...

![2018-08-14-232629_759x553_scrot](https://user-images.githubusercontent.com/852504/44131655-2df459c6-a01a-11e8-8ec1-109d815d0ba0.png)
![2018-08-14-232708_897x1015_scrot](https://user-images.githubusercontent.com/852504/44131657-2f874c6c-a01a-11e8-9132-473e0d945fd3.png)

Finally... If you can, try this on other machines too... to rule out `conky` (current-git only, please), `your 8-core hardware`, etc. Do you still have this behavior with default conky configuration too?

If not, then it might be your config. Try removing some variables too to rule out `battery` variables, to rule out `cpu` variables, etc... to see if that change anything.

**Comment by kylon** [comment]
@lasers forgot about it
here is my current config (12%)

[conky.conf.txt](https://github.com/brndnmtthws/conky/files/2290066/conky.conf.txt)

everything else is the same, arch + openbox, no fancy stuff

latest master.

i did some tests with my old config, i removed all the bars, temps, freqs etc.. and the cpu usage was the same, 5-7%

but there seem to be a bug? if i remove the last cpu bar. (cpu usage is 14%, and there's a constant redraw)
[conkybug?.conf.txt](https://github.com/brndnmtthws/conky/files/2290076/conkybug.conf.txt)

is it supposed to happen? or my old config is malformed(?)

i don't know about #341 , i always shutdown my pc when i'm done


the default config is set to 1.0 (3%), if i set it to 0.1 it flashes and the cpu usage is 10-11%

considering that the config above has the same behaviour, could it be a problem in how conky is dranw?

sadly i don't have other machines
