### ISSUE TITLE
can't apply position on all lines of output from execi command

### ISSUE THREAD

**Issue by stardiviner** [brndnmtthws/conky#240]
I use `${offset 1000}${execi cal}` to specify position for the whole output of command `cal`. But conky only can specify position for the first line.
Can conky support to specify position for the whole output from `${execi command}` ?

**Comment by plikhari** [comment]
Try this - it gets you an aligned calender

`
${font  Mono:size=9}${execpi 6000 StarDiviner=`date +%-d`; cal | sed 's/\r//g;s/^/ /g;1d;s/^/\$\{goto 20\}/;s/\<'"$StarDiviner"'\>/${color1}&${color0}/'}
`

You see the item ` \$\{goto 20\}` - you can use voffset or offset in the similar manner 
I use execpi 6000 - it is a static calender and will remain the same for next how many hours - you can have a shorter value and update every hour.

**Comment by stardiviner** [comment]
This is great. Thanks.
But I still hope conky can support this feature in the feature.

**Comment by lasers** [comment]
Duplicate https://github.com/brndnmtthws/conky/issues/32. Closing.
