### ISSUE TITLE
downspeedgraph autoranges

### ISSUE THREAD

**Issue by bswarm9568** [brndnmtthws/conky#242]
My internet connection is 100 Mbps. With conky downspeedgraph when there is heavy traffic, it seems like it autoranges to fill the graph. When there is little to no traffic, even minor traffic fills the graph. Is there a way to stop this and have the graph static at 0 bps on the bottom to 100 Mbps at the top?

**Comment by Nooby4Ever** [comment]
Do you use the -l flag/switch? (logarithmic sale; in case you do remove it)

**Comment by bswarm9568** [comment]
No, my conkyrc only has "downspeedgraph eth0 22"

**Comment by mxmlnkn** [comment]
Use the scale-option, see here  http://conky.sourceforge.net/variables.html
Unfortunately this means you will also have to specify both colors before. 
The scale itself seems to be in kB. So in order to cap at 100Mbps which is 12.5 MBps which is 12500kB/s you would have to use:

    ${downspeedgraph eth0 50,120 FFFFFF FFFFFF 12500}

**Comment by bswarm9568** [comment]
Thank you, that works. I changed it to `downspeedgraph eth0 22,230 20ff22 20ff22 12500` to keep my colors consistent with the rest of my theme.
