### ISSUE TITLE
How to load Lua script in new conky config format?

### ISSUE THREAD

**Issue by stardiviner** [brndnmtthws/conky#243]
Now, conky start to use Lua syntax format config from a specific version.
I wander how to load Lua script now?
Before new version, the old format is like this:
```lua
lua_load ~/.config/conky/plugins/Lua/clock_rings.lua
lua_draw_hook clock_rings
TEXT
...
```

My conky version is: `1.10.1_pre`

**Comment by Nooby4Ever** [comment]
It didn't change that much:

> conky.config = {
> ... -- Rest of your config
> 
> lua_load = '~/.config/conky/plugins/Lua/clock_rings.lua',
> lua_draw_hook_pre = 'clock_rings',
> };

(although i must admit the man page does not mention the use of '=' nor the place)

**Comment by stardiviner** [comment]
@Nooby4Ever Thanks.
