### ISSUE TITLE
tcp_portmon don't work inconky 1.10

### ISSUE THREAD

**Issue by chepioq** [brndnmtthws/conky#245]
I test tcp_portmon variable and it don't work with conky 1.10 (that work with conky 1.9)
My conky : 
`conky.config = {
background = false,
update_interval = 3600,
double_buffer = true,
no_buffers = true,
imlib_cache_size = 10,
alignment = 'top_left',
minimum_width = 300,
minimum_height = 225,
gap_x = 330,
gap_y = 250,
own_window = true,
own_window_type = 'normal',
own_window_transparent = true,
own_window_argb_visual = true,
own_window_hints = 'undecorated,skip_taskbar,skip_pager,below',
double_buffer = true,
draw_shades = false,
draw_outline = false,
draw_borders = true,
default_outline_color = '000000',
draw_graph_borders = false,
use_xft = true,
xftalpha = 0.8,
text_buffer_size = 256,
override_utf8_locale = true,
imlib_cache_size = 0,
}

conky.text = [[
${tcp_portmon 1 65535 rport  0}
${tcp_portmon 1 65535 rip  0}
]]
`

In console I have: 
[dominique@host-192-168-1-2 conky-sat]$ conky -c conky-test
conky: desktop window (2400019) is subwindow of root window (4a7)
conky: window type - normal
conky: drawing to created window (0x4e00002)
conky: drawing to double buffer
conky: unknown variable '$tcp_portmon'
conky: unknown variable '$tcp_portmon'

With conky 1.9, that work and display the right IP.

**Comment by Nooby4Ever** [comment]
I have tested (${tcp_portmon 1 65535 rport 0}, ${tcp_portmon 1 65535 rip 0}, ${tcp_portmon 1 65535 count}) on my system and they seem to work but I must note i'm not running the current master but a few months older version (not that it should matter). I don't see anything wrong with your config either.

**Comment by plikhari** [comment]
Confirming  - tested `tcp_portmon` in the current build and is working fine.

**Comment by marcpayne** [comment]
Hello @chepioq, what OS are you running in this case? Linux, BSD, other?

Taking a quick look through the code, I see that `BUILD_PORT_MONITORS` needs to be enabled in order for `tcp_portmon` to be available. This build option is on by default only for Linux. If you're running a BSD or something, I don't know if `tcp_portmon` will work since I haven't looked at the code in detail. But it is worth setting `BUILD_PORT_MONITORS=ON` if you compile from source.

It's super early for me right now, I haven't had enough coffee, and I need to go to work, so this is all I can dig up for now. :)

**Comment by chepioq** [comment]
I use Fedora 24, I install this rpm (x86_64) : http://koji.fedoraproject.org/koji/buildinfo?buildID=717257

And in the spec.file I can see : 
...................................................................................
%build
%cmake \
                            -DMAINTAINER_MODE=ON \
                            -DBUILD_BUILTIN_CONFIG=OFF \
                            -DBUILD_PORT_MONITORS=OFF \
    %{?with_audacious:      -DBUILD_AUDACIOUS=ON} \
    %{?with_curl:           -DBUILD_CURL=ON} \
..................................................................................

I think the fedora maintainer build conky 1.10 with port_monitor=off.

**Comment by chepioq** [comment]
Ok I attempt rebuild the rpm with -DBUILD_PORT_MONITORS=ON \  That work but when I want install this rpm I have this error : 
Erreur : nothing provides libtcp-portmon.so()(64bit) needed by conky-1.10.1-5.20160110gitb38ab1.fc25.x86_64

But I think it's not issue for you, but for the fedora maintainer.
I open a bug on fedora bugzilla.

Thanks for your comment.
I close this issue.
