### ISSUE TITLE
lua_hook call not occurring in order

### ISSUE THREAD

**Issue by towheed** [brndnmtthws/conky#255]
lua_draw_hook_pre is called before lua_startup_hook.  This causes vars initialized in the startup hook to error out if referenced in the pre_draw hook.

Startup should be called before any of the other hooks.
`conky script.....`
.
`lua_load test.lua`
`lua_startup_hook init`
`lua_draw_hook_pre predraw`
`lua_draw_hook_post postdraw`
`lua_shutdown_hook cleanup`
`.`
`.`
`lua script.....`
`function conky_init ()`
`  print ("Startup")`
`end`
` `
`function conky_predraw ()`
`  print ("Predraw")`
`end`
` `
`function conky_postdraw ()`
`  print ("Postdraw")`
`end`
` `
`function conky_ cleanup()`
`  print ("Cleanup")`
`end`

This gives:
`Predraw`
`Postdraw`
`Startup`
`Cleanup`

The startup hook should be called before the pre and post hooks so any globals declared in startup is properly seen in pre and post.  As it is, this throws an error on the first iteration of the conky script.
I think the order should be startup, pre, post and shutdown.

A workaround is is to wait for 2 iterations of the conky script before referencing vars set in startup.
`function conky_init ()`
`  print ("Startup")`
`  x=10`
`end`
`function conky_predraw ()`
`  print ("Predraw",x)`
`end`
this gives attempt to index global 'x' (a nil value).

But 
`function conky_predraw ()`
`  if tonumber(conky_parse('${updates}'))>1 then`
`      print ("Predraw",x)`
`  end`
`end`
Give the value of x.

A rather unnecessary call to $update on each iteration of the conky script.

A simple patch for this?
Thanks.

**Comment by Nooby4Ever** [comment]
Tests were done on Conky 1.10.2 (see configs below);
With `out_to_x = false`:
```
Startup Hook
PreDraw Hook
Avg CPU 7.
postDraw Hook
PreDraw Hook
Avg CPU 8.
postDraw Hook
PreDraw Hook
Avg CPU 6.
postDraw Hook
Shutdown Hook
```

With `--out_to_x = false,`:
```
conky: desktop window (1200026) is subwindow of root window (c4)
conky: drawing to desktop window
PreDraw Hook
postDraw Hook
Startup Hook
PreDraw Hook
Avg CPU 7.
postDraw Hook
Shutdown Hook
```
You can see 2 out of 3 updates are "lost" when using X. Also 2 illegal calls to `conky_preDraw` and `conky_postDraw` are made. You're right this is not correct. There are also other things than pure updates that can trigger calls to `pre` and `post` hooks, every time the window is updated eg. dragging a conky window. (although i haven't tested this on 1.10 yet). (see [Lua tips and tricks](wiki/Lua-tips-and-tricks)). There was also a discussion over this matter on [Crunchbang.org](http://crunchbang.org/forums/viewtopic.php?pid=436943#p436943), this was for conky 1.9 though.

As a quick fix i suggest using:
```
function conky_drawPost()
    if conky_window == nil or conky_window.height == 0 then return end

    print("PostDraw Hook")
end
```
The result:
```
conky: desktop window (1200026) is subwindow of root window (c4)
conky: drawing to desktop window
Startup Hook
PreDraw Hook
Avg CPU 8.
postDraw Hook
Shutdown Hook
```

I knew this bug for quiet a while, should put this on the wiki some day. Oh and you still "lose" 2 updates of cource. But technically this should be fixed some day or the manual has to be updated to reflect the current status (i suggest you leave this issue open).

****
a.conky config
```
conky.config = {
    --out_to_x = false,
    out_to_console = true,

    update_interval = 1,
    total_run_times = 3,

    lua_load = '~/test.lua',
    lua_draw_hook_pre = 'preDraw',
    lua_draw_hook_post = 'postDraw',
    lua_startup_hook = 'startup',
    lua_shutdown_hook = 'shutdown',
};


conky.text = [[
Avg CPU ${cpu cpu0}.
]];
```

test.lua
```
function conky_startup()
	print("Startup Hook")
end

function conky_shutdown()
	print("Shutdown Hook")
end

function conky_preDraw()
	print("PreDraw Hook")
end

function conky_postDraw()
	print("postDraw Hook")
end
```

**Comment by towheed** [comment]
This is from conky 1.9.0 from the Debian Jessie repos.  The test for $updates>1 does the trick.
This project needs serious clarifications on it's docs.

I just started using conky, probably 2 months or so.  The good thing is I've learned quite a bit of Lua because of conky, something I've put off for a few years now.

If here's enough interest, I'd probably, just probably considering doing a guide similar to my 'The Definitive Guide to Theming GRUB 2, which can be downloaded from https://drive.google.com/file/d/0B4ryPDYMqL_MNDgzNjYzMWEtMTIxZC00MzRkLTg1NWUtMmQzNTE0NTBjNDQ5/view?usp=sharing

So now back to what I was doing.  All of the Lua scripts I've seen places the cairo_create function in the pre_hook call.  The cairo_t struct is destroyed at the end of the script and recrearted in the next iteration.

I don't see the need to create and destroy the cairo_t struct during each iterations.

What I do is to call cairo_create in the startup_hook call and destroy the struct during the shutdown_hook call.

in conky config:
`lua_load ~/myconkytheme/test.lua`
`lua_draw_hook_pre resize`
`lua_startup_hook init`
`lua_shutdown_hook cleanup`

test.lua:
`function conky_init ()`
`	print ("Initializing")`
`	local border_size=(conky_window.border_width+conky_window.border_inner_margin+conky_window.border_outer_margin)*2`
`	wx=conky_window.text_width+border_size`
`	wy=conky_window.text_height+border_size`
	
`	cr=cairo_create(cairo_xlib_surface_create(conky_window.display,
		conky_window.drawable,
		conky_window.visual,
		wx,
		wy))`	
`end`

`function conky_cleanup ()`
`	print ("Cleaning up")`
`	cairo_destroy(cr)`
`	cr,wx,wy=nil,nil,nil`
`end`
	
`function conky_resize ()`
`	print ("Resizing window")`
`	if tonumber(conky_parse('${updates}'))>1 then`
`		if conky_window.width~=wx or conky_window.height~=wy then`
`			conky_cleanup ()`
`			conky_init ()`
`		end`
`	end`
`end`

Without the pre_hook, resizing the window loses it's contents.  I'm yet to check what is actually happening with the cairo_status call.  As you mentioned, pre_hook is also called when the window resizes, so creating and destroying the cairo_t struct within the function called by pre_hook causes window resizing to work as expected.

The above workaround works nicely for me at this time but, it'd be nicer to have the hooks occur in sequence.

BTW:  How do you create code blocks.  If I place the backticks at the start and end, the newlines within the body gets screwed up like this:
`function conky_cleanup ()
	print ("Cleaning up")
	cairo_destroy(cr)
	cr,wx,wy=nil,nil,nil
end`
[code]
function conky_cleanup ()
	print ("Cleaning up")
	cairo_destroy(cr)
	cr,wx,wy=nil,nil,nil
end[/code]
Nope....

**Comment by Nooby4Ever** [comment]
There is already a Lua guide available here [Conky Lua Turorial](https://github.com/brndnmtthws/conky/wiki). It is for 1.10 but Lua scripts will work on both 1.9 and 1.10. (the tutorial is in rather rough shape, so if you want to improve it you're more than welcome. Especially punctuation and structure). You can also add your own tutorial to the wiki or add small tricks and hints to [Tips and tricks](https://github.com/brndnmtthws/conky/wiki/Lua-tips-and-tricks)

Your approach for the `cairo_create` seems good, i can not see any disadvantages over the "usual" method. I might give it a try myself when i, someday, go back into making configs (i'm interested if there would be a noticeable performance gain).

You can write codeblocks like this:
\`\`\`
your code
here 
\`\`\`

**Comment by towheed** [comment]
Thanks for the code block tip.

How would you go about benchmarking conky's lua script?  os_clock does not do much a job and I saw something on the Lua site commenting about benchmarking Lua scripts not being too reliable.

**Comment by Nooby4Ever** [comment]
Good question, haven't any experience myself to be honest. Although hard numbers would be nice, personally my approach would be more practical (and far less accurate). Use a, non trivial, drawing script with both approaches. Set the update interval of conky very low, eg. 0.001 and see if you notice a difference in CPU usage. Not scientific by any means but should give a real world indication. (and to be honest if the gain is not significant anyway i wouldn't care too much, whether conky uses 1.1 or 0.97 CPU % is nice on paper but neglectable in practice)
