### ISSUE TITLE
Can't set more than one font with transparency

### ISSUE THREAD

**Issue by MichaelZer0** [brndnmtthws/conky#26]
It would be great if we could use transparency for each font independently, something like this:

${font Bitstream Vera Sans Mono:size=40:xftalpha=0.3}${time %M}
${font Droid Sans Mono:size=10:xftalpha=0.5}${time %S}

**Comment by mswanson-me** [comment]
Is this issue still outstanding in the current version of Conky? If so, please update this issue. Otherwise, the issue will be closed in 2 weeks.
