### ISSUE TITLE
How I can run a script without your childs finish or even the main pid exits?

### ISSUE THREAD

**Issue by ryukinix** [brndnmtthws/conky#262]
I was writing a script for parsing feed RSS and put notifications using libnotify using python, the original thread is [here](https://www.reddit.com/r/Python/comments/4jyfma/multiprocessing_problem_how_i_can_run_a_function/), whose I posted in r/Python. In the start were a Python problem, but now I think can be my script on conky. The all source is [here](https://gist.github.com/ryukinix/4bdd0eafb26c3073d0b5111c42ea8ec5).

My program puts the output of titles on the main program and the child handle the notifications & url_clicking.  However, until all the notifications are closed and the child exists properly, my conky doesn't is updated!

A useful comment on reddit thread said that for me:

> Well, I'm not sure, but maybe Conky waits for the process group to finish or the child process remains attached to some virtual terminal and Conky knows it. You can try calling `os.setsid()` (with no parameters) after forking and before calling notify().

This is really sad. Somebody can help me with this?

[StackOverflow thread](http://stackoverflow.com/questions/37308905/how-i-can-run-a-function-in-parallel-and-after-the-main-program-exits-he-still-c)

**Comment by Nooby4Ever** [comment]
I tried your config on my systems (Arch and Ubuntu) but i could not get it to generate a notification. Therefore I can not trigger the issue (probably something on my end). I tried with conky 1.10.2, the text displayed as expected just no notifications at all. I don't know the inner workings of `texti` ect so I can not comment on whether or not conky waits for the process group to finish.

ps: i got an error every time the python script updated: 
```
Traceback (most recent call last):
  File "/home/nooby4ever/Desktop/rss_parser.py", line 212, in <module>
    old_cache = get_cache(keyname)
  File "/home/nooby4ever/Desktop/rss_parser.py", line 153, in get_cache
    return get_cache_file()[key]
KeyError: '.httphackernewsdemosmonkeylearncomfeedxml.cache'
```

**Comment by ryukinix** [comment]
Sorry for this. I'll fixed locally, I will push the new changes in soon. Thanks for the attention.

**Comment by ryukinix** [comment]
Try again, please!

**Comment by ryukinix** [comment]
Ps.: see whose just running the python script at terminal works fine, the main program prints to stdout and push notifications

**Comment by Nooby4Ever** [comment]
Indeed the script works now (on my system). And unfortunately i can confirm the issue still exist in conky 1.10.2. As long as notifications are not cleared/opened conky won't update.

I'm afraid conky must be patched to allow this behaviour.

**Comment by ryukinix** [comment]
Yes, the notifications has a .cache file whose handle only the new rss in the long of time. I'm using to have a low-weight rss crawling instead user a full-featured rss handler (whose I thinks is a confusion). 

I'll really wants this works someday, because actually don't works here.

@Nooby4Ever BTW, funny name. You is the first person whose really understand which was my problem, but you has that nickname. NICE! LOL. I don't know how calling the other guies...

**Comment by Nooby4Ever** [comment]
As a work around you can try to call your python script from a lua script. For example, you can use in the text section a python script which only displays the rss feed text and another python script which is called by lua (which is called by conky) to do the notifications. Because, i'm not entirely sure (didn't look at the code), but i don't think conky waits for the return of a lua call (just fire and forget). At least if you use the `_pre` or `_post` hooks. It might be worth a shot if your really want this feature.

And you explained it pretty well in your openings post, when i ran the script the issue was very obvious since the text didn't show up until i cleared the notifications.

**Comment by ryukinix** [comment]
I think this issue is solved in the way it's documented here. Thanks
