### ISSUE TITLE
Conky 1.10.2  not work with VirtualBox

### ISSUE THREAD

**Issue by holmeslinux** [brndnmtthws/conky#282]
hi all, good morning!
after upgrading to Conky 1.10.2 it does not work anymore with the VirtualBox.
with 1.10.1 version worked perfectly with VirtualBox.
my Conky is: https://github.com/holmeslinux/Manjaro-JWM/blob/master/jwm-overlay/etc/skel/.conkyrc.

what can it be?

vlw fwi, Holmes :)

**Comment by plikhari** [comment]
Well - I have tested conky using virtualbox - ubuntu 15.10 and conky 1.10.2 - vincent PPA - aaaannnnnd - it works :)

I have noted the use of $color - while you have only defined color2 and a default_color.

So what messages do you get in the terminal window. ???

**Comment by holmeslinux** [comment]
thanks @plikhari 
here does not work in vbox using Manjaro JWM 16.06.1.
but, it works in live and installed on a real machine.
the problem is in the vbox.
the previous version worked.
open a topic in Manjaro Forum to discuss this issue, see in

[](https://forum.manjaro.org/t/troubleshooting-conky-for-jwm-edition/3713)

i will review the code and remove the unnecessary (for example $color). 

vlw fwi, Holmes :)

**Comment by plikhari** [comment]
@holmeslinux - you appear to have solved the issue (from the link you provided) - can you share what happened and also close this issue

Thanks :-)

**Comment by lasers** [comment]
![2018-08-03-114553](https://user-images.githubusercontent.com/852504/43655047-1303f910-9713-11e8-903b-ec005366f8a7.png)

`[image]`

![lodupa7f537](https://user-images.githubusercontent.com/852504/43655074-32dbd0b4-9713-11e8-9134-e67467f600b6.png)

Sweet. You got this in the bag. :sunglasses: :sunglasses: :sunglasses:
