### ISSUE TITLE
Alignment abbreviations not working

### ISSUE THREAD

**Issue by mxmlnkn** [brndnmtthws/conky#284]
The documentation for `alignment` reads:
> (also can be abreviated as tl, tr, tm, bl, br, bm, ml, mm, mr).
When I try this:

    conky.config = {
        alignment = 'tr',

I get

    conky: Invalid value 'tr' for setting 'alignment'. Valid values are: 'top_left', 'top_right', 'top_middle', 'bottom_left', 'bottom_right', 'bottom_middle', 'middle_left', 'middle_middle', 'middle_right', 'none'.

or

    conky: Invalid value 'bl' for setting 'alignment'. Valid values are: 'top_left', 'top_right', 'top_middle', 'bottom_left', 'bottom_right', 'bottom_middle', 'middle_left', 'middle_middle', 'middle_right', 'none'.

**Comment by chepioq** [comment]
I confirm this issue with conky -v = conky 1.10.2

conky: Invalid value 'tl' for setting 'alignment'. Valid values are: 'top_left', 'top_right', 'top_middle', 'bottom_left', 'bottom_right', 'bottom_middle', 'middle_left', 'middle_middle', 'middle_right', 'none'.

That work with 
alignment = 'top_left',

**Comment by chepioq** [comment]
I look for the code, and I think issue is in /src/x11.cc (line 238 to 250)

template<>
conky::lua_traits<alignment>::Map conky::lua_traits<alignment>::map = {
	{ "top_left",      TOP_LEFT },
	{ "top_right",     TOP_RIGHT },
	{ "top_middle",    TOP_MIDDLE },
	{ "bottom_left",   BOTTOM_LEFT },
	{ "bottom_right",  BOTTOM_RIGHT },
	{ "bottom_middle", BOTTOM_MIDDLE },
	{ "middle_left",   MIDDLE_LEFT },
	{ "middle_middle", MIDDLE_MIDDLE },
	{ "middle_right",  MIDDLE_RIGHT },
	{ "none",          NONE }

May be it should be :

template<>
conky::lua_traits<alignment>::Map conky::lua_traits<alignment>::map = {
	{ "top_left", "tl" ,    TOP_LEFT },
	{ "top_right", "tr",    TOP_RIGHT },
	{ "top_middle","tm",    TOP_MIDDLE },
	{ "bottom_left","bl",   BOTTOM_LEFT },
	{ "bottom_right","br",  BOTTOM_RIGHT },
	{ "bottom_middle","bm", BOTTOM_MIDDLE },
	{ "middle_left","ml",   MIDDLE_LEFT },
	{ "middle_middle","mm", MIDDLE_MIDDLE },
	{ "middle_right","mr",  MIDDLE_RIGHT },
	{ "none",          NONE }


But I am not a programmer and I don't know the exact syntax.

**Comment by chepioq** [comment]
That don't work with the modif, I have error when I rebuild my rpm...
But with that, that work:

template<>
conky::lua_traits<alignment>::Map conky::lua_traits<alignment>::map = {
	{ "top_left",      TOP_LEFT },
	{ "top_right",     TOP_RIGHT },
	{ "top_middle",    TOP_MIDDLE },
	{ "bottom_left",   BOTTOM_LEFT },
	{ "bottom_right",  BOTTOM_RIGHT },
	{ "bottom_middle", BOTTOM_MIDDLE },
	{ "middle_left",   MIDDLE_LEFT },
	{ "middle_middle", MIDDLE_MIDDLE },
	{ "middle_right",  MIDDLE_RIGHT },
	{ "tl",            TOP_LEFT },
	{ "tr",            TOP_RIGHT },
	{ "tm",            TOP_MIDDLE },
	{ "bl",            BOTTOM_LEFT },
	{ "br",            BOTTOM_RIGHT },
	{ "bm",            BOTTOM_MIDDLE },
	{ "ml",            MIDDLE_LEFT },
	{ "mm",            MIDDLE_MIDDLE },
	{ "mr",            MIDDLE_RIGHT },        
	{ "none",          NONE }
};

Alignment abbreviations work fine.

If a dev can add that to the code, thank you.

**Comment by chepioq** [comment]
The conky docs for alignment say that abreviations can be used, however they are not currently recognised by X11.cc.
This fixes this issue by adding the listed abbreviations to the alignment arguments map."
