### ISSUE TITLE
conky-1.10.2-1 segmentation faults on single-core machines still a problem...

### ISSUE THREAD

**Issue by thereallightbeam** [brndnmtthws/conky#285]
I think this issue (#257/#258) should be revisited because users, including myself, are still experiencing segmentation faults due to this issue. Downgrading to conky-1.10.1-2 fixes the issue, and with conky-1.10.2-1 removing the CPU output settings ($cpu, $cpubar) from .conkyrc file allows Conky to work. Neither solution is ideal. 

In the following discussion, you will notice that some users have reported the issue when using Virtualbox, however the issue also occurs on my single-core AMD machine with integrated graphics.

https://forum.manjaro.org/t/troubleshooting-conky-for-jwm-edition/3713/36

Thanks!

**Comment by skwerlman** [comment]
if i'm not mistaken, this is fixed by e056dca8f16696387b1710c4201eb65b252774b8
