### ISSUE TITLE
CPU frequency when number of cores is greater than 9

### ISSUE THREAD

**Issue by gitdark** [brndnmtthws/conky#288]
When number of cores is greater than 9, "freq n" returns frequency of first core for any core number greater than 9.

Attached [patch](https://github.com/brndnmtthws/conky/files/323384/conky_freq_patch.txt) fixes the problem for systems with up to 99 cores.

**Comment by brndnmtthws** [comment]
Could you please submit a PR for this change?

**Comment by lasers** [comment]
Solved by #459.
