### ISSUE TITLE
to_bytes doesn't convert decimal sizes

### ISSUE THREAD

**Issue by mkoskar** [brndnmtthws/conky#302]
E.g.,

```
${to_bytes 1M}
${to_bytes 1.1M}
```

outputs

```
1048576                                 
1.1M
```

Testing with version: `conky 1.10.1_pre`

**Comment by plikhari** [comment]
Works fine on the current version - 1.10.4

**Comment by mkoskar** [comment]
Yes indeed! I was running older packaged version under impression it's the latest one.
Should have double-checked it, sorry for the noise ;).

Closing.
