### ISSUE TITLE
No cast snafu

### ISSUE THREAD

**Issue by ghost** [brndnmtthws/conky#303]
Hello,

Why do you use the ctype header functions with arguments of **signed** int ?

https://www.securecoding.cert.org/confluence/display/c/STR37-C.+Arguments+to+character-handling+functions+must+be+representable+as+an+unsigned+char

**Comment by su8** [comment]
Thank you for reporting, it's fixed in the following commit - https://github.com/brndnmtthws/conky/commit/7bca0ca8819f03883affa5fba9e8506d8c2c5f29
