### ISSUE TITLE
High bars in cpugraph with latest conky

### ISSUE THREAD

**Issue by tsujan** [brndnmtthws/conky#307]
With the _latest_ Conky from GitHub, `cpugraph` sometimes creates very high bars. This happens very randomly and not frequently. A screenshot:

![cpugraph](https://cloud.githubusercontent.com/assets/981076/17644868/c224cc78-61a8-11e6-8dc9-0147a84505ec.png)

It never happened in Conky<=1.10.1 and started with 1.10.2.

OS: Latest Manjaro Testing and Debian Testing
Graphic card: 00:02.0 VGA compatible controller: Intel Corporation 4th Gen Core Processor Integrated Graphics Controller (rev 06)

**Comment by plikhari** [comment]
Please show us your conky config file - thanks.

**Comment by tsujan** [comment]
Here you are: https://dl.dropboxusercontent.com/u/7793460/conkyrc.gz

Since v1.10.2, I upgraded Conky several times but the issue persisted. My only option was to downgrade to v1.10.1 again and again.

**Comment by plikhari** [comment]
Well - I am using the latest commit here at git-hub and I do not have any such issue.
We will make one change at a time and see if anything happens and then go to the next - step by step.

1. You do not have **text_buffer_size** - add this `text_buffer_size = 512,` - default is 256 bytes (also the minimum) - and as the value is in bytes - do not stinge on this value. Chances are that this should sort the issue. The wiki does say that increasing this value will drastically reduce performance - well - too less of this value will also not show you correct behaviour - find that balance.

2. Change the `draw_graph_borders = true,` to `draw_graph_borders = false,`

3. Change **cpuraph** to something like this `${cpugraph cpu1 24,86  00fff3 ff0029 scale -t }` - the graph will go from cyan to red depending on the values.
From the conky wiki on cpugraph:
`CPU usage graph, with optional colours in hex, minus the #. See $cpu for more info on SMP. Uses a logarithmic scale (to see small numbers) when you use the -l switch. Takes the switch '-t' to use a temperature gradient, which makes the gradient values change depending on the amplitude of a particular graph value (try it and see)`

Let us know when conky stops misbehaving :-)

**Comment by tsujan** [comment]
> Well - I am using the latest commit here at git-hub and I do not have any such issue.

As I said above, it happens very randomly and infrequently.

> You do not have text_buffer_size - add this text_buffer_size = 512...

OK, I'll try it. Thank you!

I'm afraid (2) and (3) are just about changing some *valid* settings that should work OK.

I have no doubt that some change in v1.10.2 caused this. Since the bug can't be reproduced consistently, comparing v1.10.2 with v1.10.1 may be the best way of finding the cause.

**Comment by tsujan** [comment]
I reversed the commit https://github.com/brndnmtthws/conky/commit/98c4100b66d441c9e96a3d7adfd04e4c5501253c the day I opened this issue and the problem in question has vanished totally without any side-effect.

I didn't investigate further but, before reversing that commit, the problem happened 4-5 times a week.

**Comment by plikhari** [comment]
OK that is very interesting - perhaps our man @marius   can have a look at this :-)

**Comment by tsujan** [comment]
@plikhari Thanks!

**Comment by bunder2015** [comment]
I have four 1.10.4 installs, and this happens on one of them quite frequently.

![](http://i.imgur.com/QPxtsmG.png)
[conkyrc.txt](https://github.com/brndnmtthws/conky/files/771508/conkyrc.txt)

**Comment by tsujan** [comment]
Several months ago I reversed https://github.com/brndnmtthws/conky/commit/98c4100b66d441c9e96a3d7adfd04e4c5501253c and since then, I haven't seen a single instance of high bars, neither on Debian nor on Manjaro, neither with a relatively new laptop nor with an old desktop computer. That commit is definitely the cause.

**Comment by bunder2015** [comment]
Will test and report back in a few days.

[conky-1.10.4-fix-high-cpu-bars.patch.txt](https://github.com/brndnmtthws/conky/files/771725/conky-1.10.4-fix-high-cpu-bars.patch.txt)

**Comment by bunder2015** [comment]
Doesn't seem to fix it for me, I still get them on occasion, but not as often as before I patched the change out.

**Comment by kira78** [comment]
I've been getting the same cpu graph issues on my systems for a while. When I switched to a new computer and after adding a scaling of 0.9 to all of the cpu graphs I didn't get it for a while, but today was getting it constantly while ripping a new CD (which had one core around 100% iowait utilization). I have tracked the problem down to around line 925 in src/linux.cc, to this statement in `update_stat`:
```c
		cpu[idx].cpu_val[0] = (cpu[idx].cpu_active_total -
			cpu[idx].cpu_last_active_total) /
			(float) (cpu[idx].cpu_total - cpu[idx].cpu_last_total);
```
When the graph corruption happens, `cpu[idx].cpu_total - cpu[idx].cpu_last_total` is `0.0` and `cpu[idx].cpu_val[0]` is set to `nan`. I patched it to set `cpu[idx].cpu_val[0]` to `1.0` when the divisor would be `0.0` instead of trying to still do the division and the corruption went away while the core was still at full iowait utilization.

**Comment by bunder2015** [comment]
Got a patch?  I'd love to test it.

**Comment by kira78** [comment]
Here's the patch I used.

[conky-cpugraph-fix.patch.txt](https://github.com/brndnmtthws/conky/files/1062774/conky-cpugraph-fix.patch.txt)

**Comment by bunder2015** [comment]
Cool thanks, give me a couple days to test and I'll report back.

**Comment by bunder2015** [comment]
I think this is good, haven't seen any issues.

**Comment by Eusebius1920** [comment]
I am getting this error since a few weeks too:

Screenshot:
![image](https://user-images.githubusercontent.com/8429638/61282914-80e9b180-a7bc-11e9-9fce-bac57c431b9c.png)

Minimal `.conkyrc`:
```
conky.config = {
    alignment = 'top_right',
    background = false,
    border_width = 1,
    cpu_avg_samples = 2,
    default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    use_xft = true,
    font = 'DejaVu Sans Mono:size=12',
    gap_x = 5,
    gap_y = 35,
    minimum_height = 5,
    minimum_width = 150,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_ncurses = false,
    out_to_stderr = false,
    out_to_x = true,
    extra_newline = false,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'override',
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    show_graph_scale = false,
    show_graph_range = false
}

conky.text = [[
${membar 6}

${cpugraph 50}
]]
```

It is happening right after starting conky until the whole graph cycled through once. Should I open a new issue or is this the same problem?

**Comment by Tomunu** [comment]
This should be fixed/re-fixed with the most recent change. See Pull Request #858 and Issue #856.
