### ISSUE TITLE
crashes after a few minutes -- *** Error in `conky': free(): invalid next size (fast): 0x00000000016985b0 ***

### ISSUE THREAD

**Issue by kb5won** [brndnmtthws/conky#315]
I moved my config file over from an old computer, adjusted for ethernet port names on this computer, and ran it, and it works, for a few minutes, then dies.

If I run conky from terminal, when it dies, it gives this error:
*** Error in `conky': free(): invalid next size (fast): 0x00000000016985b0 ***
and then a bunch of memory dump type info.

I don't understand what this means.  Help please!

**Comment by kb5won** [comment]
the number in the error message changes each time.   for example, now it is: 
*** Error in `conky': free(): invalid next size (fast): 0x0000000000a35730 ***

**Comment by kb5won** [comment]
seems like I solved the issue by changing the values of 
minimum_size 300 300
maximum_width 300
to be the same.  when I had the minimum size set smaller, the conky window would adjust large/small every time it updated.....

**Comment by Nooby4Ever** [comment]
Your syntax is for conky 1.9.1 (and previous versions), make sure the "new computer" has an older version of conky installed or [update the syntax of your config](https://github.com/brndnmtthws/conky/wiki/Convert-to-new-1.10-syntax) for conky >=1.10. You can check your version with: `conky -v`

I don't know this has anything to do with the crash itself but in the new syntax it would be:
```
	minimum_width = 300,
    minimum_height = 300,
	maximum_width = 300,
```
(using the old syntax with the current conky version will cause problems)

I know the issue has been resolved already but i wanted to mention this in case other problems might occur in the future.
