### ISSUE TITLE
if_existing functionality

### ISSUE THREAD

**Issue by plikhari** [brndnmtthws/conky#318]
if_existing does not work if you have an executable line  - here template5 and template7 are files - cat will execute and create the test file even if ${template5} file does not exist.
```
${if_existing ${template5}}${execpi 11 cat ${template7} > /tmp/test }${endif}
```
However if I do not output to the test file ( `> /tmp/test` part removed )- it does not show on the conky output and works fine.

The point being - why is ${if_existing} reaching **cat** if the ${template5} file does not exist - should it not jump to the next statement after ${endif} ???

**Comment by plikhari** [comment]
OK figure it out ;-)
The above functionality as per design is correct ! 

But what if one needs to check for an existence of a file - then following works
`${texecpi 10 if [ -s ${template1} ]; then do something here; fi }`

**Comment by lasers** [comment]
Sounds like you ran into this bug https://github.com/brndnmtthws/conky/issues/334.
