### ISSUE TITLE
Conky doesn't support pulseaudio tunnel sinks

### ISSUE THREAD

**Issue by paretje** [brndnmtthws/conky#319]
When using a tunneled PulseAudio sink, I get this error when starting conky or when I send a `USR1` signal:
```
conky: Incorrect pulseaudio sink information.
```

Nonetheless, `pa_sink_volume` does return the correct volume, but it isn't updated.

If conky is already started when the default sink is set to a tunneled sink, and no signal is sent to conky, no error is shown, but `pa_sink_volume` returns `0`.

**Comment by Lompik** [comment]
If you can share how you create a tunneled PA sink, maybe I could reproduce/test more.
For now I think #333 should fix the update of the volume.

> If conky is already started when the default sink is set to a tunneled sink, and no signal is sent to conky, no error is shown, but pa_sink_volume returns 0.

I guess there should still be an issue when changing to tunneled sink when displaying card information (should bot be updated).

**Comment by paretje** [comment]
Thanks, I'll try your PR later tonight, thanks!

This is what I have in `~/.config/pulse/default.pa` on the client:
```
load-module module-tunnel-sink server=192.168.2.2 sink_name=kevin-desktop
```

In `/etc/pulse/default.pa` on the server:
```

load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1;192.168.2.0/24
```

**Comment by paretje** [comment]
I tested it, and it works for me, also when switching sinks. I used the following conky config:
```
conky.config = {
        out_to_console = true,
        out_to_x = false,
        background = false,
        update_interval = 1,
        total_run_times = 0,
        use_spacer = 'left',
        short_units = true,
};
conky.text = [[${if_up eth0}${downspeed eth0} ${upspeed eth0}$else${if_up ppp0}${execi 30 3gmonitor } | ${downspeed ppp0} ${upspeed ppp0}$else${if_up wlan0}$wireless_essid | ${downspeed wlan0} ${upspeed wlan0}$endif$endif$endif | $memperc% * $swapperc% | $cpu% ${hwmon 1 temp 1}C | ${if_empty $battery_time}full$else$battery_time$endif | ${if_pa_sink_muted}OFF$else${pa_sink_volume}%$endif | ${execi 1200 weather-temp}C | ${time %a %b %_d %H:%M:%S}]];
```
