### ISSUE TITLE
keep horizontal position on multi line ${exec ...} output

### ISSUE THREAD

**Issue by Stummi** [brndnmtthws/conky#32]
Hi,

When I change the horizontal position with ${goto xyz} and do an ${exec} then which prints multiple lines, only the first line is on its horizontal position. All lines below it are on positon 0.

I think this is a bug and It would be great to see a fix for this.

Kind Regards,
Michael

**Comment by madnight** [comment]
open since 2013, any updates? any new command since then that makes this possible?

**Comment by stardiviner** [comment]
Like command `cal` output.

**Comment by madnight** [comment]
@stardiviner thats exactly the reason why i'm here : )

**Comment by samuiyo** [comment]
${goto 100}${execpi cal} acts same way.
insert it in each line with sed 's/^/${goto 100}/',
like this: ${execpi cal|sed 's/^/${goto 100}/'}

**Comment by ivankuraj** [comment]
It would be good to have a solution in a more systematic (and efficient) way, as `execpi` parses the output and can be resource-heavy...

**Comment by lasers** [comment]
It's not a bug. It's a feature. :laughing: What if an user want some lines to shift a bit left or right? Or to print different colors per line? That's just two examples. Conky offer way more than that.

Here, I'm making a nice rainbow out of `cal`.
```lua
conky.config = {out_to_x=true}
conky.text = [[
    ${color red}${goto 100}${execi 3600 cal | sed -n 1p}
    ${color lightblue}${goto 100}${execi 3600 cal | sed -n 2p}
    ${color green}${goto 100}${execi 3600 cal | sed -n 3p}
    ${color yellow}${goto 100}${execi 3600 cal | sed -n 4p}
    ${color magenta}${goto 100}${execi 3600 cal | sed -n 5p}
    ${color cyan}${goto 100}${execi 3600 cal | sed -n 6p}
    ${color orange}${goto 100}${execi 3600 cal | sed -n 7p}
    ${color pink}${goto 100}${execi 3600 cal | sed -n 8p}
]]
```
I think we should respect newlines anyway not for `x`, but for `console`, `ncurses`, et cetera too. @brndnmtthws, please chime in with your thoughts about this issue. Thanks.

**Comment by raghav18gupta** [comment]
> ${execpi cal|sed 's/^/${goto 100}/'}

It is not working as it only appends `$goto 100}` with each line.

![screenshot from 2019-01-14 13-31-28](https://user-images.githubusercontent.com/12626208/51101551-09cd6380-1801-11e9-98db-d025896dfb71.png)

**Comment by lasers** [comment]
`${execpi 60 cal|sed 's/^/${goto 100}/'}`

**Comment by stardiviner** [comment]
This is great! Thanks

**Comment by stardiviner** [comment]
@lasers How do you make it colorful? apply `${color red}` on each line? But still don't know how do you do that?
