### ISSUE TITLE
Conky Scroll Length

### ISSUE THREAD

**Issue by laegnur** [brndnmtthws/conky#322]
Hello

I'm trying to do a new conky config with a scroll all across the screen.

In the screenshot that I attached, you can see what I do right now, a conky config with two lines.

One inside a scroll variable, which max length is 99 and start in the middle of the screen, scrolling to left, and only show a part of the text ( it cuts after cpu1: ), the other is the complete text I want to show.

Right now, it has a gap_y so I can see what I'm doing, but at the end it will have gap_y 0 so it will be under the panel, showing the scrolling between the two parts of the panel.

Is it possible to make a full screen scroll that shows the complete text?

![conky_scroll](https://cloud.githubusercontent.com/assets/501635/18436054/b25aa2b2-78f6-11e6-97d0-6b694db23e4c.png)

**Comment by plikhari** [comment]
Can you please share your config - thanks

**Comment by laegnur** [comment]
Hello
Yes, off course. You can see it on this gist: [conky_scroll.lua](https://gist.github.com/laegnur/0804f15f12669a66450386098718ac97)

**Comment by plikhari** [comment]
Thanks - I am out of town - so shall get back to you over the weekend - hold tight

**Comment by plikhari** [comment]
Increase `test_buffer_size = 512,`

on another note - you can write readable stuff like so...
```
${scroll left 120 15 #
${color1}host: ${color0}$nodename | #
${color1}kernel: ${color0}$sysname $kernel | #
${color1}uptime: ${color0}$uptime | #
${color1}cpu0: ${color0}${cpu cpu0}% | #
${color1}cpu1: ${color0}${cpu cpu1}% | #
${color1}cpu2: ${color0}${cpu cpu2}% | #
${color1}cpu3: ${color0}${cpu cpu3}% | #
${color1}cpu4: ${color0}${cpu cpu4}% | #
${color1}memory: ${color0}${mem}/${memmax}B | #
${color1}swap: ${color0}${swap}/${swapmax}B | }
```
`#` at end of line is a continuation character and you do not need to close with `${color}`

In the conky.config - do not redefine defaults and also do not define things not relevant to your configuration. You are just displaying data using the scroll thing - why do you need network or temperature stuff - here is an example. Please note - these are suggestions - use what ever makes you happy. ;-)
```
conky.config = {
  alignment='top_right',
  background=false,
  --border_inner_margin=2,
  --border_outer_margin=0,
  --border_width=0,
  color0='b4cd55',
  color1='FFFFFF',
  --color2='979797',
  cpu_avg_samples=2,
  --default_outline_color='grey',
  --default_shade_color='grey',
  double_buffer=true,
  draw_borders=false,
  --draw_graph_borders=true,
  --draw_outline=false,
  --draw_shades=false,
  --extra_newline=false,
  font='DejaVu Sans Mono:size=12',
  --format_human_readable=true,
  gap_x=0,
  gap_y=30,
  --imlib_cache_size=10,
  maximum_width=1595,
  minimum_height=22,
  minimum_width=1600,
  --net_avg_samples=2,
  no_buffers=true,
  --out_to_console=false,
  --out_to_stderr=false,
  --out_to_x=true,
  --override_utf8_locale=true,
  own_window=true,
  own_window_class='Conky',
  own_window_transparent=false,
  own_window_type='normal',
  --pad_percents=2,
  short_units=false,
  --show_graph_range=false,
  --show_graph_scale=false,
  --stippled_borders=0,
  --temperature_unit='celsius',
  text_buffer_size=512,
  --total_run_times=0,
  update_interval=1.0,
  uppercase=false,
  use_spacer='none',
  use_xft=true,
  xftalpha=0,

};
```

If this solves your issue please remember to close the issue - thanks

cheers

**Comment by laegnur** [comment]
Hello

It works!. It's a problem with the text_buffer_size, not with the scroll length. It's solved. I have to put the text_buffer_size to 1024 to show the text I have right now, and it's not the final text yet...

Many thanks for your help.
