### ISSUE TITLE
[Feature]: Use getaddrinfo() instead of gethostbyname().

### ISSUE THREAD

**Issue by luigino** [brndnmtthws/conky#324]
See [http://udrepper.livejournal.com/16116.html](http://udrepper.livejournal.com/16116.html)

**Comment by plikhari** [comment]
my dear @luigino  perhaps if you can give a description as what you want us to see. 

On many forums it is considered rude and then this is not a forum - we are all trying to sort issues here.

**Comment by lasers** [comment]
Supposedly solved by abeadb59 6 long years before you made this issue.
