### ISSUE TITLE
nvidia-settings GPUUtilization in conky

### ISSUE THREAD

**Issue by ghost** [brndnmtthws/conky#329]
I've noticed in the latest nvidia drivers the libxnvctrl which adds in more support I believe...

In nvidia-settings for the 367.44 drivers I now see a `GPU Utilization:` section that shows the load in percentage...

I want to know if it's possible to display the `GPU Utilization:` percentage in conky?

If I run this cmd `nvidia-settings -tq GPUUtilization` I see all these options;
graphics=12, memory=8, video=0, PCIe=1

The graphics=12 above as example, shows the  percentage of 12, and I only want to display this 12 percentage for the GPU load in conky.

![nvidia-settings](https://cloud.githubusercontent.com/assets/13072581/18980881/4319e158-86c8-11e6-9450-ffaef9dff71a.jpg)

**Comment by Geyup** [comment]
Ahh after posting this issue someone showed me this below.

But they said with sed, might not be the most elegant way of going about this, so any other better way then?


${execi 5 nvidia-settings -tq GPUUtilization | grep -o 'graphics=[0-9]*' | sed -e 's/graphics=//'}% 


thanks

**Comment by Geyup** [comment]
I have this at the moment;

```${exec nvidia-settings -tq GPUUtilization | awk -F '[,= ]' '{ print $2 }'}%```

**Comment by Erinor2** [comment]
Hello you can use:
GPU ${nvidia gpuutil}%, 
RAM ${nvidia membwutil}%
VIDEO ${nvidia videoutil}%
PCIe ${nvidia pcieutil}%

**Comment by frantic1048** [comment]
I'm searching same thing today, you can find what you want here: https://github.com/brndnmtthws/conky/blob/e84ca1f966b8c2903cd792914f5e0ee6d3181b68/doc/variables.xml#L2780

These commands are not listed in wiki, but usable.

**Comment by Geyup** [comment]
SORRY for getting back late, my old computer died, but I'm back in action with Nvidia again! :)

@Erinor2 wow great list of cmds I never knew.

With RAM ${nvidia membwutil}% you can see how much ram being used?
With VIDEO ${nvidia videoutil}% you can see how much video ram being used?

What's the point of this cmd, what will this do? PCIe ${nvidia pcieutil}%

Thanks

**Comment by Geyup** [comment]
Hello, can someone please explain these?

GPU ${nvidia gpuutil}%,
RAM ${nvidia membwutil}%
VIDEO ${nvidia videoutil}%
PCIe ${nvidia pcieutil}%

Thanks

**Comment by simonsjw** [comment]
look up any of the arguments (including the nvidia ones) using 
`man conky`
if you have linux. 
If not, try this link:
[https://github.com/brndnmtthws/conky/wiki/Configuration-Variables#search_word=nvidia](url)

**Comment by Geyup** [comment]
Thanks

**Comment by sebma** [comment]
@simonsjw Hi, your hyperlink is faulty. I points to https://github.com/brndnmtthws/conky/issues/url
instead of https://github.com/brndnmtthws/conky/wiki/Configuration-Variables#search_word=nvidia

**Comment by lasers** [comment]
Questions possibly answered. Thanks everyone. :+1:

**Comment by Brainiarc7** [comment]
> Hello you can use:
> GPU ${nvidia gpuutil}%,
> RAM ${nvidia membwutil}%
> VIDEO ${nvidia videoutil}%
> PCIe ${nvidia pcieutil}%

Is there a way this can be replicated for multiple GPUs?
Does the nvidia conky object allow specifying what GPU to query from?

**Comment by codywohlers** [comment]
`conky: unknown variable '$nvidia'`

(conky 1.10.8)

**Comment by su8** [comment]
@Brainiarc7 `exec` with nvidia-smi. Ask sir @lasers for more Kung Fu sed filtering.

**Comment by lasers** [comment]
>Is there a way this can be replicated for multiple GPUs?

Previous comments suggested @Brainiarc7 probably know this already which is to add `--id=GPU-sud0-su8-g00d-d4Y-t0-y0u-s1r...` or so to the _exec_ `nvidia-smi` command.


>Does the nvidia conky object allow specifying what GPU to query from?

`man conky` suggested `GPU_ID` (i.e. `${nvidia gpuutil 0}%`). Try it and see.
