### ISSUE TITLE
conditional exec always executed

### ISSUE THREAD

**Issue by bobemoe** [brndnmtthws/conky#334]
I have a conditional execi, but since updating from 1.9.0 to 1.10.5 the execi is ALWAYS executed, even when the condition is FALSE.

```
${if_match ${battery_percent BAT1}<10}
    ${execi 10 aplay ~/.i3/alert.wav}
${endif}
```

I have tried exec too and the exhibits the same behaviour.  

I have put some text inside the conditional block and it is not displayed, confirming the condition evaluates false, however the exec is still executed.

**Comment by plikhari** [comment]
Quote the values like
```
${if_match "${battery_percent BAT1}" < "10"}
    ${execi 10 aplay ~/.i3/alert.wav}
${endif}
```
See if this works.

**Comment by bobemoe** [comment]
Hi thanks for your reply.  Unfortunately that doesn't seem to make any difference.  I don't think there is a problem with the condition, as I have also put some test text inside conditional block and it is not displayed, like so:

```
${if_match "${battery_percent BAT1}" < "10"}
    TEST
    ${execi 10 aplay ~/.i3/alert.wav}
    TEST
${endif}
```

I am not seeing TEST TEST displayed but the execi is still being executed. This confirms the condition is evaluating false.  If I change the condition so it evaluates true (change 10 to 1000) then TEST TEST is displayed and the execi is still executed.

I have also tested using an if_existing as follows:

```
${if_existing /etc/}
		${execi 10 aplay ~/.i3/alert.wav}
		TEST
${endif}
```
TEST is displayed, and execi is executed.

```
${if_existing /404/}
		${execi 10 aplay ~/.i3/alert.wav}
		TEST
${endif}
```
TEST is **not** displayed, but execi is executed.

**Comment by plikhari** [comment]
Fantastic have a look at the issue I raised #318 

All of the **if_** conky variables will **only** print or not print within the condition - depending on true or false. These **if_** conditions do not stop any execution of a command with `exec, execi etc`.

So to work around this - you saw my work around there - using shell to figure things out.
`${texecpi 10 if [ -s ${template1} ]; then do something here; fi }` I use `texecpi` as I need to execute an external process. I do not know any way where a conky variable can be captured and used in this work around. 

From a common sense point of view - if the condition is false then the following code should not be evaluated at all.

**Comment by marcpayne** [comment]
Thanks for pointing to a workaround @plikhari 

All this stems from the way callbacks are handled now. Visible output from conky objects respects `${if...}` expressions and works as expected. However, the behind-the-scenes work needed to update those objects (e.g. running a command and storing its output, or getting the latest info for `${top...}`) is performed in one go, each update interval, before any `${if...}` expressions are handled.

I know this explanation doesn't fix the situation, but hopefully it sheds some light as to why it happens.

**Comment by plikhari** [comment]
Hey @marcpayne  - Many thanks for that information.

I figured this by going through the source code. 

But at some point in time - we need to find a way to handle these issues - as my workaround will only work with tangible things that shell can look at - like in my case - check if a file exists.

**Comment by dbriba** [comment]
And if you chain the command with anti-slash, like this : 
${if_match ${battery_percent BAT1}<10}\
    ${execi 10 aplay ~/.i3/alert.wav}
${endif}

**Comment by bobemoe** [comment]
@dbriba sorry to report that adding the \ has not had any affect.

@plikhari thanks for the idea, I now use a bash scrip to do the test and play the sound.  I may as well use ACPI events at this point, or a battery monitor. I guess conky isn't really the right place to be doing this sort of stuff.

I'm happy now anyway. Shall I leave this issue open for your reference? Sounds like you may want to change this behaviour as it kind of defies logic, and also breaks backward compatibility of some configs, in a kind of hard to debug way. Anyway, up to you all now, feel free to close if you are want.

Thanks :)

**Comment by dgiglio** [comment]
@plikhari 
> So to work around this - you saw my work around there - using shell to figure things out. 
> `${texecpi 10 if [ -s ${template1} ]; then do something here; fi }`

Excuse me, why do you use a template inside a condition?

**Comment by plikhari** [comment]
You can use the actual file name here - it is just that - when you are handling 20+ template files - it helps to know which external sources I am checking or using. I use a script to feed the template variables used for each template file into the help docs. I am referring to the documentation for conkywx - my weather program.
