### ISSUE TITLE
Image rendered twice (stacked)

### ISSUE THREAD

**Issue by zagortenay333** [brndnmtthws/conky#345]
I noticed that using `$image` produces two images stacked on top of each other.

In this conky ,the weather icons are stacked: https://github.com/zagortenay333/conky-Vision

To make it more visible, take a screenshot of the conky, open in gimp and import an icon on top of the screenshot.

Using conky `1.10` on gnome 3.22.

**Comment by lasers** [comment]
1 year 9 months passed. Can you determine if you're still having this problem today on 1.10.8 or 1.10.9_pre? The older versions are not trustworthy.

If you can reproduce, please explain this issue again as I didn't quite understand this one. It's not clear what you saw and what you were expecting to see... And the link goes to your project. Many thanks.
