### ISSUE TITLE
window background refresh rate 

### ISSUE THREAD

**Issue by BlackTango** [brndnmtthws/conky#348]
It will be nice to add a setting that will make conky instantly change the background (transparency) when the wallpaper change. 
What it does now is freeze for a sec whith the old wallpaper and then change to the new wallpaper.
Changing the update interval does not matter in this case, its still slow. 
![screenshot from 2016-12-05 02-09-43](https://cloud.githubusercontent.com/assets/15683321/20876422/e7b0d82a-ba8f-11e6-8a1d-bfad45fb3de1.png)

**Comment by dbriba** [comment]
I never have this issue with Fedora, KDE.
I think it's not a problem with conky, perhaps with your configuration.

**Comment by elachkarjoseph** [comment]
this is my current configuration, do you see anything abnormal? 

conky.config={


	use_xft=true,
	--xftfont_123:size='8',
	xftalpha=0.1,




	update_interval=1,
	total_run_times=0,






	own_window=true,
	own_window_class='conky',
	own_window_type='dock',
	own_window_transparent=true,
	own_window_hints='undecorated,below,sticky,skip_taskbar',
	own_window_colour='000000',
	own_window_argb_visual=false,
	own_window_argb_value=0,
	
	double_buffer=true,


	draw_shades=false,
	draw_outline=false,
	draw_borders=false,
	draw_graph_borders=false,
	default_color='white',
	default_shade_color='red',
	default_outline_color='green',


	alignment='top_middle',


	gap_x=0,
	gap_y=10,
	no_buffers=true,
	uppercase=false,
	cpu_avg_samples=2,
	net_avg_samples=1,
	override_utf8_locale=true,
	use_spacer='none',


	--minimum_size=0,
	border_width=5,
	default_color='4083ef',




};

**Comment by dbriba** [comment]
Try replace
 own_window_argb_visual=false,
by 
own_window_argb_visual=true,

**Comment by elachkarjoseph** [comment]
Thank you verry much sir, this is incredible! im closing this issue.

**Comment by dbriba** [comment]
You can also take off own_window_argb_value=0, if you want total transparency.
From http://conky.sourceforge.net/config_settings.html : 
own_window_argb_value :	When ARGB visuals are enabled, this use this to modify the alpha value used. Valid range is 0-255, where 0 is 0% opacity, and 255 is 100% opacity.

**Comment by smd3** [comment]
This also fixed my issue where conky would cause some strange background artifacts or smearing of other windows.

**Comment by lasers** [comment]
Great solution, sir. I will be closing this issue for real this time.
