### ISSUE TITLE
curl output

### ISSUE THREAD

**Issue by vaesbart** [brndnmtthws/conky#349]
Hi,

I've noticed some odd behaviour in displaying $curl output.
I want to display output from ${curl ipinfo.io/country} (region, location etc) formatted between "[  ]"
but the closing bracket "]" gets displayed on a new line. Is this expected behaviour ?

Also, is there any way to display output from tcp_ping in ms instead of ns ?

See attached conky_left.txt for my config file.
See screenshot of current ouput.

![screenshot_20161214_221942](https://cloud.githubusercontent.com/assets/10183746/21201567/ba4b77be-c24b-11e6-9b0b-7831e484e603.png)

[conky_left.txt](https://github.com/brndnmtthws/conky/files/652870/conky_left.txt)

**Comment by dbriba** [comment]
I think it is an issue with the conky's variable curl.
If you use curl with exec, like this : 
${exec curl ipinfo.io/country}
There is no problem, conky display well.

**Comment by dbriba** [comment]
You can also use execi command (with interval), you don't need update your location, country, etc every second :
${execi 1800 curl ipinfo.io/country}

**Comment by dbriba** [comment]
[![Image](https://i.goopics.net/GV1v.jpg)](https://goopics.net/i/GV1v)

**Comment by vaesbart** [comment]
Thank you for this solution :)

**Comment by dbriba** [comment]
Hello vaesbart.
I wish you an happy new year.

I find a solution to display ping with ms:
Try this : 
╶${color0} ping     ${color1}[${color0} ${exec ping -nc1 google.com | cut -d= -f4 | sed -n '2p'} ${color1}]

**Comment by plikhari** [comment]
Perhaps this will work better - you can also use more than a single ping ::
```
ping -nc1 google.com | sed -n '/icmp_seq/{s|.*time=\(.*\)$|\1|;p}'
```

**Comment by dbriba** [comment]
If you use more than one ping, you have to modify the command line, example for 2 ping : 
ping -nc2 google.com | cut -d= -f4 | sed -n '3p'

But I think it's not important because the command line is executed every second.

**Comment by plikhari** [comment]
My point being - you do not need to use `cut` when everything can be handled by `sed` :-)

**Comment by dbriba** [comment]
Ok plikhari, but I am not an expert with sed.
For example I don't understand your command

**Comment by plikhari** [comment]
Ok - it was never meant to be a critique - just to assist you with a better solution
```
ping -nc1 google.com | sed -n '/icmp_seq/{s|.*time=\(.*\)$|\1|;p}'
```
`-n` - do not print anything

`/icmp_seq/' - search each line for this pattern

`{s|.*time=\(.*\)$|\1|;p}` - Once the pattern is found - stuff in the `{}` curly braces only works on this line. Leave everything  including `time=` and capture stuff between `=` and end of line `$`. We need to escape the `(` and `)` so use `\(` and `\)`. Once we have done this search and replace end with a `;` and `p` to print out result which we got from `\1`. I used `|` pipe character as a separator but you can use any character including the standard `/` character.

Trust that explains it all :-)

**Comment by gnarlie** [comment]
I am seeing similar problems with the `stock` variable (which uses curl under the hood). I'm trying to display current price and change on day, using

``` 
${color grey}SPY: $color ${stock SPY ltp} ${stock SPY change}
```

But this puts a newline after each piece of info.

**Comment by dbriba** [comment]
you can use goto and voffset to work around this issue : 

${color grey}SPY: $color ${stock SPY ltp} ${goto 100}${voffset -22}${stock SPY change}

**Comment by ght** [comment]
@vaesbart Please close this issue if the problem is resolved :)

**Comment by vaesbart** [comment]
@ght While dbriba provided a workaround, the underlying problem of using curl within brackets (any kind of bracket -> "(" "[" "{" etc...) still remains.

**Comment by ght** [comment]
Is this an issue with conky though? if you run `curl -s http://ipinfo.io/ip | hexdump -C` on the command line, you will see that the response ends with `0x0a` (which is `\n`). So I would say it is expected behavior of conky to output the newline, but I only use a really simple `conky.conf` and maybe I am missing something here.

For the IP address you can use a different service such as <http://ipecho.net/plain> or <http://ident.me>, which both do not include a trailing newline. See <https://askubuntu.com/q/95910> for other alternatives.

**Comment by vaesbart** [comment]
Ok, tested it and using another service now. Output is indeed as expected :)
