### ISSUE TITLE
Build issue with fedora 24 and lua

### ISSUE THREAD

**Issue by D4void** [brndnmtthws/conky#350]
Hello

I got a problem I don't manage to solve. I need to compile conky to have lua enabled.
cmake doesn't find my lua 5.1 but I have installed it.

CMake Error at cmake/ConkyPlatformChecks.cmake:263 (message):
  Unable to find Lua 5.1.x
Call Stack (most recent call first):
  CMakeLists.txt:37 (include)

Tried with cmake .. -DLUA_INCLUDE_DIR="/usr/include/lua-5.1/"
idem

It's probably my fault, if someone can help and confirm.
I am not an expert at compiliing and checking depencies.

All my lua package installed:
compat-lua-libs-5.1.5-5.fc24.x86_64
lua-json-1.3.2-6.fc24.noarch
compat-lua-5.1.5-5.fc24.x86_64
lua-posix-33.3.1-2.fc24.x86_64
lua-expat-1.3.0-7.fc24.x86_64
lua-devel-5.3.3-2.fc24.x86_64
compat-tolua++-1.0.93-4.fc24.x86_64
lua-lpeg-0.12.2-2.fc24.x86_64
lua-5.3.3-2.fc24.x86_64
compat-tolua++-devel-1.0.93-4.fc24.x86_64
lua-socket-3.0-0.12.rc1.fc24.x86_64
compat-lua-devel-5.1.5-5.fc24.x86_64

dnf repoquery -l compat-lua-libs.x86_64
Vérification de l'expiration des métadonnées effectuée il y a 0:16:39 sur Fri Dec 23 11:06:19 2016.
/usr/lib64/liblua-5.1.so
/usr/lib64/lua
/usr/lib64/lua/5.1
/usr/share/doc/compat-lua-libs
/usr/share/doc/compat-lua-libs/COPYRIGHT
/usr/share/doc/compat-lua-libs/HISTORY
/usr/share/doc/compat-lua-libs/README
/usr/share/doc/compat-lua-libs/contents.html
/usr/share/doc/compat-lua-libs/cover.png
/usr/share/doc/compat-lua-libs/logo.gif
/usr/share/doc/compat-lua-libs/lua.css
/usr/share/doc/compat-lua-libs/lua.html
/usr/share/doc/compat-lua-libs/luac.html
/usr/share/doc/compat-lua-libs/manual.css
/usr/share/doc/compat-lua-libs/manual.html
/usr/share/doc/compat-lua-libs/readme.html
/usr/share/lua
/usr/share/lua/5.1

dnf repoquery -l compat-lua-devel
Vérification de l'expiration des métadonnées effectuée il y a 0:26:23 sur Fri Dec 23 11:06:19 2016.
/usr/include/lua-5.1
/usr/include/lua-5.1/lauxlib.h
/usr/include/lua-5.1/lua.h
/usr/include/lua-5.1/lua.hpp
/usr/include/lua-5.1/luaconf.h
/usr/include/lua-5.1/lualib.h
/usr/lib/pkgconfig/lua-5.1.pc
/usr/include/lua-5.1
/usr/include/lua-5.1/lauxlib.h
/usr/include/lua-5.1/lua.h
/usr/include/lua-5.1/lua.hpp
/usr/include/lua-5.1/luaconf.h
/usr/include/lua-5.1/lualib.h
/usr/lib64/pkgconfig/lua-5.1.pc

dnf repoquery -l compat-tolua++-devel
Vérification de l'expiration des métadonnées effectuée il y a 0:07:04 sur Fri Dec 23 14:07:19 2016.
/usr/bin/tolua++
/usr/include/tolua++.h
/usr/lib/libtolua++.so
/usr/bin/tolua++
/usr/include/tolua++.h
/usr/lib64/libtolua++.so

**Comment by plikhari** [comment]
Try this - you can remove lines you may not want like NVIDIA etc
```
	LDFLAGS="-llua-5.1 -lm"

	LUA_CFLAGS="-I/usr/include/lua-5.1"

	cmake \
		-D CMAKE_BUILD_TYPE=Release \
		-D CMAKE_C_FLAGS="${LUA_CFLAGS}" \
		-D CMAKE_CXX_FLAGS="${LUA_CFLAGS}" \
		-D CMAKE_EXE_LINKER_FLAGS="${LDFLAGS}" \
		-D CMAKE_INSTALL_PREFIX=/usr \
		-D BUILD_WLAN=ON \
		-D BUILD_CURL=ON \
		-D BUILD_RSS=ON \
		-D BUILD_XDBE=ON \
		-D BUILD_XSHAPE=ON \
		-D BUILD_IMLIB2=ON \
		-D BUILD_ICONV=ON \
		-D BUILD_WEATHER_METAR=ON \
		-D BUILD_WEATHER_XOAP=ON \
		-D BUILD_LUA_CAIRO=ON \
		-D BUILD_LUA_IMLIB2=ON \
		-D BUILD_LUA_RSVG=ON \
		-D BUILD_NVIDIA=ON \
		.

	make
```

**Comment by D4void** [comment]
same error. 
I even compiled lua 5.1 to /usr/local and I have the same problem.
I don't understand.
And we have set(INCLUDE_SEARCH_PATH /usr/include /usr/local/include)
in ConkyPlateformChecks...

-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Looking for include file sys/statfs.h
-- Looking for include file sys/statfs.h - found
-- Looking for include file sys/param.h
-- Looking for include file sys/param.h - found
-- Looking for include file sys/inotify.h
-- Looking for include file sys/inotify.h - found
-- Looking for include file dirent.h
-- Looking for include file dirent.h - found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for pipe2
-- Looking for pipe2 - not found
-- Looking for O_CLOEXEC
-- Looking for O_CLOEXEC - found
-- Looking for statfs64
-- Looking for statfs64 - found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Checking for module 'ncurses'
--   Found ncurses, version 6.0.20160709
-- Looking for include file iwlib.h
-- Looking for include file iwlib.h - found
-- Looking for iw_sockets_open
-- Looking for iw_sockets_open - not found
-- Looking for getnameinfo
-- Looking for getnameinfo - found
-- Looking for 5 include files netdb.h, ..., arpa/inet.h
-- Looking for 5 include files netdb.h, ..., arpa/inet.h - found
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found X11: /usr/lib64/libX11.so
-- Checking for one of the modules 'lua5.1;lua-5.1;lua51;lua'
CMake Error at cmake/ConkyPlatformChecks.cmake:263 (message):
  Unable to find Lua 5.1.x
Call Stack (most recent call first):
  CMakeLists.txt:37 (include)


-- Configuring incomplete, errors occurred!
See also "/usr/local/src/conky-1.10.6/build/CMakeFiles/CMakeOutput.log".
See also "/usr/local/src/conky-1.10.6/build/CMakeFiles/CMakeError.log".

**Comment by plikhari** [comment]
I suggest look/use this spec file - you should remove all versions of lua you have installed - unless there is dependency conflict - Fedora is using lua 5.3 (with tolua++ patched for lua 5.3) for conky - YES - lua 5.3 and not lua 5.1

I had noticed this during my testing for conkywx SIX and had to make slight changes in code since lua 5.3 has some different ways of handling integers.

Remember to change the Version: 1.10.4 to the latest conky release.

[conky spec file at Fedora](http://pkgs.fedoraproject.org/cgit/rpms/conky.git/tree/conky.spec)

**Comment by dbriba** [comment]
Why do you want compile conky from source ?
conky package are available in fedora 24 and have lua enabled (conky-1.10.4-1.fc24).

Just do : 
dnf install conky

I am with fedora and conky work fine.

**Comment by D4void** [comment]
@dbriba : yes you're right but I need nvidia and systemd journal feature.

@plikhari : thank you for your answer. I will try too look at this.
I managed to compile lua5.1 but I try and failed to compile tolua .

**Comment by plikhari** [comment]
Fantastic - but you know - you already have the framework - if you see - nvidia is already enabled - the other feature you desire can also be enabled in the same spec file. 

My point is if you have a system working with tolua++ for 5.3 and conky also - just stay with that. It is way better than lua51.

Today I released tolua++_5.3 and [conky-cairo linked to lua 5.3](https://aur.archlinux.org/packages/conky-cairo/) on AUR - Arch Linux user repo. This takes conky into a new sphere of lua 5.3 - lighter and faster.

**Comment by D4void** [comment]
ok., thank you for your recommandation.
I've done that because of this link  :
https://github.com/antonio-malcolm/conky-configs/wiki/How-To-Compile-Conky-And-Its-Lua-Bindings-From-Source

I will try to build the rpm. (I have never done that , it's time to try :) )

**Comment by D4void** [comment]
Worked like a charm with the spec file.
Just added:
                            -DBUILD_JOURNAL=ON \
                            -DBUILD_HDDTEMP=ON \

Big thanks @plikhari

**Comment by plikhari** [comment]
Thank you ;-) - Please close this issue as things have worked well for you.
