### ISSUE TITLE
${cpubar cpuX) and ${freq X}

### ISSUE THREAD

**Issue by sandboxgangster** [brndnmtthws/conky#354]
Hello,

i use ${cpubar cpuX) and ${freq X} for more then one CPUs, if one CPU Offline then show the graph/text data from a others CPU.

Example (cpubar and freq is similar):

CPU 0 Online = ${cpubar 0} OK
CPU 1 Online = ${cpubar 1} OK
CPU 2 Online = ${cpubar 2} OK
CPU 3 Offline = ${cpubar 3} Show data from CPU 2

CPU 0 Online = ${cpubar 0} OK
CPU 1 Online = ${cpubar 1} OK
CPU 2 Offline = ${cpubar 2} Show data from CPU 1
CPU 3 Offline = ${cpubar 3} Show 0% its OK

CPU 0 Online = ${cpubar 0} OK
CPU 1 Offline = ${cpubar 1} Show data from CPU0
CPU 2 Offline = ${cpubar 2} Show 0% its OK
CPU 3 Offline = ${cpubar 3} Show 0% its OK
...

**Comment by dbriba** [comment]
For ${freq X} CPUs are counted from 1
For ${cpubar cpuX) cpu0 is the total usage and CPUs are counted from 1

**Comment by sandboxgangster** [comment]
Ok, thx my fail
