### ISSUE TITLE
Weird video corruption where transparency is used

### ISSUE THREAD

**Issue by Zachs-Kappler** [brndnmtthws/conky#368]
Are there any settings I can try to fix it? I'm using Elementary OS Loki.
![selection_001](https://cloud.githubusercontent.com/assets/1700613/22943638/e14a9d84-f2b3-11e6-9f00-ccfebadfe53a.png)

**Comment by lasers** [comment]
Did you find a solution to your problem?

**Comment by lasers** [comment]
Try all of `own_window_type` options and see if one of them does anything for you.
