### ISSUE TITLE
Segfault when total CPU time is unchanged

### ISSUE THREAD

**Issue by ANerd** [brndnmtthws/conky#376]
When system is under heavy load, it seems conky can run two loops immediately following each other. 

Since /proc/stat resolution is [typically hundredths of a second](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/filesystems/proc.txt?id=refs/tags/v4.10#n1304) this makes the same values being read twice, leading to a NaN in the [calculation](https://github.com/brndnmtthws/conky/blob/a58a6d4e081ca6ab241f20fcae80a6b6c31bf1c9/src/linux.cc#L923) of the CPU usage.

When this NaN reaches the drawing code, it produces a segfault.

**Comment by su8** [comment]
@lasers This issue has been fixed.

**Comment by lasers** [comment]
@su8 Can you supply a PR / commit for historical purposes?

**Comment by su8** [comment]
@lasers Here's the commit - https://github.com/brndnmtthws/conky/commit/61c0dfaf60d78641fcce8c49e80bbed098f98559

**Comment by lasers** [comment]
Issue closed by https://github.com/brndnmtthws/conky/pull/429. Thank you @su8 :-)
