### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by kdb424** [brndnmtthws/conky#381]
There seems to be no supported way to get wildcards to be supported. For example one should be able to use something like this. It's useful for when you have USB devices that move names every time.
${if_existing /proc/net/route eth*}

**Comment by mxmlnkn** [comment]
I have a similar problem when listing all my harddrives. Currently I'm working around this by calling an external script using:

    #-------------------------------------------------------------------------------
    #                                    HDD
    #-------------------------------------------------------------------------------
    ${color2}${voffset 2}${hr 1}$color
    ${color2}${alignc}HDD$color
    ${color2}${voffset -5}${hr 1}$color
    ${execpi 10 ~/etc/conky/list_mounted.sh}

With `list_mounted.sh` containing:

    #!/bin/bash
    # Thanks to lancasrj:
    # http://www.linuxforums.org/forum/ubuntu-linux/169744-conky-display-all-mounted-drives-post944444.html#post944444

    cat /proc/mounts |  awk '{
       if ( $1 ~ /\/dev/ )
       {
          num_elem = split($2,str_array,"/")
          if (str_array[num_elem] == "")
          {
             str_array[num_elem] = "/";
          }
          printf "%5.5s:${goto 40}${fs_type %s}${goto 80}${fs_bar 8,50 %s}${alignr}${fs_used %s} / ${fs_size %s} [${fs_used_perc %s}%]${voffset -2}\n", str_array[num_elem], $2, $2, $2, $2, $2, $2
       }
    }'

You could modify that to do the same for network devices.

**Comment by lasers** [comment]
Do partial match, eg `${if_existing /proc/net/route eth}` for `eth0`, `eth1`, etc not work here?

1 years 5 months passed. We're asking you to update this issue by determining if you're still having this problem today on `1.11_pre` (git)? The older versions are not trustworthy due to too many changes that can be hard to track. Thank you.
