### ISSUE TITLE
Conver lua not working

### ISSUE THREAD

**Issue by MavropaliasG** [brndnmtthws/conky#385]
In Manjaro linux using KDE.

I'm trying to convert the file JJZkCuYr.txt which has my old conky config into hello.txt.

I get this error

`lua ./convert.lua JJZkCuYr.txt hello.txt
lua: ./convert.lua:139: attempt to index a nil value (local 'settings')
stack traceback:
        ./convert.lua:139: in main chunk
        [C]: in ?
`

I am attaching my old conky config, please update me on what I'm doing wrong.

Thanks

[JJZkCuYr.txt](https://github.com/brndnmtthws/conky/files/907392/JJZkCuYr.txt)

**Comment by dbriba** [comment]
It sometimes happens that convert.lua fail.
Try this this :

conky.config = {
own_window = true,
own_window_transparent = true,
own_window_type = 'desktop',
own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
own_window_argb_visual = true,
own_window_argb_value = 0,
out_to_console = false,
use_xft = true,
xftfont = 'cure:size=10',
update_interval = 2,
cpu_avg_samples = 2,
net_avg_samples = 2,
double_buffer = true,
maximum_width = 320,
draw_shades = false,
draw_outline = false,
draw_borders = false,
stippled_borders = 1,
border_width = 20,
default_color = 'white',
default_shade_color = 'white',
default_outline_color = 'white',
alignment = 'top_right',
gap_x = 15,
gap_y = 0,
use_spacer = 'left',
no_buffers = true,
uppercase = false
} 
conky.text = [[


${color}${alignc}${time %A %d of %B, %Y}${color lightgrey} | ${color}${time %H:%M:%S}

${alignc} ${color lightgrey}Linux $color$kernel ${color lightgrey}on $color$machine

${color}${alignc}${color lightgrey}Uptime: ${color}$uptime${color lightgrey} | ${color lightgrey}Load: $color$loadavg

${color lightgrey}${alignc}Battery:$color ${battery}${color lightgrey} | ${color lightgrey}ET: ${color}$battery_time
${alignc}${color #FFEF00}${battery_bar 8,300}
${color #656565}$stippled_hr$color
${alignc}${color} $wireless_essid${alignr}${color lightgrey}

${color lightgrey}  Down:${color}${downspeedf wlp3s0} KB/s${alignr}${color lightgrey}Up:${color}${upspeedf wlp3s0} KB/s     
${color #000000}${downspeedgraph wlp3s0 12,140 000000 FFEF00}${alignr}${color #000000}${upspeedgraph wlp3s0 12,140 000000 FFEF00}
${color lightgrey}     Total: $color${totaldown wlp3s0}${alignr}${color lightgrey}Total: ${color}${totalup wlp3s0}     

${color lightgrey}Wireless Bitrate: ${color}${wireless_bitrate wlp3s0}${color lightgrey} | ${color lightgrey}${alignr}Signal Quality:${color}${wireless_link_qual_perc wlp3s0}%
${color #656565}$stippled_hr$color
${alignc}${color}${execi 1000 cat /proc/cpuinfo | grep 'model name' | sed -e 's/model name.*: //'| uniq}
${alignc}${color #000000}${cpugraph 13,318 000000 FFEF00}

${color lightgrey}Total CPU Usage: ${color}${cpu cpu0}%${alignr}${color lightgrey}| ${color lightgrey}CPU Temperature: ${color}${hwmon 1 temp 1}°C

${color lightgrey} C1: ${color}${cpu cpu1}% ${color lightgrey}@ ${color}${freq 1} MHz${color #FFEF00}${alignr}${color lightgrey}C2: ${color}${cpu cpu2}% ${color lightgrey}@ ${color}${freq 2} MHz   
${color #FFEF00}${cpubar cpu1 6,150}${alignr}${color #FFEF00}${cpubar cpu2 6,150}
${color lightgrey} C3: ${color}${cpu cpu3}% ${color lightgrey}@ ${color}${freq 3} MHz${color #FFEF00}${alignr}${color lightgrey}C4: ${color}${cpu cpu4}% ${color lightgrey}@ ${color}${freq 4} MHz   
${color #FFEF00}${cpubar cpu3 6,150}${alignr}${color #FFEF00}${cpubar cpu4 6,150}
${color #656565}$stippled_hr$color
${alignc}${color lightgrey}Resources

${color lightgrey}Ram  ${alignc}               ${color}$mem${color lightgrey} / ${color}$memmax ${alignr}${memperc}% Used
${color #FFEF00}${membar 6,318}
${color lightgrey}Swap ${alignc}                 ${color}${swap}${color lightgrey} / ${color}${swapmax} ${alignr}${swapperc}% Used
${color #FFEF00}${swapbar 6,318}
${color lightgrey}$fs_type ${alignc}               ${color}${fs_used}${color lightgrey} / ${color}${fs_size} ${alignr}${fs_used_perc /}% Used
${color #FFEF00}${fs_bar 6,318 /}
${color lightgrey}Disk Read IO: $color${diskio_read}${alignr}${color lightgrey}Disk Write IO: ${color}${diskio_write}
${color #000000}${diskiograph_read 12,145 000000 FFEF00}${alignr}${color #000000}${diskiograph_write 12,145 000000 FFEF00}
${color #656565}$stippled_hr$color
${alignc}${color lightgrey} Processes

${color lightgrey}Processes: ${color}$running_processes${color lightgrey} / ${color}$processes${alignr}${color lightgrey}Threads: ${color}$running_threads${color lightgrey} / ${color}$threads

${color lightgrey}  PID         Process${alignr}Memory        CPU  
${color}${top pid 1}      ${top name 1}${alignr}${top mem_res 1}     ${top cpu 1}%
${color}${top pid 2}      ${top name 2}${alignr}${top mem_res 2}     ${top cpu 2}%
${color}${top pid 3}      ${top name 3}${alignr}${top mem_res 3}     ${top cpu 3}%
${color}${top pid 4}      ${top name 4}${alignr}${top mem_res 4}     ${top cpu 4}%
${color}${top pid 5}      ${top name 5}${alignr}${top mem_res 5}     ${top cpu 5}%
${color}${top pid 6}      ${top name 6}${alignr}${top mem_res 6}     ${top cpu 6}%
${color}${top pid 7}      ${top name 7}${alignr}${top mem_res 7}     ${top cpu 7}%
${color}${top pid 8}      ${top name 8}${alignr}${top mem_res 8}     ${top cpu 8}%
${color}${top pid 9}      ${top name 9}${alignr}${top mem_res 9}     ${top cpu 9}%
${color}${top pid 10}      ${top name 10}${alignr}${top mem_res 10}     ${top cpu 10}%
${color #656565}$stippled_hr$color
]]

**Comment by MavropaliasG** [comment]
Thank you @dbriba 

Now I get this error:

`[alpha@alpha-pc Desktop]$ conky
conky: desktop window (2c0000f) is subwindow of root window (281)
conky: window type - desktop
conky: drawing to created window (0x5000002)
conky: drawing to double buffer
conky: Unknown setting 'xftfont'
conky: can't open '/sys/class/hwmon/hwmon1/temp1_input': No such file or directory
please check your device or remove this var from conky
Segmentation fault (core dumped)
`

**Comment by dbriba** [comment]
Replace
xftfont = 'cure:size=10',
by
font = 'cure:size=10',

(I update my code)
For the error "conky: can't open '/sys/class/hwmon/hwmon1/temp1_input': No such file or directory", I don't know that don't work for you, I test this code and for me it's good.
remove "${hwmon 1 temp 1}°C" and see what happen.

**Comment by MavropaliasG** [comment]
thank you @dbriba 
I did change the xftfont and  removed the hwmon temp and now I simply get
`conky
conky: desktop window (2c0000f) is subwindow of root window (281)
conky: window type - desktop
conky: drawing to created window (0x4e00002)
conky: drawing to double buffer
Segmentation fault (core dumped)
`

any ideas what is wrong with this ?

**Comment by dbriba** [comment]
I don't know why you have a core dump.
with my fedora, that work fine : 
http://pix.toile-libre.org/upload/original/1491711952.jpg

Try launch conky with debug and post the result here:
conky -DD -c /path_of_conky

**Comment by dbriba** [comment]
and what is your conky version ?
conky -v

**Comment by MavropaliasG** [comment]
Hi @dbriba thank you so much for helping me.

This is my conky version
https://pastebin.com/6214tzgg

My current config:
https://pastebin.com/zhxgCWaH

And the output of the debug
`[alpha@alpha-pc ~]$ conky -DD -c /usr/bin/conky
DEBUG(0) [/build/src/conky-1.10.6/src/conky.cc:2698]: reading contents from config file '/usr/bin/conky'
conky: Syntax error (/usr/bin/conky:1: unexpected symbol near '<\127>') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: [string "..."]:139: attempt to index a nil value (local 'settings')
`
Worth noting, I want to be sure before switching to manjaro that everything work so I run manjaro and conky within a virtual machine.

Here is the output of my inxi -Fxxx
https://pastebin.com/7U7Qhfq0

Please tell me if I can provide any more information.
Thanks

**Comment by dbriba** [comment]
You have conky 1.10.6 and I have conky 1.10.7 (the latest commit), may the issue is here.
Update your conky to 1.10.7 version and see what happen.

**Comment by dbriba** [comment]
And may-be it is because you use a virtual machine, I can see some post about that, but I do not find them anymore.

**Comment by plikhari** [comment]
@MavropaliasG  - virtual machines are based on how you have configured them with ram cpu etc.

Manjaro Linux works fine - it is based on Arch Linux - you can safely start using it ;-)

Perhaps you can close this issue as well.

thanks

**Comment by MavropaliasG** [comment]
@plikhari thanks, I will try it again on a native manjaro installation and I will see if it works then.

**Comment by MavropaliasG** [comment]
Dear @dbriba thank you for your help. I have indeed installed manjaro and conky is working, however it is does not have its own window (if I click in the desktop it hides) and its not transparent. What could I change ?

This is the config  https://pastebin.com/efGe5R1R

![screenshot_20170629_190358](https://user-images.githubusercontent.com/13523909/27684744-d8476b2c-5cfd-11e7-899e-1e97e4b75a27.jpeg)

**Comment by MavropaliasG** [comment]
Thank you for your reply @dbriba 

I added the ARGB arguement in this config now, still hides if I click in the desktop take a look  https://pastebin.com/g4N0L30N

I also have translucency enabled but still gives me this black windows

![screenshot_20170630_003417](https://user-images.githubusercontent.com/13523909/27699231-2d80b2a0-5d2c-11e7-9028-b07159d70c9d.jpeg)

**Comment by dbriba** [comment]
You must enabled the compositing in kde:
System-setting==> Affichage et Ecran ==> Compositeur ==> and check "Activer le compositeur au démarrage"
Sorry I am french and I have not the translation in english

**Comment by dbriba** [comment]
In english
System-settings ==> Display and Monitor ==> Compositor ==> and check "Enable compositor on startup"

may be you can reboot.

**Comment by MavropaliasG** [comment]
@dbriba thank you for your response.

I already have this option enabled but both problems still persist.

![screenshot_20170630_111740](https://user-images.githubusercontent.com/13523909/27719602-2ff91cac-5d86-11e7-8232-22783813ce68.jpeg)

**Comment by dbriba** [comment]
Ok I test your conky and I have also both issue.
I modified your conky like this :

conky.config = {
own_window = true,
own_window_transparent = true,
own_window_type = 'dock',
own_window_argb_visual = true,
own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
own_window_argb_visual = true,
own_window_argb_value = 0,
out_to_console = false,
use_xft = true,
font = 'cure:size=10',
update_interval = 2,
cpu_avg_samples = 2,
net_avg_samples = 2,
double_buffer = true,
maximum_width = 320,
draw_shades = false,
draw_outline = false,
draw_borders = false,
stippled_borders = 1,
border_width = 20,
default_color = 'white',
default_shade_color = 'white',
default_outline_color = 'white',
alignment = 'top_right',
gap_x = 15,
gap_y = 0,
use_spacer = 'left',
no_buffers = true,
uppercase = false
}
conky.text = [[

${color}${alignc}${time %A %d of %B, %Y}${color lightgrey} | ${color}${time %H:%M:%S}

${alignc} ${color lightgrey}Linux $color$kernel ${color lightgrey}on $color$machine

${color}${alignc}${color lightgrey}Uptime: ${color}$uptime${color lightgrey} | ${color lightgrey}Load: $color$loadavg

${color lightgrey}${alignc}Battery:$color ${battery}${color lightgrey} | ${color lightgrey}ET: ${color}$battery_time
${alignc}${color #FFEF00}${battery_bar 8,300}
${color #656565}$stippled_hr$color
${alignc}${color} $wireless_essid${alignr}${color lightgrey}

${color lightgrey} Down:${color}${downspeedf wlp3s0} KB/s${alignr}${color lightgrey}Up:${color}${upspeedf wlp3s0} KB/s
${color #000000}${downspeedgraph wlp3s0 12,140 000000 FFEF00}${alignr}${color #000000}${upspeedgraph wlp3s0 12,140 000000 FFEF00}
${color lightgrey} Total: $color${totaldown wlp3s0}${alignr}${color lightgrey}Total: ${color}${totalup wlp3s0}

${color lightgrey}Wireless Bitrate: ${color}${wireless_bitrate wlp3s0}${color lightgrey} | ${color lightgrey}${alignr}Signal Quality:${color}${wireless_link_qual_perc wlp3s0}%
${color #656565}$stippled_hr$color
${alignc}${color}${execi 1000 cat /proc/cpuinfo | grep 'model name' | sed -e 's/model name.*: //'| uniq}
${alignc}${color #000000}${cpugraph 13,318 000000 FFEF00}

${color lightgrey}Total CPU Usage: ${color}${cpu cpu0}%${alignr}${color lightgrey}| ${color lightgrey}CPU Temperature: ${color}${hwmon 1 temp 1}°C

${color lightgrey} C1: ${color}${cpu cpu1}% ${color lightgrey}@ ${color}${freq 1} MHz${color #FFEF00}${alignr}${color lightgrey}C2: ${color}${cpu cpu2}% ${color lightgrey}@ ${color}${freq 2} MHz
${color #FFEF00}${cpubar cpu1 6,150}${alignr}${color #FFEF00}${cpubar cpu2 6,150}
${color lightgrey} C3: ${color}${cpu cpu3}% ${color lightgrey}@ ${color}${freq 3} MHz${color #FFEF00}${alignr}${color lightgrey}C4: ${color}${cpu cpu4}% ${color lightgrey}@ ${color}${freq 4} MHz
${color #FFEF00}${cpubar cpu3 6,150}${alignr}${color #FFEF00}${cpubar cpu4 6,150}
${color #656565}$stippled_hr$color
${alignc}${color lightgrey}Resources

${color lightgrey}Ram ${alignc} ${color}$mem${color lightgrey} / ${color}$memmax ${alignr}${memperc}% Used
${color #FFEF00}${membar 6,318}
${color lightgrey}Swap ${alignc} ${color}${swap}${color lightgrey} / ${color}${swapmax} ${alignr}${swapperc}% Used
${color #FFEF00}${swapbar 6,318}
${color lightgrey}$fs_type ${alignc} ${color}${fs_used}${color lightgrey} / ${color}${fs_size} ${alignr}${fs_used_perc /}% Used
${color #FFEF00}${fs_bar 6,318 /}
${color lightgrey}Disk Read IO: $color${diskio_read}${alignr}${color lightgrey}Disk Write IO: ${color}${diskio_write}
${color #000000}${diskiograph_read 12,145 000000 FFEF00}${alignr}${color #000000}${diskiograph_write 12,145 000000 FFEF00}
${color #656565}$stippled_hr$color
${alignc}${color lightgrey} Processes

${color lightgrey}Processes: ${color}$running_processes${color lightgrey} / ${color}$processes${alignr}${color lightgrey}Threads: ${color}$running_threads${color lightgrey} / ${color}$threads

${color lightgrey} PID Process${alignr}Memory CPU
${color}${top pid 1} ${top name 1}${alignr}${top mem_res 1} ${top cpu 1}%
${color}${top pid 2} ${top name 2}${alignr}${top mem_res 2} ${top cpu 2}%
${color}${top pid 3} ${top name 3}${alignr}${top mem_res 3} ${top cpu 3}%
${color}${top pid 4} ${top name 4}${alignr}${top mem_res 4} ${top cpu 4}%
${color}${top pid 5} ${top name 5}${alignr}${top mem_res 5} ${top cpu 5}%
${color}${top pid 6} ${top name 6}${alignr}${top mem_res 6} ${top cpu 6}%
${color}${top pid 7} ${top name 7}${alignr}${top mem_res 7} ${top cpu 7}%
${color}${top pid 8} ${top name 8}${alignr}${top mem_res 8} ${top cpu 8}%
${color}${top pid 9} ${top name 9}${alignr}${top mem_res 9} ${top cpu 9}%
${color}${top pid 10} ${top name 10}${alignr}${top mem_res 10} ${top cpu 10}%
${color #656565}$stippled_hr$color
]]

And that work that fine, without both problems.
I just change

own_window_type = 'dock',
......................................
own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

**Comment by MavropaliasG** [comment]
@dbriba thank you very much, that indeed works but now there is a different problem. If I click on conky and I switch desktop (linux distros usually have different desktops/workspaces ) then the conky is on the other window and not anchored to the desktop. I have put a screenshot to show you.

![screenshot_20170630_135308](https://user-images.githubusercontent.com/13523909/27722656-77686204-5d9b-11e7-97ee-f66529d0fd82.jpeg)

**Comment by dbriba** [comment]
If you want conky only on one desktop you must modified this line : 
own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
to
own_window_hints = 'undecorated,below,skip_taskbar,skip_pager',

But you can't choose the desktop, conky will be on the first desktop.

**Comment by MavropaliasG** [comment]
Hey @dbriba, removing the 'sticky' arguement did not fix it. Instead I experimented and found that switching the 'dock' to 'normal' in own_window_type fixed the problem. Thank you for your help !

**Comment by dbriba** [comment]
Ok if all work fine, it's good for you.
