### ISSUE TITLE
Conky Causing Ghosting of desktop in Ubuntu 17 /w Virtualbox

### ISSUE THREAD

**Issue by DarkNemie** [brndnmtthws/conky#389]
Running latest build of Ubuntu 17 in Virtualbox on a host machine of Windows 10 Pro. 
System specs:
Intel I7 - 4770k GHZ
Asus Sabertooth z87 MB
16gb hyperx ddr3 1866
Radeon R9 270X 4 gb
Samsung 250gb SSD

Virtual box version 5.1.20

Desktop and Ubuntu run fine with no graphical issues until Conky is launched - then windows render fine and so does conky but the rest of the desktop will ghost windows when you move them and smear - they never recover back to the desktop as it should. 
My Conky File is basic default with the exception of double buffer enabled and colors changed.
below is my Conky file:
-- vim: ts=4 sw=4 noet ai cindent syntax=lua

conky.config = {
	double_buffer = true,
    alignment = 'bottom_left',
    background = true,
    border_width = 1,
    cpu_avg_samples = 2,
	default_color = 'Blue',
    default_outline_color = 'Blue',
    default_shade_color = 'Blue',
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    use_xft = true,
    font = 'DejaVu Sans Mono:size=10',
    gap_x = 5,
    gap_y = 60,
    minimum_height = 5,
	minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_stderr = false,
    extra_newline = false,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    show_graph_scale = false,
    show_graph_range = false
}

conky.text = [[
${scroll 16 $nodename - $sysname $kernel on $machine | }
$hr
${color blue}Uptime:$color $uptime
${color blue}Frequency (in MHz):$color $freq
${color blue}Frequency (in GHz):$color $freq_g
${color blue}RAM Usage:$color $mem/$memmax - $memperc% ${membar 4}
${color blue}Swap Usage:$color $swap/$swapmax - $swapperc% ${swapbar 4}
${color blue}CPU Usage:$color $cpu% ${cpubar 4}
${color blue}Processes:$color $processes  ${color grey}Running:$color $running_processes
$hr
${color blue}File systems:
 / $color${fs_used /}/${fs_size /} ${fs_bar 6 /}
${color blue}Networking:
Up:$color ${upspeed eth0} ${color grey} - Down:$color ${downspeed eth0}
$hr
${color blue}Name              PID   CPU%   MEM%
${color lightblue} ${top name 1} ${top pid 1} ${top cpu 1} ${top mem 1}
${color lightblue} ${top name 2} ${top pid 2} ${top cpu 2} ${top mem 2}
${color lightblue} ${top name 3} ${top pid 3} ${top cpu 3} ${top mem 3}
${color lightblue} ${top name 4} ${top pid 4} ${top cpu 4} ${top mem 4}
]]

**Comment by lasers** [comment]
Hi. Some forum suggested `window_type = 'normal'`. See if that does anything for you. Are you still having this problem or have you moved on to different tools? Let me know. Thanks. I'd double check with Virtualbox help too to determine if it's something caused by `conky` or `Virtualbox`. Thanks.

**Comment by lasers** [comment]
One month later and no response. I think we're done here.

Sorry about the issue and thanks for the report. Keep them coming. :+1:
