### ISSUE TITLE
zfs/zpool support plus "bar" and "graph" commands.

### ISSUE THREAD

**Issue by mwm** [brndnmtthws/conky#390]
Just changed everything, so I'm now looking at conky. I wanted to use it to monitor space on my zfs pools. So that's the first request - add hooks for getting status information from zpool & zfs. Looks like you want to use libzfs & libzpool, but I'm not sure.

So I implemented it with execp. The specifc line is:
```
 ${execp zpool list -Ho name,allocated,size,capacity | awk '{ print "${color1} " $1 " ${color}" $2 "/" $3 " ${execbar echo " $4 "}" }'}
```

Note that `${execbar echo  ...` in the output.  I'm outputting code with conky formatting in it, and having conky do a second fork of echo was the only way I could see to have it format a bar using the value I had at hand. Would be nice if I could have just done `${bar ...` instead. I have similar code using execgraph.

**Comment by Alkeryn** [comment]
i did that personally 
```
${goto 50}${font Conky Icons by Carelli:size=12}M ${font}${goto 70}Stock:${goto 140}${execbar 7,75 df | awk /stock/'{x+=$3;y=x/(x+$4)*100} END {print int(y)}'}${goto 225}${exec df | awk /stock/'{x+=$3;y=x/(x+$4)*100} END {print int(y)}'}% ${fs_free /run/media/alkeryn/Stock}
```
