### ISSUE TITLE
own_window_colour doesn't work if XDBE is off.

### ISSUE THREAD

**Issue by mwm** [brndnmtthws/conky#391]
Building the current source tree with default configuration results in a version that doesn't honor own_window_colour. Running ccmake and changing BUILD_XDBE from OFF to ON  creates a binary that works fine.

I'm using Ubuntu 16.10, and uname says:
> Linux chokfi.mired.org 4.8.0-51-generic #54-Ubuntu SMP Tue Apr 25 16:32:21 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by lasers** [comment]
1 year 3 months passed. Can you paste your conky config? I'm unable to print red `own_window_colour` with either flag. Is the problem still same for you or did something changed? Thanks.

**Comment by lasers** [comment]
Okay. Apparently, I did something wrong earlier. I tried this with `BUILD_XDBE=ON` and `BUILD_XDBE=OFF`. Both gave me what I want. We need `own_window = true` in the config too.

Here's a catch... I find that if we don't use quotes for `own_window_colour`... with either flag, we will get black window instead of `red` ~~herring~~ window.  It has been like this since `v1.10.7`. I'm unable to `cmake` earlier.
```
own_window_colour=red  # bad
own_window_colour='red'  # good
own_window_colour=ff0000  # bad
own_window_colour='ff0000'  # bad
```
What do you want to do here? @brndnmtthws

**Comment by lasers** [comment]
@su8 Can you test this too?

**Comment by lasers** [comment]
@su8 Same here. I tried fewer older tags too just in case. I can't reproduce this. Can `own_window_colour` take `#hex_value`?

**Comment by su8** [comment]
>Can own_window_colour take #hex_value

I tried both **red** and **ff0000** hex value and it accepted both red colors.

**Comment by lasers** [comment]
**#ff000**

**Comment by su8** [comment]
Same, it works.

**Comment by lasers** [comment]
**#f9c** works too... The documentation specifically say this...

>**own_window_colour colour**
If own_window_transparent no, set a specified background colour (defaults to black).
 Takes either a hex value **(e.g. ffffff, note the lack of '#')** or a valid RGB name (see /usr/lib/X11/rgb.txt)

I guess we'll have to update the documentation. :confused:

**Comment by lasers** [comment]
@su8 Thanks for testing this too. :heart_eyes: **Conclusion:** We didn't find anything.
