### ISSUE TITLE
top and top_mem became useless after introducing multi-process applications

### ISSUE THREAD

**Issue by riprop** [brndnmtthws/conky#392]
Hi,
after multi-process apps becoming frequently used (like Chrome, Slack, Nozbe,... soon Firefox to fallow with e10s) top and top_mem are became useless. List of top (CPU or RAM) applications became crowded with process not showing relevant information at all. For example if Chrome have 10 or more process they will occupy whole top/top_mem list so other programs will not be shown on the list, and moreover you can't even read how much RAM/CPU Chrome is using (you have to sum manually which is impossible for 10+ fast changing processes).

New multi-process reality should be supported by Conky also.

Solution is to update top and top_mem (or introduce new commands) to  show SUM of CPU/RAM for all processes of same program, not for every process.

Thank you

**Comment by 20NE** [comment]
love conky, still
