### ISSUE TITLE
Wait curl response

### ISSUE THREAD

**Issue by ialert** [brndnmtthws/conky#393]
I have a code that obtains weather conditions and saves it to cache file, like this:

`${execi 300 curl -s "http://weather.url/" -o ~/.cache/forecast.xml}`

And command that prints result:

`${execi 300 awk -F'[<|>]' '/tmp>/{print $3}'  ~/.cache/forecast.xml}`

At the first launch, conky doesn't wait for curl response and print empty string.I need command that waits curl response and only then prints result.Is it possible? Thanks in advance!

**Comment by dbriba** [comment]
I had same problem with my conky weather, I solve that by launching my curl command before launch conky.
I use Fedora with kde, and I have a script that launch my conky.
I add the curl command on top of the script, and launch curl command with sleep, like this : 

#!/bin/bash
curl -s "http://weather.url/" -o ~/.cache/forecast.xml
sleep 5
conky -c /path/of/my/conky

**Comment by ialert** [comment]
dbriba, thank you, I did it. I wish there was builtin way.
