### ISSUE TITLE
Conky 1.10 not compatible with Cairo binding

### ISSUE THREAD

**Issue by vlaze** [brndnmtthws/conky#394]
I know this is a common issue, but I still haven't found any solution for it here. The steps are simple:

1. Clone this repo, create a directory called `build` and cd into it.

2. Run `ccmake ..` and select Cairo as a binding for your Conky build.

3. Enjoy the error. Joke. I personally got 'Unable to find Lua 5.1.x', which kicked me out of the installation.

The main problem here is that I do have both Lua 5.1 and 5.3 installed (I use AwesomeWM so 5.3 is fully working), but somehow the compilation process won't detect 5.1. I have tried to workaround this problem by modyfing `cmake/ConkyPlatformChecks.cmake` as it follows:

```
# Check for Lua itself
if(WANT_TOLUA)
        # If we need tolua++, we must compile against Lua 5.1
#       pkg_search_module(LUA REQUIRED lua5.1 lua-5.1)
#       if(NOT LUA_VERSION VERSION_LESS 5.2.0)
#               message(FATAL_ERROR "Unable to find Lua 5.1.x")
##      endif(NOT LUA_VERSION VERSION_LESS 5.2.0)
#else(WANT_TOLUA)
        # Otherwise, use the most recent Lua version
        #pkg_search_module(LUA REQUIRED lua>=5.3 lua5.3 lua-5.3 lua53 lua5.2 lua-5.2 lua52 lua5.1 lua-5.1 lua51 lua>=5.1)
        pkg_search_module(LUA REQUIRED lua5.3 lua-5.3 lua5.2 lua-5.2 lua>=5.1 lua51 lua5.1 lua-5.1)
endif(WANT_TOLUA)
```

This will build 'correctly': no errors, successful make and make install, and `conky -v` showing Cairo (and only Cairo) as a binding. However, trying to execute any file that requires Cairo wil result in a segfault.

I am using the latest release of this repo, in case that helps.

**Comment by plikhari** [comment]
Hi :-)

You have posted this issue #263 - and there you state you are also using Arch Linux - which is what I am using as well.

I had given a snippet in that issue and how to resolve and build. You do not need to change anything within the configuration files.

On Arch we have `AUR` build system which uses `makepkg` program and `PKGBUILD` config file. 

I am using current conky git version with tolua++ patched for lua 5.3 and using lua 5.3 - so you know it  works. You can get the [conky-cairo](https://aur.archlinux.org/packages/conky-cairo/) and [tolua++_5.3](https://aur.archlinux.org/packages/tolua++_5.3/) from Arch Linux AUR.

Basically uou need to communicate to cmake - where are the lua libraries etc. So to take an example from the `PKGBUILD` - in a bash script - you need to add these. 

```
	LDFLAGS="-llua5.1 -lm" 
	
	LUA_CFLAGS="-I/usr/include/lua5.1"

	cmake \
		-D CMAKE_BUILD_TYPE=Release \
		-D CMAKE_C_FLAGS="${LUA_CFLAGS}" \
		-D CMAKE_CXX_FLAGS="${LUA_CFLAGS}" \
		-D CMAKE_EXE_LINKER_FLAGS="${LDFLAGS}" \
		-D CMAKE_INSTALL_PREFIX=/usr \
		-D BUILD_WLAN=ON \
		-D BUILD_CURL=ON \
		-D BUILD_RSS=ON \
		-D BUILD_XDBE=ON \
		-D BUILD_IMLIB2=ON \
                -D BUILD_ICONV=ON \
		-D BUILD_WEATHER_METAR=ON \
		-D BUILD_WEATHER_XOAP=ON \
                -D BUILD_LUA_CAIRO=ON \
                -D BUILD_LUA_IMLIB2=ON \
                -D BUILD_LUA_RSVG=ON \
		-D BUILD_NVIDIA=ON \
		.

	make 
```

There will be some dependencies ::
```
'alsa-lib' 'libxml2' 'curl' 'cairo' 'wireless_tools' 'libxft' 'librsvg' 'glib2' 'libxdamage' 'imlib2' 'lua51'
```
Now before you actually do the make command you will to ensure you have `tolua++` installed and `libxnvctrl` if you need Nvidia support

By the way - I am unable to preview this message in github editor - so lets see ;-)

**Comment by vlaze** [comment]
Seems that downloading from the AUR worked perfectly! I haven't had time to test it in depth, though, so with your permission I'll leave this issue open for a few days in case something happens. Thank you so much!

**Comment by plikhari** [comment]
No worries - see - now you are ahead of the pack - using conky with lua 5.3 ;-)

**Comment by lasers** [comment]
>@vlaze I'll leave this issue open for a few days in case something happens.

Uh... About that... It has been 1 year 2 months 23 days already. I'll close this on your behalf. Thanks.
