### ISSUE TITLE
One line text vertical alignment

### ISSUE THREAD

**Issue by theo-m** [brndnmtthws/conky#400]
Hello,

I'm having an issue with a single line conky file (as in a bar like setup), here is the phenomenon:
![screenshot from 2017-07-14 16-40-24](https://user-images.githubusercontent.com/17948980/28230046-6058b370-68b3-11e7-9902-f751b2c5134d.png)

Here is the code:
```lua
conky.config = {
    alignment = 'top_middle',
    
    background = true,
    
    border_outer_margin = 0,
    border_inner_margin = 20,
    
    draw_borders = true,
    border_width = 3,
    default_color = grey,
    stippled_borders = 0,
    
    cpu_avg_samples = 2,
    
    draw_graph_borders = false,
    draw_outline = false,
    draw_shades = false,
    double_buffer = true,
    extra_newline = false,
    
    gap_x = 0,
    gap_y = 60,
    
    no_buffers = true,
    out_to_console = false,
    out_to_stderr = false,
    
    own_window = true,
    own_window_class = 'Conky',
    own_window_transparent = false,
    own_window_argb_visual = false,
    own_window_argb_value = 0,
    own_window_colour = "#e4e4e4",
    own_window_type = "override",
    own_window_hints = 'below',
    
    short_units = true,
    update_interval = 3,
    uppercase = false,

    use_xft = true,
    font = 'Roboto Mono:size=8',

    use_spacer = 'right',
    
    show_graph_scale = false,
    show_graph_range = false,

    color1 = '888',
    color2 = '666'
}

conky.text = [[
# ${alignc}${exec /home/theo/.local/bin/win-info | tail -n 1}
${color1}${font FontAwesome:size=12}  ${font}${exec amixer -c 0 get Master | grep -Po "Mono: Playback .* \[\K\w+"}:${color2}${exec amixer -c 0 get Master | grep -Po "Mono: Playback \d+ \[\K\d{2}"}%   |   ${color1}${font FontAwesome:size=12}${font} :${color2}${exec /home/theo/.local/bin/win-info | head -n 1 | wc -w}   |   ${color1}${font FontAwesome:size=12} ${font}: ${color2}$cpu%   |   ${color1}${font FontAwesome:size=12} ${font}: ${color2}$mem ${offset 240}${alignr}${color2}${wireless_essid}  ${color1}${font FontAwesome:size=12}${font}   |   ${color2}${time %H:%M} ${color1}${font FontAwesome:size=12}${font}    |   ${color2}${time %d/%m} ${color1}${font FontAwesome:size=12}${font}   |   ${color2}${battery} ${color1}${font FontAwesome:size=12} 
]]
```

Looking for some help as I can't see what led to that. This is font independant.

Thanks

**Comment by okraits** [comment]
+1

**Comment by Popkultur** [comment]
hi, I have the same issue, same font. I see it is not possible to align it exactly just by font sizes. So maybe an option where you can set the line-height oder valign of lines might help?

**Comment by easysid** [comment]
You need to use `${voffset}` to align things in a single line while using different fonts. Everytime you change the font, it changes the height and spacing, and gives a casacading effect where text keeps dropping down.

- method 1 - use `${voffset}` anytime a font is changed
- method 2 - write all the info you can using a single font, _then_ change the font, and use `${goto}` to go go back and insert icons in the proper place. 

This is how it looks after properly using `${voffset}`
![Fixed conky](https://i.imgur.com/pFVc7lK.png)

**Comment by lasers** [comment]
Nice job with the bar. Seems like we're done with this issue now. Closing this. Thanks.
