### ISSUE TITLE
Conky would install but wouldn't run after upgrading to a new version

### ISSUE THREAD

**Issue by sdban** [brndnmtthws/conky#401]
I upgraded from Version 1.9. 
Here is my `conky -v'
<pre><code>
conky 1.10.5_pre compiled Sat Jul 15 04:19:44 IDT 2017 for Linux 4.4.0-85-generic x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/local/lib/conky

 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * support for IBM/Lenovo notebooks
  * builtin default configuration
  * old configuration syntax
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * MPD
  * MOC

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/local/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256
</pre></code>

I changed my `conkyrc`
Here it is:
<pre><code>

conky.config = {
background = false,
font = 'Inconsolata:size= 12',
use_xft = true,
xftalpha = 0.9,
update_interval= 2.0,
total_run_times= 0,
own_window= true,
own_window_class = 'Conky',
own_window_type = 'normal',
own_window_argb_visual= true,
own_window_transparent = true,
own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
double_buffer = true,
minimum_height = 180,
minimum_width = 5,
maximum_width = 200,

draw_shades= false,
draw_outline =false,
draw_borders =false,
draw_graph_borders =true,
default_color ='cccccc',
default_outline_color= 'green',
alignment ='top_right',
gap_x=  12,
gap_y= 35,
no_buffers= true,
uppercase= false,
cpu_avg_samples= 4,
override_utf8_locale = false,
uppercase =false,
format_human_readable= true
}

conky.text = [[
CPU: ${alignr}${freq} MHz
Core 1 ${alignr}${cpu cpu1}%
${cpubar 4 cpu1}
Core 2 ${alignr}${cpu cpu2}%
${cpubar 4 cpu2}
Core 3 ${alignr}${cpu cpu2}%
${cpubar 4 cpu3}
Core 4 ${alignr}${cpu cpu2}%
${cpubar 4 cpu4}
${top name 1}$alignr${top cpu 1}
${top name 2}$alignr${top cpu 2}
${top name 3}$alignr${top cpu 3}
${top name 4}$alignr${top cpu 4}
-- ${top name 5}$alignr${top cpu 5}

RAM: ${alignr}$memmax
${membar 4} ${alignr}
Memory: ${alignc}$mem ${alignr}$memperc%
Swap : ${alignc}$swap ${alignr}$swapperc%

${top_mem name 1}$alignr${top_mem mem 1}
${top_mem name 2}$alignr${top_mem mem 2}
${top_mem name 3}$alignr${top_mem mem 3}
${top_mem name 4}$alignr${top_mem mem 4}
-- ${top_mem name 5}$alignr${top_mem mem 5}

Filesystem:
Root: ${alignr}${fs_used /} / ${fs_size /}
${fs_bar 4 /}
Home: ${alignr}${fs_used /home} / ${fs_size /home}
${fs_bar 4 /home}

Network: ${alignr}(${addr wlan0})
Down: ${downspeed wlan0}/s ${alignr}(${totaldown wlan0})
${downspeedgraph wlan0 000000 775555}
Up: ${upspeed wlan0}/s ${alignr}(${totalup wlan0})
${upspeedgraph wlan0 000000 557755}$color

Battery: ${alignr}$battery_percent

${alignr}conky:$conky_version 
]]
</pre></code>

The problem I keep getting repeatedly is:
<pre><code>
conky: desktop window (a0001b) is subwindow of root window (d5)
conky: window type - normal
conky: drawing to created window (0x2a00002)
conky: drawing to double buffer
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  62 (X_CopyArea)
  Serial number of failed request:  165
  Current serial number in output stream:  168
</pre></code>

**Comment by dbriba** [comment]
I test your conky 1.10 config and that work for me without error.
Here my conky -v:

dominique@host-192-168-1-2 ~$ conky -v
conky 1.10.6_pre compiled Mon Feb 20 15:37:19 UTC 2017 for Linux 4.9.3-200.fc25.x86_64 x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib64/conky


 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * RSS
  * Weather (METAR)
  * Weather (XOAP)
  * wireless
  * support for IBM/Lenovo notebooks
  * old configuration syntax
  * Imlib2
  * apcupsd
  * iostats
  * Internationalization support
  * Debugging extensions

 Lua bindings:
  * Cairo
  * Imlib2
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * MPD

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256

**Comment by sdban** [comment]
I am not sure what the problem is. I had conky 1.9 version and that worked flawlessly. I upgraded to conky 1.10 did necessary changes (changing conykrc) and not it crashed midway. I tried different versions from repo and also by using cmake. Nothing. 

If there is any information that I can present please let me know.

**Comment by lasers** [comment]
@sdban What about now? Your config worked okay for me.

**Comment by lasers** [comment]
>@sdban I upgraded from Version 1.9.

Okay. This issue is old.

>@sdban Here is my `conky -v'
>>conky 1.10.5_pre compiled Sat Jul 15 04:19:44 IDT 2017...

Okay. This issue is still old.

>@lasers:  @sdban What about now? Your config worked okay for me.

Okay. This config is still working.

![2018-08-30-060439_210x798_scrot](https://user-images.githubusercontent.com/852504/44848006-cb9d2200-ac1a-11e8-8b4d-9a043889cc6e.png)

>@sdban I changed my conkyrc
>Here it is:
>
>```
>conky.config = {
>    ...
>    ...
>    ...
>    own_window_argb_visual= true,
>    double_buffer = true,
>    ...
>    ...
>    ...
>```

Okay. This issue is most likely solved by https://github.com/brndnmtthws/conky/pull/383.
