### ISSUE TITLE
github variables and configuration page on github partially readable

### ISSUE THREAD

**Issue by erikdubois** [brndnmtthws/conky#403]
no bug report but a request. 
Writing a tutorial about conky's and referring to your github, I could not help but notice we can only see part of the last column.
http://erikdubois.be/how-to-change-the-conkys-in-archlabs/
Could you consider finding a way to provide us all the info that is here online.
A pdf would be awesome.
![2017-07-18-1500361478_screenshot_3840x1080](https://user-images.githubusercontent.com/10594806/28304568-7f62699a-6b98-11e7-883e-41960d443548.jpg)

**Comment by LCWilliams** [comment]
## Conky Website
The conky website actually has what you're looking for, and while not presented in the most graphically pleasing way, still works:
**Variables:** http://conky.sourceforge.net/variables.html
**Settings:** http://conky.sourceforge.net/config_settings.html

## Additional Website
There's also a website by Casey Sprangel that has them both plus more on a single page:
http://www.ifxgroup.net/conky.htm

**Comment by lasers** [comment]
>Could you consider finding a way to provide us all the info that is here online.

Here you go. http://manpages.ubuntu.com/manpages/latest/en/man1/conky.1.html

>A pdf would be awesome.

You can convert man pages to PDFs. `$ man -t conky | ps2pdf - conky.pdf`

I hope this is sufficient. Thanks. Closing.
