### ISSUE TITLE
DPI issues

### ISSUE THREAD

**Issue by Vladimir-csp** [brndnmtthws/conky#407]
Hi!
I have a question: 
Conky's priority of getting DPI setting seems to be this: fontconfig, xrdb, randr. Was it based on something? How was it chosen?

And also a request:
Please give conky the ability to apply new DPI, either automatically when it changes (if possible) or on receiving SIGUSR1/SIGHUP. It isn't very handy to kill and restart conky every time a display with different dimensions is connected.

**Comment by Vladimir-csp** [comment]
Dunst [is going to get](https://github.com/dunst-project/dunst/pull/608) this ability in next release, it changes DPI on the fly.

**Comment by LinuxOnTheDesktop** [comment]
Hello. Where are we with this, please? Here is why I ask.

I run Conky on a Linux Mint Cinnamon system that uses Hi-DPI. All was working. Then I created a new user, logged into the new user (graphically), and ran Conky but using my old Conky config. And now everything in Conky is much too large. The only way that I have found to get my Conky back to how it should look is by using a Cinnamon GUI to turn off the hi-DPI scaling. In all this, the Conky version that I am using is 1.12.2_pre.

**Comment by Caellian** [comment]
> Conky's priority of getting DPI setting seems to be this: fontconfig, xrdb, randr. Was it based on something? How was it chosen?

Conky only uses Xft.dpi from xrdb AFAICT. I added a fallback on `screen_width *  25.4 / screen_width_in_mm` when Xft is disabled. Those two are pretty standard.

XRandR isn't handled by conky, and it's a lot of work adding support for it by the looks of things.
