### ISSUE TITLE
'if_match ${wireless_link_qual_perc' fails occasionally

### ISSUE THREAD

**Issue by CottonEaster** [brndnmtthws/conky#409]
&nbsp;&nbsp;&nbsp;&nbsp;'if_match ${wireless_link_qual_perc' fails occasionally - I think when the network is coming up. To be more specific about the problem (as against when it occurs):

`${if_match ${wireless_link_qual_perc wlan0`}>70}\

returns an error to the effect that `wireless_link_qual_perc wlan0` is a string (!); and the condition seems to get evaluated as false. (Though I'll have to wait until the next time the situation occurs to be sure.)

&nbsp;&nbsp;&nbsp;&nbsp;*A related problem* is that, when the foregoing situation occurs - i.e. `wireless_link_qual_perc` gets the wrong type of value - the following condition is satisfied:

`${if_up wlan0}\`

I have `if_up_strictness` set to "`address"`.

&nbsp;&nbsp;&nbsp;&nbsp;**To sum up / clarify** - my Conky contains (among other code) the following.

```
${if_up wlan0}\
# WLAN 0
${if_match ${wireless_link_qual_perc wlan0}>70}\
```
The first line evaluates as true when, it seems, the network has not finished coming up; and when that situation obtains, the third line throws an error.

&nbsp;&nbsp;&nbsp;&nbsp;'All of this makes my Conky behaviour a bit erratic and I've had to build in checks to work around the problems.

**Conky 1.10.6-1. Linux Mint 18.2 x64.**

**Comment by su8** [comment]
Add **sleep** in there, that's how I use wpa supplicant with bringing my firewall up

**Comment by CottonEaster** [comment]
Thanks, su8. But just what exactly are you proposing? If I am to have a delay between the `if_up` and the `if_match`, then I would need to use a script, that Conky runs on a timer. And I've got _lots_ of those - scripts run by Conky - already; I have _enough_ of them already!

**Comment by lasers** [comment]
Hi. You closed an issue not long ago. Does this issue still stand today?

**Comment by CottonEaster** [comment]
Ah. No. Closing. Thanks.
