### ISSUE TITLE
conky ignores xinerama_head on e17

### ISSUE THREAD

**Issue by dgiglio** [brndnmtthws/conky#410]
Conky always appears on the same monitor despite of the value of xinerama_head. But it only happens on E17, in XFCE4 it works correctly.

**Comment by mk-fg** [comment]
Have bumped into what looks like same issue, also with enlightenment window manager and mismatched monitor resolutions.
Currently tested 4 corner aligment options, and issue only manifests with top_right and bottom_right options - bottom_left and top_left work as expected.

Using current-git version and default conky.conf with added `xinerama_head = 1` option
- `alignment = top_left` (works as expected) - https://i.imgur.com/tpZys8U.jpg
- `alignment = top_right` (wrong display/position) - https://i.imgur.com/Z5bwSXw.jpg

In the second case, conky seem to be calculating correct position within smaller right monitor (1280x1024), but then uses that position to place window on wrong monitor (left one, 1080p).

xrandr output for my hardware/xorg configuration:
https://gist.github.com/mk-fg/c1f2fdaa955d4fe63efb62e81768509e

This is the issue with head/alignment I've mentioned in #613 and seem to be also quite similar to #430 (where top_left works fine on non-primary display, but other alignments do not).

**Comment by mk-fg** [comment]
Also of note - don't think I am using xinerama extention at all - it's not in Xorg.conf (which only have ServerFlags in there) and it is not mentioned in E (enlightenment) configuration anywhere (though then neither is RandR).
xrandr display setup (in the gist above) is done by E, which sets monitor resolutions and positions on start or hotplug according to its configuration (generally done via GUI applet).

xdpyinfo reports that xinerama extension is supported on the server though:
https://gist.github.com/042be0d6d20c0f064d3c411c1805acbc

**Comment by mk-fg** [comment]
Highlighted where window position seem to be calculated incorrectly in such monitor configurations in #615, with potential fix which works in my case, though not sure if it handles all possible build/config/setup variants, as I don't understand reasoning behind code that was there previously.

**Comment by lasers** [comment]
Hi @dgiglio, could you see if #615 solves your issue? Thank you.

**Comment by lasers** [comment]
Closed via https://github.com/brndnmtthws/conky/pull/615
