### ISSUE TITLE
'Traps' / 'general protection ip' error

### ISSUE THREAD

**Issue by CottonEaster** [brndnmtthws/conky#411]
&nbsp;&nbsp;&nbsp;&nbsp;My Conky crashes - disappears - occasionally. My systemlog contains the following.

`traps: conky[3786] general protection ip:30e2c4ecc0 sp:7fff40b4a120 error:0 in libc-2.23.so[30e2c00000+1c0000]`

&nbsp;&nbsp;&nbsp;&nbsp;I built Conky from source, using the github code, but the disappearing problem predated that; it was because of that problem that I tried the github code (as against the version of Conky in my distribution's repositories).

```
Linux Mint 18.2 x64 Cinnamon.
Kernel: 4.11.0-14-generic

$ conky --version
conky 1.10.7_pre compiled Thu 10 Aug 11:34:53 BST 2017 for Linux 4.11.0-13-generic x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/local/lib/conky


 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * wireless
  * builtin default configuration
  * old configuration syntax
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/local/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256
```

**Comment by CottonEaster** [comment]
I'd like to add that I still have this problem - on two computers.

I've found [a similar crash report](https://ubuntuforums.org/showthread.php?t=1884584), on the same distribution as my computers, but from years ago.

**Comment by lasers** [comment]
A year passed. Are you still experiencing this issue? It looks like something `libc` would do. `$ man libc`

**Comment by CottonEaster** [comment]
No, I no longer have the problem, thank you.
