### ISSUE TITLE
Installation documentation

### ISSUE THREAD

**Issue by b-fg** [brndnmtthws/conky#413]
I tried to install the latest conky version compiling the source package a few days ago by following the installation documentation included in the package. Looks like this documentation is quite old as conky does not use automake and autoconf for cmake anymore.
I then opened [this thread](https://askubuntu.com/questions/945781/problem-installing-conky-package-configure-not-found) in askubuntu on SE.
Even though this is correctly explained in the wiki it would be useful too to include the updated documentation in the package itself.

**Comment by Pawamoy** [comment]
It's also available in the wiki: https://github.com/brndnmtthws/conky/wiki/Installation

But it would be good to also include that in the INSTALL document, or the README.cmake one, indeed.

**Comment by lasers** [comment]
INSTALL documentation has been removed recently (388f47f20ee349bca5d6d75fef57e78186cf0e1d) in favor of the wiki link above. Closing.
