### ISSUE TITLE
Most ${mpd_*} commands don't work from Lua conky_parse() function

### ISSUE THREAD

**Issue by fictionic** [brndnmtthws/conky#414]
First, commands like `${mpd_length}` and `${mpd_elapsed}`, and `${mpd_vol}`,  give wildly inaccurate answers--seems like an overflow issue.

Worse, many of the commands simply return an empty string. This includes all the tag info and `${mpd_file}`.

**Comment by lasers** [comment]
Hi there. It has been almost a year now. Is this still happening for you? My findings today is not same here. From what I gather, `conky` have an unspecified interval so it can be fluid... based on the supplied variables/objects. Yes, it can be several seconds late.

However, if you add `update_interval=1` to `conky.config ={}`, then it's always right on time. Maybe slightly earlier than other mpd clients. All of mentioned variables works for me with a randomly selected mp3. Can you recheck with your findings again and see where we stand now?

I don't know about unmentioned mpd variables + empty strings though. Maybe mp3 does not have anything to offer. Either way, we'll see. Thanks.

**Comment by fictionic** [comment]
Hey, you're right. It all seems to be resolved now. Thanks for the heads up!
