### ISSUE TITLE
1.10 syntax: Inconsistent comment characters

### ISSUE THREAD

**Issue by reprise5** [brndnmtthws/conky#415]
*  In relation to configuration/runtime files:
    *  `conky.config = { settings here };` section takes comments using a -- mark like in Lua, however 
    *  in the `conky.text = [[text and settings]];` section I have found that conky prints -- marks and the text following.  Using the '#' Marks like in 1.9 runtime configurations seem to function as the comment character.  

Was this intentional? It would mean there are two different comment marks in the same document. I would think this is an oversight because it's not consistent with the rest of the syntax update.

**Comment by pawamoy** [comment]
Yup, had to escape `#` in outputs of scripts used with `execp`, `execpi`, `texecpi` etc. Also I would like to be able to comment things in `conky.text = [[ ]]`.
