### ISSUE TITLE
conky: unknown variable '$image'

### ISSUE THREAD

**Issue by a11g0rhythm** [brndnmtthws/conky#418]
Version
conky 1.10.6 compiled Fri Dec  9 23:23:19 UTC 2016 for Linux 4.4.0-53-generic x86_64

Problem:
when I add 
${image /home/mariusz/Pulpit/12.png -p 20,20 -s 200x200} 
to config
conky screem:
unknown variable '$image'

**Comment by dbriba** [comment]
You say :
"when I add
${image /home/mariusz/Pulpit/12.png -p 20,20 -s 200x200}
to config"

You add this in the "conky.config = {" section ?
It's not that.
you must add your line in the "conky.text = [[" section.

**Comment by reprise5** [comment]
What version are you using?
Type ` conky --version` in the terminal

**Comment by a11g0rhythm** [comment]
conky --version 
`conky 1.10.6 compiled Fri Dec  9 23:23:19 UTC 2016 for Linux 4.4.0-53-generic x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky


 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * wireless
  * support for IBM/Lenovo notebooks
  * builtin default configuration
  * old configuration syntax
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * MPD
  * MOC

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256`

Config file:
`conky.config = {
  use_spacer = 'left',
  pad_percents = 3,
  background = false,
  double_buffer = true,
  font = 'Ubuntu Mono:size=12',
  use_xft = true,
  alignment = 'top_right',
  gap_x = 10,
  gap_y = 40,
  own_window_argb_visual = true,
  own_window_argb_value = 0,
  own_window_type = 'normal',
  own_window_hints = 'undecorated,below,skip_taskbar,skip_pager,sticky',
  own_window = true,
  update_interval = 5.0,
}

conky.text = [[
${color orange}Hostname: ${color}${nodename}
${color orange}Kernel:   ${color}${sysname} ${kernel} on ${machine}
${color orange}Uptime:   ${color}${uptime}
${hr}
${color orange}Load average: ${color}${loadavg}
${color orange}Processes: ${color}${processes} 
${color orange}Running:${color} ${running_processes}
${hr}
${color orange}RAM:  ${color}${mem}/${memmax}
${memperc}% ${membar 4}
${memgraph }
${hr}
${color orange}R:${color}${fs_used /}/${fs_size /} ${fs_bar 6 /}
${hr}

${image /home/mariusz/Pulpit/12.png -p 20,20 -s 200x200} 
${color orange}Skróty vim:${color}
${hr}
${color orange},+f${color} -> NERDTree otwiera tam gdzie plik 
${color orange},+t${color} -> NERDTree otwiera drzewo
${hr}
${color orange}ctrl+o${color} -> otwiera ostatnio używane pliki
${hr}
${color orange}ctrl+t${color} -> Nowa zakładka
${color orange}ctrl+w${color} -> Zamknij zakładkę
${color orange},+n${color} -> przejdź do wcześniejszej zakładki
${color orange},+m${color} -> przejdź do następnej zakładki
${hr}
${color orange}Shift+k${color} -> podpowiedzi z pythona
${color orange},+r${color} -> wykonaj kod pythona
]]`

**Comment by dbriba** [comment]
I test your conky, and for me it work as expected, I have no " unknown variable '$image' "
My conky -v

`dominique@host-192-168-1-2 ~$ conky -v
conky 1.10.6_pre compiled Mon Feb 20 15:37:19 UTC 2017 for Linux 4.9.3-200.fc25.x86_64 x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib64/conky


 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * RSS
  * Weather (METAR)
  * Weather (XOAP)
  * wireless
  * support for IBM/Lenovo notebooks
  * old configuration syntax
  * Imlib2
  * apcupsd
  * iostats
  * Internationalization support
  * Debugging extensions

 Lua bindings:
  * Cairo
  * Imlib2
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * MPD

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256
`

**Comment by a11g0rhythm** [comment]
In my "General:"  Imlib2 is missing.
form man conky
image <path to image> (-p x,y) (-s WxH) (-n) (-f interval)
              **Renders an image from the path specified using Imlib2.**

**Comment by dbriba** [comment]
I think you are right, problem is here.
I'm using fedora 26, with Kde, and the conky's package include Imlib2.
May be there is another package in ubuntu, like conky-all, with this lib.

**Comment by dbriba** [comment]
Have you the imlib2 package installed ?

**Comment by a11g0rhythm** [comment]
yes, It wokrs 
apt remove conky-std
apt install conky-all

**Comment by dbriba** [comment]
Ok, if that work you can close this thread.
