### ISSUE TITLE
Errors while build

### ISSUE THREAD

**Issue by mihaiturei** [brndnmtthws/conky#419]
I'm trying to build conky latest but I get the following errors

>CMake Warning (dev) at cmake/Conky.cmake:120 (if):
   Policy CMP0054 is not set: Only interpret if() arguments as variables or
   keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
   details.  Use the cmake_policy command to set the policy and suppress this
   warning.

  >Quoted variables like "CLOCK_GETTIME_LIB" will no longer be dereferenced
   when the policy is set to NEW.  Since the policy is not set the OLD
   behavior will be used.
 Call Stack (most recent call first):
   cmake/ConkyPlatformChecks.cmake:41 (AC_SEARCH_LIBS)
   CMakeLists.txt:37 (include)
 This warning is for project developers.  Use -Wno-dev to suppress it.

 >CMake Error at /usr/share/cmake-3.2/Modules/FindPkgConfig.cmake:340 (message):
   A required package was not found
 Call Stack (most recent call first):
   /usr/share/cmake-3.2/Modules/FindPkgConfig.cmake:502 (_pkg_check_modules_internal)
   cmake/ConkyPlatformChecks.cmake:370 (pkg_check_modules)
   CMakeLists.txt:37 (include)

**Comment by brndnmtthws** [comment]
I'm guessing you tried building with an outdated version of CMake.
