### ISSUE TITLE
Mouse interactions

### ISSUE THREAD

**Issue by Ahed91** [brndnmtthws/conky#42]
We need this feature
execute sth on mouse click or hover ....

**Comment by balta2ar** [comment]
I'd really love this feature too.

**Comment by stardiviner** [comment]
+1, this is really an awesome idea!

**Comment by mxmlnkn** [comment]
+1

**Comment by fennecdjay** [comment]
that issue is old, but still +1

**Comment by gandalf3** [comment]
I started poking around with this, and I noticed that the `own_window.get(l)` check at [`x11.cc:956`](https://github.com/brndnmtthws/conky/blob/master/src/x11.cc#L956) is always coming out false even when I have `own_window = true` in my config. I had assumed that `own_window.get(l)` was checking the state of that setting (I didn't dig into the lua glue code, so I may be way off base). Am I missing something?

**Comment by lockywolf** [comment]
I am against this idea entirely.
Conky's scope is not making interactive widgets, it is for displaying stuff ... basically wherever you want to display it. For example, I use it to display monitoring information on an xscreensaver.  Adding interactivity would limit the displaying ability. There are plenty of desktop widget systems out there. Essentially, every large DE provides one, and there is gkrellm for DE-independent people.
