### ISSUE TITLE
Window does not repositioning when monitor changes.

### ISSUE THREAD

**Issue by Magicloud** [brndnmtthws/conky#430]
Plasma 5.11, conky 1.10.1. Set window alignment as bottom_middle. After unpluged the external monitor, the window was gone on my laptop monitor. Another conky window sits at top_left is fine.

**Comment by lasers** [comment]
Hi @Magicloud, could you see if https://github.com/brndnmtthws/conky/pull/615 maybe solves your issue? Thank you.

**Comment by Magicloud** [comment]
@lasers , hi, sorry, I am not using KDE now. Cannot verify.

**Comment by lasers** [comment]
Closed via https://github.com/brndnmtthws/conky/pull/615
