### ISSUE TITLE
diskiograph high bars

### ISSUE THREAD

**Issue by bunder2015** [brndnmtthws/conky#431]
conky 1.10.4

similar to #307, diskiograph can sometimes also have high bars.  i typically see this shortly after starting conky, haven't noticed it during regular use.

**Comment by lasers** [comment]
9 months passed. Can you determine if you're still having this problem today on `1.10.8` or preferably `1.10.9_pre` (git)? The older versions are not trustworthy due to too many changes that can be hard to track. Thank you.

**Comment by bunder2015** [comment]
This bug happens so infrequently but I'll try to reproduce again on 1.10.8 and report back in a few days.

Pardon me asking but can you give me an example of a change that would possibly fix high bars?  I don't see anything relevant in the change logs.

**Comment by lasers** [comment]
I recall no recent changes to diskiograph. I'm hitting everybody up right now with invaliding issues, asking for updates, or to look for more information. In the last 6 days, we went from <205 down to 113 issues. That's more than 80 issues already. Hopefully it won't be too long before we went down to 100.

Closed via bug fixes, feature requests, duplicate issues, stale issues, or by asking people to see if their bugs is still there in `1.10.9_pre` (git). There might be something wrong with earlier `1.10` iterations that were simply solved by upgrading. You could be one of them.

We simply would like you to try the `1.10.9_pre` so we know where this issue stands today as there was too many changes between old `1.10.4` and current `1.10.9_pre` that can be hard to track. Owner made several changes over last few months... such as adding https://sonarcloud.io/about to analyze codes, removed old `INSTALL` methods in favor of `cmake`, and possibly some more. Thank you.

**Comment by bunder2015** [comment]
Despite my best efforts, I cannot reproduce this at the moment, short of trying to reboot the affected machines, which I can't really do right now.  I guess I have no other choice than to close this until I can get a fresh screenshot.
