### ISSUE TITLE
Quit on SIGHUP

### ISSUE THREAD

**Issue by mkoskar** [brndnmtthws/conky#436]
Especially when running `conky` with `out_to_ncurses = true` I think it really does make sense to respect `SIGHUP` signal and quit on it, rather then reloading the config as `man` suggests.

**Comment by a2wharrison** [comment]
Just wondering, but why man versus the SIGHUP ?

**Comment by mkoskar** [comment]
@a2wharrison Not entirely sure what you're asking but as far as my `man` mention goes I was referring to following section in `man conky`:

> An  easy  way to force Conky to reload your ~/.config/conky/conky.conf: "killall -SIGUSR1 conky". Saves you the trouble of having to kill and then restart. You can now also do the same with SIGHUP.

**Comment by brndnmtthws** [comment]
Why not use SIGTERM or SIGKILL if you want to kill Conky? SIGHUP is typically used for reloading/restarting nowadays.

**Comment by mkoskar** [comment]
@brndnmtthws Hmm, well I don't know any other terminal program that would use SIGHUP for such a purpose. There is already SIGUSR1 handler doing that. Consider what is SIGHUP and when it is generated. Quoting from `man 7 signal`:

> Hangup detected on controlling terminal or death of controlling process

Note that I'm talking about conky that outputs to terminal. What is it good for when terminal is gone?

**Comment by lasers** [comment]
It might be important to mention https://github.com/brndnmtthws/conky/pull/233 here before @brndnmtthws decides what to do here.

**Comment by lasers** [comment]
@su8 https://github.com/brndnmtthws/conky/commit/8dc1eab70b43ca21d8b4778cdaaa2ddffdb78372 :+1:  or :-1: :question:

**Comment by su8** [comment]
:taco: err :+1: :D

**Comment by lasers** [comment]
Closed via #642.
