### ISSUE TITLE
Unknown setting 'imlib_cache_size'

### ISSUE THREAD

**Issue by sevku** [brndnmtthws/conky#437]
While trying to start conky, the error 'imlib_cache_size' appears. How can this be fixed?

**Comment by easysid** [comment]
Could you please post your conky.conf here. Use a pasting service if the file is too long.

**Comment by a2wharrison** [comment]
Check to see if bind_to_address is commented out and uncomment it and this should work

**Comment by lasers** [comment]
8 months passed. No replies to first two comments. This issue likely does not matter anymore. Closing.
