### ISSUE TITLE
Add XKB Indicators

### ISSUE THREAD

**Issue by moyamo** [brndnmtthws/conky#439]
Some laptops and keyboards don't come with LED Caps Lock or Num Lock indicators.

It would be nice if conky could display the state of XKB indicators such as Caps Lock, Scroll Lock, Num lock etc.

**Comment by easysid** [comment]
using ` xset q | <awk/grep/sed pipeline>` in `${execi}` should be sufficient in most cases. However, it does entail a call to external process.

**Comment by su8** [comment]
Thanks, the indicators was just added and are in PR.

**Comment by moyamo** [comment]
Thanks, I appreciate it :+1:
