### ISSUE TITLE
Start multiple different config conky instances for dual monitors

### ISSUE THREAD

**Issue by stardiviner** [brndnmtthws/conky#440]
I use two screens, one is laptop's screen, one is the big screen which connected to the laptop, When the laptop, I set KDE to use the big screen as primary output screen.
I will conky can have a timer interval to detect screen size, if changed, then invoke corresponding config file.
For example:
```
detect_screen_size_option = true
screen_size_1024x768 = ~/.conky_1
screen_size_1980_1020 = ~/.conky_2
```
If it is not possible to implement in Conky internal, then is there some script (shell or lua etc) can do this?

**Comment by dbriba** [comment]
I think it's possible with a script.
On my F28 rawhide, I have a script who detect if I am with driver nouvo or nvidia driver.
`#!/bin/bash
file="/sys/module/nouveau/"
if [ -d "$file" ]
then conky -c /home/dominique/.conkyrc/conky-1.10/conky_monitor/conky-monitor-1 &
else 
conky -c /home/dominique/.conkyrc/conky-1.10/conky_monitor/conky-monitor &
fi`

But I don't know how adapt to your issue.

**Comment by dbriba** [comment]
I can see this comment here, post #10 https://ubuntuforums.org/showthread.php?t=2262398

> To make a long story short: controlling on which display Conky starts is not possible anymore w/ the latest Desktop Environments at the time of writing because they do NOT support separate X screens.

apparently it is not possible...

**Comment by dbriba** [comment]
I also find that:
http://forum.xfce.org/viewtopic.php?pid=46796

I don't know if it is relevant for your issue.

**Comment by stardiviner** [comment]
Thank you for provide those hints. Really helpful.
After reading them. I can't under following `xrandr` settings:
```shell
if xrandr | grep -q 'HDMI1 connected' ; then
  xrandr --display :0.0 --fb 6388x1800
  xrandr --display :0.0 --output HDMI1 --scale 1.66x1.66 --mode 1920x1080 --pos 0x0
  xrandr --display :0.0 --output eDP1 --pos 3187x0
fi
```
Do you understand them? I checked `man xrandr` about those options, but can't understand them together.

**Comment by dbriba** [comment]
Sorry, for me it's the same thing, I don't understand that.

**Comment by lasers** [comment]
Where do we stand on this issue today? Is it okay to close this now? Thank you.
