### ISSUE TITLE
TouchScreen bug -  logout when touched

### ISSUE THREAD

**Issue by sonvirgo** [brndnmtthws/conky#444]
Ubuntu Gnome 17.04 on TouchScreen tablet
Work fine with mouse over, left click, right click, stylus click
But immediately logout when touched by hand
```
$ uname -a
Linux Wacom-m3-7y30 4.14.3-041403-generic #201711300431 SMP Thu Nov 30 09:32:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ conky -V
conky 1.10.6 compiled Fri Dec  9 23:23:27 UTC 2016 for Linux 4.4.0-53-generic x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky


 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * RSS
  * Weather (METAR)
  * Weather (XOAP)
  * wireless
  * support for IBM/Lenovo notebooks
  * nvidia
  * eve-online
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support
  * PulseAudio

 Lua bindings:
  * Cairo
  * Imlib2
  * RSVG
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * Audacious
  * MPD
  * MOC
  * XMMS2

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256
```

**Comment by reprise5** [comment]
Your Xsession logs out? or conky quits?
I have a 2-in-1 Laptop with touchscreen support, and conky would unexpectedly quit when clicking the desktop too.  I did some research into it when it was a problem for me.  Why don't you try what I did:

 `own_window_type = 'dock',`  in the conky.config = {...} section.

**Comment by sonvirgo** [comment]
The Xsession logout. I use Gnome and own_window_type = 'normal'
I have try own_window_type = 'conky', same result.
Only own_window_type = 'desktop', party solve the issue but I have to touch elsewhere in the desktop before I touch the conky, other while Xsession logout again

**Comment by reprise5** [comment]
repeat the steps to reproduce this problem without conky running and report back.

**Comment by reprise5** [comment]
If this problem occurred while Conky wasn't running, Please close this issue as it doesn't seem to pertain to this project.  Thanks.

**Comment by sonvirgo** [comment]
In fact, I don't get what you mean by reproduce without conky running
This is mine desktop
This is my process
The problem is the Xsession logout when I tuoch the conky windows
[https://i.imgur.com/2Cp8A3G.jpg](url)
`# ps -aux | grep conky <br/>
root      1519  0.2  0.8 471840 14956 tty1     Sl+  10:53   0:02 conky -c /root/.conky/Green Apple Desktop/Gotham <br/>
root      1551  0.9  0.5 1060692 9748 tty1     Sl+  10:53   0:09 conky -c /root/.conky/Default/conky <br/>
root      1552  0.1  0.4 323704  8960 tty1     Sl+  10:53   0:01 conky -c /root/.conky/TeejeeTech/Network Panel <br/>
root      1554  0.4  0.6 1030628 12836 tty1    Sl+  10:53   0:04 conky -c /root/Documents/conky/conkyrc <br/>
`

**Comment by reprise5** [comment]
I wanted you to tap your desktop while conky wasn't running to see if you logged out.

You should also try adding or changing these lines in your config:

```

**Comment by sonvirgo** [comment]
Test your config on my 2-in-1 device. Seems ok

**Comment by reprise5** [comment]
Alright, that's great!  So if you used this default config for conky and tapped it and the bug did not occur, This means the bug is not with conky itself, but your personal config may not be optimal for your machine which is causing some wonky effects.

Did you try and edit your personal configuration and see if anything was solved?   

If everything *was* solved, you can go ahead and close this issue.

**Comment by sonvirgo** [comment]
I use conky manager, which work with old config format only

**Comment by reprise5** [comment]
If I may quote you,  You are using the newest version of conky.
`$ conky -V
conky 1.10.6 compiled Fri Dec  9 23:23:27 UTC 2016 for Linux 4.4.0-53-generic x86_64`

Conky version 1.10.6 does not support the old format of configs.  You must update them.  So the problem you are experiencing is on your end with your configurations.

[Here's is a script ](https://github.com/brndnmtthws/conky/wiki/Convert-to-new-1.10-syntax)  that you can *try* to convert your old 1.9 configurations, as well as some notes containing some information about the change.

You can also run a script to run your new configurations without the use of conky manager.  I wrote one im my repository [here](https://github.com/reprise5/CrystalConky/blob/master/config/1.10.0/startconky.sh).

**Comment by sonvirgo** [comment]
OK thank you, I close this

**Comment by reprise5** [comment]
your very welcome, good luck in the future.

**Comment by reprise5** [comment]
@mswanson-me , I noticed you were a contributor, could you please add the pending closure tag to this issue? it's all set.

**Comment by mswanson-me** [comment]
You got it! Thanks for letting me know.
