### ISSUE TITLE
$scroll works strange with Cyrillic text

### ISSUE THREAD

**Issue by VitalD** [brndnmtthws/conky#45]
Version: Conky 1.9.0 compiled Fri May 10 23:14:47 UTC 2013 for Linux 3.2.0-37-generic (x86_64) on Linux Mint 16 MATE.

When I try put Cyrillic text in $scroll then every next letter become space on 1 second and move left. I looks really strange. When text come to left edge it starts to blink.

To see this, just add "${scroll 30 Кирилический текст}" in .conkyrs

**Comment by lasers** [comment]
Reportedly fixed by #384. Thanks.
