### ISSUE TITLE
Conky crashed when I restarted network-manager service

### ISSUE THREAD

**Issue by dmknght** [brndnmtthws/conky#452]
I am using conky 1.10.6 on Parrot Security OS 3.11 (kernel 4.14.0). i am having 3 config scripts, based on black pearl conky, and It has 3 configuration files:
1. config0: displays system information
2. config1: displays network information
3. config2: displays something else (incompleted)
And i have a bash script run 3 files in 3 different processes, and i have 3 different conky panel.
So, when i run "sudo service network-manager restart", conky panel that shows network information will disappear, other panels work normally.
I tried debugging from terminal and i have this message
conky: malloc.c:2399: sysmalloc: Assertion (old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.

My fully conky version information:
conky 1.10.6 compiled Wed Sep 13 16:49:42 UTC 2017 for Linux 4.9.0-3-amd64 x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky

 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * RSS
  * Weather (METAR)
  * Weather (XOAP)
  * wireless
  * support for IBM/Lenovo notebooks
  * nvidia
  * eve-online
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support
  * PulseAudio

 Lua bindings:
  * Cairo
  * Imlib2
  * RSVG
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * Audacious
  * MPD
  * MOC
  * XMMS2

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256

My configuration file (config1, but i think this problem does not come from configuration error)
https://github.com/dmknght/conky/blob/master/conky/config1
Sorry for my bad English. I hope you guys can check and fix soon. Many thanks for awesome application.
p/s: somehow github does not show my text in correct format and i am really bad in this so please forgive me

**Comment by lasers** [comment]
If you're still experiencing this, open a terminal and start `gdb conky` then (qdb) `r -c /path/to/your/conky.conf` to run your conky. When `conky` crashes, run (qdb) `bt full` to print the backtrace. We want that backtrace. Thanks.

**Comment by dmknght** [comment]
Hi! My Parrot Sec upgraded conky to 1.10.8 and it didn't crash again. My conky in Debian 9 is using 1.10.6 version and it crashes rarely and i don't know how did it crashed.

**Comment by lasers** [comment]
Good to know you don't have this problem on `1.10.8` or `1.10.9_pre`. The older versions are not trustworthy due to too many changes that can be hard to track.

P.S...
To highlight text, wrap text in graves \` like this... \`example\` --> `example`.
To put text in code style, wrap them in triple graves \`\`\` like this...

\`\`\`
code example
code example
code example
\`\`\`
```
code example
code example
code example
```
Since you said it's working okay now on `1.10.8`, I'm going to close this. Comment again if you're still having problems and don't forget about the `gdb` backtrace above. Have a good day. Thanks.
