### ISSUE TITLE
MPD: mpd_percent division by zero

### ISSUE THREAD

**Issue by wlhlm** [brndnmtthws/conky#46]
When MPD plays a track with unknown length, it says, that track has a length of 0. This happens for example when playing back a radio icecast stream. This causes division by zero on [this line](https://github.com/brndnmtthws/conky/blob/38f05de4ca0649259b5dddee558b83e371e0fc85/src/mpd.cc#L240-241) as `status->totalTime` will be 0:

``` cpp
    if (status->state == MPD_STATUS_STATE_PLAY ||
        status->state == MPD_STATUS_STATE_PAUSE) {
        mpd_info.is_playing = 1;
        mpd_info.bitrate = status->bitRate;
        mpd_info.progress = (float) status->elapsedTime /
            status->totalTime; // <-- here
        mpd_info.elapsed = status->elapsedTime;
        mpd_info.length = status->totalTime;
    } else {
        mpd_info.progress = 0;
        mpd_info.is_playing = 0;
        mpd_info.elapsed = 0;
    }
```

Currently (tested with `conky-1.9.0`) when using the `${mpd_percent}` variable, it will print `2147483648%`.

I suggest to change the line to test whether `totalTime` is 0, like this:

``` cpp
mpd_info.progress = (float) (status->totalTime == 0) ? 0 : (status->elapsedTime / status->totalTime);
```

**EDIT:** Updated line link to refer to specific commit.

**Comment by mswanson-me** [comment]
Is this issue still outstanding in the current version of Conky? If so, please update this issue. Otherwise, the issue will be closed in 2 weeks.
