### ISSUE TITLE
'mixer' object is gone in FreeBSD (version 1.10.8)

### ISSUE THREAD

**Issue by cmanv** [brndnmtthws/conky#463]
In version 1.10.8, the 'mixer' object is no longer recognized in FreeBSD.  

I could trace the problem to this line in 'cmake/ConkyPlatformChecks.cmake':

`check_include_files("soundcard.h;sys/soundcard.h;linux/soundcard.h" HAVE_SOME_SOUNDCARD_H)`

This is wrong, since it requires all three include files to be present on the system.
On FreeBSD, it's sys/soundcard.h so just removing the two others fixes the issue for me.

**Comment by brndnmtthws** [comment]
Want to try to write a patch for it? Looks like we just need a platform check here for FreeBSD.

**Comment by cmanv** [comment]
Sure. So I moved the sound card header checks after the platform checks and followed the logic in the code:
soundcard.h -> OpenBSD
linux/soundcard.h -> Linux
sys/soundcard.h -> All others

I have tested this patch on my system.
```
--- cmake/ConkyPlatformChecks.cmake.orig        2018-02-07 09:16:39.000000000 -0500
+++ cmake/ConkyPlatformChecks.cmake     2018-02-26 13:52:38.222102000 -0500
@@ -30,8 +30,6 @@
 check_include_files(sys/param.h HAVE_SYS_PARAM_H)
 check_include_files(sys/inotify.h HAVE_SYS_INOTIFY_H)
 check_include_files(dirent.h HAVE_DIRENT_H)
-check_include_files("soundcard.h;sys/soundcard.h;linux/soundcard.h" HAVE_SOME_SOUNDCARD_H)
-check_include_files("linux/soundcard.h" HAVE_LINUX_SOUNDCARD_H)
 
 # Check for some functions
 check_function_exists(strndup HAVE_STRNDUP)
@@ -88,6 +86,16 @@
 endif(NOT OS_LINUX AND NOT OS_FREEBSD AND NOT OS_OPENBSD AND NOT OS_DRAGONFLY
   AND NOT OS_SOLARIS AND NOT OS_HAIKU)
 
+# Check for soundcard header
+if(OS_LINUX)
+       check_include_files("linux/soundcard.h" HAVE_SOME_SOUNDCARD_H)
+       check_include_files("linux/soundcard.h" HAVE_LINUX_SOUNDCARD_H)
+elseif(OS_OPENBSD)
+       check_include_files("soundcard.h" HAVE_SOME_SOUNDCARD_H)
+else()
+       check_include_files("sys/soundcard.h" HAVE_SOME_SOUNDCARD_H)
+endif(OS_LINUX)
+
 if(BUILD_I18N AND OS_DRAGONFLY)
        set(conky_libs ${conky_libs} -lintl)
 endif(BUILD_I18N AND OS_DRAGONFLY)

```

**Comment by brndnmtthws** [comment]
Looks good. Can you open a PR with that patch?

**Comment by cmanv** [comment]
Done
