### ISSUE TITLE
Text background color

### ISSUE THREAD

**Issue by bad-interpreter** [brndnmtthws/conky#469]
Would it be possible to add a ${reverse} variable in order to switch the background and the foreground color of a text selection?
Something like a terminal reversed color text.
It would help to underline some critical alert in conky.

Thanks.

**Comment by lasers** [comment]
Hi. I do not see anything in the documentation about conky having an ability to paint colored background texts... We need to add that first before we can think about adding reverse. The solution today would be to use `${if_xxx }` variables to paint identical texts in different color instead.

**Comment by 64542426** [comment]
Hello, I'm interested on this feature as well. I'm using conky as an horizontal panel. I would like it if conky imitate polybar, tint2, lemonbar in regard of reverse background colors over text colors.
an example
![Untitled-3](https://user-images.githubusercontent.com/35492934/110931538-4aae5d80-8322-11eb-9835-89a1a88f6f6b.jpg)
I'm often following this open ticket in hope that one day it will be possible.
Now i'm asking, is it planned to be implemented sometimes?
