### ISSUE TITLE
Feature Request: INCLUDE statement for conky.text section

### ISSUE THREAD

**Issue by sebma** [brndnmtthws/conky#473]
Hi,

I have done a `conky.text` specific to Nvidia in a `~/.config/conky/conky-nvidia.conf` file  in case I boot my USB linux on a pc that has a Nvidia graphic card.

I would be great if one could import such a file from `~/.config/conky/conky.conf`.

In the meantime, is there a way to concatenate the `conky.text` variable ?

I tried this, but it does not work : 
```
config.text = config.text .. [[
GPU Utilization: $alignr ${nvidia gpuutil} % ${nvidiagraph gpuutil} %
GPU Temp: $alignr ${nvidia temp}°C
GPU Utilization: $alignr ${nvidia gpuutil} %
GPU VRAM Utilization: $alignr ${nvidia memutil}%
GPU VRAM: $alignr ${nvidia memused}MiB/${nvidia memmax}MiB
$hr
GPU Processes:
${execi 1 gpustat -cpu | awk -F '|' '/^.[0-9]+/{print$NF}' | tr ' ' '\n' | tr : '\t'}
]]
```

Any idea ?

**Comment by dbriba** [comment]
Try this:

conky.text = [[
GPU Utilization: $alignr ${nvidia gpuutil} % ${nvidiagraph gpuutil} %
GPU Temp: $alignr ${nvidia temp}°C
GPU Utilization: $alignr ${nvidia gpuutil} %
GPU VRAM Utilization: $alignr ${nvidia memutil}%
GPU VRAM: $alignr ${nvidia memused}MiB/${nvidia memmax}MiB
$hr
GPU Processes:
${execi 1 gpustat -cpu | awk -F '|' '/^.[0-9]+/{print$NF}' | tr ' ' '\n' | tr : '\t'}
]]

**Comment by sebma** [comment]
@dbriba I think you have answered to quickly :)

I want to be able to concatenate a previous `config.text` configuration my Nvidia `config.text` config. if (and only if) there is a Nvidia graphic card in the hardware I booted from.

That is why I have used the `..` Lua string concatenation operator.

**Comment by dbriba** [comment]
Ok also try that
conky.text = [[
${if_existing /proc/driver/nvidia/version/
GPU Utilization: $alignr ${nvidia gpuutil} % ${nvidiagraph gpuutil} %
GPU Temp: $alignr ${nvidia temp}°C
GPU Utilization: $alignr ${nvidia gpuutil} %
GPU VRAM Utilization: $alignr ${nvidia memutil}%
GPU VRAM: $alignr ${nvidia memused}MiB/${nvidia memmax}MiB
$hr
GPU Processes:
${execi 1 gpustat -cpu | awk -F '|' '/^.[0-9]+/{print$NF}' | tr ' ' '\n' | tr : '\t'}${endif}

**Comment by sebma** [comment]
@dbriba Thanks a lot !

I'll do that tomorrow at work.

**Comment by lasers** [comment]
Clever use of `${if_existing }`. 4 months passed so I'll be closing this. Thanks.
