### ISSUE TITLE
no transparent own_window_type dock

### ISSUE THREAD

**Issue by johndoe71rus** [brndnmtthws/conky#475]
beta lubutnu 18.04 
conky 1.10.8. conky -v https://paste.ubuntu.com/p/XBDcRKrSW6/
conkyrc https://paste.ubuntu.com/p/p95vYKhzyR/

if own_window_type dock the is no transparent 
dock https://imgur.com/a/cQPXo
normal, desktop, panel https://imgur.com/a/slmdk

**Comment by dbriba** [comment]
With your setting and with Fedora 27, no problems, my conky is transparent.

**Comment by johndoe71rus** [comment]
for 14.04 i use own_window_type = conky
but for  conky 1.10.8

`conky
conky: Invalid value 'conky' for setting 'own_window_type'. Valid values are: 'normal', 'dock', 'panel', 'desktop', 'override'.
conky: desktop window (a000b2) is subwindow of root window (13d)
conky: window type - normal
`

**Comment by johndoe71rus** [comment]
the same situation with calculate linux 17.12.2 
https://i.imgur.com/Bj69tvd.png
https://i.imgur.com/8E8F4oI.jpg

**Comment by johndoe71rus** [comment]
@dbriba 
What DE do you use? Do you use compositing?

**Comment by dbriba** [comment]
I use KDE with compositing enable.

**Comment by lasers** [comment]
@johndoe71rus Anything new with this issue? Have you tried `compton`?

**Comment by johndoe71rus** [comment]
no news. yes i try compton without success.

**Comment by lasers** [comment]
Can you try the current master? Thanks.

```bash
git clone https://github.com/brndnmtthws/conky
cd conky
mkdir -p build
cd build
cmake ..
make -j4  # 4 cores to run in parallel
src/conky -c ~/conky.conf # <-- your config goes here
```

**Comment by johndoe71rus** [comment]
can't build. error at the end. calculate linux 17.12.2(gentoo based)

``
[ 98%] Building CXX object src/CMakeFiles/conky.dir/nc.cc.o
[100%] Linking CXX executable conky
/usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/conky.dir/conky.cc.o: undifined link to symbol «stdscr»
/lib64/libtinfo.so.6: error adding symbols: DSO is not specified on the command line
collect2: error: ld completed with return code 1
make[2]: *** [src/CMakeFiles/conky.dir/build.make:1515: src/conky] error 1
make[1]: *** [CMakeFiles/Makefile2:218: src/CMakeFiles/conky.dir/all] error 2
make: *** [Makefile:152: all] error 2

**Comment by johndoe71rus** [comment]
finaly.
Can confirm, latest git no transparent dock and pannel to 
https://paste.ubuntu.com/p/qnz9n5FrtV/

**Comment by johndoe71rus** [comment]
check latest conky 1.11.1_pre compiled
problem still present
