### ISSUE TITLE
convert.lau throws bad interpreter

### ISSUE THREAD

**Issue by throwawayamillion** [brndnmtthws/conky#477]
I'm trying to run the convert.lua file to update an older file, and I get ./convert.lua: /usr/bin/lua: bad interpreter: no such file or directory

is there a repository i need to run this? any other ideas? I'm on Ubuntu 16.04

**Comment by dbriba** [comment]
Look that:
https://forums.bunsenlabs.org/viewtopic.php?id=3983

You need copy the convert.lua file in your /bin folder and make it executable.

**Comment by lasers** [comment]
Thank you for being helpful. 4 months passed so I'll be closing this. Thanks.
