### ISSUE TITLE
conky crash

### ISSUE THREAD

**Issue by progserega** [brndnmtthws/conky#478]
conky: Syntax error (/home/Serega/.conkyrc:2: unexpected symbol near '#') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: desktop window (4b1) is root window
conky: window type - override
conky: drawing to created window (0x1400001)
conky: drawing to double buffer
*** Error in `conky': corrupted size vs. prev_size: 0x00000000023ad0f0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f42576457e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x82aec)[0x7f4257650aec]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7f4257652184]
/lib/x86_64-linux-gnu/libc.so.6(realloc+0x358)[0x7f4257652a18]
/usr/lib/x86_64-linux-gnu/liblua5.1.so.0(+0xfcee)[0x7f425824fcee]
/usr/lib/x86_64-linux-gnu/liblua5.1.so.0(+0xd0e6)[0x7f425824d0e6]
/usr/lib/x86_64-linux-gnu/liblua5.1.so.0(lua_pushcclosure+0x41)[0x7f4258247c51]
conky(_ZN3lua5state8gettableEi+0x3e)[0x45889e]
conky(_ZN5conky23config_setting_templateIbE3getERN3lua5stateE+0x7e)[0x42be1e]
conky(_Z15calc_text_widthPKc+0x7e)[0x42f78e]
conky[0x430278]
conky[0x43298c]
conky[0x434d2e]
conky(main+0x67a)[0x42726a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f42575ee830]
conky(_start+0x29)[0x42afb9]
======= Memory map: ========
00400000-004a6000 r-xp 00000000 fc:00 1457082                            /usr/bin/conky
006a5000-006a6000 r--p 000a5000 fc:00 1457082                            /usr/bin/conky
006a6000-006a7000 rw-p 000a6000 fc:00 1457082                            /usr/bin/conky
006a7000-006cd000 rw-p 00000000 00:00 0 
0237d000-0245c000 rw-p 00000000 00:00 0                                  [heap]
7f420c000000-7f420c021000 rw-p 00000000 00:00 0 
7f420c021000-7f4210000000 ---p 00000000 00:00 0 
7f4210000000-7f4210021000 rw-p 00000000 00:00 0 
7f4210021000-7f4214000000 ---p 00000000 00:00 0 
7f4214000000-7f4214021000 rw-p 00000000 00:00 0 
7f4214021000-7f4218000000 ---p 00000000 00:00 0 
7f4218000000-7f4218021000 rw-p 00000000 00:00 0 
7f4218021000-7f421c000000 ---p 00000000 00:00 0 
7f421c000000-7f421c021000 rw-p 00000000 00:00 0 
7f421c021000-7f4220000000 ---p 00000000 00:00 0 
7f4220000000-7f4220021000 rw-p 00000000 00:00 0 
7f4220021000-7f4224000000 ---p 00000000 00:00 0 
7f4224000000-7f4224021000 rw-p 00000000 00:00 0 
7f4224021000-7f4228000000 ---p 00000000 00:00 0 
7f4229ffc000-7f4229ffd000 ---p 00000000 00:00 0 
7f4229ffd000-7f422a7fd000 rw-p 00000000 00:00 0 
7f422a7fd000-7f422a7fe000 ---p 00000000 00:00 0 
7f422a7fe000-7f422affe000 rw-p 00000000 00:00 0 
7f422affe000-7f422afff000 ---p 00000000 00:00 0 
7f422afff000-7f422b7ff000 rw-p 00000000 00:00 0 
7f422b7ff000-7f422b800000 ---p 00000000 00:00 0 
7f422b800000-7f422c000000 rw-p 00000000 00:00 0 
7f422c000000-7f422c021000 rw-p 00000000 00:00 0 
7f422c021000-7f4230000000 ---p 00000000 00:00 0 
7f42307f9000-7f42307fa000 ---p 00000000 00:00 0 
7f42307fa000-7f4230ffa000 rw-p 00000000 00:00 0 
7f4230ffa000-7f4230ffb000 ---p 00000000 00:00 0 
7f4230ffb000-7f42317fb000 rw-p 00000000 00:00 0 
7f42317fb000-7f42317fc000 ---p 00000000 00:00 0 
7f42317fc000-7f4231ffc000 rw-p 00000000 00:00 0 
7f4231ffc000-7f4231ffd000 ---p 00000000 00:00 0 
7f4231ffd000-7f42327fd000 rw-p 00000000 00:00 0 
7f42327fd000-7f42327fe000 ---p 00000000 00:00 0 
7f42327fe000-7f4232ffe000 rw-p 00000000 00:00 0 
7f4232ffe000-7f4232fff000 ---p 00000000 00:00 0 
7f4232fff000-7f42337ff000 rw-p 00000000 00:00 0 
7f42337ff000-7f4233800000 ---p 00000000 00:00 0 
7f4233800000-7f4234000000 rw-p 00000000 00:00 0 
7f4234000000-7f4234021000 rw-p 00000000 00:00 0 
7f4234021000-7f4238000000 ---p 00000000 00:00 0 
7f4238000000-7f4238021000 rw-p 00000000 00:00 0 
7f4238021000-7f423c000000 ---p 00000000 00:00 0 
7f423c000000-7f423c021000 rw-p 00000000 00:00 0 
7f423c021000-7f4240000000 ---p 00000000 00:00 0 
7f4240000000-7f4240025000 rw-p 00000000 00:00 0 
7f4240025000-7f4244000000 ---p 00000000 00:00 0 
7f4244000000-7f4244029000 rw-p 00000000 00:00 0 
7f4244029000-7f4248000000 ---p 00000000 00:00 0 
7f4248000000-7f4248021000 rw-p 00000000 00:00 0 
7f4248021000-7f424c000000 ---p 00000000 00:00 0 
7f424c000000-7f424c021000 rw-p 00000000 00:00 0 
7f424c021000-7f4250000000 ---p 00000000 00:00 0 
7f4250117000-7f4250122000 r-xp 00000000 fc:00 659308                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f4250122000-7f4250321000 ---p 0000b000 fc:00 659308                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f4250321000-7f4250322000 r--p 0000a000 fc:00 659308                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f4250322000-7f4250323000 rw-p 0000b000 fc:00 659308                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
7f4250323000-7f4250329000 rw-p 00000000 00:00 0 
7f4250329000-7f425032a000 ---p 00000000 00:00 0 
7f425032a000-7f4250b2a000 rw-p 00000000 00:00 0 
7f4250b2a000-7f4250b2b000 ---p 00000000 00:00 0 
7f4250b2b000-7f425132b000 rw-p 00000000 00:00 0 
7f425132b000-7f425132c000 ---p 00000000 00:00 0 
7f425132c000-7f4251b2c000 rw-p 00000000 00:00 0 
7f4251b2c000-7f4251b2d000 ---p 00000000 00:00 0 
7f4251b2d000-7f425232d000 rw-p 00000000 00:00 0 
7f425232d000-7f425232e000 ---p 00000000 00:00 0 
7f425232e000-7f4252b2e000 rw-p 00000000 00:00 0 
7f4252b2e000-7f4252b2f000 ---p 00000000 00:00 0 
7f4252b2f000-7f425332f000 rw-p 00000000 00:00 0 
7f425332f000-7f4253330000 ---p 00000000 00:00 0 
7f4253330000-7f4253b30000 rw-p 00000000 00:00 0 
7f4253b30000-7f4253b31000 ---p 00000000 00:00 0 
7f4253b31000-7f4254331000 rw-p 00000000 00:00 0 
7f4254331000-7f4254332000 ---p 00000000 00:00 0 
7f4254332000-7f4254b32000 rw-p 00000000 00:00 0 
7f4254b32000-7f4254b33000 ---p 00000000 00:00 0 
7f4254b33000-7f4255333000 rw-p 00000000 00:00 0 
7f4255333000-7f4255334000 ---p 00000000 00:00 0 
7f4255334000-7f4255b38000 rw-p 00000000 00:00 0 
7f4255c35000-7f425603f000 r--p 00000000 fc:00 1444081                    /usr/lib/locale/locale-archive
7f425603f000-7f4256063000 r-xp 00000000 fc:00 660677                     /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f4256063000-7f4256262000 ---p 00024000 fc:00 660677                     /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f4256262000-7f4256263000 r--p 00023000 fc:00 660677                     /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f4256263000-7f4256264000 rw-p 00024000 fc:00 660677                     /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f4256264000-7f425627d000 r-xp 00000000 fc:00 660626                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f425627d000-7f425647c000 ---p 00019000 fc:00 660626                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f425647c000-7f425647d000 r--p 00018000 fc:00 660626                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f425647d000-7f425647e000 rw-p 00019000 fc:00 660626                     /lib/x86_64-linux-gnu/libz.so.1.2.8
7f425647e000-7f42564a4000 r-xp 00000000 fc:00 655560                     /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f42564a4000-7f42566a4000 ---p 00026000 fc:00 655560                     /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f42566a4000-7f42566a6000 r--p 00026000 fc:00 655560                     /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f42566a6000-7f42566a7000 rw-p 00028000 fc:00 655560                     /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f42566a7000-7f42566ac000 r-xp 00000000 fc:00 1452136                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f42566ac000-7f42568ab000 ---p 00005000 fc:00 1452136                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f42568ab000-7f42568ac000 r--p 00004000 fc:00 1452136                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f42568ac000-7f42568ad000 rw-p 00005000 fc:00 1452136                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f42568ad000-7f42568af000 r-xp 00000000 fc:00 1452125                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f42568af000-7f4256aaf000 ---p 00002000 fc:00 1452125                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f4256aaf000-7f4256ab0000 r--p 00002000 fc:00 1452125                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f4256ab0000-7f4256ab1000 rw-p 00003000 fc:00 1452125                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f4256ab1000-7f4256aba000 r-xp 00000000 fc:00 1452158                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f4256aba000-7f4256cb9000 ---p 00009000 fc:00 1452158                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f4256cb9000-7f4256cba000 r--p 00008000 fc:00 1452158                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f4256cba000-7f4256cbb000 rw-p 00009000 fc:00 1452158                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f4256cbb000-7f4256d5f000 r-xp 00000000 fc:00 1443420                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f4256d5f000-7f4256f5e000 ---p 000a4000 fc:00 1443420                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f4256f5e000-7f4256f64000 r--p 000a3000 fc:00 1443420                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f4256f64000-7f4256f65000 rw-p 000a9000 fc:00 1443420                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f4256f65000-7f4256fa2000 r-xp 00000000 fc:00 1457367                    /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.9.0
7f4256fa2000-7f42571a1000 ---p 0003d000 fc:00 1457367                    /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.9.0
7f42571a1000-7f42571a3000 r--p 0003c000 fc:00 1457367                    /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.9.0
7f42571a3000-7f42571a8000 rw-p 0003e000 fc:00 1457367                    /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.9.0
7f42571a8000-7f42571c9000 r-xp 00000000 fc:00 1453503                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f42571c9000-7f42573c8000 ---p 00021000 fc:00 1453503                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f42573c8000-7f42573c9000 r--p 00020000 fc:00 1453503                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f42573c9000-7f42573ca000 rw-p 00021000 fc:00 1453503                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f42573ca000-7f42573cd000 r-xp 00000000 fc:00 659272                     /lib/x86_64-linux-gnu/libdl-2.23.so
7f42573cd000-7f42575cc000 ---p 00003000 fc:00 659272                     /lib/x86_64-linux-gnu/libdl-2.23.so
7f42575cc000-7f42575cd000 r--p 00002000 fc:00 659272                     /lib/x86_64-linux-gnu/libdl-2.23.so
7f42575cd000-7f42575ce000 rw-p 00003000 fc:00 659272                     /lib/x86_64-linux-gnu/libdl-2.23.so
7f42575ce000-7f425778e000 r-xp 00000000 fc:00 659093                     /lib/x86_64-linux-gnu/libc-2.23.so
7f425778e000-7f425798e000 ---p 001c0000 fc:00 659093                     /lib/x86_64-linux-gnu/libc-2.23.so
7f425798e000-7f4257992000 r--p 001c0000 fc:00 659093                     /lib/x86_64-linux-gnu/libc-2.23.so
7f4257992000-7f4257994000 rw-p 001c4000 fc:00 659093                     /lib/x86_64-linux-gnu/libc-2.23.so
7f4257994000-7f4257998000 rw-p 00000000 00:00 0 
7f4257998000-7f42579ae000 r-xp 00000000 fc:00 655704                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7f42579ae000-7f4257bad000 ---p 00016000 fc:00 655704                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4257bad000-7f4257bae000 r--p 00015000 fc:00 655704                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4257bae000-7f4257baf000 rw-p 00016000 fc:00 655704                     /lib/x86_64-linux-gnu/libgcc_s.so.1
7f4257baf000-7f4257cb7000 r-xp 00000000 fc:00 655549                     /lib/x86_64-linux-gnu/libm-2.23.so
7f4257cb7000-7f4257eb6000 ---p 00108000 fc:00 655549                     /lib/x86_64-linux-gnu/libm-2.23.so
7f4257eb6000-7f4257eb7000 r--p 00107000 fc:00 655549                     /lib/x86_64-linux-gnu/libm-2.23.so
7f4257eb7000-7f4257eb8000 rw-p 00108000 fc:00 655549                     /lib/x86_64-linux-gnu/libm-2.23.so
7f4257eb8000-7f4258032000 r-xp 00000000 fc:00 1446990                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f4258032000-7f4258231000 ---p 0017a000 fc:00 1446990                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f4258231000-7f425823b000 r--p 00179000 fc:00 1446990                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f425823b000-7f425823d000 rw-p 00183000 fc:00 1446990                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.24
7f425823d000-7f4258240000 rw-p 00000000 00:00 0 
7f4258240000-7f425826b000 r-xp 00000000 fc:00 1452493                    /usr/lib/x86_64-linux-gnu/liblua5.1.so.0.0.0
7f425826b000-7f425846b000 ---p 0002b000 fc:00 1452493                    /usr/lib/x86_64-linux-gnu/liblua5.1.so.0.0.0
7f425846b000-7f425846d000 r--p 0002b000 fc:00 1452493                    /usr/lib/x86_64-linux-gnu/liblua5.1.so.0.0.0
7f425846d000-7f425846e000 rw-p 0002d000 fc:00 1452493                    /usr/lib/x86_64-linux-gnu/liblua5.1.so.0.0.0
7f425846e000-7f4258482000 r-xp 00000000 fc:00 1452144                    /usr/lib/x86_64-linux-gnu/libXft.so.2.3.2
7f4258482000-7f4258681000 ---p 00014000 fc:00 1452144                    /usr/lib/x86_64-linux-gnu/libXft.so.2.3.2
7f4258681000-7f4258682000 r--p 00013000 fc:00 1452144                    /usr/lib/x86_64-linux-gnu/libXft.so.2.3.2
7f4258682000-7f4258683000 rw-p 00014000 fc:00 1452144                    /usr/lib/x86_64-linux-gnu/libXft.so.2.3.2
7f4258683000-7f4258688000 r-xp 00000000 fc:00 1452140                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f4258688000-7f4258887000 ---p 00005000 fc:00 1452140                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f4258887000-7f4258888000 r--p 00004000 fc:00 1452140                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f4258888000-7f4258889000 rw-p 00005000 fc:00 1452140                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f4258889000-7f425888b000 r-xp 00000000 fc:00 1452134                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f425888b000-7f4258a8a000 ---p 00002000 fc:00 1452134                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f4258a8a000-7f4258a8b000 r--p 00001000 fc:00 1452134                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f4258a8b000-7f4258a8c000 rw-p 00002000 fc:00 1452134                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f4258a8c000-7f4258a9d000 r-xp 00000000 fc:00 1452138                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f4258a9d000-7f4258c9c000 ---p 00011000 fc:00 1452138                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f4258c9c000-7f4258c9d000 r--p 00010000 fc:00 1452138                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f4258c9d000-7f4258c9e000 rw-p 00011000 fc:00 1452138                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f4258c9e000-7f4258dd3000 r-xp 00000000 fc:00 1452121                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f4258dd3000-7f4258fd3000 ---p 00135000 fc:00 1452121                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f4258fd3000-7f4258fd4000 r--p 00135000 fc:00 1452121                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f4258fd4000-7f4258fd8000 rw-p 00136000 fc:00 1452121                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f4258fd8000-7f4258fe0000 r-xp 00000000 fc:00 660593                     /lib/x86_64-linux-gnu/libiw.so.30
7f4258fe0000-7f42591df000 ---p 00008000 fc:00 660593                     /lib/x86_64-linux-gnu/libiw.so.30
7f42591df000-7f42591e0000 r--p 00007000 fc:00 660593                     /lib/x86_64-linux-gnu/libiw.so.30
7f42591e0000-7f42591e1000 rw-p 00008000 fc:00 660593                     /lib/x86_64-linux-gnu/libiw.so.30
7f42591e1000-7f4259206000 r-xp 00000000 fc:00 660708                     /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f4259206000-7f4259405000 ---p 00025000 fc:00 660708                     /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f4259405000-7f4259409000 r--p 00024000 fc:00 660708                     /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f4259409000-7f425940a000 rw-p 00028000 fc:00 660708                     /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f425940a000-7f425942b000 r-xp 00000000 fc:00 660616                     /lib/x86_64-linux-gnu/libncurses.so.5.9
7f425942b000-7f425962a000 ---p 00021000 fc:00 660616                     /lib/x86_64-linux-gnu/libncurses.so.5.9
7f425962a000-7f425962b000 r--p 00020000 fc:00 660616                     /lib/x86_64-linux-gnu/libncurses.so.5.9
7f425962b000-7f425962c000 rw-p 00021000 fc:00 660616                     /lib/x86_64-linux-gnu/libncurses.so.5.9
7f425962c000-7f4259644000 r-xp 00000000 fc:00 659091                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7f4259644000-7f4259843000 ---p 00018000 fc:00 659091                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7f4259843000-7f4259844000 r--p 00017000 fc:00 659091                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7f4259844000-7f4259845000 rw-p 00018000 fc:00 659091                     /lib/x86_64-linux-gnu/libpthread-2.23.so
7f4259845000-7f4259849000 rw-p 00000000 00:00 0 
7f4259849000-7f425986f000 r-xp 00000000 fc:00 659038                     /lib/x86_64-linux-gnu/ld-2.23.so
7f42598fe000-7f42598ff000 rw-p 00000000 00:00 0 
7f42598ff000-7f4259903000 r--p 00000000 fc:00 2248116                    /usr/share/fonts/X11/misc/ter-u12b_unicode.pcf.gz
7f4259903000-7f425990e000 r--s 00000000 fc:00 2100435                    /var/cache/fontconfig/945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-6
7f425990e000-7f4259910000 r--s 00000000 fc:00 2122100                    /var/cache/fontconfig/99e8ed0e538f840c565b6ed5dad60d56-le64.cache-6
7f4259910000-7f4259916000 r--s 00000000 fc:00 2101265                    /var/cache/fontconfig/2cd17615ca594fa2959ae173292e504c-le64.cache-6
7f4259916000-7f4259917000 r--s 00000000 fc:00 2101264                    /var/cache/fontconfig/0d8c3b2ac0904cb8a57a757ad11a4a08-le64.cache-6
7f4259917000-7f4259922000 r--s 00000000 fc:00 2101263                    /var/cache/fontconfig/6d41288fd70b0be22e8c3a91e032eec0-le64.cache-6
7f4259922000-7f4259926000 r--s 00000000 fc:00 2116592                    /var/cache/fontconfig/de156ccd2eddbdc19d37a45b8b2aac9c-le64.cache-6
7f4259926000-7f425993b000 r--s 00000000 fc:00 2101262                    /var/cache/fontconfig/04aabc0a78ac019cf9454389977116d2-le64.cache-6
7f425993b000-7f425993c000 r--s 00000000 fc:00 2101261                    /var/cache/fontconfig/1ac9eb803944fde146138c791f5cc56a-le64.cache-6
7f425993c000-7f4259940000 r--s 00000000 fc:00 2101259                    /var/cache/fontconfig/385c0604a188198f04d133e54aba7fe7-le64.cache-6
7f4259940000-7f4259941000 r--s 00000000 fc:00 2101258                    /var/cache/fontconfig/dc05db6664285cc2f12bf69c139ae4c3-le64.cache-6
7f4259941000-7f4259944000 r--s 00000000 fc:00 2101257                    /var/cache/fontconfig/767a8244fc0220cfb567a839d0392e0b-le64.cache-6
7f4259944000-7f4259945000 r--s 00000000 fc:00 2114727                    /var/cache/fontconfig/4794a0821666d79190d59a36cb4f44b5-le64.cache-6
7f4259945000-7f4259985000 r--s 00000000 fc:00 2101254                    /var/cache/fontconfig/0bd3dc0958fa2205aaaa8ebb13e2872b-le64.cache-6
7f4259985000-7f425998a000 r--s 00000000 fc:00 2101249                    /var/cache/fontconfig/8801497958630a81b71ace7c5f9b32a8-le64.cache-6
7f425998a000-7f42599c5000 r--s 00000000 fc:00 2101204                    /var/cache/fontconfig/365b55f210c0a22e9a19e35191240f32-le64.cache-6
7f42599c5000-7f42599c9000 r--s 00000000 fc:00 2116591                    /var/cache/fontconfig/c57959a16110560c8d0fcea73374aeeb-le64.cache-6
7f42599c9000-7f42599ca000 r--s 00000000 fc:00 2101248                    /var/cache/fontconfig/bab58bb527bb656aaa9f116d68a48d89-le64.cache-6
7f42599ca000-7f42599d1000 r--s 00000000 fc:00 2101243                    /var/cache/fontconfig/3047814df9a2f067bd2d96a2b9c36e5a-le64.cache-6
7f42599d1000-7f42599d9000 r--s 00000000 fc:00 2101242                    /var/cache/fontconfig/bf3b770c553c462765856025a94f1ce6-le64.cache-6
7f42599d9000-7f42599da000 r--s 00000000 fc:00 2101241                    /var/cache/fontconfig/56cf4f4769d0f4abc89a4895d7bd3ae1-le64.cache-6
7f42599da000-7f42599db000 r--s 00000000 fc:00 2101235                    /var/cache/fontconfig/b9d506c9ac06c20b433354fa67a72993-le64.cache-6
[1]+  Аварийный останов         (подготовлен дамп ядра) conky

**Comment by progserega** [comment]
[conkyrc.txt](https://github.com/brndnmtthws/conky/files/1898618/conkyrc.txt)

config

**Comment by Barben360** [comment]
conkyrc is old syntax

**Comment by shevegen** [comment]
> conkyrc is old syntax

In this case, I believe a decent error message and graceful exit would be better than crashes or segfaults.

I can not even start conky 1.10.1 - it segfaults right away. I did not have this problem with older conky versions.

**Comment by Barben360** [comment]
> In this case, I believe a decent error message and graceful exit would be better than crashes or segfaults.

The first  line is quite explicit about it as it states a syntax error and gives the line.

> I can not even start conky 1.10.1 - it segfaults right away. I did not have this problem with older conky versions.

Have you tried starting it with a conky script adapted to the new syntax? I have no problem building and running 1.10.1.
Indeed if you want to keep your old conky files it is better to stay on an older conky version.

**Comment by progserega** [comment]
Thank you!
I was convert config by script to new syntax and conky not crash. 
Thank you very match!

**Comment by lasers** [comment]
Everything worked out better than expected. :-) Closing.
