### ISSUE TITLE
question: Wireless stats for all Operating Systems

### ISSUE THREAD

**Issue by npyl** [brndnmtthws/conky#481]
Hello!
I have begun porting conky to macOS (only small steps due to school) and I noticed that Wireless Stats are only an option for Linux.  Not even FreeBSD.   Why is this? Is there some reason that we shouldn't have an option listed with `ccmake` to choose whether to build Wireless Stats or not? 

Thanks!

btw: the project is located [here](https://github.com/Conky-for-macOS/conky-for-macOS)
PS: I am sorry if asking questions here is wrong, it is the only place I know!

**Comment by brndnmtthws** [comment]
IMO it makes sense to have the stats for all OSs. Most likely the answer for why it's not there is that nobody wrote the code 😀

**Comment by npyl** [comment]
😀 xaxa thats nice! I will make a PR once i've added the WIFI stats then! :)
