### ISSUE TITLE
Problems with execibar and exec(i)graph in conky 1.10.1

### ISSUE THREAD

**Issue by sardus-X** [brndnmtthws/conky#483]
Hi All,
I'm having some problems editing a conky config: if an expression is used like,i.e.:
`${execigraph "dash ~/.conky/LOADAVG_PERC.sh 1 4" 13,185 b8001a b8001a}`,
`${execibar 10 hddtemp /dev/sda -n}`,
`${execibar 10 dash ~/.conky/TEMP.sh 0 2}`
the bars and graphs seem to work but I have an error message:
`conky: reading exec value failed (perhaps it's not the correct format?)`,
moreover if I use the variable execgraph or execigraph the height of the graph does not match the settings in:
`default_graph_height   = 13,
default_graph_width    = 185,`
I have read some discussions about it here too but I could not figure out whether it could depend on syntax and / or formatting errors or other problem.
Any help or hint will be appreciated
Thanks in advance

**Comment by lasers** [comment]
3 months passed. I'm going ahead and close this. Here's what I think.

* Missing code for `~/.conky/LOADAVG_PERC.sh`. Can't tell what's in it.
* Missing code for `~/.conky/TEMP.sh`. Can't tell what's in it.
* Running `hddtemp /dev/sda -n` can produce this output...

```bash
2d [user:~] 1 % hddtemp /dev/sda -n
/dev/sda: open: Permission denied

```
which could be why you received `reading exec value failed` message. You should take all variables out and start putting one in... one at a time... until you find your trouble. Let me know how that goes.
