### ISSUE TITLE
Images fail to load with KDE color correction

### ISSUE THREAD

**Issue by beojan** [brndnmtthws/conky#49]
Image fail to load in conky when KDE color correction is enabled.

See this bug: https://bugs.kde.org/show_bug.cgi?id=331495

**Comment by lasers** [comment]
Latest comment from the link above.
```
Martin Flöser 2017-07-02 16:09:18 UTC                              Comment 9 

Color correction got dropped from KWin. Thus the bug cannot be fixed any more.
```
Closing due to 4 years and 2 months of inactivity. Open again if you are still affected. Thanks.
