### ISSUE TITLE
When displaying temperature values in Fahrenheit, an odd "A" character is displayed

### ISSUE THREAD

**Issue by servebeer** [brndnmtthws/conky#511]
When displaying temperature values in Fahrenheit, an odd "A" character is displayed. 

I am using these commands:
Core 1 Temp:   ${exec sensors -f| grep 'Core 0'}
Core 2 Temp:   ${exec sensors -f| grep 'Core 1'}
Core 3 Temp:   ${exec sensors -f| grep 'Core 2'}
Core 4 Temp:   ${exec sensors -f| grep 'Core 3'}
HDD SDA Temp:  ${execi 300 hddtemp /dev/sda --unit=F}
HDD SDB Temp:  ${execi 300 hddtemp /dev/sdb --unit=F}

The output:
![screenshot from 2018-05-22 15-22-43](https://user-images.githubusercontent.com/8514341/40388043-0962bf40-5dd4-11e8-9b87-8ca374e62243.png)

shows an "A" charcter with a special mark above it. Is there a way to display the temperature with a space in place of this "A" character?

**Comment by servebeer** [comment]
That did it...

Thanks!

**Comment by lasers** [comment]
@brndnmtthws General question/support. Please close this.

**Comment by lasers** [comment]
Thank you @lasers for solving this problem. I appreciate it. Closing. ;-)
