### ISSUE TITLE
Latest git won't configure, and gives uninformative error

### ISSUE THREAD

**Issue by CottonEaster** [brndnmtthws/conky#516]
```
 CMake Error at /usr/local/share/cmake-3.11/Modules/FindPkgConfig.cmake:418 (message):
   A required package was not found
 Call Stack (most recent call first):
   /usr/local/share/cmake-3.11/Modules/FindPkgConfig.cmake:585
 (_pkg_check_modules_internal)
   cmake/ConkyPlatformChecks.cmake:444 (pkg_check_modules)
   CMakeLists.txt:36 (include)
```

**Comment by brndnmtthws** [comment]
It's looking for libcurl. I'm not sure why it doesn't print a more useful error message. You can either a) install libcurl or b) disable curl.

**Comment by CottonEaster** [comment]
Thanks,. I like option (a). However, I cannot determine which package I need to install. I have one called 'libcurl3' installed already.

**Comment by CottonEaster** [comment]
Also, I find that Conky won't configure even with the 'CURL' function disabled.

**Comment by CottonEaster** [comment]
I add that, in order to try to get Conky to build (which it used to be able to do on my system) I've installed a new version of CMake put links to the latter's files into /usr/local.

**Comment by brndnmtthws** [comment]
Here's an example of how to build it on Ubuntu (from the Dockerfile): https://github.com/brndnmtthws/conky/blob/master/Dockerfile

You need to install a bunch of dev packages by default, or disable the features you don't want.

**Comment by CottonEaster** [comment]
Thanks; I thought I had all the dependencies, but I did not. Conky now builds, albeit with warnings (see [this pastebin](https://pastebin.com/enKY0NeP)). However, when it runs, I get this:

```
conky: desktop window (3a0a8af) is subwindow of root window (146)
conky: window type - desktop
conky: drawing to created window (0x4000002)
conky: drawing to double buffer
conky: basic_string::_M_create
```

**Comment by brndnmtthws** [comment]
Is it not running? Does it print anything else? I did a big code refactor recently so it's not unlikely that master has some new bugs.

**Comment by CottonEaster** [comment]
[Certainly](https://pastebin.com/tHF01zJw).

**Comment by i6o6i** [comment]
I came across a problem similar to it. 

Call Stack (most recent call first):
   /usr/local/share/cmake-3.13/Modules/FindPkgConfig.cmake:622
 (_pkg_check_modules_internal)
   cmake/ConkyPlatformChecks.cmake:446 (pkg_check_modules)
   CMakeLists.txt:36 (include)

Finally I run `sudo yum install libcurl-devel.x86_64` to install the curl module, my os is "centos7"
