### ISSUE TITLE
There are no instructions for uninstalling Conky

### ISSUE THREAD

**Issue by CottonEaster** [brndnmtthws/conky#517]
How does one uninstall Conky, if one built it from source? I've run `make uninstall` in various places, but so doing merely generates an error.

**Comment by dbriba** [comment]
In the INSTALL file file for conky there is:

`5. You can remove the program binaries and object files from the
     source code directory by typing `make clean'.  To also remove the
     files that `configure' created (so you can compile the package for
     a different kind of computer), type `make distclean'.  There is
     also a `make maintainer-clean' target, but that is intended mainly
     for the package's developers.  If you use it, you may have to get
     all sorts of other programs in order to regenerate files that came
     with the distribution.`

Try that

**Comment by CottonEaster** [comment]
Thanks.

`make clean` within the /build subdirectory worked or at least did not generate an error.

One may need also to remove a conky bin file from some system (not the source) folder. (I forget from which folder, because - since [I could not get git conky to work](https://github.com/brndnmtthws/conky/issues/516) - I reverted to the old version in my distro's repositories.)

**Comment by brndnmtthws** [comment]
Annoyingly CMake doesn't provide an uninstall target by default, but there are instructions here on how to do it: 

https://stackoverflow.com/questions/41471620/cmake-support-make-uninstall?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by lasers** [comment]
You could try `sudo ln -sf ~/src/conky/build/src/conky /usr/local/bin/conky` instead of `make install`. Use `make -j4` instead and keep everything in the `conky` folder.

**Comment by CottonEaster** [comment]
Thanks. However, I am inclined to try your suggestion - viz., substitute

1. `sudo ln -sf ~/src/conky/build/src/conky /usr/local/bin/conky`

and

2. `make -j4` 

for the `make install` command - only if you are confident it will cause no problems or complications.

**Comment by CottonEaster** [comment]
Thanks. Partly because I do use lua functions from within conky (lua functions I wrote myself), I will stick with the 'make install' method, but thank you for the tip about `build/install_manifest.txt`.
