### ISSUE TITLE
${nvidia memfreq} value is half of what it should be.

### ISSUE THREAD

**Issue by thevik** [brndnmtthws/conky#518]
This is on Arch (4.16)
GPU: ASUS Strix GTX 1070

NVIDIA X Server Settings is reporting a memory transfer rate of 8200 Mhz, but the value displayed by memfreq is 4100 Mhz.

![screenshot from 2018-06-03 15-10-30](https://user-images.githubusercontent.com/5505269/40890210-889e9f5c-6740-11e8-9477-88796dd7b3ee.png)
![screenshot from 2018-06-03 15-11-26](https://user-images.githubusercontent.com/5505269/40890211-8c8cbe5a-6740-11e8-879a-0b45b731d227.png)

**Comment by dbriba** [comment]
I can see in nvidia.cc, line 1013 to 1019 : 
 case ATTR_MEM_FREQ:  // memfreq (calculate out of memfreqmax)
        temp1 = get_nvidia_value(nvs->target, ATTR_MEM_FREQ, nvs->gpu_id);
        temp2 = get_nvidia_string_value(nvs->target, ATTR_PERFMODES_STRING,
                                        (char *)"memclockmax", SEARCH_MAX,
                                        nvs->gpu_id);
        value = ((float)temp1 * 100 / (float)temp2) + 0.5;
        break;

that seems to mean that the memfreq is divided by the perfmode, in my case it is 2, and I think it's the general value.

But I don't know why...

**Comment by lasers** [comment]
I looked into this. I'm pretty sure this is correct. `memfreq` and many other variables could be updated to go 1:1 with nvidia names. From what I understand or think... conky's `memfreq` is akin to nvidia's `memclock` and conky's `mtrfreq` is akin to nvidia's `memTransferRate`.

I believe you were supposed to use `${nvidia mtrfreq}`, not `${nvidia memfreq}`.

**Comment by thevik** [comment]
@lasers thank you! this solved the issue :)
