### ISSUE TITLE
Will conky slow down my computer ?

### ISSUE THREAD

**Issue by ReductoAdAbsurdum** [brndnmtthws/conky#519]
I have a laptop with Celeron N3060 and 4GB of RAM....Will conky run properly on this setup ? will it use up too much RAM and CPU ?

**Comment by KaMiila** [comment]
Yes, it will run properly on that computer.  No it will not use many resources (RAM and CPU).  I run conky on systems with much less than your computer (Raspberry Pi), you will not notice a hit to performance.

**Comment by lasers** [comment]
@brndnmtthws General question/support. Please close this.

**Comment by lasers** [comment]
Conky will run okay on your machine. It should not use up too much resources. Thanks.
