### ISSUE TITLE
too high cpu usage with conky

### ISSUE THREAD

**Issue by tiiiecherle** [brndnmtthws/conky#521]
Hey,

first of all thanks for conky, it`s awesome.

I don`t know in what correlation it occurs and with which version it started, but using conky in latest version (also with the current conky-git) an the latest xorg-server 1.20 on archlinux (with all packages up-to-date) the cpu usage of xorg jumps from 0,7% to around 3-5 %. Killing conky solves it and I know that it has not been an issue in the past...

I´ve read about other packages (e.g. mate-power-manager) that caused similar issues with xorg 1.20 and got an update for that.
[https://github.com/mate-desktop/mate-power-manager/issues/248](https://github.com/mate-desktop/mate-power-manager/issues/248)

I narrowed my issue down to conky as I killed the running processes one-by-one and killing conky braught the xorg usage back to normal.

Sorry I can`t help more from describing. If you need my conky config or anything else from logs etc. just let me know.

Thanks for fixing in advance.

Kind regards

**Comment by su8** [comment]
Probably related to https://github.com/brndnmtthws/conky/issues/512

**Comment by tiiiecherle** [comment]
Hey, thanks for getting back to this. I'm sorry to report that the problem is not solved in latest git version. It still persists in the same way.

Thanks for fixing in advance.

**Comment by lasers** [comment]
Thank for dropping in. Can we have your config too?

**Comment by tiiiecherle** [comment]
> Thanks for dropping in. Can we have your config too?


sure
[conky_archvbox.txt](https://github.com/brndnmtthws/conky/files/2279068/conky_archvbox.txt)

**Comment by lasers** [comment]
Ha. Can we have a screenshot too? I'm wondering if I'm off with something. It seems like I need to install `conkycolors` font too. Anyhow, it's for comparison. Don't forget to block out the public IP. Thank you.

**Comment by tiiiecherle** [comment]
yes, the setup requires conky-colors-git. I like this config ;)

Here is a screenshot of my desktop and the separate conky.

![screenshot_desktop](https://user-images.githubusercontent.com/7059936/43978834-eb7b16d6-9ce8-11e8-8ddd-35e870b51156.jpg)
![screenshot_conky](https://user-images.githubusercontent.com/7059936/43978835-eb975ae4-9ce8-11e8-9ea0-25387a287c34.jpg)
