### ISSUE TITLE
Panel width is different from minimum_width and maximum_width

### ISSUE THREAD

**Issue by Numrod** [brndnmtthws/conky#522]
I'm not certain this a bug, but I can't find any reference to it, so I have to assume it is one.

I use panel mode, and have `minimum_width` and `maximum_width` set to the same number. The actual width on the desktop is always 5 pixels more than `minimum_width` and `maximum_width`.

For example, if I have `minimum_width = 1000` and `maximum_width = 1000`, the actual width will be 1005 pixels.

I'm using Xubuntu 16.04, xfwm4.

**Comment by lasers** [comment]
Can you share the conky config file? Have you tried running this under... maybe `openbox` to rule out potential `xfce4`-related behaviors?

**Comment by lasers** [comment]
Can I have your config, please?

**Comment by Numrod** [comment]
My screen resolution is 1366x768. I've compensated for the problem by altering the values for `goto`.

For example, without `${goto 6}` at the start, the arrow on the left starts slightly beyond the left of the screen.

My `conky.conf` is below. Sorry, I can't find how to insert a continuous block of code and it won't let me attach a text file.

`conky.config = {`
`alignment = 'top_left',`
`background = false,`
`border_width = 1,`
`cpu_avg_samples = 2,`
`default_color = 'white',`
`double_buffer = true,`
`draw_borders = false,`
`draw_outline = false,`
`draw_shades = false,`
`use_xft = true,`
`font = 'DejaVu Sans Mono:size=10',`
`gap_x = 0,`
`gap_y = 0,`
`minimum_height = 5,`
`minimum_width = 1361,`
`maximum_width = 1361,`
`net_avg_samples = 2,`
`no_buffers = true,`
`out_to_console = false,`
`out_to_stderr = false,`
`own_window = true,`
`own_window_class = 'Conky',`
`own_window_type = 'panel',`
`update_interval = 1.0,`
`uppercase = false,`
`use_spacer = 'none'`
`}`

`conky.text = [[
${goto 6}▼ ${downspeed wlp3s0}${goto 118}▲ ${upspeed wlp3s0}${goto 294}Σ▼ ${totaldown wlp3s0}${goto 414}Σ▲ ${totalup wlp3s0}${goto 598}RAM $memperc%${goto 726}SWP $swapperc%${goto 854}CPU $cpu%${goto 1046}R $diskio_read${goto 1158}W $diskio_write
]]`

**Comment by lasers** [comment]
Thanks. I'll look into this soon or later. Need to set up Lubuntu, Xfce4, etc to compare this and other issues. I fixed your config too with code blocks. You can look how it's done. Cheers.

**Comment by lasers** [comment]
Heh. Can we have a screenshot too? Many thanks. :smile:

**Comment by Numrod** [comment]
Thanks. Screenshot attached.
![screenshot_2018-09-04_22-05-05](https://user-images.githubusercontent.com/40263781/45058137-9ddb3180-b08f-11e8-9c90-2b177022864a.png)

**Comment by Numrod** [comment]
I've now discovered that the left end of the panel starts 5 pixels beyond the left of the screen, so actually the width of the panel is always 10 pixels more than `minimum_width` and `maximum_width`.

If I start conky with `-x 5`, or I put `gap_x = 5,` in `conky.conf`, the panel starts exactly at the left edge of the screen.

**Comment by lasers** [comment]
@brndnmtthws Low-key comment. This might be a trivial fix because the window width is 10 pixel longer than the specified `maximum_width` (5 on each side).
