### ISSUE TITLE
Nested if_match?

### ISSUE THREAD

**Issue by DanyGee** [brndnmtthws/conky#531]
I would like my conky configs (in one file) to launch according to time.

For time <= 06 AND time >=20 - config with colors for the night.
else
config with colors for the day.

For now I have something like this, but it does not seem to work:

```
${if_match "{time %H}" <= "06"}${if_match "{time %H}" >= "20"}
night config
${else}
day config
${endif}${endif}
```
Conky does show nothing in this case.

conky -v
conky 1.10.1 compiled Wed Jan  6 17:11:44 UTC 2016 for Linux 3.19.0-43-generic x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky

 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * RSS
  * Weather (METAR)
  * Weather (XOAP)
  * wireless
  * support for IBM/Lenovo notebooks
  * nvidia
  * eve-online
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support

 Lua bindings:
  * Cairo
  * Imlib2
  * RSVG
 X11:
  * Xdamage extension
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * Audacious
  * MPD
  * MOC
  * XMMS2

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256

**Comment by dbriba** [comment]
Try this
${if_match ${time %H} <= 06}${if_match ${time %H} >= 20}
night config
${else}
day config
${endif}${endif}

**Comment by DanyGee** [comment]
> Try this
> ${if_match ${time %H} <= 06}${if_match ${time %H} >= 20}
> night config
> ${else}
> day config
> ${endif}${endif}

Thanks! This worked as it should. Case closed.

**Comment by dbriba** [comment]
Sorry but that don't work properly I have alway no response or "day config"
This line make better :
${if_match ${time %H} <=06}${else}${if_match ${time %H} >=20}
night config
${else}
day config
${endif}${endif}

**Comment by DanyGee** [comment]
> ${if_match ${time %H} <=06}${else}${if_match ${time %H} >=20}
> night config
> ${else}
> day config
> ${endif}${endif}
This code only shows day config. If I change the hour span to >=6 and <=20 - it shows nothing again.
Today I'll test something like this:
${if_match ${time %H} >= 6}${if_match ${time %H} <= 19}
day config
${else}
${if_match ${time %H} >= 20}${if_match ${time %H} <= 5}
night config
${endif}${endif}${endif}${endif}

**Comment by dbriba** [comment]
I test your last code, but that don't work well.
I think it's not possible to chain more two if_match.
But I think this code work :

${if_match ${time %H} <=06}
night config
${endif}\
${if_match ${time %H} >=20}
night config
${endif}\
${if_match ${time %H} >=07}
day config
${endif}\
${if_match ${time %H} ==00}
night config
${endif}

**Comment by dbriba** [comment]
And I see what your code don't work
there are ${if_match ${time %H} <= 19} (day config) and ${if_match ${time %H} <= 5}(night config)
that is not possible.

**Comment by dbriba** [comment]
sorry but my last code don't work in every cases.
And I know why.
There is an incoherence between ${if_match ${time %H} >=07}(day config) and ${if_match ${time %H} >=20} (night config).
And I don't know how solve that...

**Comment by dbriba** [comment]
Try this code, that work for me : 
`${if_match ${time %H} <= 06}night config ${else}${if_match ${time %H} >= 19}night config ${else}day config
${endif}${endif}`

**Comment by DanyGee** [comment]
> Try this code, that work for me :
> ${if_match ${time %H} <= 06}night config ${else}${if_match ${time %H} >= 19}night config ${else}day config ${endif}${endif}

Thx dbriba, this finally works as it should :+1: 
![bitmoji](https://render.bitstrips.com/v2/cpanel/eb1a2ea1-7c1f-4a92-abdb-e89cdc52edfd-fe85af63-ad51-4198-8b90-cb1af6ce89fd-v1.png?transparent=1&palette=1&width=246)
