### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by vignesh0504** [brndnmtthws/conky#537]
Hi

I followed installation method in this URL https://github.com/brndnmtthws/conky/wiki/Installation. 
After i typed "ccmake .." and while configure i am receiving error 
![screenshot1](https://user-images.githubusercontent.com/40589465/42642777-408710e8-8615-11e8-8d48-79e1ecfb157d.png). i need help

**Comment by npyl** [comment]
It seems that you haven't installed git. If you are on ubuntu type: `sudo apt install git`

**Comment by vignesh0504** [comment]
Thanks for your comment. I am installing on ubuntu and now receives this error 
![screenshot0](https://user-images.githubusercontent.com/40589465/42651207-5f7fde50-862c-11e8-8f18-be15facd4272.png)

I have downloaded these files imlib2;Imlib2. but i do not know which path to install it.

**Comment by vignesh0504** [comment]
Thanks for your comment. I am installing on ubuntu. Now i receives this error 
![screenshot](https://user-images.githubusercontent.com/40589465/42651497-2b3b8f1c-862d-11e8-8905-1c8b1876cc9e.png)
I have downloaded these imlib2;Imlib2 but i don't know which path to install it.

**Comment by npyl** [comment]
I am not sure but I think the missing package is `libimlib2-dev` on Ubuntu. So you should do: `sudo apt install libimlib2-dev`

**Comment by vignesh0504** [comment]
It worked :-). The package name was correct. Thanks.
