### ISSUE TITLE
Conky curl not displaying characters correctly

### ISSUE THREAD

**Issue by vuksavic** [brndnmtthws/conky#542]
I have this piece of code which is supposed to display my hometown's weather:
`${texeci 100 curl -s wttr.in | sed -n '3,7{s/\d27\[0-9;]*m//g;s/^..//;s/ *$//;p}'}`
Instead of showing it like [here](https://wttr.in/belgrade), it appears like this:
![conky output](https://i.imgur.com/m4xqAdS.png)
I tried changing the font, but they all produce the same output. What gives?

**Comment by npyl** [comment]
Hi! These characters are escape-sequences that are used to set text / background colour in a terminal.  Conky doesn't know how to interpret them and only sees them as characters.

I havent tried it but something like [this](https://github.com/rsteube/ansi2conky) may help

**Comment by npyl** [comment]
Although this script converts escape-sequences to conky-understandable variables such as `color1`, `color2`, etc, conky doesn't understand the output as its own-script thus can't replace them with actual colors.

You can see this if you put the `ansi2conky` script in the same directory as your conky-config and use this code instead:

`${texeci 100 curl -s wttr.in | sed -n '3,7{s/\d27\[0-9;]*m//g;s/^..//;s/ *$//;p}'}`

**Comment by npyl** [comment]
I think I got it

**Comment by npyl** [comment]
I think this command fixes it:

`${eval ${execi 100 curl -s wttr.in | gsed -n '3,7{s/\d27\[0-9;]*m//g;s/^..//;s/ *$//;p}' | ./ansi2conky}}`

By using an `${eval ...}` variable whatever output comes from our code above must be processed by CONKY.

Conky will see all the `${colorX}` variables and will replace them with colors appropriately.

**Comment by npyl** [comment]
Once you try it out can you post here the colors you are using 🤣? (you need to set them as for the script to work 😎)

**Comment by vuksavic** [comment]
Right now I'm fighting with the fact that my .conky can't see the script right next to it... says it's not found... chmod +x, right?

**Comment by npyl** [comment]
Yeah that would be a reason

**Comment by vuksavic** [comment]
So close!
![heh](https://i.imgur.com/0WywBEQ.png)

**Comment by vuksavic** [comment]
Is it a font issue now?

**Comment by vuksavic** [comment]
Also, i'm only using FFFFFF, it's an all white Conky...

**Comment by npyl** [comment]
No.  The escape-sequences on the left can be eliminated (I suppose) by patching more the `ansi2conky` script.
But that needs knowledge of reg-expressions which I don't have.  Probably someone else may be able to help you from here ☺️

For the color, it is up to you to set it using the `color0` etc variables.

**Comment by npyl** [comment]
`${execpi 100 curl -s wttr.in | sed -n '3,7{s/\d27\[0-9;]*m//g;s/^..//;s/ *$//;p}' | ./ansi2conky}`

This should have the same effect with the previous code but it is now cleaner.  Not sure which is more resource consuming though.

**Comment by npyl** [comment]
**NOTE:** I am testing the code on a port of conky for macOS, and `sed` is not the same here.
As a result I accidentally gave you code that uses `gsed`.
I updated the code and now it is correct, though it seems that it worked for you anyway.

**Comment by vuksavic** [comment]
Resources are not a problem for me, I just need a working Conky. Thank you so much for your help, hope someone else here can also chip in with some ideas...

**Comment by vuksavic** [comment]
Also, the last line of code you've sent me now displays all the info and the complete ASCII art, now it all just needs to remove the escape sequences on the beginning of every line.

**Comment by npyl** [comment]
Thats awesome!
