### ISSUE TITLE
Compile Error with BUILD_BUILTIN_CONFIG 

### ISSUE THREAD

**Issue by Vallimar** [brndnmtthws/conky#547]
https://github.com/brndnmtthws/conky/blob/fa5e56720faabe56627173cc28ccf7be3ddf4a3d/src/conky.cc#L2695

When BUILD_BUILTIN_CONFIG is defined, you get an error due to an extra brace.

```diff
@@ -2692,7 +2692,9 @@ void load_config_file() {
     } else {
 #endif
       l.loadfile(current_config.c_str());
+#ifdef BUILD_BUILTIN_CONFIG
     }
+#endif
   } catch (lua::syntax_error &e) {
 #define SYNTAX_ERR_READ_CONF "Syntax error (%s) while reading config file. "
 #ifdef BUILD_OLD_CONFIG
```

**Comment by brndnmtthws** [comment]
Yeah that's connect. Would you like to submit a PR to fix this?

**Comment by lasers** [comment]
Closed by https://github.com/brndnmtthws/conky/pull/566 and https://github.com/brndnmtthws/conky/pull/563. I'm an idiot. Sorry about that. :face_with_head_bandage:
