### ISSUE TITLE
Question: Which is conky's main loop

### ISSUE THREAD

**Issue by npyl** [brndnmtthws/conky#557]
Does anyone happen to know which is conky's main loop (I have seen the function `main_loop` in `conky.cc`) but I wasn't really sure if it fits my needs.

I am trying to implement some macOS functionality and in order for that to happen I need to know if conky has shown all variables of the config file for the first time (<=> first iteration).  I am planning to set a flag upon first iteration of main loop and be able to check for this flag in `darwin.cc`.

Hope this makes sense, my english is really bad.

**Comment by su8** [comment]
https://github.com/brndnmtthws/conky/blob/cb5833e2fc147a2d578fbf0e0e7b2aeb1e3d6fc8/src/conky.cc#L3066

https://github.com/brndnmtthws/conky/blob/cb5833e2fc147a2d578fbf0e0e7b2aeb1e3d6fc8/src/conky.cc#L2878

https://github.com/brndnmtthws/conky/blob/cb5833e2fc147a2d578fbf0e0e7b2aeb1e3d6fc8/src/conky.cc#L2684

**Comment by npyl** [comment]
Thank you but I think I am searching for something else! I am searching for the loop that is responsible for calling the functions that gather info for the conky-variables.  Such functions are e.g `update_cpu_usage()` and `update_net_stats`.

**Comment by npyl** [comment]
Thank you! But this doesn't to help my goal.

To make things clearer, I am trying to implement `update_cpu_usage` for multiple cores.
The way I understand it, conky parses the config file, sees what variables are in there and creates a loop that in every iteration calls the respective functions (that gather info for the variables).

Upon first iteration end, I need to set a flag `conky_workloop_ended_once` to `true` so that my algorithm knows that there is no need to allocate a handle for each `cpuXXXX` - related variable and instead use an existent one.

**Comment by su8** [comment]
You can test against 

https://github.com/brndnmtthws/conky/blob/cb5833e2fc147a2d578fbf0e0e7b2aeb1e3d6fc8/src/core.cc#L669

so here `cpu` can be tested with `strncmp("cpu", s, 3)` where `s` is the source string provided to you when it's parsed. You can have `extern cpu_var;` that just increases it's number or other logic.

That's the configuration options parser and the variables that are extracted back to you.

**Comment by npyl** [comment]
Thank you for your help I think I have solved my problem!
