### ISSUE TITLE
New version of conky fails to recognise wifi after suspend; old version halts shutdown

### ISSUE THREAD

**Issue by CottonEaster** [brndnmtthws/conky#561]
I have a version of Conky taken from github a day or so ago. It takes some five minutes to recognise my wifi, after the computer resumes from suspend (and has problems with battery power, but that is being worked upon: #538). (Admittedly, I have reported this problem with wifi-sleep before: #546.) I would use the older version of Conky - the one in my repositories (version 1.0.8-1) - but that one suffers from the somewhat notorious hang-at-shutdown problem (which is #233).

Please advise how to resolve my dilemma.

Linux Mint 19 Cinnamon.

**Comment by lasers** [comment]
I think to help you best, we would need you to `git clone https://github.com/brndnmtthws/conky` and compile from there. When you said `a version of Conky`, it's meaningless without a number.

If you really want to solve this issue, then you'll have to get dirty too for a while. I'm unfamiliar with `make`, but I think @su8 may be more than helpful to walk you through.

Maybe @su8 can try and spot bad `wireless` codes first.  If he can't find anything, then you should have to `make` repeatedly between current and old versions during `git bisect` to find a bad commit... then @su8 might be able to rectify this problem for you. 

* https://github.com/brndnmtthws/conky/issues/538 -- Solved
* https://github.com/brndnmtthws/conky/issues/546  -- Seems same as this one.
* https://github.com/brndnmtthws/conky/pull/233  -- Solved.

**Comment by CottonEaster** [comment]
Sorry if I was unclear about the version. I meant that I had indeed, very recently, compiled from git clone https://github.com/brndnmtthws/conky. I have done the same a few hours ago; my conky version and basic configuration is, now, as follows.

```
<pre>conky 1.10.9_pre compiled Sun  5 Aug 02:19:09 BST 2018 for Linux 4.17.9-041709-generic x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/local/lib/conky


 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * wireless
  * support for IBM/Lenovo notebooks
  * eve-online
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * OSS mixer support
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * Xshape extension (click through)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * CMUS
  * MPD
  * MOC

 Default values:
  * Netdevice: eth0
  * Local configfile: c
  * Localedir: /usr/local/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256
</pre> 
```

The shutdown problem (#233) does indeed seem solved. The same goes for the battery problem (#528) As to the network problem (this bug report, and indeed #546) I am still having some problems but they may not owe to Conky; I intend to investigate and then either close or elaborate this the current bug report. Thank you for your work.

**Comment by su8** [comment]
That gotta be wireless-tools/iwlib, we should change the wireless interface to libnl instead.

**Comment by CottonEaster** [comment]
Actually I think the problem might be that Conky as a whole freezes after suspend. And I think that the cause might be this: lua scripts of mine that do not abort if there is no conky window. But I am guessing, and older versions of conky did not have the problem.

**Comment by CottonEaster** [comment]
I am still getting some delays to shutdown that look as though they may be caused by Conky. They look that way in that, during the stall, other applications have quit and Conky remains visible. Could you help me diagnose this, please?

**Comment by lasers** [comment]
Duplicate https://github.com/brndnmtthws/conky/issues/546. Closed by user.
