### ISSUE TITLE
Could not connect hddtemp host

### ISSUE THREAD

**Issue by andoruB** [brndnmtthws/conky#57]
I've had conky work properly with hddtemp before I reinstalled the OS (CrunchBang with Debian testing repos), and this time it doesn't work at all, even with the same settings.
I've tried with the default interface and port, also specifying custom values for those two (and I changed that in the conky config file too), made sure that I have the right permissions on /usr/sbin/hddtemp (I can see the temp values without any root privileges or a sudoer), and made sure that the daemon is running.
Here's the relevant part of conky:
       HDD1:${alignr}${hddtemp /dev/sdb}°C
       HDD2:${alignr}${hddtemp /dev/sda}°C

Any help would be appreciated

**Comment by Ovnuniarchos** [comment]
Check that hddtemp is still running. In the latest Debian, it sometimes shuts down itsel (confirmed bug), thus Conky can't access it.

**Comment by MARESFAC** [comment]
vi /etc/default/hddtemp
# hddtemp network daemon switch. If set to true, hddtemp will listen for incoming connections.
set RUN_DAEMON="false" => RUN_DAEMON="true"
:wq

then 'service hddtemp restart/start'
it works on my ubuntu 16.04 laptop

**Comment by lasers** [comment]
Chalking this up as an odd case and move on. Also, `${hddtemp /dev/sda}` work okay for me.
