### ISSUE TITLE
[RFC] cycles for i in ...

### ISSUE THREAD

**Issue by Nefelim4ag** [brndnmtthws/conky#58]
Good time of day, i have a config with code:
Disk I/O sdc: ${diskio /dev/sdc}${hr 2}
${diskiograph /dev/sdc}
Disk I/O sdd: ${diskio /dev/sdd}${hr 2}
${diskiograph /dev/sdd}
Disk I/O sr0: ${diskio /dev/sr0}${hr 2}
${diskiograph /dev/sr0}

this is very similar code and i think if conky have cycles, like for, it can be written like:
${for i in /dev/sdb /dev/sdc /dev/sdd /dev/sr0}
Disk I/O $i: ${diskio $i}${hr 2}
${diskiograph $i}
$endfor

What you think about it?

**Comment by mswanson-me** [comment]
If question is still relevant, please update this issue. Otherwise, the issue will be closed in 2 weeks due to inactivity.
