### ISSUE TITLE
Require display of both ipv4 & ipv6 addresses at the same time

### ISSUE THREAD

**Issue by slothbag** [brndnmtthws/conky#59]
From what I can tell I have to compile Conky in either ipv4 or ipv6 mode.

**Comment by TheDoctorsLife** [comment]
Any update on this?

**Comment by Caellian** [comment]
> Would be nice to include IPv6, it's a bit ancient to not to.

I think the issue was that the features are exclusive. Closing as both `v6addrs` and `addrs` can be used. IPv6 is also enabled by default these days.
