### ISSUE TITLE
if_match not working

### ISSUE THREAD

**Issue by bad-interpreter** [brndnmtthws/conky#593]
My $apcupsd_status variable is "ONLINE". But if I do 

`${if_match "${apcupsd_status}" != "ONLINE"}NOT ONLINE${endif}`

it will print "NOT ONLINE" too, in the same config.
Is it a bug?

conky 1.10.8_pre compiled lun 16 lug 2018, 13.24.10, CEST for Linux 4.14.55-zion x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib64/conky

 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * RSS
  * Weather (METAR)
  * Weather (XOAP)
  * wireless
  * support for IBM/Lenovo notebooks
  * nvidia
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support

 Lua bindings:
  * Cairo
  * Imlib2
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * Xshape extension (click through)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * Audacious
  * MPD
  * MOC

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256

**Comment by bad-interpreter** [comment]
I solved: the variable ${apcupsd_status} has a trailing space, so it must be compared with "ONLINE " and "ONBATT ".

**Comment by su8** [comment]
What happens when you change the following line:

https://github.com/brndnmtthws/conky/blob/3720e96ca5ae94f838a7fc39fe1f1d559961a3a4/src/apcupsd.cc#L164

to

```c
FILL("STATUS", APCUPSD_STATUS, TRUE);
```

**Comment by su8** [comment]
```bash
git clone https://github.com/brndnmtthws/conky
cd conky
mkdir -p build
cd build
cmake ..
make -j4 # 4 cores to run in parallel
src/conky -c ~/conky.conf # <-- your config goes here
```

**Comment by bad-interpreter** [comment]
Works as expected! No trailing space anymore!

**Comment by lasers** [comment]
@su8 Mind pushing a fix on new branch on this repository or should I do it?

**Comment by su8** [comment]
@lasers You go ahead and open a PR with this fix :heart:

**Comment by lasers** [comment]
@su8 What do I describe this? I see it's defined on line 136 saying... FIRST?

**Comment by su8** [comment]
>What does if (FIRST) does? I see it check for a space, but the second one?

It stops on first encountered space character and terminates with '\0' or 0.

>More accurate to use remove trailing whitespace or remove trailing newline ?

remove trailing whitespace should be fine.

**Comment by lasers** [comment]
Closed via https://github.com/brndnmtthws/conky/issues/593. Thank you for the report. Keep them coming.
