### ISSUE TITLE
LUA API: uptime in the conky_info table appears not to be working

### ISSUE THREAD

**Issue by CottonEaster** [brndnmtthws/conky#596]
This table entry appears to be blank - whereas the update_interval entry works. Apologies if some compile-time option is needed for this (which I have not enabled).

Linux Mint 19 Cinnamon x64.

conky 1.10.9_pre compiled Thu  9 Aug 22:06:55 BST 2018 for Linux 4.17.13-041713-generic x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/local/lib/conky

 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * wireless
  * support for IBM/Lenovo notebooks
  * eve-online
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * OSS mixer support
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * Xshape extension (click through)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * CMUS
  * MPD
  * MOC

 Default values:
  * Netdevice: enp0s31f6
  * Local configfile: $HOME/conky/.conkyrc
  * Localedir: /usr/local/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256

**Comment by lasers** [comment]
Do you have an example config we can use to test this?

**Comment by CottonEaster** [comment]
Certainly. Here are gutted but hopefully stil functional - apart from with respect to the problem at issue! - versions of my [conky script](https://pastebin.com/ifeUfG41) and [the lua [](script](https://pastebin.com/4ieazRvT)) in question. (The originals are a bit large and involved.)

I edited the title of this bug report, to clear up a confusion I had introduced. To be clear: the problem is with the _update_ field in the conky_info table.

**Comment by lasers** [comment]
Pastebin does not last long. I'm copying the config to here.

```lua
--	   ______            __
--	  / ____/___  ____  / /____  __
--	 / /   / __ \/ __ \/ //_/ / / /
--	/ /___/ /_/ / / / / ,< / /_/ /
--	\____/\____/_/ /_/_/|_|\__, /
--	                      /____/


-- ///////////////////////
-- //	CONFIGURATION	//
-- ///////////////////////

conky.config =
{
		update_interval = 1.1,
		update_interval_on_battery = 1.25,

		total_run_times = 0,

		short_units = true,

		format_human_readable = true,

		own_window_type = "desktop",
		own_window_hints = "undecorated,below,sticky,skip_taskbar,skip_pager",

		own_window_transparent = false,

		own_window_argb_visual = true,
		own_window_argb_value = 3,
		
		gap_x = 40,
		gap_y = 10,

		minimum_width = 2560,

		maximum_width = 2560,

		alignment = "top_left",
		
		border_outer_margin = 3,
		
		draw_graph_borders = true,

		use_xft = true,

		font = "Noto Sans:size=19",

		draw_shades = false,

		use_spacer = "left",


	-- // LUA script(s) //
	lua_load = '~/test.lua',
	-- See inter alia: https://github.com/brndnmtthws/conky/wiki/Lua-API
}

-- ///////////////
-- //	Main	//
-- ///////////////

conky.text = [[
${lua_parse conky_test}\
]]
```

**Comment by CottonEaster** [comment]
OK. But I set the Pastebin's expiry on both scripts to six months.

**Comment by lasers** [comment]
Stupid question. Am I missing a second script? I only see one script.

**Comment by CottonEaster** [comment]
My mistake. Something had gone wrong with the formatting in my post. I've fixed it and [here too](https://pastebin.com/4ieazRvT) is a link to that same - previousy missing - lua script.

**Comment by lasers** [comment]
So far, I see duplicate `maximum_width = 2560`. I see that it printed `0` for `uptime` and `1.1` for `update_interval` because you specified that in your config. Also, you may be interested in trying `/usr/bin/env lua` so it can find `lua` well on other machines.

@plikhari Can you see if he's doing Lua correctly?
@su8 Can you see if this is correct? It's only two lines in `~/src/lluaa.cc`.
```
./src/llua.cc:539:  llua_set_number("uptime", i->uptime);
./src/llua.cc:555:  llua_set_number("uptime", i->uptime);
```

**Comment by plikhari** [comment]
`uptime` has always printed `0` - but is this not the system Uptime - in which case it should match `${uptime}` variable. In LUA you can also derive this value using `conky_parse('${uptime}')`

`update_interval` has always worked !!!

**Comment by su8** [comment]
Here's the initialization of `uptime`

https://github.com/brndnmtthws/conky/blob/bbaa0e9ac8d8024245c2dde676ed4b6376f8300e/src/llua.cc#L539

Here's the initialization of the above function
https://github.com/brndnmtthws/conky/blob/bbaa0e9ac8d8024245c2dde676ed4b6376f8300e/src/conky.cc#L3048

Even if we add this:

```diff
diff --git a/src/conky.cc b/src/conky.cc
index 52422ce5..09157b74 100644
--- a/src/conky.cc
+++ b/src/conky.cc
@@ -3045,6 +3045,7 @@ void initialisation(int argc, char **argv) {
 #ifdef BUILD_X11
   X11_create_window();
 #endif /* BUILD_X11 */
+  update_uptime();
   llua_setup_info(&info, active_update_interval());
 
   /* Set signal handlers */
```

The uptime information will be updated only once :disappointed:

**Comment by plikhari** [comment]
Ahh so there you have it - if it is only going to update one time - we really have no use for it.
I have always seen `conky_parse("${uptime}")` in use - so we can change the docs and remove the `uptime` part.

**Comment by CottonEaster** [comment]
Thanks, all. (What I really need, though, is time in seconds or milliseconds since either boot or resumption from sleep . .)

**Comment by plikhari** [comment]
For that you can use the `cat /proc/uptime` or `uptime` - former gives 2 values - 1st is the uptime in seconds.

**Comment by CottonEaster** [comment]
Thanks. Also, though, I do not understand the comment above about

`/usr/bin/env`

**Comment by lasers** [comment]
I think it'd be good idea to take out the whole `conky_info` if it's going to require a sole option `update_interval` to work. Maybe I don't see it, but is there a Lua function to parse conky settings like `update_interval`, `default_bar_width`, etc...? 

For waking up...
```
$ journalctl -b  | grep 'ACPI: Waking up' | tail -n1
Aug 14 04:23:29 z420 kernel: ACPI: Waking up from system sleep state S3
```

**Comment by lasers** [comment]
Change `#!/usr/local/bin/lua` to `#!/usr/bin/env lua` so it know where to find `lua`.

I have `/usr/bin/lua` here. Your `lua` seems to be coming from non-distro installation.

**Comment by plikhari** [comment]
hey that is a very critical option - please leave it as it is

**Comment by plikhari** [comment]
if you are running lua from within conky - then do not use environment statement on the first line !!!

**Comment by lasers** [comment]
@plikhari Why? `#!/usr/local/bin/lua` should have higher precedence over `#!/usr/bin/lua` either way.

**Comment by plikhari** [comment]
i am not talking about any precedence - this line need not be used as the lua interpreter is triggered by `lua_load = filename.lua` variable in the config section.

**Comment by CottonEaster** [comment]
Well, on my computer anyway, conky can run lua files just fine, whether they start with (1)

`#!/usr/local/bin/lua`

or with what was suggested to me on this thread, viz., (2)

`#!/usr/bin/env lua`

And I've tested 1 (but not 2) on two other computers (all admittedly running the same Linux distribution, namely, Mint Cinnamon).

**Comment by su8** [comment]
`#!/usr/bin/env lua` will traverse the `$PATH` to find any lua executables, and is the preferred way to write portable scripts/programs.

**Comment by plikhari** [comment]
If you are running lua scripts as stand alone and not within conky - then you need to use the environment shebang - otherwise - it is not the **preferred way** if the script is being run within conky + lua using lua_load.

This is also not required if you are going to run the script as for example `lua ./luascript.lua`.

**Comment by plikhari** [comment]
That line is not even looked at in conky + lua thing.

I just tested with  `#!/bin/bash` in a lua file and it still runs as lua file !

**Comment by plikhari** [comment]
There is no other way to get `update_interval` from within LUA other than `conky_info` - and my `lua_startup_hook` depends on that !!

**Comment by su8** [comment]
>lua ./luascript.lua

You are using the interpreter here, that's why it ignores the shebang.

---

Add `#!/bin/bash`, `chomd +x luascript.lua` and try running it by executing `./luascript.lua`

**Comment by lasers** [comment]
>Maybe I don't see it, but is there a Lua function to parse conky settings like update_interval, default_bar_width, etc...?

@su8 Is it trivial to implement this? All conky settings, not just `update_interval`.
