### ISSUE TITLE
conky unable to find files

### ISSUE THREAD

**Issue by plikhari** [brndnmtthws/conky#601]
I am getting this message when I try to run my conky and conkywx weather program ...

```
sh: /home/param/bin/projects/conkywx/source/conkywx_source/conkywx.sh -c /home/param/bin/projects/conkywx/source/conkywx_source/examples/conkywx-02.conf -t /home/param/bin/projects/conkywx/source/conkywx_source/examples/hartley-template: No such file or directory
sh: line 1: 21554 Segmentation fault      (core dumped) conky -c ./examples/alert-smscrollrc
sh: line 1: 21593 Segmentation fault      (core dumped) conky -c ./examples/alert-smscrollrc
sh: line 1: 21677 Segmentation fault      (core dumped) conky -c ./examples/alert-smscrollrc
sh: line 1: 21755 Segmentation fault      (core dumped) conky -c ./examples/alert-smscrollrc
```
conky is not able to read full path or standard short ones - can someone else confirm with an example please.

Thanks

**Comment by lasers** [comment]
```bash
conky -c ~/src/conky/data/conky.conf

cd ~/src/conky && conky -c data/conky.conf

cd ~/src/conky/data && conky -c conky.conf
```
All three works for me. Do you have `hartley-template`? Reported `No such file or directory.`

**Comment by plikhari** [comment]
Fantastic - Thanks @lasers - I am checking through - shall get back with more once I have figured it out.

Yes - everything works fine with conky 1.10.8 - some things just not working anymore ... 

OK regarding your 2nd message - Yes - LUA stuff working fine - I have mostly everything working off LUA - so that is fine. Just this path issue.

my resource file for system is up - let me dive deeper 

thanks

**Comment by plikhari** [comment]
Double quotes does not appear to be working - in this situation we cannot use single quotes or double square brackets. We do need the quotes as shell plays havoc if you have space in path.

if we remove these 6 quotes - things start to work.

```
${execpi 1800 "${template0}" -c "${template1}" -t "${template2}" }
```
The errors that are fired up in the terminal are
```
sh: -c: line 0: unexpected EOF while looking for matching `"'
sh: -c: line 1: syntax error: unexpected end of file
```
I am also investigating an issue where if a `${templateN}` - say a file - is missing then the whole conky windows will not show - shall revert re that in a separate issue if found valid.

**Comment by lasers** [comment]
Can you bisect the bad commit? I think it might be #591.

**Comment by lasers** [comment]
Try `${execpi 1800 '"${template0}" -c "${template1}" -t "${template2}"' }` or..
Try `${execpi 1800 ""${template0}" -c "${template1}" -t "${template2}"" }`.

**Comment by plikhari** [comment]
No - even escaping single/double quotes - encomposing with quotes as you have suggested does not work

**Comment by lasers** [comment]
ACK. You'll have to deal this with @su8... Maybe in 6 hours or so.

**Comment by su8** [comment]
Can we have your config and -c ${template1} -t ${template2} files.

**Comment by lasers** [comment]
@su8 Untested, but you can try various files in `conkywx`, which he made.

**Comment by plikhari** [comment]
```
template0 = './conkywx.sh',
template1 = './examples/conkywx-02.conf',
template2 = './examples/big-luamix-template',

${execpi 1802 ${template0} -c "${template1}" -t "${template2}"}
```

Now the first part `${template0}` need not be quoted - I have tested with a space in the path and it still works - so the variable is being passed to the shell as a single unit - even if it has a space. This is good.

If this is the case - then the need to quote is not required - only issue happens is that if it is quoted - it breaks down.

But here is the crux !!!

conky and shell usage is very close - people using the shell HAVE to quote strings that contain spaces - **suddenly conky will not work with quotes**  - having different comments for config and text is BAD enough.

The issue with quotes is a conky issue- it gives the shell error - it is not a shell error and is very confusing - till you read the conky code.

You will need to install conkywx - if you want those files ...

**Comment by su8** [comment]
The quoting is trimmed because of https://github.com/brndnmtthws/conky/issues/580 , the guy wanted to use `${execbar "echo 51"}` which was causing issues with the shell when the command is passed to `pid_popen()`.

Only the initial quotes are trimmed, the rest are left untouched.

If you want to still use quotes do make sure to put everything in another pair of quotes like this:

```bash
${execpi 2 ""${template0}" -c "${template1}""}
${execpi 2 '"${template0}" -c "${template1}"'}
```

Here the initial quotes are stripped and the rest do their job.

**Comment by plikhari** [comment]
My point is that quoting or not quoting should not break the system. At present with this change it does break.

```
${execpi 1802 ${template0} -c "${template1}" -t "${template2}"}
```
So what you are saying is that `1802` has to be without quotes - which it is - but `${template0}` should be free to be quoted or without quotes. This is where things break on a much larger scale that a single `${execbar}` issue.

**Comment by lasers** [comment]
@su8 Revert?

**Comment by su8** [comment]
I don't think that we have a issue here. If we revert single commands with quotes will be broken and we'll get more issues spawning like this.

**Comment by plikhari** [comment]
OK - let's roll with it - we keep it the way it is - even though we have a different perspective over this issue - we have the same goal ;-))
