### ISSUE TITLE
how can I make ${image} accept alignc and offset commands

### ISSUE THREAD

**Issue by amosbird** [brndnmtthws/conky#602]
Currently I'm doing something like this
```
${execi 300 cp -f ${template0}/$(jq .weather[0].id ~/.cache/jelly-conky/weather.json).png ~/.cache/jelly-conky/current.png}${image ~/.cache/jelly-conky/current.png -p 920,150 -s 64x64}\
```

I have to manually calculate the position of the image. It breaks when switching to different screens. How can I specify ${alignc} and ${offset/voffset} like commands to ${image}?

**Comment by dbriba** [comment]
I don't think it's possible, ${alignc} and ${offset/voffset} are only for text.

**Comment by plikhari** [comment]
Unless you are using a list of image files to be displayed in a sequence - `${alignc}` makes no sense and same goes for offsets. conky only supports single image position - which is perfect.

There is a way - but for that you have to use the power of LUA - this is the embedded scripting language for conky.

**Comment by amosbird** [comment]
@plikhari > conky only supports single image position - which is perfect.

well when switching to different sized display, it doesn't work well.

**Comment by plikhari** [comment]
The `${image}` variable has an absolute position placeholder - yes it does not scale as it is using absolute position. 

There is a difference from the developers perspective - an image object and text object require a different way in which they are handled and displayed.

Once you have spent some time with this fantastic program - you will get that realisation - that conky does not scale well !!!

BUT

Before you start changing the positioning variables - look at the font values
```
use_xft = true,
xftalpha = 0.8,
font = 'DejaVu Sans:size=9.5',
```
if it is the resolution - change that font value and you will have things scaling well. Only absolute position values need your attention like `${image}`

Having said that - you have broached a subject close to my heart - **scalability of conky**. I have developed a LUA solution (under testing) which scales and contracts etc as desired with certain limitations - yes and amigos who test it are equally divided about it's functionality  :-)

**Comment by dbriba** [comment]
You can try xrandr with ${ifmatch...}, but I can't test that because I have just one display.
example:
dominique@host-192-168-1-2 ~$ xrandr | sed -n '4p' | awk '{print $1}'
1600x900
In your conky
${if_match "${execi 3600 xrandr | sed -n '4p' | awk '{print $1}'}"  =="1600x900"  ${image ~/.cache/jelly-conky/current.png -p 920,150 -s 64x64}$endif\
${if_match "${execi 3600 xrandr | sed -n '4p' | awk '{print $1}'}"  =="other_resolution"  ${image ~/.cache/jelly-conky/current.png -p other_position_and_size}$endif\
.............................................

**Comment by amosbird** [comment]
@dbriba Thanks!

**Comment by dbriba** [comment]
I do mistake in my code , I update it...
