### ISSUE TITLE
New logo for conky

### ISSUE THREAD

**Issue by su8** [brndnmtthws/conky#619]
Hello sir @Tobaloidee,

Can you make some logo for the awesome conky ?

Regards

**Comment by Tobaloidee** [comment]
Hi @su8 nice to hear from you again..Surely! I'll make a design for awesome conky and post it here when done..thanks!

**Comment by Tobaloidee** [comment]
Hi, good day! @su8 here's what i came up with..

I created a meaningful and simple design that targets the purpose of the project which is to display any kind of information on desktops. I laid it out on a light and dark background to show that it is very visible on both. It is also very visible in small sizes. I hope you like it. However, it is still open for suggestions. I picked that color (purple) from the images displayed on the readme.md 

![conky-01](https://user-images.githubusercontent.com/36028424/44192355-ba0b4300-a161-11e8-9518-21965525f15a.png)

**Comment by su8** [comment]
Great work, your designs are always amazing. Where does this creativity comes from :D 

I like the horizontal one, @lasers what's your opinion here ?

**Comment by su8** [comment]
Can you fill the bars inside the display with real conky configs like this one for example: ![](https://upload.wikimedia.org/wikipedia/commons/2/2b/Conky-unix-program-screen-shot.png)

**Comment by lasers** [comment]
@su8 Same opinion. White and calm. Would like to see smaller versions since conky often cramp things in small window.. Feels weird to see a large size font popping out. Idk. Maybe it's fine if we scale it down.

**Comment by Tobaloidee** [comment]
here i made some adjustments to it from suggestions 

![conky-02](https://user-images.githubusercontent.com/36028424/44196205-de6d1c80-a16d-11e8-9506-13489765861b.png)

**Comment by su8** [comment]
You nailed it my good sir :smiley:

**Comment by lasers** [comment]
Can we see one without white boxes inside the `C`?

**Comment by Tobaloidee** [comment]
without the white bars :)

![conky3-03](https://user-images.githubusercontent.com/36028424/44196646-10cb4980-a16f-11e8-9e46-a3332f06f78a.png)

**Comment by su8** [comment]
The one without the bars rocks. @lasers shall we proceed ahead and tell mister @Tobaloidee  to open up a PR ?

**Comment by lasers** [comment]
I leave this to @brndnmtthws.

**Comment by lasers** [comment]
It would be interesting to see what @Tobaloidee could do with the logo above. ;-)

**Comment by lasers** [comment]
@su8 I think I would like to have him in the logo. Too good to pass it up.

**Comment by su8** [comment]
@lasers I don't know if we are breaching any copyrights if mister @Tobaloidee proceeds ahead with this new idea.

**Comment by plikhari** [comment]
That old one was from some Canadian TV series - right - I think the new one with the white thingies is good - else the small one looks too dull.

**Comment by brndnmtthws** [comment]
@Tobaloidee thanks for the contribution.

I think [the logo here](https://github.com/brndnmtthws/conky/issues/619#issuecomment-413462991) is the one to go with.

Would you like to open a PR to add the logo to the repo? And perhaps put it into the README as well. If you have source files (svg or whatever) those would be great.

**Comment by Tobaloidee** [comment]
Yes yes, i will finalize the files and make a PR..thanks thanks! :)

**Comment by Tobaloidee** [comment]
here's the PR  #630 for the logo upload & readme update. 

You can also get all the different versions and file formats like SVG-PNG-Ai on this [LINK](https://drive.google.com/drive/folders/1RS3LGbzB-5pk4-4YyNHa3sdhUm1BbaDb)

Thanks and my best regards to the project!

-Tobaloidee

**Comment by npyl** [comment]
This can be closed now.  The logo is awesome! Thank you!

**Comment by npyl** [comment]
Just one question:  I am thinking of using the logo for the [conky-for-macOS organisation](https://github.com/Conky-for-macOS) and for [ConkyX](https://github.com/Conky-for-macOS/ConkyX)/[ManageConky](https://github.com/Conky-for-macOS/Manage-Conky).

What is the license of the logo?  Am I allowed to do it?
I am a total illiterate when it is about licenses!

Thank you! ;)

**Comment by brndnmtthws** [comment]
I guess the logo would be under the GPLv3 along with the rest of the
project. Conky isn't trademarked or anything, so you're free to do as you
please with it.

**Comment by npyl** [comment]
@brndnmtthws Thank you for the info!
