### ISSUE TITLE
Need help with if_match

### ISSUE THREAD

**Issue by tupo2** [brndnmtthws/conky#621]
Hi,

${if_match "one" == "one"}${exec touch one}${endif}
${if_match "two" == "three"}${exec touch two}${endif}

Second line does not work as expected, a file "two" is created.
On the other hand, these are ok:

${if_match "one" == "one"}${exec echo one}${endif}
${if_match "two" == "three"}${exec echo two}${endif}

Can you explain me why?

**Comment by lasers** [comment]
You found a bug... https://github.com/brndnmtthws/conky/issues/334... Try this... `bad_ifmatch.conf`
```
conky.config = {
    out_to_x=false,
    out_to_console=true,
}
conky.text = [[
    ${if_match "one" == "one"}${exec echo one}${exec "echo 1 :: $(date) >> /tmp/date.log"}${endif}
    ${if_match "two" == "cat"}${exec echo two}${exec "echo 2 :: $(date) >> /tmp/date.log"}${endif}
]]
```
Run `conky -c bad_ifmatch.conf` in a terminal,  `tail -f /tmp/date.log` in another terminal.

Results:
```
conky -c ~/conky/bad_ifmatch.conf
    one

    one

    one
```
```
tail -f /tmp/date.log
2 :: Thu Aug 16 16:43:30 CDT 2018
1 :: Thu Aug 16 16:43:30 CDT 2018
1 :: Thu Aug 16 16:43:33 CDT 2018
2 :: Thu Aug 16 16:43:33 CDT 2018
1 :: Thu Aug 16 16:43:34 CDT 2018
2 :: Thu Aug 16 16:43:34 CDT 2018
```
