### ISSUE TITLE
execpi "interval" number is not in seconds if update interval less than 1

### ISSUE THREAD

**Issue by plikhari** [brndnmtthws/conky#625]
In order to create a smooth motion with high frame rate we need to have a rather low `update_interval` - with a range of 0.04 to 0.07.

```coffee
${execpi 100000 ./conkywx.sh -c ./examples/vertical-scroller-weather . . .}
```
that value of 100000 roughly equates to 38 minutes or 2300 seconds

**Comment by lasers** [comment]
Issue worth mentioning https://github.com/brndnmtthws/conky/issues/239. This happens to you too?

**Comment by lasers** [comment]
@su8 We could close this today. Find out what's happening behind a (green) curtain.

**Comment by plikhari** [comment]
If you see #239 - I have stated - I do not have high cpu when running any scrolling.

It depends what you are showing on the conky window and the frequency of update will determine cpu usage. What is being discussed on #239 is natural and expected behaviour.

**Comment by su8** [comment]
The current code registers the sleeping numbers

https://github.com/brndnmtthws/conky/blob/84e1eec2ed53437bfca598a714ec81f4adc00d12/src/exec.cc#L256

https://github.com/brndnmtthws/conky/blob/84e1eec2ed53437bfca598a714ec81f4adc00d12/src/exec.cc#L322-L325

but in `pid_popen()` and/or `exec_cb` there is no option to respect the sleeping intervals.

**Comment by plikhari** [comment]
Yes I understand - it was just that I saw the value and wanted to see if there was a way to fix the glitch.

It would be great if we could have all config values in conky_info table and very simple dumb variables - nothing complicated like templateN.

**Comment by lasers** [comment]
@brndnmtthws Do you want to mention anything about this issue? Thx.
