### ISSUE TITLE
Does a new ${github_notifications} variable makes sence ?

### ISSUE THREAD

**Issue by su8** [brndnmtthws/conky#636]
I'm willing to write a new variable `${github_notifications}` that parses all unread github notifications and counts them up. 

Does it makes sense to add it in conky :grey_question: 

edit: How often it should call the github API to obtain the current notifications status, I've set it to 60 seconds.

**Comment by lasers** [comment]
Yes to all questions. :octocat:

**Comment by lasers** [comment]
Calm your titties down. Wait until we get this in first. :wink:
