### ISSUE TITLE
Feature request: Weather - OpenWeatherMap data

### ISSUE THREAD

**Issue by frisbee00** [brndnmtthws/conky#65]
I'm not sure whether this is the right place for a feature request.

Fetch weather data from http://openweathermap.org/.
This looked like a good idea.

Useful links:
http://openweathermap.org/api
http://openweathermap.org/current
http://openweathermap.org/weather-conditions

**Comment by lasers** [comment]
Closing this due to duplicate https://github.com/brndnmtthws/conky/issues/210 even although you were the first one to request this. \o/
