### ISSUE TITLE
Choose CPUs  to make average data

### ISSUE THREAD

**Issue by Ygarr** [brndnmtthws/conky#652]
We can get now common average data for all CPUs and pass it into LUA, or we can get data for  separate CPU e.g. cpu0, cpu1..... cpuN.

How Can we get for 4 CPUs( cpu0 cpu1 cpu2 cpu3) get (cpu0+cpu1)/2  or (cpu2+cpu3)/2
to get 2 averaged values from  4  CPU? (And how pass it to LUA)

**Comment by plikhari** [comment]
You can do something like this in LUA script 
```lua
local ct = {}

ct[1] = tonumber(conky_parse('${cpu cpu1}'))
ct[2] = tonumber(conky_parse('${cpu cpu2}'))
ct[3] = tonumber(conky_parse('${cpu cpu3}'))
ct[4] = tonumber(conky_parse('${cpu cpu4}'))

local avg1 = (ct[1] + ct[2])/2
local avg2 = (ct[3] + ct[4])/2

print('avg 1: ' .. avg1, ct[1], ct[2])
print('avg 2: ' .. avg2, ct[3], ct[4])
```

**Comment by Ygarr** [comment]
Just tried but no success(arg or name not suitable), if it is interesting and your please - mine config:

[Conky_Antergos.zip](https://github.com/brndnmtthws/conky/files/2363708/Conky_Antergos.zip)

**Comment by plikhari** [comment]
Here is the corrected file - and should work. I have changed a few things to dot notation. Also keep in mind the count starts with `cpu1` while `cpu0` is average of all your cpus. The data for cpu 3 and 4 is commented out as you just need data for 2 cpus.

Kindly close this issue if things are working as desired.


[clock_rings.lua.zip](https://github.com/brndnmtthws/conky/files/2364819/clock_rings.lua.zip)

**Comment by lasers** [comment]
@plikhari Thanks for the help. I think we're done here. Kindly closing this issue.
