### ISSUE TITLE
New variables?

### ISSUE THREAD

**Issue by bad-interpreter** [brndnmtthws/conky#655]
I'm using conky with these build options:

```
$ conky -v
conky 1.10.8_pre compiled lun 16 lug 2018, 13.24.10, CEST for Linux 4.14.55-zion x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib64/conky


 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * RSS
  * Weather (METAR)
  * Weather (XOAP)
  * wireless
  * support for IBM/Lenovo notebooks
  * nvidia
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support

 Lua bindings:
  * Cairo
  * Imlib2
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * Xshape extension (click through)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * Audacious
  * MPD
  * MOC

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256
```

I found some new variables at the bottom of the variables list in [Configuration variables](https://github.com/brndnmtthws/conky/wiki/Configuration-Variables) I'm giving them a try, but they seem not to work:

```
conky: unknown variable '$num_led'
conky: unknown variable '$caps_led'
conky: unknown variable '$scroll_led'
conky: unknown variable '$kb_layout'
conky: unknown variable '$mouse_speed'
conky: unknown variable '$password'
conky: unknown variable '$freq2'
```

What am I missing? I'm using the latest stable release!

**Comment by lasers** [comment]
You're using stable release. Try the current master.

```bash
git clone https://github.com/brndnmtthws/conky
cd conky
mkdir -p build
cd build
cmake ..
make -j4  # 4 cores to run in parallel
src/conky -c ~/conky.conf # <-- your config goes here
```
The wiki need to be updated with new variables.
* `key_caps_lock`
* `key_num_lock`
* `key_num_lock`
* `keyboard_layout`

**Comment by bad-interpreter** [comment]
The master branch build works well with those new variables. I think they have to be tagged as "only in master branch" in the wiki.
You wrote "key_num_lock" twice, I think you intended "key_scroll_lock". It actually gives me an "Off" value, but it never changes!

**Comment by lasers** [comment]
I copied and pasted lines. Yeah, I meant `scroll`. I think `scroll` is disabled most of time.
You can try few things.
* `xset led named "Scroll Lock"` (toggle on)
* `xset -led named "Scroll Lock"` (toggle off)
* `xmodmap -e 'add mod3 = Scroll_Lock'` (enable scroll_lock ; untested)

**Comment by bad-interpreter** [comment]
works perfectly!

thanks
