### ISSUE TITLE
Disk input ouput in lua  rings

### ISSUE THREAD

**Issue by Ygarr** [brndnmtthws/conky#656]
I found that transferring a diskio data to an LUA  script with other parameters does not make the desired effect and result. Is there any possibility at all?
My script is in attach(wanna diskio instea
[Big_lua.zip](https://github.com/brndnmtthws/conky/files/2386619/Big_lua.zip)
d of battery )
![2018-09-16-163755_467x571_scrot](https://user-images.githubusercontent.com/14309871/45597060-0353ea00-b9cf-11e8-8ada-132f5ae0165b.png)

**Comment by dbriba** [comment]
Have you error when you launch your conky with consola ?

**Comment by Ygarr** [comment]
hmm no,  if I change 'diskio' to something random  than I got - conky: unknown variable '$random'

**Comment by lasers** [comment]
`exec echo $(($RANDOM % 100))` should give you `1-100` random. Problem with IO % is that script (or program) may have to keep doing calculation between start of the script/program or from boot time. 

grep 'sda ' /proc/diskstats 
grep 'sda ' /proc/diskstats 

`cat /proc/diskstats`  # output
https://www.kernel.org/doc/Documentation/ABI/testing/procfs-diskstats

Tools like `iostat` do their own calculations. Maybe if you use `cut`, `awk`, etc on those tools, then you can have some numbers to work with... but it won't be percents.

If you feel `1-100` random percents is a "good enough" replacement, please close this. Thanks.
