### ISSUE TITLE
Exclude icons from space occupied by conky?

### ISSUE THREAD

**Issue by ghost** [brndnmtthws/conky#663]
I am sorry if this is answered already somewhere (and/but I did search the bug tracker) but is there a way of preventing this sort of thing, please?

![image](https://user-images.githubusercontent.com/9998846/46577166-98973c80-c9d7-11e8-9ff3-67ca7ab3a8ae.png)

Note how the icon overlaps - almost, anyway - the conky.

I can set

`own_window_type = "panel",`

but then no _windows_ - not just _icons_ - can overlap any conky. Nor does `minimum_height` help, as one can see from this image:

![image](https://user-images.githubusercontent.com/9998846/46577141-02631680-c9d7-11e8-9903-7922dbf7a85a.png)

**Comment by lasers** [comment]
What about `own_window_type = "dock"`?

**Comment by CottonEaster** [comment]
No dice, I am afraid:

```
own_window_type = "dock",
own_window_hints = "undecorated,below,sticky,skip_taskbar,skip_pager",
draw_borders = true,
-- Draw borders around text. Useful for DEBUGGING.
```

![image](https://user-images.githubusercontent.com/9998846/47271593-bb4a5900-d572-11e8-8409-d06b6b155540.png)

**Comment by lasers** [comment]
Do you have a config? It looks like you're running MATE? I can try and mess around with it, but I don't guarantee anything.

**Comment by CottonEaster** [comment]
Thanks. I do have a config - a large one that runs lua scripts, bash scripts, and some compiled C. I am using Cinnamon. My config is [here](https://pastebin.com/Gtp4Mc4Y). Thank you. I would not be suprised were the problem to owe to Cinnamon.
