### ISSUE TITLE
no transparent own_window_type desktop // KDE - Plasma

### ISSUE THREAD

**Issue by cmddroid** [brndnmtthws/conky#665]
Antergos
KDE 5.50.0 / Plasma 5.13.5
Conky 1.10.8 https://pastebin.com/cWpEW2Uc
conkrc https://pastebin.com/uXN37PdD

**Comment by dbriba** [comment]
Change that : 
own_window_transparent no 
by
own_window_transparent yes 
and also
 own_window_argb_value 100
by 
own_window_argb_value 0

**Comment by lasers** [comment]
@cmddroid Update on this issue, please. Does it work for you? Thx. :-)

**Comment by cmddroid** [comment]
Sorry, no effect for me

**Comment by lasers** [comment]
@cmddroid Hi. You can try a new setting `draw_blended = true/false` in `conky 1.11.0` as it's related to transparent. You should play with other settings too. Here's your config in the new format too. Please let me know if this solves your issue. Thank you.
```
conky.config = {
-- Elegant Conky settings #
	background = false,
	update_interval = 1,
	total_run_times = 0,

	cpu_avg_samples = 2,
	net_avg_samples = 2,

	override_utf8_locale = true,

	double_buffer = true,
	no_buffers = true,

	text_buffer_size = 2048,

-- Window specifications #
	own_window_class = 'conky-semi',
	own_window_class = 'normal',
	own_window = true,
	own_window_type = 'desktop',
	own_window_transparent = false,
	own_window_hints = 'undecorated,below,skip_taskbar,skip_pager',
	own_window_argb_visual = true,
	own_window_argb_value = 100,

	border_inner_margin = 0,
	border_outer_margin = 0,

	minimum_width = 200, minimum_height = 250,
	maximum_width = 200,

	alignment = 'top_right',
	gap_x = 10,
	gap_y = 35,

-- Graphics settings #
	draw_shades = false,
	draw_outline = false,
	draw_borders = false,
	draw_graph_borders = false,

-- Text settings #
	use_xft = true,
	font = 'DejaVu Sans:size=9',
	xftalpha = 0.8,
	text_buffer_size = 2048,

	uppercase = false,
	temperature_unit = 'celsius',
	default_color = '#FFFFFF',

};

conky.text = [[
${font zekton:style=Bold:pixelsize=14}SYSTEM${font  Snap.se:size=8} ${color 1783B4}${hr}${color}
${voffset 2}${font OpenLogos:size=12}u${font}   OS: ${alignr}${execi 10800 ~/.conky/scripts/version}
${font StyleBats:size=12}q${font}   Kernel: ${alignr}${kernel}
${font StyleBats:size=12}x${font}   Hostname: ${alignr}${nodename}
${font StyleBats:size=12}p${font}   Uptime: ${alignr}${uptime}
${font StyleBats:size=12}k${font}   Processes: ${alignr}${processes} ($running_processes running)

${font zekton:style=Bold:pixelsize=12}SYSTEM LOAD${font  Snap.se:size=8} ${color 1783B4}${hr}${color}
${font StyleBats:size=12}A${font}   CPU1: ${cpu cpu1}% ${alignr}${freq1} MHz
${color 1783B4}${cpubar 8 cpu1}${color}
${font StyleBats:size=12}A${font}   CPU 2: ${cpu cpu2}% ${alignr}${freq2} MHz
${color 1783B4}${cpubar 8 cpu2}${color}
${font StyleBats:size=12}A${font}   CPU3: ${cpu cpu3}% ${alignr}${freq3} MHz
${color 1783B4}${cpubar 8 cpu3}${color}
${font StyleBats:size=12}A${font}   CPU4: ${cpu cpu4}% ${alignr}${freq4} MHz
${color 1783B4}${cpubar 8 cpu4}${color}

${font StyleBats:size=12}g${font}   RAM ${alignr}$mem / $memmax ($memperc%)
${color 1783B4}${membar 8}${color}
${font StyleBats:size=12}j${font}   SWAP ${alignr}$swap / $swapmax ($swapperc%)
${color 1783B4}${swapbar 8}${color}

${font zekton:style=Bold:pixelsize=14}TOP PROCESSES${font Snap.se:size=8} ${color 1783B4}${hr}${color}
Highest CPU/MEM $alignr CPU MEM
${top name 1}$alignr${color 1783B4}${top cpu 1}${color}${top mem 1}
${top name 2}$alignr${color 1783B4}${top cpu 2}${color}${top mem 2}
${top name 3}$alignr${color 1783B4}${top cpu 3}${color}${top mem 3}
${top name 4}$alignr${color 1783B4}${top cpu 4}${color}${top mem 4}
${top name 5}$alignr${color 1783B4}${top cpu 5}${color}${top mem 5}

${font zekton:style=Bold:pixelsize=12}FILESYSTEM ${font Snap.se:size=8} ${color 1783B4}${hr}${color}
${voffset 4}${font StyleBats:size=12}4${font}   Root: ${alignr}${fs_free /} / ${fs_size /}
${voffset 4}${color 1783B4}${fs_bar 8 /}${color}
${voffset 4}${font StyleBats:size=12}4${font}   Home: ${alignr}${fs_free /dev/sda3} / ${fs_size /home}
${voffset 4}${color 1783B4}${fs_bar 8 /home}${color}

${font zekton:style=Bold:pixelsize=14}NETWORK${font  Snap.se:size=8} ${color 1783B4}${hr}${color}
${if_existing /proc/net/route wlp2s0b1}
${voffset -6}${font PizzaDude Bullets:size=12}O${font}   Up: ${upspeed wlp2s0b1} kb/s ${alignr}${upspeedgraph wlp2s0b1 8,60 1783B4 FFFFFF}
${voffset 4}${font PizzaDude Bullets:size=12}U${font}   Down: ${downspeed wlp2s0b1} kb/s ${alignr}${downspeedgraph wlp2s0b1 8,60 1783B4 FFFFFF}
${voffset 4}${font PizzaDude Bullets:size=12}N${font}   Upload: ${alignr}${totalup wlp2s0b1}
${voffset 4}${font PizzaDude Bullets:size=12}T${font}   Download: ${alignr}${totaldown wlp2s0b1}
${voffset 4}${font PizzaDude Bullets:size=12}Z${font}   Signal: ${wireless_link_qual wlp2s0b1}% ${alignr}${wireless_link_bar 8,60 wlp2s0b1}
${voffset 4}${font PizzaDude Bullets:size=12}a${font}   Local Ip: ${alignr}${addr wlp2s0b1}
${voffset 4}${font PizzaDude Bullets:size=12}a${font}   Public Ip: ${alignr}${execi 10800 ~/.conky/scripts/conkyIp}${else}${if_existing /proc/net/route eth0}
${voffset -6}${font PizzaDude Bullets:size=12}O${font}   Up: ${upspeed eth0} kb/s ${alignr}${upspeedgraph eth0 8,60 1783B4 FFFFFF}
${voffset 4}${font PizzaDude Bullets:size=12}U${font}   Down: ${downspeed eth0} kb/s ${alignr}${downspeedgraph eth0 8,60 1783B4 FFFFFF}
${voffset 4}${font PizzaDude Bullets:size=12}N${font}   Upload: ${alignr}${totalup eth0}
${voffset 4}${font PizzaDude Bullets:size=12}T${font}   Download: ${alignr}${totaldown eth0}
${voffset 4}${font PizzaDude Bullets:size=12}a${font}   Local Ip: ${alignr}${addr eth0}
${voffset 4}${font PizzaDude Bullets:size=12}a${font}   Public Ip: ${alignr}${execi 10800 ~/.conky/scripts/conkyIp}${else}${if_existing /proc/net/route eth1}
${voffset -6}${font PizzaDude Bullets:size=12}O${font}   Up: ${upspeed eth1} kb/s ${alignr}${upspeedgraph eth1 8,60 1783B4 FFFFFF}
${voffset 4}${font PizzaDude Bullets:size=12}U${font}   Down: ${downspeed eth1} kb/s ${alignr}${downspeedgraph eth1 8,60 1783B4 FFFFFF}
${voffset 4}${font PizzaDude Bullets:size=12}N${font}   Upload: ${alignr}${totalup eth1}
${voffset 4}${font PizzaDude Bullets:size=12}T${font}   Download: ${alignr}${totaldown eth1}
${voffset 4}${font PizzaDude Bullets:size=12}a${font}   Local Ip: ${alignr}${addr eth1}
${voffset 4}${font PizzaDude Bullets:size=12}a${font}   Public Ip: ${alignr}${execi 10800 ~/.conky/scripts/conkyIp}${else}
Network Unavailable${endif}${endif}${endif}]];
```

**Comment by lasers** [comment]
@femarschall What distro? I'm seeing `libcurl4-gnutls-dev` in `.travis.yml` and `Dockerfile` so it might be working okay already. My wild assumption is that you might be missing one of the `curl`*`-dev` package. Either way, we might want more information from you about this error.

**Comment by femarschall** [comment]
I use:

- KDE  neon User Edition 5.14, based on Ubuntu 18.04
- Plasma 5.14.4

excuse me for my lack of experience..
I now installed all the dependencies listed on the Dockerfile but it failed on make:
[ 91%] Linking CXX executable conky
CMakeFiles/conky.dir/common.cc.o: In function `print_github(text_object*, char*, unsigned int)':
/home/marschall/Downloads/conky-master/src/common.cc:766: undefined reference to `curl_global_init'
/home/marschall/Downloads/conky-master/src/common.cc:767: undefined reference to `curl_easy_init'
/home/marschall/Downloads/conky-master/src/common.cc:770: undefined reference to `curl_easy_setopt'
...

**Comment by lasers** [comment]
@npyl @brndnmtthws Can you look into this?

**Comment by brndnmtthws** [comment]
Works fine here, with libcurl4-gnutls-dev:amd64 (7.58.0-2ubuntu3.5). `cmake` shows:

```
-- Checking for module 'libcurl'
--   Found libcurl, version 7.58.0
```

**Comment by femarschall** [comment]
damn.. this is embarassing...
Probably something that I installed turned compositor off.

After turning it on by pressing alt + shift + F12 transparency started working again.

**Comment by lasers** [comment]
@femarschall and/or @cmddroid: Can you try and play with @cmddroid's config [[link]](https://github.com/brndnmtthws/conky/issues/665#issuecomment-445883862) to see if we can resolve this issue? Hopefully, @cmddroid's problem was that he/she had his/her compositor off too. Otherwise, I think we need more details about what's not working or such.

**Comment by CareF** [comment]
Meet similar thing. 
With compositor on, I can get transparent conky with ``own_window_type = 'normal'``, but for ``own_window_type = 'desktop'`` it's not working.. 
The same config file works fine on Gnome. 
``own_window_type = 'normal'`` doesn't allow conky to show on show-desktop.

**Comment by 01885404983** [comment]
My friend has the same problem: if he uses `own_window_type = 'override'` conky crashes, with  `own_window_type = 'normal'`, conky will be minimized when pressing Super+D, and in the case of `own_window_type = 'desktop'`, no transparency even with compositor on. I use OpenBox and have no problem with that config file, he uses Plasma on Manjaro. The config file is the one from Gotham theme converted to new format.

**Comment by sebma** [comment]
I managed to build `conky` on Ubuntu 18.04 by installing these dependencies : 
```bash
$ sudo apt install -V cmake libncurses5-dev libx11-dev libxdamage-dev libxinerama-dev libxext-dev libcurl4-openssl-dev liblua5.3-dev # as documented at "https://github.com/brndnmtthws/conky/wiki/Installation"
$ sudo apt install -V libfreetype6-dev libxft-dev libimlib2-dev # Found thanks to "apt-cache search"
$ cmake .. && make && sudo checkinstall
```

Regarding the `own_window_type = 'desktop'`, I've tried everything given above, nothing seem to make it transparent and relative placement to the taskbar doesn't work either.

**Comment by simonwiles** [comment]
I'm having the same problem -- transparency works with `own_window_type = 'normal'` and `own_window_type = 'override'`, but nothing I've tried will make it work with `own_window_type = 'desktop'` on plasma.  Compositor is enabled.  Conky `v1.11.6`.

**Comment by ariefra** [comment]
I use following to work around this issue
```
    own_window_type = 'dock',       
    own_window_argb_visual = true,  
    own_window_argb_value = 128,  
```

**Comment by Rabcor** [comment]
There's actually a super easy solution to this problem:
(Set conky window type to normal or dock; then configure kwin to override it as desktop.)
![image](https://user-images.githubusercontent.com/5684325/186060120-0fae99ab-5007-40bb-af2c-b47588a5cc39.png)

**Comment by whtyger** [comment]
@Rabcor Though it is a good idea, it works the same way as setting `own_window_type = 'desktop'` in Conky's configuration file.
