### ISSUE TITLE
Pass conky object to external script

### ISSUE THREAD

**Issue by sirfoga** [brndnmtthws/conky#666]
I have a conky object, and I want to pass it as parameter of a `bash` / `lua` script. How do I do it?

# Example:
**conky object**: `${tcp_portmon 1 61000 lport 0}`
i.e the port of the first `tcp` connection

**script**: `$ lsof -i :<PORT> | sed -n 2p | awk '{print $1}'`
i.e finds the process with that port

# What I tried (unsuccessfully):
- `${exec lsof -i :${tcp_portmon 1 61000 lport 0} | sed -n 2p | awk '{print $1}'}`
- `${exec echo $(lsof -i :${tcp_portmon 1 61000 lport 0} | sed -n 2p | awk '{print $1}')}`
- `${lua conky_proc_port ${tcp_portmon 1 61000 lport 0}}`, where `conky_proc_port` simply outputs the parameter

How do I do it?

PS: for reference, [here](https://stackoverflow.com/questions/52707979/pass-conky-object-to-external-script) is the link to the Stackoverflow question

**Comment by varingst** [comment]
If all you want is to see what conky evaluates the expression to, you can create a conkyrc that only outputs to console, and run conky only one tick:

`$ conky -i 1 -c special_conkyrc -t '${tcp_portmon 1 61000 lport 0}'`

That said, conky is almost certainly the wrong tool for the job here. Try `ss -tnp` or `netstat -tnp`
