### ISSUE TITLE
Executing certain X applications causes '(null)' to be printed on screen

### ISSUE THREAD

**Issue by andreas--e** [brndnmtthws/conky#67]
Hi, just found a bug in latest conky, which probably was there in previous versions as well.

Here's my .conkyrc, stripped down to the max:

double_buffer yes
own_window yes
own_window_class Conky
own_window_hints undecorated,sticky # ,skip_taskbar
own_window_transparent yes

background yes
total_run_times 0

use_xft yes
xftfont Bitstream Vera Sans:size=7
xftalpha 0.85
override_utf8_locale yes

minimum_size 150
maximum_width 480

border_width 1

uppercase no

TEXT
\
${texeci 6000 /usr/bin/xclock}
\
--other conky stuff goes here---

And it's not the interval that causes this. Happens with 600, 6k and 60k likewise.
xclock itself executes very well in threaded mode and (unlike with $pre_exec, $exec, $execi, $execp) it will not block conky from appearing.

Just this '(null)' is a bit disturbing, to put it mildly. Wish I knew what triggers this, and why.
Surely it is _not_ any kind of stderr output (tried 2>/dev/null to no avail).

**Comment by lasers** [comment]
3 years 11 month passed. Can you determine if you're still having this problem today on `1.10.8` or preferably `1.10.9_pre` (git)?  Thank you.

**Comment by lasers** [comment]
Hi. I tested the config above. For historical purposes, here's the new syntax config.
```lua
conky.config = {
    out_to_x=yes,   -- custom
    out_to_console=yes, -- custom
    double_buffer=yes,
    own_window=yes,
    own_window_class=Conky,
    own_window_hints='undecorated,sticky',
    own_window_transparent=yes,
    background=yes,
    total_run_times=0,
    use_xft=yes,
    xftfont='Bitstream Vera Sans:size=7',
    xftalpha=0.85,
    override_utf8_locale=yes,
    minimum_size=150,
    maximum_width=480,
    border_width=1,
    uppercase=no,
}
conky.text = [[
    ${uptime}
    ${uptime_short}
    ${user_names}
    ${processes}
    ${texeci 10 /usr/bin/xclock}
]]
```

I did not see any `(null)` on the screen nor in the console. I don't view this a bug either and I think that users shouldn't add X11 apps directly in the config. It should fare better if we put them in scripts instead where it can decide what to do if the process is still running, to return empty or custom strings, and more.

3 years 11 months ago passed and a lot has changed already. Conky went through a major rewritten and several iterations too so I'm going ahead with closing this stale issue. Thank you.
