### ISSUE TITLE
IRC shows up as ${irc}

### ISSUE THREAD

**Issue by RossComputerGuy** [brndnmtthws/conky#670]
I'm trying to make conky connect to the Arch Linux IRC and I have this snippet in my `/etc/conky/conky.conf` file. But it shows up as ${irc}, what am I doing wrong and how do I fix it?
```
${color grey}Arch Linux IRC:
 $color${irc chat.freenode.net:6667 #archlinux}
```

**Comment by SpaceboyRoss01** [comment]
There is a command called irc:
![image](https://user-images.githubusercontent.com/19699320/47225117-22e58600-d372-11e8-94be-4d00ad2236f6.png)

**Comment by dbriba** [comment]
Excuse me, je n'avais pas vu this command in my setting.
Have you the 6667 port open in your firewall ?

**Comment by SpaceboyRoss01** [comment]
Port 6667 is open, I compiled with IRC support now and now the IRC command doesn't show up as ${IRC} but it doesn't display anything at all.

**Comment by dbriba** [comment]
May be the name of the channel is not #archlinux bur other name.

**Comment by SpaceboyRoss01** [comment]
No, it is. https://wiki.archlinux.org/index.php/IRC_channel

**Comment by dbriba** [comment]
In your link I see that:

> In order to reduce spam #archlinux and #archlinux-offtopic have the channel mode set to +r and +q $~a. This means you have to be identified via NickServ to be able to join these channels and send messages, respectively. If you are not registered and identified, you will be forwarded to #archlinux-unregistered.

May be you must be identified to see the channel

**Comment by SpaceboyRoss01** [comment]
Well, how do I do that?

**Comment by lasers** [comment]
I don't have access to conky right now to play with ${irc}. You can try
joining a random channel (e.g. ###conky) along with your IRC client there
to see if it's working okay. I'm not sure about registration thing, but you
may have better luck with ii and some other conky variable like {cat} or
{exec tail}. http://manpages.ubuntu.com/manpages/latest/en/man1/ii.1.html
The better solution probably might be to just run irssi or weechat inside
screen or tmux so you would be able to do more than just reading messages.

**Comment by SpaceboyRoss01** [comment]
I know +r is set but I just need a way to log in.--Sent from Yandex.Mail for mobile19.10.2018, 22:26, "dbriba" <notifications@github.com>:The channel is set to +r
See here : https://freenode.net/kb/answer/channelmodes

r : Prevents users who are not identified to services from joining the channel.

**Comment by dbriba** [comment]
I see that in your link : 

> k (password)	
To enter the channel, you must specify the password on your /join command. Keep in mind that modes locked with ChanServ's MLOCK command can be seen by anyone recreating the channel; this includes keys. Also keep in mind that users being on the channel when +k is set will see the key as well.

try this : ${irc chat.freenode.net:6667 #archlinux +k your_password}

**Comment by SpaceboyRoss01** [comment]
It didn’t work--Sent from Yandex.Mail for mobile19.10.2018, 22:40, "dbriba" <notifications@github.com>:I see that in your link :

k (password)
To enter the channel, you must specify the password on your /join command. Keep in mind that modes locked with ChanServ's MLOCK command can be seen by anyone recreating the channel; this includes keys. Also keep in mind that users being on the channel when +k is set will see the key as well.

try this : ${irc chat.freenode.net:6667 #archlinux +k your_password}

**Comment by dbriba** [comment]
Maybe your_password must are between parenthesis ()

**Comment by lasers** [comment]
If you looked at `IRCSERVERPASS` variable in `src/irc.cc` code, you will see that it's not being used nor verified anywhere so it's probably not possible to identify / join registered channels. Just a heads up.

No idea what will happen to this issue. You might have better luck (fifo) piping out irssi/weechat/others to conky instead.

**Comment by Llewellynvdm** [comment]
Has anyone been able to get this to work? I would really like to use this.

There is a crazy work around via [Telegram-IRSSI](https://github.com/stargo/irssi2telegram) bridge, and then via [telegram-messenger-cli](https://github.com/vysheng/tg/tree/test#telegram-messenger-cli-) stream to Conky. Close to madness... but it works. Just seems like there should be a easier way.

**Comment by brndnmtthws** [comment]
The irc support is not enabled unless you build with `BUILD_IRC=ON`. It depends on a library called `libircclient`, and I'm not sure of the status of it at the moment.

**Comment by SpaceboyRoss01** [comment]
I had built it with irc enabled.04.01.2019, 12:19, "Brenden Matthews" <notifications@github.com>:The irc support is not enabled unless you build with BUILD_IRC=ON. It depends on a library called libircclient, and I'm not sure of the status of it at the moment.

**Comment by brndnmtthws** [comment]
Let me try testing it to see if it works. If not, I'll probably remove the code unless someone wants to shepherd it.
