### ISSUE TITLE
Format percentages of `top_*` commands

### ISSUE THREAD

**Issue by iago-lito** [brndnmtthws/conky#674]
I would be glad to save a few characters if I could transform the output of `${top_mem cpu 1}`

    ` 25,54`

Into something more compact like:

    ` 26`

But I'm not sure that the `pad_percent` option is the one I need, because I can see no effect of setting it to 0, 1 or 5. How could I make this output shorter and get rid of unwanted decimals?

**Comment by lasers** [comment]
PRs welcome. Maybe something like...

* `${top_mem cpu 1}` --> `25,54`. 
* `${round ${top_mem cpu 1} 0}` --> `26`. 
* `${round ${top_mem cpu 1} 1}` --> `25.6`.

**Comment by iago-lito** [comment]
I see the idea. I may try to have a look into this :)
