### ISSUE TITLE
conky report error on BAT0 invalid path, but I didn't use BAT0 in config

### ISSUE THREAD

**Issue by stardiviner** [brndnmtthws/conky#675]
When I start conky from terminal , it reports error:
```
can't open /sys/class/power_supply/BAT0/uevent: No such file or directory
conky: can't open /proc/acpi/battery/BAT0/state: No such file or directory
conky: can't open /proc/apm: No such file or directory
```
But I didn't use `BAT0` in my conky config file:
```
# Battery:  ${apcupsd_charge}
${voffset 140}
${offset 1250}${color1}${font DejaVu Sans Mono:size=8}Battery: ${color2}${battery BAT1}
${offset 1250}${color2}${font DejaVu Sans Mono:size=8}${battery_time BAT1}
${offset 1250}${color2}${font DejaVu Sans Mono:size=8}${battery_bar 6,100 BAT1} ${battery_percent BAT1}%
```

And I only have `BAT1`:
```
#+begin_src sh
ls /sys/class/power_supply/ | grep "BAT"
#+end_src

#+RESULTS[<2018-04-06 10:23:04> ffe9120fc7c9f4905f02fa416d150829ed2c0a76]:
: BAT1
```
In `/sys/class/power_supply/BAT1`. I got:
```
#+begin_src sh
ls /sys/class/power_supply/BAT1
#+end_src

#+RESULTS[<2018-04-06 10:23:39> b9ab96ea25cf3a1d6160c584edf2421d81016a38]:
#+begin_example
alarm
capacity
capacity_level
cycle_count
device
energy_full
energy_full_design
energy_now
manufacturer
model_name
power
power_now
present
serial_number
status
subsystem
technology
type
uevent
voltage_min_design
voltage_now
#+end_example
```

**Comment by lasers** [comment]
@stardiviner So I tried this on my computer (no battery). They all printed `BAT1` for me. Maybe, we need more information or your config. What conky version? `conky -V | head -n1`.
```
conky: desktop window (25a) is root window
conky: window type - desktop
conky: drawing to created window (0x3800001)
conky: can't open /sys/class/power_supply/BAT1/uevent: No such file or directory
conky: can't open /proc/acpi/battery/BAT1/state: No such file or directory
conky: can't open /proc/apm: No such file or directory
conky: can't open /sys/class/power_supply/BAT1/uevent: No such file or directory
conky: can't open /proc/acpi/battery/BAT1/state: No such file or directory
```
Seems like most of them are in in `core.cc`.
```
src/core.cc:    strncpy(bat, "BAT0", 5);
src/core.cc:    strncpy(bat, "BAT0", 5);
src/core.cc:  END OBJ(battery_status, 0) obj->data.s = strndup(arg ? arg : "BAT0", text_buffer_size.get(*state));
src/core.cc:    strncpy(bat, "BAT0", 5);
src/core.cc:    strncpy(bat, "BAT0", 5);
src/core.cc:    strncpy(bat, "BAT0", 5);
src/core.cc:    strncpy(bat, "BAT0", 5);
src/core.cc:    strncpy(bat, "BAT0", 5);
src/core.cc:  END OBJ(battery_status, 0) obj->data.s = strndup(arg ? arg : "BAT0", text_buffer_size.get(*state));
src/core.cc:    strncpy(bat, "BAT0", 5);
src/core.cc:    strncpy(bat, "BAT0", 5);
src/core.cc:    strncpy(bat, "BAT0", 5);
```
But I wonder if it is because of `update_interval_on_battery` since this seems hardcoded.
```cc
#endif /* BUILD_XSHAPE */

	last_update_time = 0.0;
	next_update_time = get_time() - fmod(get_time(), active_update_interval());
	info.looped = 0;
	while (terminate == 0
			&& (total_run_times.get(*state) == 0 || info.looped < total_run_times.get(*state))) {
		if(update_interval_on_battery.get(*state) != NOBATTERY) {
			char buf[64];

			get_battery_short_status(buf, 64, "BAT0");
			on_battery = (buf[0] == 'D');
		}
		info.looped++;
```
Do you still get that message with `default.conf`?

**Comment by stardiviner** [comment]
My conky version: `conky 1.11.0_pre`
This error does not appears with default config `/usr/share/doc/conky-1.11.0_pre/conky.conf`.
With `update_interval_on_batter` added in the default config. I still get same error.

**Comment by lasers** [comment]
What caused `BAT0` in your config. Was it `update_interval_on_battery` or one of the `battery` variables? If latter, does it happen with all of them or with one of the variables?

Also, see `detect_battery`. Maybe you need to add `detect_battery = "BAT0,BAT1"` to your config?

**Comment by stardiviner** [comment]
> What caused BAT0 in your config? Was it update_interval_on_battery or one of the battery variables? If latter, does it happen with all of them or with one of the variables?

I only added one line `update_interval_on_battery = 2` in default config `/usr/share/doc/conky-1.11.0_pre/conky.conf`. Then start conky with `conky -c /usr/share/doc/conky-1.11.0_pre/conky.conf`. Before adding that line, no this error. After adding that line, this error raised.

After adding line `detect_battery = "BAT0,BAT1"`. Problem still persists. BTW, I indeed don't have that file. I even don't have `/proc/acpi/battery/` path.

**Comment by AmadeusGhost** [comment]
I have the same problem. Have you solved it?

**Comment by Tomunu** [comment]
I was looking into this a little (no code yet). I didn't find the solution to the problem, but I found out some things. 

On my system (running Arch Linux (5.1.7-arch1-1-ARCH)) I tried out the partial config from the original question. My laptop battery is numbered `BAT0`, so the `BAT1` in the config causes conky errors, but none of them defaults to `BAT0` (whether or not the `update_interval_on_battery` option is used). 

Having the actual config files that display this problem (and the configs where the problem doesn't happen) might help.

**Comment by stardiviner** [comment]
I have `detect_battery = "BAT0,BAT1",` in my conky config. It should be detected.

**Comment by LinuxOnTheDesktop** [comment]
I have the same wrinkle - conky prints an error about the unavailability of `bat0` to the console, even though my conky script does not refer to that object.

My conky script is large and calls a great number of executables. But here is the relevant snippet:

```
${if_match "${battery BAT1}"=="charged"}\
[. . .]
${else}
[. . .]
${endif}
```

Note though that conky prints its warning early upon conky's start - _before_ the snippet is executed.

Conky 1.21.7-pre-788ac88b
PC: Framework 13 AMD
Kernel 6.8.0.45
Distro: Linux Mint 22

**Comment by Caellian** [comment]
The `detect_battery` should only contain batteries which you do have (i.e. not the ones you're getting warnings about them missing).

Code checks for all listed batteries.

I'm closing this issue as the only hardcoded place where "BAT0" is used is [when `battery` isn't given any arguments](https://github.com/brndnmtthws/conky/blob/b05810d439447666bb7a8c3823d94833cc282033/src/core.cc#L554). So this should only be caused by bad (default) `detect_battery` config option.

Let me know if you're still somehow getting these warning even after providing correct values for `detect_battery` and I'll reopen the issue.

**Comment by LinuxOnTheDesktop** [comment]
@Caellian 

Ah - I did not know of the `detect_battery` option. I find:

- the option it is an option for one's config file / the config part of one's conky script;
- the syntax is `detect_battery = "BAT0"` or  `detect_battery = "BAT1"` or `detect_battery = "BAT0,BAT1"`;
- using the option suppressed the warning.

Thanks!

**Comment by Caellian** [comment]
> the syntax is detect_battery = "BAT0" or detect_battery = "BAT1" or detect_battery = "BAT0,BAT1";

Yup, `detect_battery` should be set to comma (`,`) separated list of batteries listed by commands I provided earlier, default value is `BAT0`.
