### ISSUE TITLE
segv on missing mailfile

### ISSUE THREAD

**Issue by DavidBiesack** [brndnmtthws/conky#68]
If a .conkyrc file uses

```
TEXT
${new_mails}
```

I get a segv with conky 1.9.0

**\* Error in `/usr/bin/X11/conky': double free or corruption (fasttop): 0x00000000009bc9b0 ***

I also get the segv if I use

```
mail_spool /path/to/my/mail/file
TEXT
$new_mails
```

It works if I use 

```
${new_mails /path/to/my/mail/file}
```

or

```
mail_spool /path/to/my/mail/file
TEXT
${new_mails}
```

**Comment by lasers** [comment]
3 years, 10 months passed. It's time for someone to close this issue. Thanks.
