### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by Mic92** [brndnmtthws/conky#684]
A user wanted to add a not-released revision as a new package in nixpkgs to get access to some bug fixes: https://github.com/NixOS/nixpkgs/pull/51147

I therefore wonder if it would be time for a new conky release instead?

**Comment by brndnmtthws** [comment]
I acknowledge the request, I'll try to get around to it soon :) Things have been busy for me recently. Please ping me again in a week or two if I haven't done it.

**Comment by lasers** [comment]
@brndnmtthws released [Conky v1.11.0 🎉](https://github.com/brndnmtthws/conky/releases/tag/v1.11.0) today.
