### ISSUE TITLE
Empty space in ${wireless_link_qual_perc}

### ISSUE THREAD

**Issue by orschiro** [brndnmtthws/conky#69]
Hi there,

I am using the following variables in my output:

```
Wifi: [${wireless_essid wls1}] [${wireless_link_qual_perc wls1}%] \
```
As you can see from the below screenshot, the above code is producing a space before the 44%.

![screenshot](https://cloud.githubusercontent.com/assets/170947/4738459/36d78070-59fd-11e4-81db-58bae2cd5e11.png)

Any ideas where this empty space is coming from?

```
conky 1.9.0-4
Arch Linux 64-bit
```

**Comment by orschiro** [comment]
Sorry to come back with this issue. Magically the issue returned back. Please see the space between the network ESSID and the percentage sign:
![image](https://cloud.githubusercontent.com/assets/170947/6017764/87489c48-ab91-11e4-8f27-cb553ac4edb7.png)

```
# avoid flicker
double_buffer yes

# own window to run simultanious 2 or more conkys
own_window  yes
own_window_transparent no
own_window_type dock
own_window_hints undecorated,below,sticky,skip_taskbar,skip_pager
own_window_title conky

# borders
draw_borders no

# shades
draw_shades no

# Avoid empty spaces
# https://github.com/brndnmtthws/conky/issues/69#issuecomment-60115548
use_spacer none

# position
gap_x 0
gap_y 0
alignment top_left
stippled_borders 0

# behaviour
update_interval 60

# colour
default_color d3cabc
# default_shade_color 000000
own_window_colour 2D2D2D

# font
use_xft yes
xftfont Droid Sans:style=bold:size=8
# Show umlauts
override_utf8_locale yes

# to prevent window from moving
use_spacer right
minimum_size 1040 0

TEXT
  ${alignr}${if_running flickrsmartsync}${font FontAwesome:size=9}${font}$endif \
  ${if_running rsync}${font FontAwesome:size=9}${font}  Rsync$endif \
  ${font FontAwesome:size=9}  ${font}${execpi 300 python ~/Bin/gmail.py} \
  ${font FontAwesome:size=9}  ${font}${fs_free} \
  ${font FontAwesome:size=9}  ${font}${battery BAT0} \
  ${font FontAwesome:size=9}  ${font}${wireless_essid wls1} ${wireless_link_qual_perc wls1}% \
  ${font FontAwesome:size=9}  ${font}${exec amixer sget Master | awk '/%/{}END{gsub(/[\[\]]/,""); print $5}'} ${exec amixer sget Master | awk '/%/{}END{gsub(/[\[\]]/,""); print $6}'} \
  ${font FontAwesome:size=9}  ${font}${execpi 3600 checkupdates | wc -l}  ${execpi 3600 cower -u | wc -l} \
  ${font FontAwesome:size=9}  ${font}${exec xkb-switch} \
  ${font FontAwesome:size=9}  ${font}${time %H:%M}  ${execpi 30 cat ~/.conkytimer}\
  ${font FontAwesome:size=9}  ${font}${time %a %d %b %Y}   
```

**Comment by Tucos** [comment]
Previously you said `use_spacer none` resolved the problem; your current config effectively has `use_spacer right`, which corresponds to the output (although i'm not sure it makes sense for 100%, but that's a different issue).
Note that you have `none` underneath "# Avoid empty spaces", but `right` underneath "# to prevent window from moving".

**Comment by orschiro** [comment]
@Tucos 

Apologize for this unnecessary message. I copied a configuration snippet from someone else and overlooked completely that he had already set a `use_spacer right`. I removed it and now everything is fine again. 

Thank you!

Robert
