### ISSUE TITLE
should conky be printing "defining struts" 

### ISSUE THREAD

**Issue by oniGino** [brndnmtthws/conky#699]
> conky: defining struts
> conky: defining struts
> conky: defining struts
> conky: defining struts
> conky: defining struts

I'm not sure how useful this output is, there is not any way to stop it so long as you are using "panel" window type.

it would be nice if conky didn't print this at all, or if its an actual error, it be an error that can be resolved.

https://github.com/brndnmtthws/conky/blob/a0d4393826b9775fb7b4b4c6b51d54fd32a36b91/src/conky.cc#L2123

Thank You

**Comment by npyl** [comment]
I think a `DBGP()` call would be more appropriate here!

**Comment by npyl** [comment]
It should now work as expected! :)
