### ISSUE TITLE
Enhancement request: Support for backslash in template definitions

### ISSUE THREAD

**Issue by andreas--e** [brndnmtthws/conky#70]
This request can be worded in a brief summary:

Currently, you must squeeze everything into one SINGLE LINE in template defininitions for them to work. (feels a bit like ancient CBM BASIC times :))

This is why I'd like to request the support for the backslash, so templates can be defined multi-line and (in particular the complex ones) can be more easily expanded and, if necessary, debugged.
Thanks for considering.

**Comment by lasers** [comment]
More than 4 years 1 month passed. I'm closing this stale issue. No progress has been made on this enhancement. Please reopen if you're still requesting this enhancement. Thank you. :)
