### ISSUE TITLE
Widgets with maximize and minimize buttons

### ISSUE THREAD

**Issue by hdawg12** [brndnmtthws/conky#702]
How can I get rid of the maximize and minimize buttons on a widget.  For example, the Mira_blue clock widget has both those buttons.  You can also move the widget around.  I like the look, but I want to get rid of that part.  Where in .conkyrc do I need to look at in order to change it.  

I looked online everywhere and also on here in the "Issues" section but I can't find an answer to this question.  

Thanks,

**Comment by hdawg12** [comment]
yup.  I tried them, but can you give me advice just in case I missed something?

**Comment by lasers** [comment]
@hdawg12 AFAIK that's the option. If it does not work, then I wonder what distro and DE/WM you are on. It is possible that some DE allows you to specify window rules. I'm certain KDE allows that.

`own_window_type` might not work on all DE/WM. I think LXDE is one of them. Changing `own_window_type` to `override` works perfectly for me on i3wm.

**Comment by hdawg12** [comment]
It worked.  I typed "own_window_type desktop"  I must have misread the legacy Documentation because I thought it said at first, desktop dock.  When it actually says desktop, dock(with a comma in-between them).  

Thanks,

**Comment by lasers** [comment]
No problem. You might want to switch to the newer config syntax while you're at it.

* Download https://github.com/brndnmtthws/conky/blob/master/extras/convert.lua 
* Make a backup just in case you wanted to keep the old one.
* Run `./convert.lua your_current_conkyrc`.
* Run `conky` with newer config syntax. :fire:

**Comment by hdawg12** [comment]
@lasers, sorry for the dumb question, where in that link do I go to download?  Do I use "git clone"?

**Comment by lasers** [comment]
`Raw` button on right side.
