### ISSUE TITLE
Short_units always true

### ISSUE THREAD

**Issue by X0rg** [brndnmtthws/conky#703]
Since Conky v1.11.0, units are always short, whatever `short_units`.

It was working fine in v1.10.8. This regression was introduced in fa5e56720faabe56627173cc28ccf7be3ddf4a3d.
This patch should be reverted, and another path should be proposed for #352.

Let me explain: `"%.*f%.1s"` format allow only one letter, the prefix (e.g. **G** or **M** or **K**).
`"%.*f%.3s"` allow 3 letters, the prefix and the unit (e.g. **GiB** or **MiB** or **KiB**).

So, since fa5e56720faabe56627173cc28ccf7be3ddf4a3d, when `short_units = false`, `width = 7` but `format = "%.*f%.1s"`.
`short_units` does not have the expected behavior anymore.
***
Example:
`short_units = true`
![short_true](https://user-images.githubusercontent.com/2873785/50052241-5e59c200-0121-11e9-84a5-8b4df8019cdb.png)

`short_units = false`
![shot_false](https://user-images.githubusercontent.com/2873785/50052242-5e59c200-0121-11e9-8f8d-d8523c5512c3.png)

Config:
```
conky.config = {
    alignment = 'top_left',
    background = false,
    border_width = 1,
    cpu_avg_samples = 2,
	default_color = 'white',
    default_outline_color = 'white',
    default_shade_color = 'white',
    draw_borders = false,
    draw_graph_borders = true,
    draw_outline = false,
    draw_shades = false,
    use_xft = true,
    font = 'DejaVu Sans Mono:size=12',
    gap_x = 5,
    gap_y = 60,
    minimum_height = 5,
	minimum_width = 5,
    net_avg_samples = 2,
    no_buffers = true,
    out_to_console = false,
    out_to_stderr = false,
    extra_newline = false,
    own_window = true,
    own_window_class = 'Conky',
    own_window_type = 'desktop',
    stippled_borders = 0,
    update_interval = 1.0,
    uppercase = false,
    use_spacer = 'none',
    show_graph_scale = false,
    show_graph_range = false,
	short_units = false,
}

conky.text = [[
${color grey}RAM Usage:$color $mem/$memmax - $memperc% ${membar 4}
${color grey}Swap Usage:$color $swap/$swapmax - $swapperc% ${swapbar 4}
$hr
${color grey}File systems:
 / $color${fs_used /}/${fs_size /} ${fs_bar 6 /}
${color grey}Networking:
Up:$color ${upspeed} ${color grey} - Down:$color ${downspeed}
]]

```

**Comment by brndnmtthws** [comment]
This is indeed broken, I think the other patch was overzealous.

**Comment by lasers** [comment]
@X0rg Thanks for the bug report. Keep them coming. :sweat_smile:
