### ISSUE TITLE
wrong wiki on rss update interval

### ISSUE THREAD

**Issue by freddii** [brndnmtthws/conky#715]
in the wiki is written:
rss uri interval_in_minutes
https://github.com/brndnmtthws/conky/wiki/Configuration-Variables

but conky works like:
rss uri interval_in_seconds

i am using conky-all 1.10.8-1

**Comment by lasers** [comment]
I fixed the typo. Thanks. For your information, you can press `Edit` button and fix it yourself. 

@brndnmtthws 
To be honest, the `Configuration {Settings,Variables}` section in the wiki could go away. There are several changes in `man conky` made by me and others that hadn't been "synced" to the `wiki`.

Thoughts on replacing the table with... 
* `man -P 'less -p "OBJECTS/VARIABLES"' conky`
* `man -P 'less -p "CONFIGURATION SETTINGS"' conky`

**Comment by brndnmtthws** [comment]
@lasers sounds fine by me.

**Comment by lasers** [comment]
@brndnmtthws I have a wiki commit that consolidates `Configuration-Settings`, `Configuration-Variables`, and `Convert-to-new-1.10-syntax` into a single `Configurations`. I whittled down lot of things leaving only the essentials. Should I push it or do you prefer to keep all three separate?

**Comment by brndnmtthws** [comment]
@lasers consolidation sounds good to me. Less is more. 👍
