### ISSUE TITLE
alignment top_right and middle_right and own_window_type=panel

### ISSUE THREAD

**Issue by adam-kulagowski** [brndnmtthws/conky#724]
Hi,

I've encountered strange behavior of conky window properties when using `own_window_type= 'panel'` . My aim is to make conky act as a panel type of window so that space will be reserved when maximizing other windows. When I set the the variable: `alignment` to `middle_right` and position (using gap_x and `gap_y`) conky window in top_right corner, then everything works fine and as expected. However when I set the aligment to `top_right` and  set the `gap_y` to position the window in the same spot, the XFCE window manager ignores conky and maximized other windows below.

From quick look I suspect that there might something wrong with `_NET_WM_STRUT_PARTIAL` property but I'm no expert here :)

I'm attaching: 
- working conky config (middle_right-conf.txt)
- broken config (top_right-conf.txt)
- output of xprop of both windows (the only difference is below)
```
diff /tmp/top_right.txt /tmp/middle_right.txt 
1,2c1,2
< _NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 615, 0, 0, 0, 0, 0, 5121, 5208, 0, 0
< _NET_WM_STRUT(CARDINAL) = 0, 0, 615, 0
---
> _NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 87, 0, 0, 0, 0, 0, 615, 0, 0, 0, 0
> _NET_WM_STRUT(CARDINAL) = 0, 87, 0, 0
```

This bug occurs on xubuntu 18.10 (with single and multiple monitors and with and without `xinerama_head` option). I'm using latest github version.

[middle_right-conf.txt](https://github.com/brndnmtthws/conky/files/2711853/middle_right-conf.txt)
[top_right-conf.txt](https://github.com/brndnmtthws/conky/files/2711854/top_right-conf.txt)
[middle_right.txt](https://github.com/brndnmtthws/conky/files/2711855/middle_right.txt)
[top_right.txt](https://github.com/brndnmtthws/conky/files/2711856/top_right.txt)

**Comment by lasers** [comment]
Can you try this on other WM/DE too to rule out XFCE? I know we have some XFCE-related issues.

**Comment by adam-kulagowski** [comment]
Yep, You are right (unfortunately):
- Marco, OpenBox, metacity - they don't have that issue

Right now I'm using two conky instances at the same time. The second is a dummy one: fully transparent and 1px height (and middle_right aligment) and w/ the same  width as the original one.

Ugly but gets the job done.

**Comment by ThaChillera** [comment]
I'm experiencing the same issue I think:

When running XFCE & conky in panel mode, conky doesn't ever reserve space. Except when on my left-most monitor - aligned bottom-right, then it reserves space along the bottom of my centre monitor (?!).

Other than that, it never reserves space.

I have tested the exact same config with cinnamon DE, and it works perfectly.
