### ISSUE TITLE
Pull request #698 breaks mouse event passthrough to root window

### ISSUE THREAD

**Issue by xythrez** [brndnmtthws/conky#729]
Running Arch Linux, used PKGBUILD file for both extra/conky and aur/conky-git.
Config file [here](https://gitlab.com/xythrez/dotfiles/blob/master/conky/conky.conf)
WM: Openbox

Commit a0d4393826b9775fb7b4b4c6b51d54fd32a36b91 made mouse events (Left/Right/Middle click + scroll wheel) passed to the root window inconsistent. Most clicks are ignored. However in some cases the event does go through (and subsequent events for the same button works for a period of time). This seems to happen when the mouse button is triggered outside of the conky window, then later moved onto conky and triggered again.

**Comment by lasers** [comment]
Duplicate #709.
