### ISSUE TITLE
Path to image may not contain whitespace

### ISSUE THREAD

**Issue by jfrankenau** [brndnmtthws/conky#73]
Trying to render an image with whitespace in its path does not work for [obvious reasons](https://github.com/brndnmtthws/conky/blob/689b4046068bf68683df901679ebbcdb9a435d87/src/imlib2.cc#L124).

**Comment by easysid** [comment]
Is there a workaround for this? Quoting the path, or escaping the whitespace doesn't work.

**Comment by plikhari** [comment]
It depends on how you are passing it to conky. 

If it is a script - you can have a sub folder in /tmp - copy the image there and pass that path/image to conky.

If you have lua rendering the image it works fine with spaces as well

**Comment by mswanson-me** [comment]
Since there are very reasonable workarounds, I am closing this issue.
