### ISSUE TITLE
automate syntax highlights instead of asking users

### ISSUE THREAD

**Issue by lasers** [brndnmtthws/conky#738]
From one of wiki pages...
>If you have added **new variables or setting** make sure to update the syntax highlights:
>- /extras/nano/
>- /extras/vim/

I know for sure that this is long outdated. There are several new variables and maybe couple of settings. It would be nice if Conky can automate this part (i.e. make syntax highlights) out of `config_settings.xml` and `variables.xml` instead of asking users to do that. 

May need to be careful with some files where it would use option tag twice, e.g...

>maximum_width ~~pixels~~
>* Maximum width of window.

>minimum_height ~~height~~
>* Minimum height of the window.

>minimum_width ~~width~~
>* Minimum width of window.

**Comment by brndnmtthws** [comment]
We could just have conky itself generate the syntax highlight definitions for popular editors. Shouldn't be too tricky.

One catch, however, is that (depending on how it's implemented) we would only generate the highlights for objects where the support is compiled in. I think this is probably a good thing: if you tried using objects that aren't supported by the installed build of conky, you'd get a visual indication.
