### ISSUE TITLE
Add option to escape variables for JSON

### ISSUE THREAD

**Issue by mkaito** [brndnmtthws/conky#74]
The specific use case is for output to `i3bar`, which accepts JSON objects for colour coding and item separation. `i3bar` will balk when presented with improper JSON strings.

My proposal is for an option to be added that would cause all printed variables to be piped through a JSON encoder for escaping. Something like `escape_json yes`, or `use_json yes`, perhaps.

**Comment by lasers** [comment]
3 years, 8 months passed. Do you still need this feature? Let us know. Thanks.

**Comment by lasers** [comment]
@su8 I notice you had been busy with JSON lately... See if you can solve this too. :rofl:

**Comment by su8** [comment]
One can you python for this job:

```python
import json;
a = {"hello":"world", "some": 123};
print(json.dumps(a, indent=4));
```

Where the dictionary **a** can be argv or if **python -c "import json;a=$1;print(json.dumps(a, indent=4));"** is used then a position argument can be used inside the **a** variable to supply the data.

Just quote the strings and leave the numbers untouched.

**Comment by lasers** [comment]
This is for https://i3wm.org/docs/user-contributed/conky-i3bar.html.

```lua
conky.text = [[
[
    { "full_text": "Home ${fs_free /home} Free" , "color": "\#ffffff" },\#ff0000"${endif} }
],
```
Sometimes our variables prints quotes. We escape them with `json=true` config.
