### ISSUE TITLE
Native icmp_ping variable support

### ISSUE THREAD

**Issue by tanertas** [brndnmtthws/conky#747]
I want to change network icon behavior according to my local and broadband connection status. There is `$tcp_ping` variable but it is not suitable since it doesn't support ICMP ping. I think that if we want to implement something related with "ping", ICMP should be first since it is the standard definition of this subject.

`$tcp_ping` variable's default is 80. If you decide to implement icmp as a feature of `$tcp_ping`, default (if no port defined) can be changed to icmp.

**Comment by brndnmtthws** [comment]
Agreed, this would be useful. Would be nice to have a time series plot as well.
