### ISSUE TITLE
Mix of right aligned/left aligned table cells

### ISSUE THREAD

**Issue by ndk-** [brndnmtthws/conky#748]
**Issue**

Right aligned tables

**Information**

Wasn't sure where to ask, so I would ask here.
Is there an easy way to have a table with a mix of left/right aligned values?
I am working on weather widget and want to right align some information, while having another information left aligned.

Things I have tried already (not a full list, there were also many variations of those):
1. ```${goto X}${execpi Y cat content_with_aligned_leading_spaces}${alignr}{execpi Y cat another_content}```
2. ```${alignr 150}${execpi Y cat not_aligned_content}${alignr}{execpi Y cat another_content}```
3. ```${alignr 150}${execpi Y cat not_aligned_content}${alignr}{execpi Y cat another_content_with_leading_spaces}```
4. ```${goto X}${execpi Y cat content_with_aligned_leading_spaces}${goto Z}{execpi Y cat another_content_with_leading_spaces}```
5. I have tried to use: https://unix.stackexchange.com/questions/62948/conky-string-formatting, but it does not seem to like leading spaces when I used something like ```${lua_parse format %10s ${execpi cat ....}}```. 

There is no clear documentation how to do it either.

It would be great if I am missing something trivial.

**Comment by lasers** [comment]
I'm not sure either. Take a look at [wiki/Configs](https://github.com/brndnmtthws/conky/wiki/Configs). Some of them may be doing what you're looking for. In short, I think it might be something simple like... `leftleftleft{alignr}rightrightright`. There is also `${offset}` and `${voffset}` variables. 

@plikhari made [conkywx](https://bitbucket.org/plikhari/conkywx_pub/wiki/Home) which you might find it useful to try / borrow / experiment / etc for your weather widget.
