### ISSUE TITLE
tcp_ping doesn't work as expected

### ISSUE THREAD

**Issue by tanertas** [brndnmtthws/conky#749]
```
${tcp_ping ${gw_ip} }
${tcp_ping 1.1.1.1 53}
```
Regardless my network cable plugged or not, `${tcp_ping ${gw_ip} }` always produces "0".
If I plug off my network cable (no internet), `${tcp_ping 1.1.1.1 53}` produces numbers above 300 whereas it produces normal values (12-15) when network cable plugged in. ${gw_ip} is my router and resulted IP address is correct.

conky: 1.11.1
OS: Alpine Linux, 4.19.3 kernel (musl-libc)

**Comment by brndnmtthws** [comment]
`${tcp_ping}` does not evaluate the result of `${gw_ip}`. If you want to do that, currently you'd have to do it with Lua or try your hand with `${eval}`.

What's the behaviour you expect when the cable is unplugged?

**Comment by tanertas** [comment]
> What's the behaviour you expect when the cable is unplugged?

I wanted to change icon (actually glyph font) depending on LAN and WAN status. Btw, `${if_existing /sys/class/net/eth0/operstate up}` did what I was expecting from `${tcp_ping ${gw_ip} `}. But you have to set network interface statically which means configuration only works for particular setup.
```
${if_existing /sys/class/net/eth0/operstate up}\
${if_match ${tcp_ping 1.1.1.1 53} > 0 }${color1}${else}${color4}${endif}\
${else}${color4}${endif}
```
