### ISSUE TITLE
RTL languages not supported

### ISSUE THREAD

**Issue by moceap** [brndnmtthws/conky#75]
![10864042_420651738084229_4584166603244457579_o](https://cloud.githubusercontent.com/assets/4345211/5558284/f8ca160e-8d31-11e4-9226-7b84f757abef.jpg)

Should be like الجمعة ، ديسمبر , there is a way here to fix this issue :

https://github.com/faisal-oead/conky-arabic-support

I think this issue must fix immedetly. Thank you.

**Comment by moceap** [comment]
@Tucos 

I try to create a pullrequest but I can't due to changes on conky... I hope if you create a new patch and ask a pullrequest.

Thanx

**Comment by Tucos** [comment]
Sorry, I will not bother with pull requests myself. The patch should still
apply cleanly to 1.9.1, as there's only been 1 commit in an unrelated file.
The master branch is conky 2.x, which is a rewrite of pretty much
everything. Either somebody other than me would have to rebase the patch
for that branch, or you need to make sure to checkout 1.9.1 before trying
to apply the patch.

**Comment by brndnmtthws** [comment]
Can you open a PR against master?

**Comment by su8** [comment]
@lasers we need @brndnmtthws as I don't understand cmake how to find linkage dependencies.
