### ISSUE TITLE
Automated builds for all platforms (BSD)

### ISSUE THREAD

**Issue by brndnmtthws** [brndnmtthws/conky#754]
Currently Travis only provides Linux, macOS, and Windows builds. We should have automated builds & testing for all supported platforms, including the BSDs, Haiku, Solaris, etc.

**Comment by lasers** [comment]
I wanted to ask you if this is still accurate today, [FAQ: Conky does not compile on NetBSD](https://github.com/brndnmtthws/conky/wiki/FAQ#conky-doesnt-compile-on-netbsd), where we need to "just uncomment appropriate lines".

**Comment by brndnmtthws** [comment]
Apparently [Cirrus CI](https://cirrus-ci.org/) supports FreeBSD. I have not used it before, but it might be worth trying. If anyone has any thoughts, please chime in.

**Comment by brndnmtthws** [comment]
Regarding CI improvements, I've added the following:

- [LabHub](https://github.com/brndnmtthws/labhub), a bot for building external PRs. It can also retry failed builds if you comment with `@labhub-bot retry`.
- [gitlab-gce-autoscaler](https://github.com/brndnmtthws/gitlab-gce-autoscaler), a simple autoscaler for the FreeBSD build runners.
