### ISSUE TITLE
Get sonarcloud bugs/vulnerabilities down to 0.

### ISSUE THREAD

**Issue by brndnmtthws** [brndnmtthws/conky#763]
At the time of writing, sonar shows 20 bugs and 12 vulnerabilities. Let's try and get this down to 0.

https://sonarcloud.io/dashboard?id=conky

**Comment by Mithil467** [comment]
May I try to solve some of the bugs and vulnerabilities? @brndnmtthws

**Comment by brndnmtthws** [comment]
@Mithil467 that'd be great 😄
