### ISSUE TITLE
Can't load font when using "yes" instead of "true".

### ISSUE THREAD

**Issue by CTimmerman** [brndnmtthws/conky#778]
This is how my Conky looks after fixing it on Linux Mint Xfce (https://github.com/brndnmtthws/conky/pull/777):

![image](https://user-images.githubusercontent.com/9662163/52071703-cbb39c00-2583-11e9-9303-7643e083f04c.png)

After changing all "true" to "yes", Conky looks like this:

![image](https://user-images.githubusercontent.com/9662163/52071511-7aa3a800-2583-11e9-9de4-70d1d4bd33bf.png)

**Information**

Linux minty-VirtualBox 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
conky 1.10.8 compiled Wed Feb 28 17:11:42 UTC 2018 for Linux 4.4.0-101-generic x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky

 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * RSS
  * Weather (METAR)
  * Weather (XOAP)
  * wireless
  * support for IBM/Lenovo notebooks
  * nvidia
  * eve-online
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support
  * PulseAudio

 Lua bindings:
  * Cairo
  * Imlib2
  * RSVG
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * Xshape extension (click through)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * Audacious
  * MPD
  * MOC
  * XMMS2

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256

```--[[
Conky, a system monitor, based on torsmo

Any original torsmo code is licensed under the BSD license

All code written since the fork of torsmo is licensed under the GPL

Please see COPYING for details

Copyright (c) 2004, Hannu Saransaari and Lauri Hakkarainen
Copyright (c) 2005-2019 Brenden Matthews, Philip Kovacs, et. al. (see AUTHORS)
All rights reserved.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
]]

conky.config = {
	alignment = 'bottom_right',
	background = false,
	border_width = 1,
	cpu_avg_samples = 2,
	default_color = 'white',
	default_outline_color = 'grey',
	default_shade_color = 'black',
	double_buffer  = yes,
	draw_borders = false,
	draw_graph_borders = yes,
	draw_outline = false,
	draw_shades = yes,
	extra_newline = false,
	font = 'DejaVu Sans Mono:size=11',
	gap_x = 5,
	gap_y = 60,
	minimum_height = 5,
	minimum_width = 5,
	net_avg_samples = 2,
	no_buffers = yes,
	out_to_console = false,
	out_to_stderr = false,
	own_window = yes,
	own_window_argb_value = 0,
	own_window_argb_visual = yes,
	own_window_class = 'Conky',
	own_window_hints = 'below',
	own_window_type = 'desktop',
	show_graph_range = false,
	show_graph_scale = false,
	stippled_borders = 0,
	update_interval = 1.25,
	uppercase = false,
	use_spacer = 'none',
	use_xft = yes
}

conky.text = [[
$nodename | ${scroll 16 $sysname $kernel $machine}
$hr
${color grey}Uptime:$color $uptime
${color grey}Frequency (in MHz):$color $freq
${color grey}Frequency (in GHz):$color $freq_g
${color grey}RAM Usage:$color $mem/$memmax - $memperc% ${membar 4}
${color grey}Swap Usage:$color $swap/$swapmax - $swapperc% ${swapbar 4}
${color grey}CPU Usage:$color $cpu% ${cpubar 4}
${color grey}Processes:$color $processes  ${color grey}Running:$color $running_processes
$hr
${color grey}File systems:
 / $color${fs_used /}/${fs_size /} ${fs_bar 6 /}
${color grey}Networking:
Up:$color ${upspeed} ${color grey} - Down:$color ${downspeed}
$hr
${color grey}Name              PID   CPU%   MEM%
${color lightgrey} ${top name 1} ${top pid 1} ${top cpu 1} ${top mem 1}
${color lightgrey} ${top name 2} ${top pid 2} ${top cpu 2} ${top mem 2}
${color lightgrey} ${top name 3} ${top pid 3} ${top cpu 3} ${top mem 3}
${color lightgrey} ${top name 4} ${top pid 4} ${top cpu 4} ${top mem 4}
]]

```

**Comment by CTimmerman** [comment]
It works fine with `use_xft = true`.

**Comment by lasers** [comment]
Your conky config is literally a Lua script.
```lua
$ lua
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
> true == true
true
> true == "yes"
false
>
```

**Comment by CTimmerman** [comment]
> > true == "yes"
> false

So that's why "no" instead of "false" did work. Old configs on the web are confusing.
