### ISSUE TITLE
background not immediately updated to new desktop wallpaper

### ISSUE THREAD

**Issue by pweisenburger** [brndnmtthws/conky#78]
When starting conky in an environment without a composite manager, it will use "fake transparency" and just use the current desktop background. When changing the desktop background, conky does not immediately update its background. It would be nice if conky would update the background when a property notification event is fired for `_XROOTPMAP_ID` or `_XROOTMAP_ID` (tint2 also uses that approach).

I attached a patch against the 1.9.1 and the 1.9.0 branch, which can be applied using `git am` if desired.

[conky-1.9.1+background-change-fix.patch](https://gist.githubusercontent.com/pweisenburger/58dd04e080bf0a13513b/raw/50636c55a6b4af05e351df2b0b53c7acdf0a8b84/conky-1.9.1+background-change-fix.patch)

[conky-1.9.0+background-change-fix.patch](https://gist.githubusercontent.com/pweisenburger/2d86417b8d4507df6cb2/raw/616683e7208e5df402bed65167201770b035c70e/conky-1.9.0+background-change-fix.patch)

**Comment by gitcior** [comment]
Hi pweisenburger!

I've just tried your patch for 1.9.0 conky. It didn't work for some reason. After compiling conky I am getting a message "Conky: unknown variable image" every 2 sec (my update interval).
I use fvwm 2.6.5 with any composing manager. It would be great to have this working as this background update is quite annoying. Would this patch be incorporated into mainline conky?

**Comment by pweisenburger** [comment]
Yes, you need Imlib2 to render images. Concerning background update speed: I had a serious improvement using this patch with Openbox as window manger (with and without compositing manager). The background is refreshed nearly instantly. Sorry I currently cannot help you with that problem since I don't have time to investigate the issue further.

**Comment by luebking** [comment]
The problem is that conky will still usleep and need_to_update = 1; will only affect the next event cycle.

adding "next_update_time = 0;" should cause an update "asap" (there's still a frame delay between root and conky update, but we're talking about < 30ms ;-)

@pweisenburger, willing to create a pull request? (since imo it improves conky considerably)

**Comment by pweisenburger** [comment]
Sorry, I haven't had the time to look into that again, but I'm glad to see you merged the patch. So I think this issue can be closed now.
