### ISSUE TITLE
[Feature Request] Using Old Config Files 

### ISSUE THREAD

**Issue by zero77** [brndnmtthws/conky#815]
Can you please add some kind of support or ideally conversion for old config files.
Perhaps, create a backup of the config and then converting the simple incompatibilities like changing spaces to equals and other such things.
The big changes could be suggested in a log file or as comments for users to change manually.
Thanks

**Comment by plikhari** [comment]
There is a already such a utility - convert.lua - included in the conky installation.

**Comment by zero77** [comment]
Thanks

**Comment by lasers** [comment]
https://github.com/brndnmtthws/conky/wiki/Configurations#converting-old-configs-to-110
