### ISSUE TITLE
Conky now requires FUSE

### ISSUE THREAD

**Issue by sabrehagen** [brndnmtthws/conky#816]
Now that conky is packaged as an AppImage, it requires FUSE to run. When installing conky in a container, FUSE is almost always not available. This blocks installation of the latest version of conky.

![image](https://user-images.githubusercontent.com/1094600/54875310-b99dfd80-4e50-11e9-863e-db7979de1bd8.png)

**Comment by brndnmtthws** [comment]
Just to clarify, [AppImage requires fuse](https://github.com/AppImage/AppImageKit/wiki/FUSE). As per the instructions, you can bypass this by passing `--appimage-extract` argument and using the extracted contents instead.
