### ISSUE TITLE
[Bug] Covers Up Other Windows In i3

### ISSUE THREAD

**Issue by zero77** [brndnmtthws/conky#818]
**Issue**
This only seams to be happening in i3 and not openbox which i have also tested.

Conky starts and runs without any problems but, the conky configs always cover up other windows.
**Information**

i3 version 4.16-110-gfeb2912e
conky 1.11.3
Ubuntu: 18.04

**Comment by lasers** [comment]
I don't see your config. For i3, you might like `own_window_type override`.

**Comment by zero77** [comment]
@lasers 
Configs 1 and 2
https://pastebin.com/avSL0pgU
https://pastebin.com/jvfqmay7

Also, is this what you mean.

```
conky.config = {
    own_window = true,
    own_window_type = 'override',
}
```

**Comment by lasers** [comment]
@zero77 Yes, sir. With `jvfqmay7`, it worked fine as-is with window appearing in front of i3 containers. Using `override` puts it in the background. With `avSL0pgU`, it ran fine as-is, but I can't find it anywhere.

**Comment by zero77** [comment]
@lasers 
I made the changes you suggested and it looks like it's working now.
Thanks
