### ISSUE TITLE
${time %p} changes case depending on when it is run

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [brndnmtthws/conky#823]
**Issue**

When I run conky at boot, `${time %p}` produces the text 'AM' (if it is morning) or 'PM' (if it is night). Run at any other time, Conky produces the same output, but *lowercase*. Lowercase is the expected behaviour for my locale. Or at least it is were Conky to be going by the GNU conventions defined the POSIX command 'date'. For, the manual for that command says:

    %p     locale's equivalent of either AM or PM; blank if not known

and the GNU developers tell me that my locale, namely en_GB, uses the 'equivalents' that are lowercase 'am' and lowercase 'pm'. That is (and this indeed does seem to be the case): on my system, the relevant `date` command (namely `date +%p`) always produces lowercase letters. Yet, and as said, when first run, and only then, Conky produces upper case. The plot thickens when one realises that Conky says it adheres to the 'strftime' standard. Now, running `man strftime` in a BASH terminal emulator yields output that contains this:

    %p     Either "AM" or "PM" according to the given time value, or the corresponding strings for the current locale.

That definition is disjunction and it does not seem to say how one disjunct is picked over the other. (I did try writing a c program to test how `strftime` - a c function - works, but so doing was beyond my ability. For, I do not understand what sort of input that function takes.)

If I remove conky from my boot sequence, reboot, and the run conky manually, it produces lowercase 'am'/'pm'. But, as said, if I run conky at boot automatically, then I get capitals. Perhaps the locale get applied only relatively late in the boot sequence? (I have conky set to run with a three second delay, and it is, of course, a userspace program.)

I _prefer_ Conky to give capitalised output for `${time %p}` but at any rate it seems to be that Conky should be consistent (even, perhaps, if the problem is to do with the application of the locale).

**Information**

Conky 1.11.1_pre
Linux Mint 19.1 x64 Cinnamon

**Comment by lasers** [comment]
It seems like an issue with environment variable/locale.

I don't know how you run conky at boot automatically, but what if you adjust conky to run with different locale? Something like `env -u LANG conky` or `unset LANG && conky` or `LANG=en_US.UTF-8 conky`.

**Comment by LinuxOnTheDesktop** [comment]
Thanks. I tried `unset LANG && conky` and `LANG=en_US.UTF-8 conky` and neither changed the relevant behaviour. What would `env -u LANG conky` do, please? (I have not tried that one.) Also, if there is a non-conky bug here, I wonder to whom I should report it. Thank you for your time.

**Comment by lasers** [comment]
```
env - run a program in a modified environment

       -u, --unset=NAME
              remove variable from the environment
```
It looks similar to `unset LANG && conky` and I think it may be a race condition with how you start your applications at startup as you reported that it works okay much earlier... so I don't know if there is somebody to file reports with. Also, How do you run conky at startup?

**Comment by lasers** [comment]
>I prefer Conky to give capitalised output for ${time %p} but at any rate it seems to be that Conky should be consistent (even, perhaps, if the problem is to do with the application of the locale).

This would go against users' wishes (or locales) as conky have over 250+ variables.

After uncommenting `en_GB.UTF-8 UTF-8` in `/etc/locale.gen` and run `sudo locale-gen`, I can produce lowercase `am/pm` using `LANG=en_GB.UTF-8 conky` or `env LANG=en_GB.UTF-8 conky`. 

And with `date +%p` too.
```bash
[Conky/823] $ date +%p                 
AM
[Conky/823] $ LANG=en_GB.UTF-8 date +%p
am
[Conky/823] $ env LANG=en_GB.UTF-8 date +%p
am
```

You can use `${time %^p}` instead according to `man strftime`.

`^      Convert alphabetic characters in result string to uppercase.`
```bash
[Conky/823] $ env LANG=en_GB.UTF-8 date +'%^p'
AM
```

**Comment by LinuxOnTheDesktop** [comment]
Thank you. I do not fully understand all that, and I don't fancy globally removing my own locale (which seems to be what you were suggesting) but `${time %^p}` works! Thank you very much.

How I run Conky at boot: I use Mint's Startup Applications program (and I don't know exactly how that works) to run a bash script after a two second delay. The business part of that script is as follows.

```
conky_startConky ()
{
	[ "$CONKY_DEBUG" -eq 0 ] && conky_logWithEcho "${FUNCNAME[ 0 ]}"
	if [ "$START_CLEANLY" -eq 0 ] ; then
		if pidof -s -n -x -o %PPID "$CONKY_PART_PATH" > /dev/null 2>&1 ; then
			sudo killall conky > /dev/null 2>&1 && sleep 0.5
		fi
	fi
	conky -d -c "$CONKY_FULL_PATH" >/dev/null
}
```
Currently I have `START_CLEANLY` set to `1`. And `sudo killall conky` does not require a password on my system.

I tried prepending `LANG=en_US.UTF-8 && ` to the `conky` command but it did not help. As said, though: `${time %^p}` does.

I will close this issue now. Thanks again.
