### ISSUE TITLE
Conky runs callbacks twice

### ISSUE THREAD

**Issue by mtrower** [brndnmtthws/conky#829]
Commit https://github.com/brndnmtthws/conky/commit/c352069b31b2dbb4d87503603d6c6d3ddd517df6 runs callbacks and parses vars ~~twice~~ multiple times per cycle (once normally, plus once per evaluate() variable (`execp`, `lua_parse`, etc).

This causes various unwanted side effects such as disk I/O reporting at half the actual value (due to too-frequent updates), luabars generated by lua code appearing twice instead of once, colors being messed up, etc.  The severity of the latter effects depends on how much you dynamically generate your conky.text with lua (or probably exec, etc.) vs static configuration.

I don't know what the correct approach to parsing nested exec variables is, but this doesn't seem to be quite it.

**Comment by CoalZombik** [comment]
I examined this error and I probably found fix.
See pull request 831.
Please @mtrower, review this fix for your problems.

**Comment by mtrower** [comment]
@CoalZombik

#831 addresses the second portion of this Issue (parsing).  I've since worked around the problem in my config (I initially thought it was Solaris-related, and didn't save a snapshot of that state), but the changes are logical, and what I'm able to test on that front, is resolved.

It does not address the first and titular portion of the Issue, which is that callbacks are run twice.  Not only is this semantically incorrect (it disobeys update_interval, and runs callbacks that have nothing to do with nesting problem), it actively breaks various metrics (a specific example is disk activity).

Metrics such as those are are expressed by the operating system as running totals since boot.  The standard way to report them is to poll them twice over some interval, then divide the difference by elapsed time.  Running callbacks twice per interval means that the difference used in calculations is from half the elapsed time that it's being divided by (actually, not necessarily half, just some fraction -- but in practice, it seems to be about half).

**Comment by CoalZombik** [comment]
Can you paste here some example configuration with these problem?

**Comment by mtrower** [comment]
Uh, sure..

`conky.text = [[${execp true}${diskio}]]`

That's all you need.  Of course, this will give you white text drawn on your background in the lower left; if that's not suitable, add whatever config variables you desire for rendering.  Just running with own_window is probably enough in most environments; e.g. `conky -o -c conkyrc`.

Fire up some disk activity and observe; example: `cat` a disk to `/dev/null` and compare against `iostat 3`.  Add additional `${execp true}` variables (or whatever you'd like, to trigger eval), and watch the numbers tank further.

**Comment by mtrower** [comment]
@brndnmtthws presumably you understand the core architecture better than anyone, and you also signed off on #804 -- can you comment on the correctness of calling `conky::run_all_callbacks() `  more than once per `update_interval`?  Not all of those callbacks are idempotent...

In other words, is calling `run_all_callbacks()` more than once per `update_interval` considered a bug, or is a callback which adjusts for time-lapse using `update_interval` considered bugged?

**Comment by brndnmtthws** [comment]
@mtrower I'm aware of the issue where callbacks are called more often than expected. It has to do with some legacy behaviour (specifically making sure that data is available before trying to draw things on the screen). I suppose it's not unreasonable to make it behave in a more sane fashion.

The downside with changing old behaviour is that it almost always breaks things for some people :)

**Comment by mtrower** [comment]
> The downside with changing old behaviour is that it almost always breaks things for some people :)

True...

It doesn't really matter to me personally; I just reverted the commit privately until such a time as it is fixed.  Nevertheless, `${diskio}` is a builtin variable displaying a core system metric; it probably shouldn't break just because someone called `${execp}`.

Two solutions come immediately to mind, depending on whether you want to fix `evaluate()` or `update_diskio`.

`evaluate()`:
Semantically, you don't actually want to run all callbacks here --- you want to run the callbacks that are new since pars.  One way would be to get the list of callbacks before parsing, compare that to the list of callbacks after parsing, and run only the new ones (although, if you nest exec inside exec inside exec... well, this might not scale very deep =] ).  Or, track whether an update has ever been called, and just call the ones that haven't been.  Or, track which updates are pending this cycle, and call only pending ones.  (or...)  This, in my opinion, is the correct solution.

`update_diskio`:
Instead of dividing by `active_update_interval()`, track actual time passed.  Additionally, instead of averaging a fixed sample size, average a number of samples such that total elapsed time is approximate to `diskio_avg_samples * update_interval`.  This should yield at least acceptable results even if you run callbacks 1000 times per interval =].  I don't promise nothing else is broken, however, if `update_interval` is not respected.

I think it would probably be most correct to implement both of them.  I'd be willing to submit a PR at some future date, but that date could be next week, next month, or next year.  If someone wants to work on it in the meantime, the above may offer a starting point.

Of course, you could also drop the aforementioned legacy behaviour, clean up the whole callback system, and sidestep the issue that way.  I've no idea what that approach would look like.

**Comment by lasers** [comment]
Closed via #831.

**Comment by mtrower** [comment]
Why was this closed?  #831 only partially addresses the issue (parsing, but not callbacks).

**Comment by lasers** [comment]
Ah okay. Sorry, I thought it was resolved. Cheers.
