### ISSUE TITLE
Solaris CPU reporting incorrect

### ISSUE THREAD

**Issue by mtrower** [brndnmtthws/conky#830]
The array containing CPU usage is intended to be n+1 large, with index 0 containing aggregate stats, and individual stats following after.  However, solaris.cc:update_cpu_usage() just builds the array starting at index 0 (causing aggregate CPU0 variables to report CPU1 statistics, and last CPU variables to report nothing at all).

patch: [0001-Fix-CPU-reporting-on-Solaris.patch](https://manta.sol.blackshard.net/mtrower/public/srv/0001-Fix-CPU-reporting-on-Solaris.patch)
(I know, it's not a PR.  Use/modify/do whatever you want with it.  Or don't.)

**Comment by lasers** [comment]
cc @senjan

**Comment by senjan** [comment]
Thanks, nice catch. I'll prepare a PR.
Jan

**Comment by lasers** [comment]
Closed via #838.
