### ISSUE TITLE
nvidia API not working through xRDP (multi xfc4-session)

### ISSUE THREAD

**Issue by Quedale** [brndnmtthws/conky#833]
**Issue**
Unable to use nvidia API when running a second xfce4-session through xRDP.
I know the same configuration file work on this computer when logging in locally.

**Information**

I configured xRDP to create a new xfce4-session to allow multiple session for the same user.
To accomplish this, I configured my ~/.xsession file like this : 
```
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
xfce4-session
```

I'm testing "${nvidia gpuutil}" which return the following error :
```
conky: get_nvidia_target_count:
          Trying to query Nvidia target failed (using the propietary drivers).
          Are you sure they are installed correctly and a Nvidia GPU is in use?
          (display: -319876112,Nvidia target_count: -1)
```
nvidia-smi command still works fine. For instance, the following line works "${exec nvidia-smi --query-gpu=gpu_name --format=csv,noheader,nounits}".

I'm using Nvidia proprietary driver version 418.

I tried to generate a crash report, but "bt full" returned "No stack".

**Comment by lasers** [comment]
What happen if you add `nvidia_display=":0"` to your config settings?

**Comment by Quedale** [comment]
That did it! Never noticed I could configure a specific display. Thanks!
