### ISSUE TITLE
imap_unseen and -p

### ISSUE THREAD

**Issue by aloneuser** [brndnmtthws/conky#839]
imap_unseen does not understand the parameter "-i"	
Because I specify -i 3000, and mail comes instantly!
{ "full_text": "yd:${imap_unseen localhost mail@yandex.by pass -i 3000 -p 993 -r 1}"},
conky -v
conky 1.10.6 compiled Fri Dec  9 09:25:13 UTC 2016 for Linux 3.16.0-4-amd64 x86_64

And also after a while the Conky begin to load the processor heavily. If I remove all fields with imap_unseen, then there is no extra load.

**Comment by aloneuser** [comment]
My conkyrc:
`conky.config = {
    out_to_x = false,
    own_window = false,
    out_to_console = true,
    background = false,
    max_text_width = 0,

    -- Update interval in seconds
    update_interval = 10,

    -- This is the number of times Conky will update before quitting.
    -- Set to zero to run forever.
    total_run_times = 0,

    -- Shortens units to a single character (kiB->k, GiB->G, etc.). Default is off.
    short_units = true,

    -- How strict should if_up be when testing an interface for being up?
    -- The value is one of up, link or address, to check for the interface
    -- being solely up, being up and having link or being up, having link
    -- and an assigned IP address. 
    if_up_strictness = 'address',

    -- Add spaces to keep things from moving about?  This only affects certain objects.
    -- use_spacer should have an argument of left, right, or none
    use_spacer = 'left',

    -- Force UTF8? note that UTF8 support required XFT
    override_utf8_locale = false,

    -- number of cpu samples to average
    -- set to 1 to disable averaging
    cpu_avg_samples = 2,
};

conky.text = [[
[
	{ "full_text": "yd:${imap_unseen localhost mail@yandex.by pass -i 3000 -p 993 -r 1}"},
	{ "full_text": "${imap_unseen localhost mail@yandex.ru pass -i 6000 -p 994 -r 1}"},
	#{ "full_text": "gmail:${imap_unseen localhost mail@gmail.com pass -i 8000 -p 995 -r 1}"},
	{ "full_text": "ukr.net:${imap_unseen localhost mail@ukr.net pass -i 12000 -p 996 -r 1}"},
	{ "full_text": "IP:${texeci 432000 wget -O - -q icanhazip.com}" , "color": "\#ffffff"},
	#{ "full_text": "Загрузка:$downspeed" , "color": "\#0000ff"},{ "full_text": "Отдача:$upspeed" , "color": "\#ffff00"},
	#{ "full_text":"HDD${hddtemp}°C" , "color": ${if_match ${hddtemp}<50}"\#00ee00"${else}"\#ff0000"${endif} }, # HDD: /${fs_free /} /home${fs_free /home}
	{ "full_text": "RAM free:$memfree used:$mem($memperc%)/$memmax%", "color" : ${if_match ${memfree}<50}"\#00ee00"${else}"\#ff0000"${endif}},
	{ "full_text": "CPU:${cpubar}${acpitemp}°C", "color" : ${if_match ${cpu}<50}"\#00ee00"${else}"\#ff0000"${endif}}, #${cpubar}% $laptop_mode $top
	{ "full_text": "Заряд:$battery_short $battery_time", "color" : ${if_match ${battery_percent}>70}"\#00ee00"${else}"\#ff0000"${endif}},
	{ "full_text": "${time %k:%M %A, %d %B %Y}"} # :%S`

**Comment by lasers** [comment]
>conky 1.10.6 compiled Fri Dec 9 09:25:13 UTC 2016 for Linux 3.16.0-4-amd64 x86_64

Just a heads up. Your conky is too outdated. `2016-12-04 13:13:57 -0200  (tag: v1.10.6)`

It'd be nice to know if this still occurs on latest `conky` master. You can follow this instruction:
https://github.com/brndnmtthws/conky/wiki/Installation#110-and-later-versions

Unrelated:  It looks like you want to pipe conky to i3bar so I'd just say you also can try [other i3status replacements/wrappers](https://wiki.archlinux.org/index.php/I3#i3status). In [py3status](https://github.com/ultrabug/py3status), you might find `mail` and `conky` module useful. The other modules will be able to replace everything you listed here.
