### ISSUE TITLE
${memperc} showing wrong values

### ISSUE THREAD

**Issue by plikhari** [brndnmtthws/conky#841]
**Issue**

${memperc} showing wrong values

**Information**

Using current git version - noticed that `${memperc}` shows 90% used while it is only about 29%. 

output from `free -m`
```
              total        used        free      shared  buff/cache   available
Mem:           7954        2277         915          76        4762        5343
Swap:         32767          37       32730
```

**Comment by plikhari** [comment]
OK am closing this issue as everything seems fine today - perhaps it is an issue with spacefm file manager

**Comment by lasers** [comment]
`${memperc}` looks okay to me. The percent does not look to be rounded. 53.99 prints 53 instead of 54.

**Comment by plikhari** [comment]
To replicate the issue:

copy a large size data say 3 to 4 GB to another partition and at the end you should have `memperc` show you that high value in the 90s percent - if we revert back to the last release the percentage drops back to 5 to 6 percent.

[conky release vs GIT image link](https://ibb.co/yddj7S0)

**Comment by lasers** [comment]
There are 54 commits between `master` and the last release that looks nothing to do with `memperc`. 

Look up on running a git bisect to find the first bad commit and report back with a has. :-)

**Comment by Monsterovich** [comment]
![Снимок экрана_2019-05-26_14-14-12](https://user-images.githubusercontent.com/3750982/58381711-cc53c080-7fc0-11e9-9a68-b27e37db80dd.png)

Yup.

**Comment by plikhari** [comment]
I do not have the bandwidth to pinpoint the issue - but there is an issue with all mem related things and I am just noticing the internet speed issue is also there - these are show stoppers.
