### ISSUE TITLE
fs_bar, fs_used, fs_free fail

### ISSUE THREAD

**Issue by hongquan** [brndnmtthws/conky#85]
`fs_bar`, `fs_used`, `fs_free` fail to work with 1 of my ext4 filesystem, as described here:

https://github.com/helmuthdu/conky_colors/issues/58

Used precompiled conky 1.9.0 in Ubuntu 15.04

**Comment by mswanson-me** [comment]
Is this issue still outstanding in the current version of Conky? If so, please update this issue. Otherwise, the issue will be closed in 2 weeks.

**Comment by hongquan** [comment]
This was fixed.
