### ISSUE TITLE
[Documentation / Wiki section - FAQ] Would it be possible to add an entry to the wiki, showing how to call a ruby / python / perl / shell script?

### ISSUE THREAD

**Issue by rubyFeedback** [brndnmtthws/conky#850]
Hello conky devs,

First it is great that conky is still alive. For some time it did not seem to be active but I hope this
is gone, and conky is active now. The idea is great.

Now to the issue request here:

I had a look at this URL of the conky wiki, the FAQ:

https://github.com/brndnmtthws/conky/wiki/FAQ

I was specifically looking for a short example how to call a ruby .rb script. I was unable to find it.

I remember vaguely how to do so ... but I am not sure if things work anymore (I think the last time I modified my old conkyrc was almost 10 years ago ... so I am very rusty).

So my specific request:

- Would it be possible if someone could add a section in the FAQ, just a short one, showing how to call a e. g. .rb file or .py python file? I can modify this once I know how this works (I do essentially use ruby scripts for everything, but I also included other "scripting" languages so that people who use these languages, could also benefit from such an entry in the wiki).

Thank you for reading and perhaps considering - feel free to close this issue at any moment in time as you see fit. Conky on! \o/

Edit: To explain this, I would indeed need a specific example by someone who got things to work. I assume it is simple, but probably not 0% simple (for example how does conky call that, what if we don't get any output even if it were to work for us on the commandline, etc... )

**Comment by lasers** [comment]
>Would it be possible if someone could add a section in the FAQ, just a short one...

Anybody can contribute to Conky wiki.

>...showing how to call a e. g. .rb file or .py python file? 

Please see https://github.com/brndnmtthws/conky/issues/438#issuecomment-445818603. I hope this is more than enough. Cheers.

**Comment by lasers** [comment]
https://github.com/brndnmtthws/conky/wiki/FAQ#how-can-i-run-custom-scripts
