### ISSUE TITLE
Graphs are leaking memory (fix provided)

### ISSUE THREAD

**Issue by SpartanJ** [brndnmtthws/conky#856]
Hi today I found a critical memory leak. I already encountered why and how this is happening:
It's happening since [this commit](https://github.com/brndnmtthws/conky/commit/594d0c85baff7e930ec4c9568690bb53d3cd5d2a) graphs are leaking memory since the `copy_graph` allocations are never being freed. I compiled conky and analyzed with valgrind ( [valgrind log here](https://github.com/brndnmtthws/conky/files/3332650/valgrind.txt) ) and the leak appeared there, and makes sense since it happens only with graphs.

I created a patch and tested it. With the patch applied now valgrind shows that no memory leaks are registered: 
[conky_mem_leak_fix.txt](https://github.com/brndnmtthws/conky/files/3332819/conky_mem_leak_fix.txt)
The fix also changes `new` in favor of `malloc` and `calloc` because of two reasons: graphs reallocation is being done with `realloc` and `free_specials` is using `free` for the graphs. Also `calloc` should be used because otherwise the array is uninitiated and contains random values creating a random render glitch.

So: happens since conky 1.11.4 and any sample using graph should be enough.
This is the one I used to test it:
```lua
conky.config = {
	own_window = true,
	own_window_type = 'override',
	own_window_transparent = true,
	own_window_hints = 'undecorated,below,sticky,skip_taskbar',
	draw_borders = false,
	draw_shades = true,
	alignment = 'top_left',
	gap_x = 2350,
	gap_y = 40,
	double_buffer = true,
	update_interval = 1,
	default_color = ffffff,
	use_xft = true,
	font = 'Monospace:size=10',
	use_spacer = 'none',
	minimum_width = 120,
	text_buffer_size = 256,
	default_graph_width = 200,
	default_graph_height = 20,
	default_bar_width = 200,
	default_bar_height = 20,
}

conky.text = [[
${cpugraph 20,200 cccccc ffffff}
${diskiograph 20,200 cccccc ffffff}
${downspeedgraph enp6s0 20,200 cccccc ffffff 3125}
]]
```

After running conky for about 10 hours it was using 350 mb of RAM. So this leak is quite severe.

Thanks.

**Comment by brndnmtthws** [comment]
Paging @Tomunu

**Comment by Tomunu** [comment]
I messed up. I cought one memory leak before I issued the pull request, but I missed this one. And I guess I didn't test it long enough to notice the leak.

**Comment by Tomunu** [comment]
Just confirmed that the memory leak started with the commit that SpartanJ pointed out. 

But the proposed fix doesn't work if the graph uses the default size instead of specifying a size. (Any maybe other cases cause it not to work too.) I haven't looked into why this is happening yet. 

The error:
`double free or corruption (fasttop)` 

conky.conf
`conky.text = [[
${memgraph}
]];`

**Comment by SpartanJ** [comment]
That's because I forgot about the `realloc` in `new_graph`. Here's the fix: 
[conky_memory_leak_fix.txt](https://github.com/brndnmtthws/conky/files/3337134/conky_memory_leak_fix.txt)

**Comment by texstar** [comment]
This patch also seems to fix the graphics corruption when starting conky. Thanks!

https://i.ibb.co/wzm8vzC/shot-conky-2.png

**Comment by Tomunu** [comment]
Agreed. With that newest change, I don't see any more memory leak, and the random value rendering seems to be fixed too.

**Comment by lasers** [comment]
I take it we don't need this anymore. https://github.com/brndnmtthws/conky/pull/858#issuecomment-50696808. Thank you for the patch. Much appreciated!

**Comment by dBl-BzH** [comment]
Hi, i've memory leaks with "conky 1.11.4-1", how can apply this patch plz ?

![2019-07-19_17-26](https://user-images.githubusercontent.com/44306432/62686807-b6ea1200-b9c5-11e9-9fb2-63d21365bcc5.png)

**Comment by bitwombat** [comment]
Critical bug and patch (thanks SpartanJ!) @brndnmtthws are you considering removing the releases affected by this bug?

**Comment by brndnmtthws** [comment]
I've just published a new release, sorry for the hold up.

**Comment by bitwombat** [comment]
Cool, and many thanks for such a cool piece of software. It's something I use (and enjoy) every single day.

**Comment by dBl-BzH** [comment]
i've replaced my conky package from official arch repo by conky-lua-archer package in AUR repo and all is ok since :)
