### ISSUE TITLE
Conky memery shows wrong value

### ISSUE THREAD

**Issue by godcrying** [brndnmtthws/conky#857]
**Issue**
![图片](https://user-images.githubusercontent.com/11704413/60354771-98c0e780-99ff-11e9-9fb1-df03265b8798.png)
In the htop, memery is just around 3Gib used,  but conky shows wrong values.
$mem, $memperc and $membar is all wrong.

**Information**

I'm using Archlinux, conky release is 1.11.4
sorry for my weak English.

**Comment by lasers** [comment]
Duplicate #841? Is it always or occasionally show the wrong values?

**Comment by godcrying** [comment]
> Duplicate #841? Is it always or occasionally show the wrong values?

I have downgraded to v1.11.3, and the value is correct. 
I have ever tried the v1.11.4 appimage release, it also has wrong values.

**Comment by jbenden** [comment]
Please try #859.

Thanks,
-Joe

**Comment by lasers** [comment]
@godcrying Can you do a `git bisect` to find a bad commit? If you don't know how to, look at `https://github.com/brndnmtthws/conky/issues/718#issuecomment-467254662` (not wanting to ref) or you can search `git bisect`.

My random guess is 9da1101b5ba00295aee149262767f6200cc76f23 and because this is between `HEAD (i.e. v1.11.4)` and `v1.11.3`, there are only 68 commits and shouldn't take long to find the bad commit. You will need to compile `conky` repeatedly until you find it.

**Comment by jbenden** [comment]
The PR posted adjusts how memory usage is computed. I do believe if you have a look at it, you'll find it displays the values you'd rather see.

On an aside, it doesn't account for the rounding pointed out above. The values with the PR are indeed ever slightly off, so the rounding may be a part of why.

**Comment by VortexAcherontic** [comment]
I also have some strange behavior with the latest conky version. Below you can find 2 screenshots of conky.

Version: 1.11.4:
![Screenshot_20190905_001235](https://user-images.githubusercontent.com/11244092/64295670-0b0af680-cf72-11e9-9bc1-76c100d55d09.png)

Version: 1.11.5
![Screenshot_20190905_001430](https://user-images.githubusercontent.com/11244092/64295723-31309680-cf72-11e9-866b-4ee879bd9d24.png)

As you can see negative ram usage and the NVidia Dataproviders seems to be broken.

NVidia Driver is: 435.21
OS: openSUSE Tumbleweed
Kernel: 5.2.11

**Comment by lasers** [comment]
>latest conky version

~~Version: 1.11.4~~ The fix might be 0d44902 and it is 1.11.6_pre.
