### ISSUE TITLE
Conky doesn't display units in the International System of Units (SI)

### ISSUE THREAD

**Issue by ghost** [brndnmtthws/conky#86]
It is known that units come in two flavors: SI units (powers of 10) and binary units (powers of 2). Is there a way so that Conky can select which one to use? like in a config setting? I know there's a method to convert bytes to the human readable form (format_human_readable), you can use this together with a setting like (possibly) use_si_units yes|no to use powers of 10 instead of 2 (that is, divide by 1000 instead of by 1024). I hope you can take this into account or else, how can I submit this as a patch? (I'm new to github).

**Comment by lasers** [comment]
@su8 Easy fix? 
```
$ grep -R 'human.*1024' ~/src/conky
```

**Comment by lasers** [comment]
Closed via https://github.com/brndnmtthws/conky/pull/581
