### ISSUE TITLE
Conky will not start as systemd user service

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [brndnmtthws/conky#869]
**Issue**

Cf. #673.
But I thought I should start a new report (though I did comment a little while ago on that issue).

**Information**

conky 1.1.4_pre (later versions produce erroneous formatting on my system; see #821.)
Linux Mint 19.2 Cinnamon

I have this systemd user service:

```
[Unit]
Description=conky
After=xorg.target

[Service]
Type=simple
StandardError=syslog
StandardOutput=syslog
# SyslogIdentifier=conky start service
ExecStart=/home/<my username>/scripts/Conky/meta/conky_start
Environment="DISPLAY=:0" "XAUTHORITY=/home/nicholas/.Xauthority"

[Install]
WantedBy=graphical.target
```

`conky_start` is set to run conky _undaemonised_. When I start the service manually, conky runs - all is well. When the service runs automatically on boot, the syslog tells me conky has started but there is no output on the screen. If I change the script to run conky *daemonised*, then, when the script is run via the service, there is no visible conky whether I run the service automatically _or_ manually.

EDIT: adding a delay of 20 seconds, within the `conky_start` script, does not change anything if I use a service to run that script and - via that script - conky.

I am trying to run conky via a service because, as I say in my comment on #673, on my system conky can fails to display on my system is set to run as a normal autostarting program. More specifically: if run that way, there must be a seemingly arbitary delay before Conky runs, else Conky fails to appear. I infer from the conjunction of that and the systemd problem that there is something in conky and/or Cinnamon that is causing both problems.

**Comment by brndnmtthws** [comment]
What's in the `conky_start` script? What does `journalctl -u conky` show?

By the way, I wouldn't recommend running Conky as root (or anything, for that matter, unless you absolutely must).

**Comment by LinuxOnTheDesktop** [comment]
The `conky_start` script is complicated or at least the bash library that it invokes is complicated. I think it best if, at least initially, you try to reproduce the problem using a script that contains only the following.

`conky -d -c "$PATH_CONKY_FILE"`

though you may want to test the following too:

`conky -c "$PATH_CONKY_FILE"`

Running as root: by running Conky as as a *user* service, I am _not_ running it as root - no?

**Comment by brndnmtthws** [comment]
I missed the bit about it being a user service.

Right now, without more information, I don't have a lot to go on. Try adding `-DD` to the arguments to see if you can get any useful debug info.

**Comment by LinuxOnTheDesktop** [comment]
Here is what `-DD` yields.

![image](https://user-images.githubusercontent.com/47056543/61966263-24f80780-afca-11e9-98c8-fb16feea7e94.png)

But I do not see my conky. Nor does changing conky's window type to 'normal' help. The same goes for disabling double buffering.

**Comment by LinuxOnTheDesktop** [comment]
Ah - I should say that the following now works: After boot, manually running the (user) service that runs (daemonises) conky. (That it did not was due to an error my end, to do with the script that launches conky - a script launched by a service - stopping the service.)

What still does not work is having the service set to autostart; in that case, on boot, there is this error in my log (generated by the bash script that the services calls): `X Error: Display <some hex>`.
