### ISSUE TITLE
execi timeout

### ISSUE THREAD

**Issue by fagcinsk** [brndnmtthws/conky#87]
If my device hibernated, some script will not exexuted after powerup.
May be every global update tick we need to check last update time?

**Comment by mswanson-me** [comment]
Can you please elaborate? When you wake your device from hibernation, what exactly happens? Please provide as much detail as you can! :)

**Comment by lasers** [comment]
I'm closing 3 years, 2 months old issue. f you're still experiencing issues with `execi timeout`, chime in here with many details as you can.... and we'll open this again. Otherwise, it's all in the past.  Thanks.
