### ISSUE TITLE
Lost variables (audacious related)

### ISSUE THREAD

**Issue by freebird54** [brndnmtthws/conky#872]
A script I have been running for a good while now suddenly died with a switch from 1.10.8 to the 1.11.3 found on my new install. Here is the example code fragment:
${voffset 43}${if_match "${audacious_status}" != "Stopped"}${goto 8}${color3}${audacious_bar 8,435}${font}${endif}
This results in  the variable name being printed where the bar should be. Both audacious_status and audacious_bar are reported as unknown variables on startup:
conky: unknown variable '$audacious_status'
conky: unknown variable '$audacious_bar'
There are conflicts with other packages if I try to downgrade/upgrade on this system. Just thought it might be something you should know.
freebird

**Comment by lasers** [comment]
For what it's worth...
>`libaudclient` is a legacy D-Bus client library that used to be included with Audacious. Though it is no longer actively maintained, libaudclient still works with the current version of Audacious and can be downloaded separately.

_source: https://audacious-media-player.org/download_

The replacement is a command line tool `audtool`.

Option 1) We look into this... and try to fix it.
Option 2) We drop this in favor of external `${exec audtool...}`.

**Comment by freebird54** [comment]
Was not aware that library was the probable cause. I have found that it *IS* on the various 'buntus I run, (where everything works fine) and NOT on the version that pacman gives me on Arcolinux. I tried downloading as suggested, but cannot get the result to work - perhaps it should be installed somewhere unexpected?
I make extensive use of audtool as it is, so getting status is not a problem, but replacing the audacious_bar is a bit harder - the execbar family don't take width,height arguments, and all the other bars are tied to specific conky variables as far as I can see. I guess I'll have to lose the colour change on on CPU temps, and use execibar for audacious use instead.
Thanks again for the quick response, and sorry for suggesting it was a conky version issue...

freebird

**Comment by lasers** [comment]
Seeing how you're on Arc*linux, I see an orphaned `aur/conky-audacious` which tells me that you might have a version of `conky` built/installed without `BUILD_AUDACIOUS` flag. Ubuntu and others probably have more things enabled.

More information can be found at https://github.com/brndnmtthws/conky/wiki/Installation#110-and-later-versions if you want to try and compile `conky` yourself with `BUILD_AUDACIOUS` flag.

**Comment by freebird54** [comment]
For someone who used to make a living programming I am nearly helpless with today's package building setups. It was so much simpler in 680x0 assembler! (and bare-bones C - and Modula-2 - and even BCPL :) I'll give it a look though - and thanks for the ideas. Perhaps the aur (if not TOO old) might help too - if not I'll just keep hoping that execbar gets its own parameters someday :)

freebird

**Comment by freebird54** [comment]
Despite my doubts, I managed to modify an AUR pkgbuild to lose nvidia support and substitute BUILD_AUDACIOUS with libaudclient - and all is currently working. Thanks for the suggestions.
freebird
