### ISSUE TITLE
Process is now called "AppRun" instead of "conky"

### ISSUE THREAD

**Issue by bitwombat** [brndnmtthws/conky#875]
In Linux, the conky process now shows up as `AppRun` (ostensibly because of the newish AppImage packaging?). This is a little inconvenient, because I either have to remember this fact, or I have to hunt it down each time.

For example, it means I have to do `killall -9 AppRun` instead of `killall -9 conky`.

This is on Ubuntu 16.04 LTS.

Is it reasonably easy to make the process name `conky` again?

**Comment by probonopd** [comment]
Have e.g., an `AppRun` script that execs the `conky` process.
