### ISSUE TITLE
1.11. 5 No Man Page

### ISSUE THREAD

**Issue by 0pLuS0** [brndnmtthws/conky#879]
**Issue**

1.11.3 created a man page just fine, but since 1.11.4 and 1.11. 5 I can't get a man page created when I compile from source.

**Information**

1.11.5 - Slackware 14.2 x86_64

Slackware 14.2 comes with linuxdoc-tools-0.9.69 which has /usr/bin/docbook2x-man

All I can think is that I need a newer version of linuxdoc-tools-0.9.69 with docbook2x?

Hmm

**Comment by 0pLuS0** [comment]
I updated to the latest version of linuxdoc-tools-0.9.73 in Slackware Current and it didn't help.

Man is not being created...

**Comment by 0pLuS0** [comment]
Ahh I figured it out for anyone compiling from source.

I needed to add this for 1.11.5 which I didn't use before... :)

-DBUILD_DOCS=ON

**Comment by lasers** [comment]
Thank you for the follow up. ;-)
