### ISSUE TITLE
wiki - broken image 

### ISSUE THREAD

**Issue by CarlFK** [brndnmtthws/conky#881]
https://github.com/brndnmtthws/conky/wiki/Using-Lua-scripts-(Part-02)%3A-Displaying-stuff-in-conky

`For example, you can open up gimp and use it to get a color you like:` 

https://camo.githubusercontent.com/3de49812764fefa05afe4a8c11f4daf191c13709/687474703a2f2f656e2e7a696d6167657a2e636f6d2f6d696e6961747572652f73637265656e73686f7466656462653732383533646338343434386536653936366366636534636565652e706e67
HTTP/1.1 404 Not Found  / Cannot proxy the given URL

**Comment by lasers** [comment]
Thanks!
