### ISSUE TITLE
no mpd values and conky crashing

### ISSUE THREAD

**Issue by kinleyd** [brndnmtthws/conky#882]
My conky setup has been working for several years but in the last couple of months has stopped working properly. Firstly, I'm not getting mpd values as I used to, and after sometime conky completely freezes.

wrt to the mpd values, I used to have this in my lua script:

... time=conky_parse ("${time %a %b %d %H:%M:%S}")
mpd=conky_parse ("[$mpd_status] $mpd_artist - $mpd_date - $mpd_album - ${mpd_title 60} [${mpd_bar 7,15}] $mpd_elapsed/$mpd_length ${mpd_percent}% Bitrate ${mpd_bitrate}")

When rendered the above used to work. Now it works only if I add the extra call to an mpd variable to my time string, like so:
time=conky_parse ("${time %a %b %d %H:%M:%S} $mpd_status")

I don't know why it works, but it's a useful workaround for now, though it'd be good if it could be sorted out.

And yes, secondly conky freezes regularly and I have no idea why.

I'm using conky 1.11.5-1, dzen2 0.9.5.14 and lua 5.3.5-2 on Arch Linux with exwm. 

I have this setup:

conky.config = {
    out_to_x = false,
    double_buffer = true,
    out_to_console = true,
    short_units = true,
    update_interval = 1,
    music_player_interval = 1,
    lua_load = "/../panel.lua",
    lua_draw_hook_post = "main"
}

TIA

**Comment by brndnmtthws** [comment]
Bummer. Have you ever been able to attach a debugger when it freezes? A stack trace would be invaluable.

It's possible that the MPD stuff has a regression as it seems to have fallen out of fashion.

**Comment by kinleyd** [comment]
Thanks for getting back, Brenden.
I'll get back with a stack trace as soon as I can.

**Comment by kinleyd** [comment]
So I ran conky in a gdb stack trace, and waited for the crash which usually happened inside 5 to 10 minutes. And I waited and waited, but no crash was forthcoming. So I re-ran my normal conky setup in its dzen2 panel expecting it to crash there, but nope. Waited for a long time and no crash.

So I'm figuring something got updated on my system and fixed the part that was crashing. No idea what it was, but yay!

The mpd_* variables continue to be problematic though. I still have to use the additional call to an mpd_* variable when setting up my time string in order to get mpd variables to refresh in the mpd string in my set up.

What I wanted to add is that though I have this problem when running my dzen2 panel, I have no problems with mpd variables if I run conky in a standard shell without dzen2.

**Comment by kinleyd** [comment]
I've run my setup in multiple ways with gdb and encountered crashes with these runs. Unfortunately I have not been able to get any stack traces. At best I get a 'No stack.' response. 

When I do this, conky only runs in the shell window without the dzen2 panel, and doesn't crash either, so there isn't anything to trace:
$ gdb conky
(gdb) run -c ~/.myconky.set.up 

When I do this, the dzen2 panel runs, and crashes ater some time, but I don't get to run the back trace as the shell doesn't return me to the prompt:
$ gdb conky
(gdb) run -c ~/.myconkyconfig | dzen2 ~/.mydzen2config 

Is there any other way I should try to run this when combining conky and dzen2?

**Comment by brndnmtthws** [comment]
I've got too much on my plate to test this myself right now, so if anyone wants to help out then obtaining a stack trace would be invaluable (for the crashes).

For the mpd issues, can you try running conky with debug mode enabled and share the output? Run with `-DD` to get the most verbose output, and double check there's nothing sensitive.

**Comment by kinleyd** [comment]
I ran:
$ conky -DD -c conky.script | dzen2

If I don't add the extra $mpd_artist (or other mpd variable) to the time string I mentioned in my first post, my mpd string comes out this way:
`DEBUG(1) [/build/conky/src/conky-1.11.5/src/conky.cc:739]: evaluated '[$mpd_status] $mpd_artist - $mpd_date - $mpd_album - ${mpd_title 60} [${mpd_bar 7,15}] 
$mpd_elapsed/$mpd_length ${mpd_percent}% Bitrate ${mpd_bitrate}' to '[]  -  -  -  [...............] 0:00/0:00 0% Bitrate 0'  `

If I do add the extra mpd variable, I get this collection of lines just before it crashed:

`...
DEBUG(1) [/build/conky/src/conky-1.11.5/src/conky.cc:739]: evaluated '[$mpd_status] $mpd_artist - $mpd_date - $mpd_album - ${mpd_title 60} [${mpd_bar 7,15}] 
$mpd_elapsed/$mpd_length ${mpd_percent}% Bitrate ${mpd_bitrate}' to '[Stopped] Guns N' Roses - 1991 - Use Your Illusion II - Civil War [...............] 0:00
/0:00 0% Bitrate 0'                                                                                                                                         
DEBUG(1) [/build/conky/src/conky-1.11.5/src/fonts.cc:149]: loading fonts
DEBUG(1) [/build/conky/src/conky-1.11.5/src/fonts.cc:94]: setting up fonts
DEBUG(1) [/build/conky/src/conky-1.11.5/src/core.cc:2031]: no templates to replace
DEBUG(1) [/build/conky/src/conky-1.11.5/src/fonts.cc:149]: loading fonts
DEBUG(1) [/build/conky/src/conky-1.11.5/src/conky.cc:739]: evaluated 'exwm Arch $sysname $kernel $machine ' to 'exwm Arch Linux 5.3.1-arch1-1-ARCH x86_64 '
DEBUG(1) [/build/conky/src/conky-1.11.5/src/core.cc:2031]: no templates to replace
DEBUG(1) [/build/conky/src/conky-1.11.5/src/fonts.cc:149]: loading fonts
DEBUG(1) [/build/conky/src/conky-1.11.5/src/conky.cc:739]: evaluated '/ ${fs_used_perc /}% (${fs_used /}/${fs_size /}) /home ${fs_used_perc /home/}% (${fs_us
ed /home/}/${fs_size /home/}) disk-stuff ${fs_used_perc /disk-stuff/}% (${fs_used /disk-stuff/}/${fs_size /disk-stuff/}) ' to '/ 76% (22.6G/29.4G) /home 72% 
(137G/190G) disk-stuff 73% (2.64T/3.58T) '                                                                                                                  
DEBUG(1) [/build/conky/src/conky-1.11.5/src/core.cc:2031]: no templates to replace
DEBUG(1) [/build/conky/src/conky-1.11.5/src/fonts.cc:149]: loading fonts
DEBUG(1) [/build/conky/src/conky-1.11.5/src/conky.cc:739]: evaluated '$uptime Load $loadavg ' to '0h 54m 22s Load 0.70 0.84 0.88 '
DEBUG(1) [/build/conky/src/conky-1.11.5/src/core.cc:2031]: no templates to replace
DEBUG(1) [/build/conky/src/conky-1.11.5/src/core.cc:686]: Adding $cpu for CPU 0`

And that's where the debug output ends.

**Comment by kinleyd** [comment]
I have run my dzen panel for sometime without calling mpd variables, and so far conky has not crashed at all. It would seem that it is purely an mpd issue as you mentioned it might be.
