### ISSUE TITLE
Wrong RAM values

### ISSUE THREAD

**Issue by vmxoxo** [brndnmtthws/conky#883]
RAM values drop back to low false values at intervals.
The Fix #878 don't work for me.

OS: Arch Linux
Package: conky
Version: conky 1.11.5-2
```

conky.config = {
    no_buffers = true,
    out_to_x = false,
    out_to_console = true,
    update_interval = 3.0,
    short_units = true,
}
conky.text = [[ RAM ${mem} ${top_mem mem_res 1} ]]
```

> conky -c conky.conf
>  RAM 3,91G 2,29G 
>  RAM 3,91G 2,29G 
>  RAM 186M 2,29G 
>  RAM 183M 2,29G 
>  RAM 180M 2,29G 
>  RAM 196M 2,29G 
>  RAM 192M 2,29G 
>  RAM 189M 2,29G 
>  RAM 187M 2,29G 
>  RAM 3,90G 2,29G

**Comment by CtrlSequence** [comment]
I did a quick check and the current Arch Linux version (1.11.5-2) doesn't include #878 since there hasn't been a new release version tagged yet.

I want to make sure that the fix doesn't work, so I need to know if this output is from the Arch version or if you've built it locally from the git.

**Comment by vmxoxo** [comment]
The output comes from the Arch version.

**Comment by CtrlSequence** [comment]
OK. If you can, try and build the git version and run the git version to see if the problem continues.

The recent Arch version `1.11.5-2` only updated `PKGBUILD` release version to include nvidia support, but still uses the archive version tagged `1.11.5` which doesn't include the recent modifications.

If you run current git version and there are no problems, a quick fix would be to switch to the AUR `conky-git` version for the time being until a new release is tagged.

If you run the git version and the problem persists please comment to let me know so I can figure out what's going on.

**Comment by vmxoxo** [comment]
OK, thanks. I'm waiting for the next release.
https://bugs.archlinux.org/task/63597
