### ISSUE TITLE
Syntax error: attempt to load lua script instead of config

### ISSUE THREAD

**Issue by AlexAndHisScripts** [brndnmtthws/conky#884]
**Issue**

I am trying to install [this](https://github.com/carriejv/dotfiles/blob/master/mcrn/.conky/conky-mcrn.lua) and having added package.preload['cairo'] I have an error I can't find anything about-

```
[redacted]@[redacted]-ubuntu-Lenovo110s:~/.conky$ conky -c conky-mcrn.lua
conky: Syntax error (conky-mcrn.lua:2: '=' expected near 'package') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: [string "..."]:139: attempt to index local 'settings' (a nil value)
```

**Information**

Ubuntu budgie, conky -v returns:

```conky 1.10.8 compiled Thu May  3 21:07:47 UTC 2018 for Linux 4.4.0-122-generic x86_64

 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * RSS
  * Weather (METAR)
  * Weather (XOAP)
  * wireless
  * support for IBM/Lenovo notebooks
  * nvidia
  * eve-online
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support
  * PulseAudio

 Lua bindings:
  * Cairo
  * Imlib2
  * RSVG
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * Xshape extension (click through)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * Audacious
  * MPD
  * MOC
  * XMMS2

 Default values:
  * Netdevice: eth0
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 64
  * Maximum text size: 16384
  * Size text buffer: 256
```

Does anyone have any idea how to fix this?

**Comment by lasers** [comment]
You want to use `-c` to load `conkyrc`, not lua script(s).

Inside your `conkyrc`, you can load lua script(s) using various `lua_*` configuration settings.

In that case, use https://github.com/carriejv/dotfiles/blob/master/mcrn/.conkyrc  and fix the path.

**Comment by AlexAndHisScripts** [comment]
Thanks for the help! I now have another problem, when trying to load the script I get


```X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  1 (X_CreateWindow)
  Serial number of failed request:  104
  Current serial number in output stream:  106
```

**Comment by lasers** [comment]
Try commenting out `own_window` settings. If that doesn't work, I don't have anything else in mind.

**Comment by lasers** [comment]
1) First problem has been solved. Conky ran okay.
2) Second problem (i.e. X Error) is out of my scope.
*  It may be possible to solve this by applying different `own_window`* settings.

No response for two weeks. I'm closing this. Thanks. :+1:
