### ISSUE TITLE
How many digits can ${top pid} display?

### ISSUE THREAD

**Issue by morfikov** [brndnmtthws/conky#885]
I'm using the following sysctl setting:

```
# sysctl -a | grep pid_max
kernel.pid_max = 4194304
```
But it looks like the ${top pid} displays max first 5 digits and cut the rest off, so instead of a pid 1234567, I get 12345. Should this happen?

**Comment by lasers** [comment]
>Should this happen?

Probably not. I think the code is here. `%5i`. https://github.com/brndnmtthws/conky/blob/0d449029eaee689da88fcf1d0d572188f4e757d6/src/top.cc#L541

**Comment by morfikov** [comment]
Maybe the column is to narrow?

**Comment by lasers** [comment]
Fixed by https://github.com/brndnmtthws/conky/pull/895.
