### ISSUE TITLE
无法放到任务栏上，你就是无用

### ISSUE THREAD

**Issue by yanhuizhou** [brndnmtthws/conky#887]
调来调去，都没办法放到任务栏的位置，真心不好！
只是想能及时看到网络、ip、cup的运行状态而已～其它功能，有多漂亮多好看，都是不中用！

**Comment by lasers** [comment]
Google Translated:
>Adjusted to adjust, there is no way to put it in the position of the taskbar, really bad!
Just want to be able to see the running status of the network, ip, cup in time ~ other functions, how beautiful and how beautiful, are not used!

My reply:
尝试各种`own_window`设置。 有`own_window_type`，你可以指定`normal`，`desktop`，`dock`，`panel`或`override`。 它可能有所帮助。 另外，请参阅`own_window_hints`设置。

>Try various `own_window` settings. There is `own_window_type` where you can specify `normal`, `desktop`, `dock`, `panel` or `override`. It may help. Also, see `own_window_hints` setting too.

**Comment by lasers** [comment]
No response for more than a week. I'm closing this. Thanks. :fries:
