### ISSUE TITLE
Stall after damonizing with ${no_update ${fs_size /}}

### ISSUE THREAD

**Issue by hexchain** [brndnmtthws/conky#888]
**Issue**
Conky stalls after daemonizing (`conky -d`) with the following config.

**Information**

```lua
conky.config = {
    no_buffers = true,
    out_to_x = false,
    out_to_console = true,
}
conky.text = [[ ${no_update ${fs_size /}} ]]
```

**Comment by lasers** [comment]
How long before it stalls? What version? Seems okay for me on `conky 1.11.6_pre`.

**Comment by hexchain** [comment]
Sorry, I forgot to mention that it stalls only in daemon mode, i.e. with `conky -d -c conky.conf`.

It happens with the current git master.

**Comment by lasers** [comment]
I'm able to find `conky` with `pgrep -a conky` after an hour. I do not recall `-d`. I also don't know how to check if the variables are still being printed out with this simplistic config. How are you viewing the variables in console + daemon?

I'm wondering if it's something recent or if it's a longstanding bug. Once I am able to reproduce your bug, I'd want to git bisect this to see if a recent commit caused it... or if you're able to do that too, that'd be good too.

(Opinion) I think `-d` may be more for X11 than console, ncurse, web, etc.

**Comment by hexchain** [comment]
I had the problem when running conky from the .desktop file with my normal config - the window just doesn't show up but a process is hanging there if I start `conky` from the Plasma application menu. I tried to remove irrelevant parts of my config to isolate the culprit, which is `${no_update ${fs_size /}}`, or just `no_update` - in fact, it works if you remove the `no_update` tag.

Having it output to console is for the ease of debugging. Even if conky forked to background it should still retain the reference to the invoking tty as its stdout. If you remove the `no_update` part then the output should look like this:
```
/tmp $ conky -dc conky.conf
conky: forked to background, pid is 236076
/tmp $
 468GiB
 468GiB
 468GiB
 468GiB
 468GiB
kill 236076  # this is input
 468GiB
conky: received SIGHUP, SIGINT, or SIGTERM to terminate. bye!
```

And with `no_update`:
```
/tmp $ conky -dc conky.conf
conky: forked to background, pid is 236515
/tmp $

/tmp $ kill 236515
/tmp $ kill 236515
/tmp $ kill -9 236515
/tmp $ kill -9 236515
bash: kill: (236515) - No such process
```

**Comment by lasers** [comment]
c352069b31b2dbb4d87503603d6c6d3ddd517df6 is the first bad commit

**Comment by hexchain** [comment]
I can't seem to reproduce this issue anymore.
