### ISSUE TITLE
Feature Request: switch direction of cpugraph

### ISSUE THREAD

**Issue by reece146** [brndnmtthws/conky#890]
It would be cool if there was a switch/toggle for cpugraph (or any graph object) to reverse the direction from right to left to left to right. Hey - up and down would be cool also. :)

Thanks.

**Comment by dicktyr** [comment]
I think graph inversion is indeed useful
and I've come to appreciate it for network activity

uplink on top
downlink on bottom (and inverted)

the two graphs share the time axis
and bringing the baselines together
by inverting the bottom graph
makes for a more coherent display

**Comment by develop-Greenant** [comment]
similar to #1156

**Comment by dicktyr** [comment]
github-actions is stale
