### ISSUE TITLE
up/downspeedgraph autoscales even with defined scale parameter

### ISSUE THREAD

**Issue by cppt** [brndnmtthws/conky#891]
Looking to tweak the up/downspeedgraph objects in my conky.conf file to make the graphed values relative to a max value rather than, by default, autoscaling depending on the amount of traffic.  

Adjusting the scale parameter to a little above my connection speed (100 Mb/s), the graph _still_ autoscales, such that even with limited traffic up or down, the graph occasionally fills most of the plot.  

I'm using the below line in my config file.  Why doesn't the below remove autoscaling?

`${downspeedgraph wlp2s0 20,250 DimGray DimGray 14000}`

**Comment by lasers** [comment]
> Why doesn't the below remove autoscaling?

I tried various parameters and nothing worked. This might be broken for quite a long time because I tried `git bisect` to find a bad commit. I only can go as far back to `1.10.8_pre` and it printed the same thing. Some graphs (in the screenshot below) contains `-t`. I think you just found a bug. 

![2019-10-06-023503_260x665_scrot](https://user-images.githubusercontent.com/852504/66265803-fd9b9300-e7e1-11e9-99e8-b1ebe4956c06.png)

**Comment by cppt** [comment]
@lasers thanks for this.  What's the protocol for getting the bug fixed then?

**Comment by lasers** [comment]
There is no protocol. Anything goes. Helping is helping.

It's not always the collaborators or the owner that does everything.

Conky and other projects likely accepts contributions, bugfixes, new features, etc from anyone that want to fix or contribute. If you want to try fixing this or other issues, then go ahead and try that.

I'm here to help out what I can -- Addressing issues, trying out the pull requests, occasioanlly helping out users with their conky troubleshooting, fixing up docs + wiki, etc... and nothing to do with the code.

**Comment by cppt** [comment]
workaround to this.  for some reason, the below achieves the fixed plot:
`${color DimGray}${upspeedgraph wlp2s0 20,250 1400}`

**Comment by pbtsrc** [comment]
It seems the scale parameter of up/downspeedgraph is in B/s now, not in kB/s
So just add 000 to the current value
