### ISSUE TITLE
mem/membar objects don't update correctly

### ISSUE THREAD

**Issue by cppt** [brndnmtthws/conky#899]
Working within Ubuntu 18.04 with a working conky config file, I've recently noticed the mem and membar objects don't update accurately.

I updated OS and restarted earlier, which remedied the issue, but has cropped up again in the last couple hours. 

Any guidance on how these objects access the information form Ubuntu are appreciated. 

```
$font${color DimGray}MEM $alignc $mem / $memmax $alignr $memperc%
$membar
```

![Screenshot from 2019-10-30 01-00-18](https://user-images.githubusercontent.com/40817827/67840261-afad3e80-fab2-11e9-9a32-243ac29716b0.png)

**Comment by lasers** [comment]
We had problems with this for some time. I believe it was fixed recently (i.e. 9 days ago). https://github.com/brndnmtthws/conky/pull/859. 

You would need to use conky-git `v1.11.6_pre` or compile conky yourself to confirm this. It's not in the current release right now too. Ubuntu 18.04 (LTS) is currently on `v1.10.8`. I'll go ahead and close this. Any more questions and I'll answer them. Cheers.
