### ISSUE TITLE
lua_gettable's return type is int, not void in lua-5.3

### ISSUE THREAD

**Issue by vesath** [brndnmtthws/conky#90]
conky-1.10.0 fails to compile against lua-5.3; the error is:

In file included from /usr/include/lua.hpp:6:0,
                 from /build/conky/src/conky-1.10.0/src/luamm.hh:30,
                 from /build/conky/src/conky-1.10.0/src/luamm.cc:24:
/build/conky/src/conky-1.10.0/src/luamm.cc: In member function 'void lua::state::gettable(int)':
/build/conky/src/conky-1.10.0/src/luamm.cc:370:3: error: no matches converting function 'safe_misc_trampoline' to type 'lua_CFunction {aka int (*)(struct lua_State*)}'
   lua_pushcfunction(cobj.get(), (&safe_misc_trampoline<&lua_gettable, 1>));
   ^
/build/conky/src/conky-1.10.0/src/luamm.cc:168:7: note: candidate is: template<void (* misc)(lua_State*, int), int nresults> int lua::{anonymous}::safe_misc_trampoline(lua_State*)
   int safe_misc_trampoline(lua_State *l)
       ^
src/CMakeFiles/conky.dir/build.make:675: recipe for target 'src/CMakeFiles/conky.dir/luamm.cc.o' failed

It turns out lua_gettable returns an int in lua-5.3. The attached patch fixes this issue, though as currently written it is specific to lua-5.3.

**Comment by vesath** [comment]
```
diff -aur old/src/luamm.cc new/src/luamm.cc
--- old/src/luamm.cc	2015-06-28 16:38:47.793615922 -1000
+++ new/src/luamm.cc	2015-06-29 09:05:44.646667638 -1000
@@ -165,7 +165,14 @@
 		}
 
 		template<void (*misc)(lua_State *, int), int nresults>
-		int safe_misc_trampoline(lua_State *l)
+		int safe_misc_trampoline_set(lua_State *l)
+		{
+			misc(l, 1);
+			return nresults;
+		}
+
+		template<int (*misc)(lua_State *, int), int nresults>
+		int safe_misc_trampoline_get(lua_State *l)
 		{
 			misc(l, 1);
 			return nresults;
@@ -326,7 +333,7 @@
 		if( rawequal(index1, index2) )
 			return true;
 
-		return safe_compare(&safe_compare_trampoline<lua_equal>, index1, index2);
+		return safe_compare(&safe_compare_trampoline<&lua_equal>, index1, index2);
 	}
 
 	int state::gc(int what, int data)
@@ -367,7 +374,7 @@
 		checkstack(2);
 		pushvalue(index);
 		insert(-2);
-		lua_pushcfunction(cobj.get(), (&safe_misc_trampoline<&lua_gettable, 1>));
+		lua_pushcfunction(cobj.get(), (&safe_misc_trampoline_get<&lua_gettable, 1>));
 		insert(-3);
 		call(2, 1, 0);
 	}
@@ -492,7 +499,7 @@
 		checkstack(2);
 		pushvalue(index);
 		insert(-3);
-		lua_pushcfunction(cobj.get(), (&safe_misc_trampoline<&lua_settable, 0>));
+		lua_pushcfunction(cobj.get(), (&safe_misc_trampoline_set<&lua_settable, 0>));
 		insert(-4);
 		call(3, 0, 0);
 	}
```

**Comment by ismaelpuerto** [comment]
With F22 not working this patch
