### ISSUE TITLE
Blanks at the end of the output of ${top name X}

### ISSUE THREAD

**Issue by jerigondor78** [brndnmtthws/conky#902]
**Issue**
With ${top name X}, the output string have some blanks at the end.
For example, if you write ${top name 1}${top name 1}${top name 1} you have:
conky      conky       conky
But I think it should show:
conkyconkyconky

It's a problem when you want to aling the output to the right.

**Information**

Debian 10 buster.
Xfce 4.12
conky 1.10.8

**Comment by lasers** [comment]
Process names vary. It's hard to keep things organized. See default config for an example.
https://github.com/brndnmtthws/conky/blob/26d23cb70718956493df7d3102dc3000f0f56685/data/conky.conf#L80-L85

Maybe something like https://github.com/brndnmtthws/conky/issues/780 would be nice along with text alignment option. I dunno.

**Comment by philer** [comment]
I don't know if this is related but it looks like a similar issue applies to $downspeed and $totaldown:
```
${alignr 10}${downspeed enp0s31f6}
${alignr 10}${totaldown enp0s31f6}
```
![2019-11-05-121841_crop](https://user-images.githubusercontent.com/4589347/68204282-eb229e00-ffc7-11e9-9d5a-9fe5de89f03f.png)
The misalignment only happens while the units are different.  When the downspeed goes up to KiB/MiB/GiB the strings become aligned.
