### ISSUE TITLE
Global variables gets shared between two lua scripts

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [brndnmtthws/conky#905]
**Issue**

I run two lua scripts from conky. Each has a global variable called `debug`. Each does something if `debug` is not zero. If I set debug to `1` in one of the scripts, then the _other_ script acts as if _its_ version of the variable had been changed. Is this a known limitation?

**Information**

conky 1.11.4_pre. (I would use a more recent version, were I not to encounter bug #821.)

**Comment by lasers** [comment]
Internet tells me it is a typical lua behavior because of global variables. Look this up and modify your scripts to add local to everything so you don't accidentally assign wrong variables.

**Comment by LinuxOnTheDesktop** [comment]
Understood.
