### ISSUE TITLE
positioning  enhancement

### ISSUE THREAD

**Issue by 54freebird** [brndnmtthws/conky#906]
**Issue**
Conky must internally maintain a 'position' coordinate from which ${voffset} and ${goto} are derived. Access to this position would simplify life considerably, as currently a change in one place propagates throughout a script. Using an object with a -px,y capability is fine - but then where you 'are' is difficult to know - and can lead to hard-to-find 'bugs' (such as writing text slightly out of the window confines - causing weird reactions in subsequent sections.
My suggestion, if easy to implement, would be an object to ${set x,y} as needed as you go - perhaps by script "code section" - both to limit the cascading reactions effect, and to accurately place text where you intend it to go.
Of course there are other methods of achieving the same thing (creating a text object with coords) but I suspect they would be more involved/expensive to implement - whereas this set x,y would be used only when needed and would use the already existing internal mechanisms.
I'd be interested to hear why this wouldn't work, if it wouldn't... but I would love to see it implemented!
freebird54

**Comment by 54freebird** [comment]
Forgot to mention, a ${read x,y} to find out where the coordinate currently points would be about as good for accuracy, although it wouldn't stop change cascades.
fb

**Comment by philer** [comment]
I think this is asking for the same as #450. $goto already allows us to do absolute horizontal positioning and $alignr does it from the right. Adding a vertical version (e.g. $vgoto) would complement that. ${set x,y} would then be slightly more verbose with ${goto x}${vgoto y}.

**Comment by 54freebird** [comment]
Whatever mechanism results in the least amount of work to implement is the preferred option! Anything to allow the script(er) to KNOW where the vertical position currently resides, or to SET where the vertical position is. I have implemented a few complicated scripts over the years that the 'cascade' effects have driven me near to distraction - for example one had me inserting elements into a background picture of an airplane cockpit (redefining what the 'glass panels' show, and showing the clock as a digital readout, and putting weather on the "stormscope" etc. TGhere was massive use of negative {voffset}s, and a tweak one place caused need for more tweaks in 4 or five others. Another script has different 'views' flipping into sight depending on elapsed time since refresh, and again there is no simple way to ensure that text will appear where you want it when a new view flips in. You can see what I mean with a look at  https://vimeo.com/373829842 - the problem was the location ID text at the bottom left of each panel - if too low took out the NEXT flip page!
Sure would appreciate SOME mechanism for avoidance - so far I have found lua beyond me.. :)
freebird

**Comment by philer** [comment]
I know your problem. It's what made me write a layout engine for Lua widgets (https://github.com/philer/polycore). It does away with the issue for anything rendered by Lua. Unfortunately, cairo's font rendering isn't as good as conky's, so for plain text I'm still relying on good old `conky.text`… With $vgoto I could at least use my layout engine to automatically position that text.

**Comment by bi4k8** [comment]
I don't think there's a fundamental reason not to do this. However, this is indeed a duplicate of #450.

**Comment by bi4k8** [comment]
Duplicate of #450.

**Comment by bi4k8** [comment]
I'll be damned if I can get GH to show a ["marked as duplicate" event](https://docs.github.com/en/issues/tracking-your-work-with-issues/marking-issues-or-pull-requests-as-a-duplicate).
