### ISSUE TITLE
RAM monitot does not work correctly

### ISSUE THREAD

**Issue by Dimerbone** [brndnmtthws/conky#909]
### After upgrading my system, my conky became like this:
![1](https://user-images.githubusercontent.com/40519811/69472317-8480eb00-0de3-11ea-8170-c074d6c09dcc.gif)
### The dependent code is:
```
${voffset 5}${color1}${font ubuntu:size=11:regular}RAM usage: ${font}${color6}$mem${color1}${alignr}${font ubuntu:size=11:regular}Free: ${font}${color6}$memeasyfree
${color6}${membar}
```
## Informations
System:Manjaro 18.1.3
DE:Deepin Desktop Environment
Kernel:Linux 4.19.84-1-MANJARO

**Comment by lasers** [comment]
That should be fixed already. Try `aur/conky-git`. Close this when you confirm it. Thanks.

**Comment by benutzer74** [comment]
I have this issue too. Using conky 1.11.5, conky shows a negative RAM value every few seconds, e.g. "-2,75 GiB/31,0 GiB".
This bug has appeared after using a 5.3.x kernel. It seems conky has problems with kernel 5.x.?

**Comment by lasers** [comment]
Is it possible you updated both conky and kernel? https://github.com/brndnmtthws/conky/pull/878 is not part of `1.11.5` so it'll be in `1.11.6` (not released). Also, you can try older version `1.11.4`.

Duplicate https://github.com/brndnmtthws/conky/issues/886.

**Comment by Dimerbone** [comment]
> That should be fixed already. Try `aur/conky-git`. Close this when you confirm it. Thanks.

It works！Thank you.
