### ISSUE TITLE
db2x_manxml fails on non-ascii chars

### ISSUE THREAD

**Issue by vesath** [brndnmtthws/conky#91]
In maintainer mode, db2x_manxml from docboox2x-0.8.8 fails to convert conky-1.10.0's docs.mxml to a man page because it contains non-ascii characters. In fact, db2x_manxml runs `iconv -futf8 -tascii` as a subroutine and iconv itself fails on invalid characters.

I'm not sure what should be done about this. Removing the characters (see patch below) allows the manpage to be generated.

**Comment by vesath** [comment]
Here is the error message:

/usr/bin/iconv: illegal input sequence at position 7849
/usr/bin/db2x_manxml: program in pipeline exited with an error
doc/CMakeFiles/docs.dir/build.make:51: recipe for target 'doc/docs.html' failed
make[2]: *** [doc/docs.html] Error 1
CMakeFiles/Makefile2:218: recipe for target 'doc/CMakeFiles/docs.dir/all' failed

And the obvious patch:

```
diff -aur old/doc/config_settings.xml new/doc/config_settings.xml
--- old/doc/config_settings.xml	2015-06-21 14:49:06.000000000 -1000
+++ new/doc/config_settings.xml	2015-06-29 10:05:00.147318479 -1000
@@ -80,7 +80,7 @@
         </term>
         <listitem>A comma-separated list of strings to use as the bars of a graph output
         to console/shell. The first list item is used for the minimum bar height and the
-        last item is used for the maximum. Example: " ,_,▁,▂,▃,▄,▅,▆,▇,█".
+        last item is used for the maximum.
         <para /></listitem>
     </varlistentry>
     <varlistentry>
```

**Comment by andreas--e** [comment]
That's more like a workaround than a real fix. Think of manuals in complex scripts like Japanese or so. These would most likely still fail because what you did is simply *remove* the non-ascii part (see "patch" snippet), but not properly *handle* it.

**Comment by marcpayne** [comment]
@andreas--e The commit by @paulegan (which is the one that got merged) properly addresses the problem without removing the non-ascii characters.

**Comment by andreas--e** [comment]
Whoops...looks it was late then. Thanks for the heads-up. The "that" in my statement *"That's more like a workaround than a real fix IMO"* was (obviously)  referring to vesath's patch, which suggested that the "fix" was just to remove those "blocky" characters after the *"Example:"* text. Sorry for the noise. In any case, it would be better if the person who does a proper fix also *participated* in this report, instead of doing things stealthily like a street cat. ;-)

**Comment by vesath** [comment]
Thanks for your insight, @andreas--e, but obviously nobody (myself included) never mistook my patch as a proper fix... Just a workaround so conky compiles for the time being. That's why I wrote: "I'm not sure what should be done about this..."
