### ISSUE TITLE
Install after making a clone/download from here

### ISSUE THREAD

**Issue by pundittech** [brndnmtthws/conky#913]
**Issue**

G'day guys,

I am in an environment where I do not have internet so I am trying to install conky on that system. So I have downloaded (Clone) from here. 

I cannot seem to find the proper instructions to install it when downloaded this way; a step-by-step instruction. It is possible that I am looking at the wrong place for it. 

Could you please point me in the right direction or please provide me a step-by-step instruction?

Thank you so much.
Pundit.

**Comment by su8** [comment]
https://github.com/brndnmtthws/conky/wiki/Installation

**Comment by lasers** [comment]
@su8 Thank you for pointing in the right direction. Xo.
