### ISSUE TITLE
Can't change conky configuration

### ISSUE THREAD

**Issue by 1605200517** [brndnmtthws/conky#915]
**Issue**

Whatever I do following the simple installation and configuration tutorial, I see a default view after restart.

https://askubuntu.com/questions/1195057/ubuntu-live-world-clock-app-as-desktop-wallpaper-or-widget-possible?noredirect=1#comment2001614_1195057

**Information**

Xubuntu LTS 18.04

Is there a (debug) log to follow which configuration file has been loaded?

**Comment by lasers** [comment]
>Is there a (debug) log to follow which configuration file has been loaded?

`conky -D` in the terminal.

>$ conky -D
DEBUG(0) [/home/user/src/conky/src/conky.cc:2544]: reading contents from config file '/home/user/.conkyrc'

I don't think it parses `~/.config/conky.conf` by default. You can add `conky -c ~/.config/conky.conf` to your application launcher.

**Comment by 1605200517** [comment]
@lasers thank you a lot! `conky -c` does the job!
