### ISSUE TITLE
Random appearance of widgets

### ISSUE THREAD

**Issue by tiagojpavan** [brndnmtthws/conky#916]
**Issue**

OK, in reality isn't a bug report, is more like a question plus sugestion of (maybe) new config option?
I'm looking over internet and don't find nothing related. I'm trying to make a theme for desktop based on conky, but one widget I really like to make appears and disappears randonly on the same location of screen, or at last make it appears from time to time, but without affect the others widgets on screen. Is that possible? I already looked over conky documentation too, but won't see nothing related
Any help, pleeeease?

**Information**
Parrot OS 4.6
Conky 1.10.8-1+b1
Conky Manager 2.4~136kali2

**Comment by su8** [comment]
Théré aré ††if†† variablés
