### ISSUE TITLE
Own window background always black

### ISSUE THREAD

**Issue by adamreichold** [brndnmtthws/conky#92]
After Arch Linux updated to version 1.10, I have the problem that the background of conky's window is always black. I usually use black text on a white background, so I get a completely black window. But if I switch to white text, everything appears as expected on the still black background.

I use the following `own_window_*` configuration settings

```
own_window = true,
own_window_type = 'desktop',
own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
double_buffer = true,

own_window_colour = 'white',
default_color = 'black',
```

I am running Xfce 4.12 without compositing and during reinitialization conky logs

```
conky: desktop window (1800003) is subwindow of root window (aa)
conky: window type - desktop
conky: drawing to created window (0x2e00001)
conky: drawing to double buffer
```

I tried using a hexadecimal value for `own_window_colour` or using `own_window_color` to no avail. Thank you for your help in resolving this.

**Comment by oberon2007** [comment]
I have the same issue and also weird formatting with the upgrade 1.9 => 1.10
Documented here: https://forum.manjaro.org/index.php?topic=23951.msg208185#msg208185

**Comment by kamek-pf** [comment]
Exact same thing, downgraded to 1.9 and everything is fine.

**Comment by edeustua** [comment]
Same here.

**Comment by oberon2007** [comment]
Setting 'double-buffer = false' does not solve it for me. It creates a different problem here and does not restore transparency. Looks like this: http://www.zimagez.com/zimage/screenshot2015-06-3020-53-49.php

**Comment by kamek-pf** [comment]
@oberon2007 your conky background looks transparent though, we can see you wallpaper through it. How does if look with `double_buffer = false` ?

**Comment by adamreichold** [comment]
Arch Linux just updated its package (to 1.10-2) enabling XDBE during the build which seems to resolve the issue for me. Hence I'd say this was an downstream issue and could be marked invalid from my point of view. (Maybe this is therefore actually a duplicate of issue #55.)

**Comment by oberon2007** [comment]
@kamek-pf no! the wallpaper you can only see around the conky. its black.

**Comment by oberon2007** [comment]
i take that back! :D

**Comment by oberon2007** [comment]
but i cannot get it more transparent than that! ;)

**Comment by oberon2007** [comment]
Confirm that transparency is fixed for me with the Arch 1.10.0-2 package. The old offset values however still have different effect than before - will open a new issue for that.

**Comment by oberon2007** [comment]
My bad! In fact ${alignr 50} is working correctly now in 1.10 while it had been ignored in 1.9 and that's the reason why my conky looks different now ;)

**Comment by alexbel** [comment]
1.10.0-2 package didn't fix the problem for me.
Kde plasma 5
```
background yes
own_window yes
own_window_type normal
own_window_hints undecorated,below,sticky,skip_taskbar,skip_pager
own_window_argb_visual yes
```

**Comment by oberon2007** [comment]
@alexbel, do you have ```own_window_transparent yes``` somwhere, too?

**Comment by alexbel** [comment]
@oberon2007 I have it in 1.9 config. Transparency doesn't work without it.
In 1.10.0-2 it doesn't have any effect.

**Comment by fguzm** [comment]
double_buffer = false makes it transparent for me

**Comment by chapagain** [comment]
`own_window = false` and `double_buffer = false` worked for me.

> background = true,
> own_window = false,
> own_window_class = 'Conky',
> own_window_type = 'desktop',
> double_buffer = false,

**Comment by Magicloud** [comment]
As of today, on Plasma 5.11. Nothing can get me a transparent window. Set "own_window = false" crashes plasmashell (black desktop) and Conky.

**Comment by santiagobenoit** [comment]
I can confirm this issue running Plasma 5 on the latest Arch Linux. If I set `double_buffer` to no, the black screen goes away but I get the overlapping rendering issue.

**Comment by alexbel** [comment]
`double_buffer` works for me.
Plasma 5.11.4
Arch Linux
Conky 1.10.6_pre
[my config](https://github.com/alexbel/conky/blob/master/configs/base_settings.conf)

**Comment by Pawamoy** [comment]
Tried many combinations of `double_buffer`, `no_buffers`, `own_window`, `own_window_argb_visual`, `own_window_transparent`, `own_window_type` and `xftalpha` but nothing worked, stil have a black, not transparent background.

`conky 1.10.6_pre compiled Tue Dec 19 21:03:36 CET 2017 for Linux 3.16.0-4-amd64 x86_64`

**Comment by JanSurft** [comment]
Hello, you might want to start a composite manager like compton for this to work:

From the conky hp about **own_window_argb_visual**:

> Boolean, use ARGB visual? ARGB can be used for real transparency, note that a composite manager is required for real transparency. This option will not work as desired (in most cases) in conjunction with 'own_window_type override'. 

Check the rest of the configuration details there. http://conky.sourceforge.net/config_settings.html

**Comment by Pawamoy** [comment]
Thanks, I think it worked. I tried with a freshly compiled conky 1.10.8, with the following configuration:
```lua
conky.config={
  double_buffer=true,
  -- own_window_argb_visual=true,
  -- own_window_argb_value=0,
  own_window_class="conky",
  own_window_hints="undecorated,below,skip_taskbar,skip_pager,sticky",
  own_window_transparent=true,
  own_window=true,
  own_window_type="normal"
  -- and the rest...
}
```

I commented out `own_window_arg` options because it does not seem to change anything (though it is still working with).

My compton config has this line set in `~/.config/compton.conf`:
```config
shadow-exclude = [ "i:e:conky", "i:e:xfce4-screenshooter" ];
```

Note how `"i:e:conky"` matches `own_window_class="conky"`.
