### ISSUE TITLE
conky autostart with Xfce

### ISSUE THREAD

**Issue by l0f4r0** [brndnmtthws/conky#933]
**Issue**

In order for conky to start with my DE, I have added a Desktop Entry in ~/.config/autostart/conky.desktop.

Can you please explain to me why "Exec=/usr/bin/conky -c ~/.conkyrc -p 30" doesn't work and why I need instead to have "Exec=sh -c '/usr/bin/conky -c ~/.conkyrc -p 30'"?

Thanks in advance :)

**Information**

I have Debian 10 (kernel 5.4.8-1~bpo10+1), Xfce 4.12.5 and conky 1.10.8.

**Comment by lasers** [comment]
I assume `sh` is required to convert `~/.conkyrc` to a full path.

**Comment by l0f4r0** [comment]
@lasers indeed, thank you very much!
I'm closing this thread :)
