### ISSUE TITLE
[Documentation/FAQ] Add how to use a comment

### ISSUE THREAD

**Issue by rubyFeedback** [brndnmtthws/conky#936]
Hey guys,

I have found conky many years ago. Was great back then.

There were lots of changes in conky and after not using it for quite a
while, I decided to start de-novo, aka from scratch, and create a
new config file; I assume this is lua format,

But anyway, would it be possible to simply add to the FAQ how
to add a new comment? I first tried '#' and '//' without the ' quotes
and these don't work - I have not tried a lua comment but I think
it will work. I just added this here so that other people coming to
conky may have a slightly easier time. Thanks. :)

**Comment by lasers** [comment]
https://github.com/brndnmtthws/conky/wiki/Configurations#110-and-later-versions :wink:
