### ISSUE TITLE
[Documentation/FAQ] Available colours + format?

### ISSUE THREAD

**Issue by rubyFeedback** [brndnmtthws/conky#937]
Another documentation requestion - I am currently modifying my conkyrc
and I am trying to adapt to available colours.

Would it be possible to list which colours we can pick?

E g. I see:

    ${color grey}

But I don't know which colours are all supported. Does it support the html-colours, such as steelblue or royalblue, as well? Can we use RGB formatting and/or hex values too?

It would be great if someone could add this to the FAQ one day.

Thanks for all the nice work - conky is really great. Soon I hope to also call some ruby scripts that do the work that I need, for display in conky (I wonder if we can use update intervals differently, depending on the scripts e. g. some scripts I'd like to run only once per 5 minutes, others in 10 seconds intervals but I digress).

**Comment by SzymonScholz** [comment]
${color #000000} - RGB works.
html colors works but i think not all
