### ISSUE TITLE
make ${time} independent to update interval

### ISSUE THREAD

**Issue by beta-tester** [brndnmtthws/conky#941]
**Issue**

using ${time} and ${utime} is only updated, when a global update interval is triggered.
this is an issue, then you want to have the seconds in the time shown and the update_interval is bigger than 0.5s to reduce the updates to reduce the CPU resources...

it happens, that the shown time is way off the current system time.

**Information**

```lua
conky.config = {
    update_interval = 5,
};

conky.text = [[
${time %F %X}
]];
```

**Comment by beta-tester** [comment]
still alive from my side

**Comment by Caellian** [comment]
Conky uses update_interval to redraw all text content.

`time` doesn't update on its own, it's a command we use to query current system time, i.e. conky doesn't get notified time has changed.

In other words, conky can't tell that the seconds value is different and instead updates at a constant rate (update_interval).

If you wish the clock to update every second, set the update_interval to 1s. If you want to display nanoseconds, use a smaller interval - it's impractical (and wasteful) to make conky update according to lowest common denominator of all commands (guessed) change interval.

Closing as wont-fix
