### ISSUE TITLE
Conky does not allign to top right on multi monitor KDE Plasma 5.17.5

### ISSUE THREAD

**Issue by Siggemada** [brndnmtthws/conky#943]
**Issue**
Conky does not allign to top right on multi monitor KDE Plasma 5.17.5.

[Illustrations on this thread.](https://forum.kde.org/viewtopic.php?f=289&t=164218)

**Information**
Conky moves down or sideways when computer wakes up from sleep or when an application changes resolution.

Restarting Conky makes it appear at the correct place.

conky 1.10.8 compiled Wed Feb 28 17:11:42 UTC 2018 for Linux 4.4.0-101-generic x86_64
on KDE Neon 5.17.5

`conky.config = {
        alignment = 'top_right',
        update_interval = 1,
        cpu_avg_samples = 2,
        net_avg_samples = 2,
        out_to_console = false,
        override_utf8_locale = true,
        double_buffer = true,
        no_buffers = true,
        text_buffer_size = 32768,
        imlib_cache_size = 0,
        own_window = true,
        own_window_type = 'normal',
        own_window_argb_visual = true,
        own_window_argb_value = 0,
        own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
        own_window_transparent = yes,
        own_window_class = 'Conky',
        border_inner_margin = 5,
        border_outer_margin = 0,
        xinerama_head = 0,
        gap_x = 0,
        gap_y = 50,
        draw_shades = false,
        draw_outline = false,
        draw_borders = false,
        draw_graph_borders = false,
        use_xft = true,
        font = 'Ubuntu Mono:size=12',
        xftalpha = 0.8,
        uppercase = false,
        default_color = 'white',
        own_window_colour = '#000000',
        minimum_width = 300, minimum_height = 0
};

conky.text = [[
${time %H:%M:%S}${alignr}${time %d-%m-%y}
${voffset -16}${font sans-serif:bold:size=18}${alignc}${time %H:%M}${font}
${voffset 4}${alignc}${time %A %B %d, %Y}
${font}${voffset -4}
${font sans-serif:bold:size=10}SYSTEM ${hr 2}
${font sans-serif:normal:size=8}$sysname $kernel $alignr $machine
Host:$alignr$nodename
Uptime:$alignr$uptime
File System: $alignr${fs_type}
Processes: $alignr ${execi 1000 ps aux | wc -l}

${font sans-serif:bold:size=10}CPU ${hr 2}
${font sans-serif:normal:size=8}${execi 1000 grep model /proc/cpuinfo | cut -d : -f2 | tail -1 | sed 's/\s//'}
${font sans-serif:normal:size=8}${cpugraph cpu1 80,280}
CPU: ${cpu cpu1}% ${cpubar cpu1}

${offset 15}Core 1   ${color ff8300}${cpubar cpu1 6}${color FFFDE2}
${offset 15}Core 2   ${color ff8300}${cpubar cpu2 6}${color FFFDE2}
${offset 15}Core 3   ${color ff8300}${cpubar cpu3 6}${color FFFDE2}
${offset 15}Core 4   ${color ff8300}${cpubar cpu4 6}${color FFFDE2}
${offset 15}Core 5   ${color ff8300}${cpubar cpu5 6}${color FFFDE2}
${offset 15}Core 6   ${color ff8300}${cpubar cpu6 6}${color FFFDE2}
${offset 15}Core 7   ${color ff8300}${cpubar cpu7 6}${color FFFDE2}
${offset 15}Core 8   ${color ff8300}${cpubar cpu8 6}${color FFFDE2}

${font sans-serif:bold:size=10}MEMORY ${hr 2}
${font sans-serif:normal:size=8}RAM $alignc $mem / $memmax $alignr $memperc%
$membar
SWAP $alignc ${swap} / ${swapmax} $alignr ${swapperc}%
${swapbar}

$hr
${color1}Temperatures in Celsius:
${color1}Core 0 temp: ${alignr} ${color} ${execi 60 sensors | grep 'Core 0' | cut -c 8-24}
${color1}Core 1 temp: ${alignr} ${color} ${execi 60 sensors | grep 'Core 1' | cut -c 8-24}
${color1}Core 2 temp: ${alignr} ${color} ${execi 60 sensors | grep 'Core 2' | cut -c 8-24}
${color1}Core 3 temp: ${alignr} ${color} ${execi 60 sensors | grep 'Core 3' | cut -c 8-24}

${color1}GPU                    ${alignr}       ${color} ${execi 60 nvidia-settings -query [gpu:0]/GPUCoreTemp -t}°C
${color1}Graphics card:         ${alignr}       ${color} ${execi 10 nvidia-smi -q -a | grep -Eo 'GTX .+'}
${color1}Fan Speed:             ${alignr}       ${color} ${execi 10 nvidia-smi | grep -Eo '...%.+?W' | awk '{print $1}'}
${color1}GPU temp / max:        ${alignr}       ${color} ${execi 10 nvidia-smi | grep -Eo '...%.+?W' | awk '{print $2}'} / 99°C
${color1}Perf level:            ${alignr}       ${color} ${execi 10 nvidia-smi | grep -Eo '...%.+?W' | awk '{print $3}'}
${color1}Power use / max:       ${alignr}       ${color} ${execi 10 nvidia-smi | grep -Eo '...%.+?W' | awk '{print $4}'} / 120W
$hr

${font sans-serif:bold:size=10}DISK USAGE ${hr 2}
${font sans-serif:normal:size=8}/ $alignc ${fs_used /} / ${fs_size /} $alignr ${fs_used_perc /}%
${fs_bar /}

${font Ubuntu:bold:size=10}NETWORK ${hr 2}
${font sans-serif:normal:size=8}Local IPs:${alignr}External IP:
${execi 1000 ip a | grep inet | grep -vw lo | grep -v inet6 | cut -d \/ -f1 | sed 's/[^0-9\.]*//g'}  ${alignr}${execi 1000  wget -q -O- http://ipecho.net/plain; echo}
${font sans-serif:normal:size=8}Down: ${downspeed eno1}  ${alignr}Up: ${upspeed eno1} 
${color lightgray}${downspeedgraph eno1 80,130 } ${alignr}${upspeedgraph eno1 80,130 }$color
${font sans-serif:bold:size=10}TOP PROCESSES ${hr 2}
${font sans-serif:normal:size=8}Name $alignr PID   CPU%   MEM%${font sans-serif:normal:size=8}
${top name 1} $alignr ${top pid 1} ${top cpu 1}% ${top mem 1}%
${top name 2} $alignr ${top pid 2} ${top cpu 2}% ${top mem 2}%
${top name 3} $alignr ${top pid 3} ${top cpu 3}% ${top mem 3}%
${top name 4} $alignr ${top pid 4} ${top cpu 4}% ${top mem 4}%
${top name 5} $alignr ${top pid 5} ${top cpu 5}% ${top mem 5}%
${top name 6} $alignr ${top pid 6} ${top cpu 6}% ${top mem 6}%
${top name 7} $alignr ${top pid 7} ${top cpu 7}% ${top mem 7}%
${top name 8} $alignr ${top pid 8} ${top cpu 8}% ${top mem 8}%
${top name 9} $alignr ${top pid 9} ${top cpu 9}% ${top mem 9}%
${top name 10} $alignr ${top pid 10} ${top cpu 10}% ${top mem 10}%
]];
`

**Comment by SzymonScholz** [comment]
This version of conky was released on Feb 7, 2018. It's 2y old.

Can you use not an outdated one?

**Comment by Siggemada** [comment]
Uninstalled maintainerts "conky-all" and installed appimage as instructed by this git page.

The problem remains the same.

~/Applications$ ./conky-x86_64_e157688b1d59dd57d0a2f27a53bfead1.AppImage --version
conky 1.11.5 compiled Tue Aug 13 23:50:04 UTC 2019 for Linux 4.15.0-1028-gcp x86_64

Compiled in features:

System config file: /etc/conky/conky.conf
Package library path: /usr/lib/conky


 General:
  * math
  * hddtemp
  * portmon
  * IPv6
  * Curl
  * Weather (METAR)
  * support for IBM/Lenovo notebooks
  * builtin default configuration
  * old configuration syntax
  * Imlib2
  * OSS mixer support
  * apcupsd
  * iostats
  * ncurses
  * Internationalization support
 X11:
  * Xdamage extension
  * Xinerama extension (virtual display)
  * Xshape extension (click through)
  * XDBE (double buffer extension)
  * Xft
  * ARGB visual
  * Own window

 Music detection:
  * CMUS
  * MPD
  * MOC

 Default values:
  * Netdevice: eno1
  * Local configfile: $HOME/.conkyrc
  * Localedir: /usr/share/locale
  * Maximum netdevices: 256
  * Maximum text size: 16384
  * Size text buffer: 256
