### ISSUE TITLE
Character encoding for time format

### ISSUE THREAD

**Issue by luv4bytes** [brndnmtthws/conky#950]
**Issue**

The month part of the time information displayed by the following line seems to expect another encoding. There should be an "ä" (U+00E4) instead.

The line in my ".conkyrc" file:
"${font Verdana:style=Bold:size=16}${color #009bf9}${alignc}${time %a %d. %b %k:%M}"

**Information**

My locales:
LANG="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"

Picture:
![ConkyEncoding](https://user-images.githubusercontent.com/61706439/76159289-1c9aaa00-611f-11ea-9864-8cf273f23910.png)

**Comment by Roesjka** [comment]
Have you tried date AFAIK for use type date --help in a terminal. time doesn't take variables.
