### ISSUE TITLE
Conky was remove from Debian Testing repo

### ISSUE THREAD

**Issue by kraamis** [brndnmtthws/conky#951]
I can't install or found conky in Debian Testing repository

**Comment by Roesjka** [comment]
Noticed it too. Just download the sid package and install it and then lock the version for the time being.
The one thing I don't understand what the removal has to do with tolua++ package as far as I can see conky doesn't depend on it.
cheers

**Comment by lockywolf** [comment]
Seems to be there: https://packages.debian.org/testing/source/conky

Close?

**Comment by DeeDeeRanged** [comment]
Sorry completely forgot abt. it. For me you can close it, I don't know for kraamis but take it he also has the latest and greatest on Debian :)

**Comment by lockywolf** [comment]
I'm not the owner :). I think that either creator or owner can close issues.
