### ISSUE TITLE
Documentation for conky.conf on Xfce 4.14 (transparency issue)

### ISSUE THREAD

**Issue by dajare** [brndnmtthws/conky#962]
**Issue**

The [documentation for window configuration for Xfce][1] ***appears*** to be out-of-date for the latest version of Xfce. The docs here currently instruct users to include this line in the configuration file:

 ```lua
conky.config = {
    -- snip
    own_window_transparent = false, 
    -- snip
}
```

For [some users on Xfce 4.14][2], there is a non-transparent, black screen problem that I also encountered. After doing a LOT of testing, searching, and checking something caught my eye so that I tried:

```lua
    own_window_transparent = true,
```

and (w00t!) success! The transparency settings now work. **Does the documentation need to be updated?**

**Information**

I'm running Mint 19.3, Xfce 4.14.1, AMD RC410M, X11/X.Org 1.20.5. My [working conky.conf file is saved as a gist][g], if that's of any interest.

[1]: https://github.com/brndnmtthws/conky/wiki/Window-Configuration#cinnamon-xfce
[2]: https://forum.xfce.org/viewtopic.php?id=13723
[g]: https://gist.github.com/dajare/e021605486ee074d2eda7af0349bded7

**Comment by lockywolf** [comment]
I wish I could upvote this. conky-xfce needs some love.

I wish it would be possible to make conky work with 
```
own_window = false
```
but this is not really usable on xfce 4.12, and using "own_window = true" makes using desktop icons inconvenient.

**Comment by freddii** [comment]
Same problem here.
Not possible to make desktop icons clickable behind conky.
