### ISSUE TITLE
Conky Disapearing on Desktop

### ISSUE THREAD

**Issue by droidus** [brndnmtthws/conky#966]
I am running Arch Linux.  I run "conky", and when I click on the desktop, the dashboard disappears.  But the command is still running in the terminal.  Here is my .conkyrc file:
`# Create own window instead of using desktop (required in nautilus)

own_window yes
#own_window no
own_window_type override
#own_window_type desktop
own_window_transparent yes

own_window_hints undecorated,below,sticky,skip_taskbar,skip_pager
#own_window_hints below,sticky,skip_taskbar,skip_pager

# Use double buffering (reduces flicker, may not work for everyone)

double_buffer yes

# fiddle with window

use_spacer yes

use_xft yes

# Update interval in seconds

update_interval 5

# Minimum size of text area

minimum_size 280 5

# Draw shades?

draw_shades no

# Text stuff

draw_outline no # amplifies text if yes

draw_borders no

# Draw borders around graphs

draw_graph_borders no

uppercase no # set to yes if you want all text to be in uppercase

# Stippled borders?

#stippled_borders 8

# border margins

border_margin 4

# border width

border_width 2

# Default colors and also border colors, 90 == #e5e5e5

default_color white

#default_shade_color white

default_outline_color white

own_window_colour blue

own_window_transparent yes

# Text alignment, other possible values are commented

#alignment top_left

alignment top_right

#alignment bottom_left

#alignment bottom_right

# Gap between borders of screen and text

gap_x 20

gap_y 20

# stuff after 'TEXT' will be formatted on screen

override_utf8_locale yes

xftfont Candera:size=8

xftalpha 0.9

TEXT

${font :size=16}${color 00ffff}${alignc}${time %A, }${color 00ffff}${time %e %B %G}

${color 00ffff}${alignc}${time %H:%M:%S}

${font :size=8}${color }UpTime: ${color }$uptime

${color }Linux:  ${color }$kernel

${offset 30}${color }CPU 1   ${color }${cpu cpu1}%${offset 80}${color }CPU 2   ${color }${cpu cpu2}%

${color }${cpugraph cpu1 20,150 0000ff ff0000}${color }${cpugraph cpu2 20,150 0000ff ff0000}

    

${color }Processes: ${color }$processes       Running:   ${color }$running_processes

${color #FF5555}${top name 1}${alignr}${top pid 1} ${top cpu 1} ${top mem 1}

${color #FFaa55}${top name 2}${alignr}${top pid 2} ${top cpu 2} ${top mem 2}

${color #FFff55}${top name 3}${alignr}${top pid 3} ${top cpu 3} ${top mem 3}

${color #aaFF55}${top name 4}${alignr}${top pid 4} ${top cpu 4} ${top mem 4}

${color #55ff55}${top name 5}${alignr}${top pid 5} ${top cpu 5} ${top mem 5}

${color #55ffdd}${top name 6}${alignr}${top pid 6} ${top cpu 6} ${top mem 6}

${color }MEM: ${font :size=8}$alignc${color }$memperc% $mem/$memmax

${color lightgrey}${membar 5,300}

${font :size=8}${color }SWAP: ${font :size=8}$alignc${color }$swapperc% $swap/$swapmax

${color lightgrey}${swapbar 5,300}

${font :size=8}${color }LINUX: ${font :size=8}$alignc${color }${fs_free_perc /}%  ${fs_free /}/${fs_size /}

${color lightgrey}${fs_bar 5,300 /}

${font :size=8}${color }NET: IP ${color }${alignc}${addr wlan0}${color }

${offset 30}${color}Up:  ${color }${upspeed wlan0}k/s${offset 80}${color}Down:  ${color }${downspeed wlan0}k/s${color}

${color }${upspeedgraph wlan0 20,150 0000ff ff0000}${color }${downspeedgraph wlan0 20,150 0000ff ff0000}

`

**Comment by HoLLy-HaCKeR** [comment]
I have the same issue on both Manjaro XFCE and Manjaro KDE, using the default config. Enabling double buffering doesn't seem to fix it.

**Comment by MichielJ1998** [comment]
What happens if you use `own_window_type = desktop` instead of `own_window_type = override`? Normally this should pin your conky widget on the desktop. This works in my Ubuntu 20.04, I am not familiar with conky on Arch.

**Comment by HoLLy-HaCKeR** [comment]
That seems to fix it on Xfce, although it breaks transparency. Haven't tested on KDE but I assume it would work there as well.

**Comment by HoLLy-HaCKeR** [comment]
The default was already `desktop`, but changing it to `override` did fix it. This broke transparency, though.

**Comment by MichielJ1998** [comment]
Does using the `normal` window type fix it?

**Comment by HoLLy-HaCKeR** [comment]
`normal` works but shows it as a window which is rather inconvenient and requires some hacks to work as well as `override` and `desktop` would. Copying your transparency settings doesn't fix `override`'s transparency behavior.

However, I tried `dock` and `panel` as window_type and that did seem to work, but then it draws over all other windows, which is pretty inconvenient :)

**Comment by plikhari** [comment]
There was a time when on XFCE  - **override** was the way to go...
This is how things will work
```
	own_window = true,
	own_window_transparent = true,
	own_window_type = 'normal',
	own_window_class = 'conky-semi',
	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

	own_window_argb_visual = true,
	-- own_window_argb_value = 255,
```

**Comment by HoLLy-HaCKeR** [comment]
That does seem to fix it pretty well, I haven't found a flaw with it yet!

**Comment by plikhari** [comment]
@HoLLy-HaCKeR 
That is great news

@droidus 
kindly marked this as solved if this solves your issue - thanks
