### ISSUE TITLE
[SOLVED] Can't get Conky "Image" to display Audacious cover art

### ISSUE THREAD

**Issue by rizlaw** [brndnmtthws/conky#971]
I don't see any similar report of this particular issue.
I am using Ubuntu 20.04LTS. Audacious 3.10.1 (Ubuntu repo) and Conky 1.10.8 (Ubuntu repo).
I can't seem to get Conky to display the Audacious cover art jpg file for the currently playing song track with the following code:
`${image ~/tmp/audacious-temp-xxxxxx -p 0,0 -s 85x85}`

Audacious puts the current cover art file in the **/tmp** folder and gives it the name **"audacious-temp-xxxxxx**" without a "jpg" extension (The "xxxxxx" part of the filename is actually six random alphanumeric characters). With each Album/song change, the only part of the filename that changes are the last six places shown by "xxxxxx". The last six places in the filename are random combinations of letters and numbers, i.e., "JDEBL0".  In addition, the filename does **not** show a "jpg" extension in the Nautilus file manager, but the properties of the file are listed as "jpeg". Adding "jpg" to the filename does not change the result that Conky won't display an image. The result of this behavior is that I can't get the current Audacious cover art image to display in Conky. I believe this is due to the fact that the filename is always changing and possibly also the missing "jpg" extension. As far as I can tell, Conky doesn't permit using wildcard characters to address the problem:
${image ~/tmp/audacious-temp-?????? -p 0,0 -s 85x85}
${image ~/tmp/audacious-temp-* -p 0,0 -s 85x85}
${image ~/tmp/audacious-temp-??????.jpg -p 0,0 -s 85x85}

I have no problem with displaying Quodlibet cover art since Quodlibet's temp cover art file is always the same name with a "jpg" extension.

Any ideas how to overcome this problem? BTW, I'm not a programmer so any suggestions will have to be simple, clear and straightforward. Thanks.

**Comment by kushraj** [comment]
Is there any way you can launch a custom script everytime on a song change ?
( I think there is a plugin called "Song Change" )
In the script copy the current cover file to another for conky (Original might still be in use )
`cp /tmp/audacious-temp* /tmp/cover.png`
and use that file for conky reference

**Comment by rizlaw** [comment]
> Is there any way you can launch a custom script everytime on a song change ?
> ( I think there is a plugin called "Song Change" )
> In the script copy the current cover file to another for conky (Original might still be in use )
> `cp /tmp/audacious-temp* /tmp/cover.png`
> and use that file for conky reference

**kushraj,** thanks for the help. After a little experimenting your suggestion worked. For anyone else who may be interested, here is what I did:
1. Opened Audacious and selected "Settings > Plugins > Song Change > Settings
2. In first box "Command to run when starting a new song" entered:
`cp /tmp/audacious-temp* /tmp/audacious-cover.jpg`

3. In next box "Command to run at end of song" entered: **%n**
4. Save and exit. Recheck "Song Change" plugin (not sure why original check mark disappears when you make changes in the plugin).
5. Add the following line of code in your Conky Audacious template:
`${image /tmp/audacious-cover.jpg -p 0,0 -s 120x120 -n}`
You will need to make adjustment to the image command for your particular cover art size and location. BTW, if you omit the **-n** in the above code, the cover art will not change with each song change.

Hope this helps the next person who may have the same problem.

**Comment by plikhari** [comment]
Please mark this solved if you have resolved your issue - thanks

**Comment by 54freebird** [comment]
This seems to work quite well - except that frequently the image file is NOT showing up in /tmp. Anyone know what triggers (or not) the image to show up? Still using 'C' code to backtrack the song path for 'folder.jpg' to get it into conky...

**Comment by kushraj** [comment]
I don't know how audacious works , but this issue could be because of extra time it might have been taking to download the file into tmp folder.
Try adding a slight delay before cp command 
`sleep 1 && cp /tmp....as before`

**Comment by rizlaw** [comment]
In regard to **54freebird's** observation that "the image file is NOT showing up in /tmp, I don't have an answer, but I believe it's a bug in Audacious.

I noticed this problem too, so I ran Audacious with its own internal **Cover Art Plugin**. The Audacious Cover Art Plugin works 100% of the time with ALL of my audio library's cover art jpegs and png files.

As a test I simultaneously started Audacious playing random tracks and then:

1. opened and ran the Audacious Cover Art Plugin;
2. I also opened Nautilus to the **/tmp** folder and monitored it;
3. I opened a second instance of Nautilus to my **/home/audacious-cover** folder where I copy the **/tmp/audacious-cover.xxxxxx** renamed to **audacious-cover.jpg**; also
3. I ran and monitored my desktop Conky script for realtime display of Audacious' cover art.

So I had 4 places to see what was happening. What I observed was that every once in a while the Audacious Cover Art Plugin would display the right coverart but the Audacious-Conky script would display NOTHING on the same playing song. Additionally, and simultaneously, I observed that when this happened, Audacious DID NOT write a cover art file in the **/tmp** folder. (This would be the normal expected thing for Audacious to do, notwithstanding the format of the file generated by Audacious would be something like **"audacious-cover.1Rst68"** which,  as previously mentioned above, is useless for Conky's "image" variable format. Furthermore, the fact that Audacious DIDN'T write a cover art file to **/tmp** explains why Conky wasn't displaying a cover art image.

Without the **audacious-cover.xxxxxx** file in  **/tmp** there is no way that the copy command entered into Audacious' **Song Change** plugin can work its magic. That's why **kushraj's** recommendation fails to work 100% of the time.

**Comment by rizlaw** [comment]
I just discovered a hidden feature in the Audacious "Cover Art Plugin" that may go a long way to, at least, temporarily solve the cover art problem with Audacious in Conky scripts. It works in Ubuntu 20.04 LTS, but I don't know about any other distros. The feature I'm referring to is not documented anywhere I can find, so here's how to do it:

1. Activate the Audacious Album Art Plugin: **Settings > Plugins > General > Album Art**
2. On your desktop you should now see the "Album Art" plugin which is a moveable window. 
3. Start Audacious playing a song, then move, resize and position the window to your liking. (I leave a blank area in my Conky script for the Album Art plugin to fit perfectly.)
4. **Right click** on the title bar and select **"always visible on all desktops"** (if that's what you need).
5. Now the important part: **MIDDLE CLICK once** on the Album Art title bar. You should notice that the cover art image slightly enlarges. Now, **left click on the title bar and hold the left mouse button down and drag the title bar away from the cover art image**.  Place the title bar somewhere, out of the way on your desk top. You will now have a full sized cover art window locked to the position where you placed it when you middle clicked. Assuming you don't close the Album Art window, every time you close Audacious and restart it, the Album Art window should re-open exactly where you left it.
By the way you can do the same thing with the Audacious **VU Meter" plugin.

**Comment by 54freebird** [comment]
I don't know that this is any kind of a bug. For instance - what if the /tmp file entry is triggered by the absence of folder.jpg 'beside' the song file? It would certainly explain why it rarely works for me - as I have made an effort to ensure that folder.jpg is ALWAYS there :) I have left an enquiry over at Audacious, no info on the reason for it yet.

**Comment by rizlaw** [comment]
> I don't know that this is any kind of a bug. For instance - what if the /tmp file entry is triggered by the absence of folder.jpg 'beside' the song file? It would certainly explain why it rarely works for me - as I have made an effort to ensure that folder.jpg is ALWAYS there :) I have left an enquiry over at Audacious, no info on the reason for it yet.

I saw your post over on the Audacious forum. I certainly know nothing about programming but, in my particular case, the **cover art** is embedded in each and every music track as well as a separate **cover.jpg** file in each album's folder/directory. (All of my music is full albums). So, in my case, Audacious should have no issues in writing the **audacious-cover.xxxxxx** file to /tmp **every** time. Audacious certainly works 100% of the time with it's own **Album Art** plugin feature.
The only other thing that might cause this problem (a wild guess on my part) is that some of my cover art files are in **png** format or converted from PNG to JPG, AND some are very hirez images which have very large file sizes in the range of over 250KB and some even 1MB. I wonder if this could cause the problem?
Anyway, I hope you get an answer or fix from the Audacious programers.
Of course, the best answer would be for them to add an additional command in Conky for **cover art** like **${audacious_cover_image  -p 0,0 -s 120x120 -n}** ,just as they did for the Audacious progress bar **${audacious_bar 10, 100}**.
