### ISSUE TITLE
${if_updatenr} requires at least 4 update cycles?

### ISSUE THREAD

**Issue by Galicarnax** [brndnmtthws/conky#974]
**Issue**

I was going to implement mail notification with text blinking in conky. I would expect this to work as intended, using 1-second update interval:
```
${if_updatenr 1}Hello${endif}${if_updatenr 2}${endif}
```
However, the blink is not correct - text is displayed for 1 sec, and then is missing for ~3 seconds. If, instead, I do this:
```
${if_updatenr 1}Hello${endif}${if_updatenr 2}${endif}${if_updatenr 3}Hello${endif}${if_updatenr 4}${endif}
```
then text blinks uniformly in time, as expected.

This happens even if no other things are present in conky's `TEXT`. I did not find any limitations on `if_updatenr` in the documentation. So why doesn't it work properly with two-cycle version?

**Comment by bi4k8** [comment]
I wasn't able to reproduce this--the below `.conkyrc` blinks on and off evenly once per second for me:
```
conky.config = { 
    out_to_wayland = true, 
    alignment = 'middle_middle', 
    own_window_argb_value = 0, 
    own_window = false,
    default_shade_color = 'grey', 
    draw_shades = true, 
    font = 'Mono:size=13', 
    update_interval = 1,
    default_color = '#ffffff',
} 
 
conky.text = [[ 
${if_updatenr 1}Hello${endif}${if_updatenr 2}${endif}
]]
```
