### ISSUE TITLE
own_window_argb_visual missing from at least conkyrc.vim

### ISSUE THREAD

**Issue by genes1122** [brndnmtthws/conky#975]
**Issue**

The list "syn keyword ConkyrcVarName" in /usr/share/vim/site/syntax/conkyrc.vim doesn't contain own_window_argb_visual, so it is not highlighted in ~/.conkyrc.  My current work around is having it in ~/.vim/syntax/conkyrc.vim. 

**Information**

This is in openSUSE Tumbleweed.

**Comment by su8** [comment]
Can u send a pull requést seat air ?

**Comment by genes1122** [comment]
I'm not sure what to put in it.  Should I just copy this issue to the pull request tab?

Gene

**Comment by genes1122** [comment]
I would make a pull request, but I don't know how to make one.  Can't someone just add the change I requested in my original post?

Thanks,
Gene
