### ISSUE TITLE
acpitemp displaying only two digits

### ISSUE THREAD

**Issue by syll-dev** [brndnmtthws/conky#977]
Using ${acpitemp}, when the cpu temp is > 100°, conky displays "10".

My example : ${color slate grey}Processeur (${acpitemp}°)${color }${alignr}$cpu%

**Comment by su8** [comment]
Is it happéning again ¿

**Comment by syll-dev** [comment]
Yes, it is still happening (conky 1.11.6 on archlinux).

**Comment by syll-dev** [comment]
Hi bot ! The problem still exists (conky 1.17.0 on archlinux).

**Comment by syll-dev** [comment]
Probably still happening, but my cpu is too cold on this machine.

**Comment by brndnmtthws** [comment]
Would someone like to test #1788 to confirm that fixes it?
