### ISSUE TITLE
Can't drawn varying length and width horizontal lines (FEATURE REQUEST)

### ISSUE THREAD

**Issue by rizlaw** [brndnmtthws/conky#978]
Conky has no variable command to draw solid horizontal lines of varying length and width.

The **$hr** variable draws a horizontal line of varying thickness, but with no ability to limit it length. The **$execbar** variable can do the job, but I'm not sure if it impacts cpu cycles to have a command like ${execbar 2,1050} draw a horizontal line which doesn't do anything else (like show the progress of something).

Perhaps there is a simple way to do this, that's not immediately obvious to me. If so, I'd appreciate the help in pointing out how to do it without additional programming.

**Comment by 54freebird** [comment]
This is easily worked around with a little subterfuge :) I have a few little .png files in a pix subdirectory off my conky storage location. They tend to be about 2x100 pixels (or 100x2) with a definite colour, and are named vl-w.png (for white) vl-y.png (for yellow) etc, along with hl-y.png. The ${image} capability can resize them as required (say 1x400) as well as place them precisely when and where you want them. Oh - the hl=horizontal line and vl=vertical line :)
Here's a screenshot link to give you an idea of one possible use:
https://drive.google.com/file/d/1gzgy_4sxYhLC9m3WLH7intZ6y4TTVSrp/view?usp=sharing
It's somewhat overdone (experimental - setup not kept) but clearly shows the possibilities.

**Comment by rizlaw** [comment]
**54freebird**, thanks for the work-around tip and link. Tried it and got it to work, but, I still think adding more capability to conky via modification of the **$hr** variable to add height and length modifiers would be a lot easier.

**Comment by 54freebird** [comment]
I see what you mean - but then you are left without vertical lines... and I have other priorities in mind for conky! Extending the positioning found in the ${image} command to other elements (whether by ${set x,y} or by ${vgoto} doesn't matter, but absolute positioning instead of relative would be HUGE! It can drive you nuts with moving one element causing edits on 20-odd others...

**Comment by A9G-Data-Droid** [comment]
The greybeards had this problem in the days of text. They had blessed us with box art in the extended character set. Alas, these characters are not as easy to use in the Unicode world. You need to ensure that your font has logos in the Unicode numbers for box art.

These work in `${font FreeSerif}`

```
┌─┐
│ │ 
└─┘
```
