### ISSUE TITLE
Links on wiki are broken

### ISSUE THREAD

**Issue by corpix** [brndnmtthws/conky#98]
For example https://github.com/brndnmtthws/conky/wiki/wiki/Command-Line-Options

**Comment by nathanmusoke** [comment]
Also https://github.com/brndnmtthws/conky/wiki/Screenshots, linked to from https://github.com/brndnmtthws/conky/wiki/FAQ#where-did-the-default-conkyrc-go-i-ran-conky-and-looked-in-my-home-directory-and-i-couldnt-find-it.

**Comment by mswanson-me** [comment]
I'll start sorting through these broken links this week.

**Comment by lasers** [comment]
The links here are mostly invalid. The wiki seems to be working okay. Closing now. Thanks. :+1:
