### ISSUE TITLE
[Feature Request] luai (like execi, but for calling lua functions with specific interval)

### ISSUE THREAD

**Issue by mgrotke** [brndnmtthws/conky#980]
**Issue**

It would be nice if we could have a conky command like:

```
# Call MyLuaFunction every 300 seconds
${luai 300 MyLuaFunction arg0 arg1 arg2}
```

Thank you for the wonderful program conky

**Comment by plikhari** [comment]
You really do not need this.

you can count the seconds in many ways - one of them is using the conky update_interval 
```tonumber(conky_parse("${updates}")```

based on the number of ticks you can do what ever you desire.
