### ISSUE TITLE
Question: Is conky a framework that allows me to create widgets?

### ISSUE THREAD

**Issue by Joe23232** [brndnmtthws/conky#981]
I am looking for a framework that allows me to easily create my own widgets for Linux. Is Conky one of them?

If so then can I create the widgets using any language that I please?

**Comment by ernesto1** [comment]
When you say widgets do you mean [something like this](https://i.imgur.com/Wi8KqTy.png)?

**Comment by Joe23232** [comment]
Yeah soemthing like that.

**Comment by ernesto1** [comment]
You can do it with conky but it is not something that is supported right out of the box.  So you  have to get creative.

The screenshot I shared is my own setup.  I mixed the vanilla conky graphs with images I designed on gimp to create the dashboard.

If you know LUA, you can draw your own shapes and create fancier graphs than what vanilla conky provides.

**Comment by philer** [comment]
I made [polycore](https://github.com/philer/polycore) which is a widget library / layout framework. You may be able to learn from that and/or build on top of it.

**Comment by Joe23232** [comment]
I see, can I use Rust to configure polycore?

**Comment by philer** [comment]
It's written in Lua and Lua is the only language integrated with conky. So unless you want to _generate_ Lua code (or do some weird cross compilation) I doubt that's possible.

**Comment by Joe23232** [comment]
Oh ok thanks anyways mate.
