### ISSUE TITLE
Default values for configuration settings

### ISSUE THREAD

**Issue by jidak** [brndnmtthws/conky#982]
What are the default values of Conky's configuration settings please? For example, default border_width; default cpu_avg_samples etc.

I cannot find this information in the man page.

Thank you

**Comment by ernesto1** [comment]
If you run the command `conky -C` it should print the default configuration file it is using.

I'm running version `1.11.6_pre` on fedora 31 and the `-C` option is deprecated.
Instead if you run `conky -v` you will get a print of the details behind your conky setup, one of the items shown is the default config file it is using

```
[ernesto@strike ~]$ conky -v
conky 1.11.6_pre compiled Tue Jul 28 07:44:30 UTC 2020 for Linux 5.6.15-300.fc32.x86_64 x86_64

Compiled in features:

System config file: /etc/conky/conky.conf    << THE FILE
Package library path: /usr/lib64/conky


 General:
  * math
  * hddtemp
```
