### ISSUE TITLE
Lua library not found

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [brndnmtthws/conky#987]
**Issue**

`module 'lunajson' not found` though I have installed 'lunajson' (_sic_) via luarocks and my Lua script that uses that library runs fine within the Lua interpreter (i.e. when it is run not via Conky).

**Information**

Linux Mint 20 Cinnamon.
Conky 1.11.6_pre (compiled from source).

Cf. issue #705?

**Comment by Ritace** [comment]
Hey there did you find a solution? I was running into the same issue.

**Comment by LinuxOnTheDesktop** [comment]
I did, eventually!

I had to use my distro's package manage to install a package called 'lua-json' - thusly:

`sudo apt install lua-json`

Then in my lua file I had to do the following.

`local jsonOrWhateverYouWantToCallIt = require ( 'json' )`
