### ISSUE TITLE
Kernel 5.7.12 - conky and conky-git not working anymore

### ISSUE THREAD

**Issue by IvoAndonov** [brndnmtthws/conky#991]
**Issue**
Today kernel 5.7.12 arrived and conky isn't starting anymore. In the last few months I was using conky-git and it was working fine. I even tried package conky (without -git in the name) but it won't start either.

**Information**

OS: Arch Linux
Conky-git version: 1.11.5.r10.g26d23cb7-1

Here's a system info, though I doubt it would do any good.

$ sysinfo
 OS: Arch Linux 
 Kernel: x86_64 Linux 5.7.12-arch1-1
 Uptime: 10m
 Packages: 1164
 Shell: bash
 Resolution: 1920x1080
 DE: Cinnamon 4.6.6
 WM: Muffin
 WM Theme: Mint-Y-Brownish-v4.3_for-Cinnamon_by-Valso (Cinnamox-Rhino)
 GTK Theme: Mint-Y-Brownish-v4.3_for-Cinnamon_by-Valso [GTK2/3]
 Icon Theme: Humanity-Dark
 Font: Noto Sans Bold 10
 Disk: 840G / 1,5T (59%)
 CPU: Intel Core i7-4770 @ 8x 3.9GHz [39.0°C]
 GPU: GeForce GTX 1050 Ti
 RAM: 1564MiB / 32034MiB

**Comment by wright-p** [comment]
After updating my arch system today conky stopped starting, so I tried starting it from a terminal window, and it complained about not being able to find a `lua` shared object -- maybe the update to arch's `lua` package is the problem here.

I use my own PKGBUILD that builds from source and recompiling seems to have fixed it for me.

**Comment by palanthis** [comment]
I ran into this issue on Arch, too. I pulled and installed a  previous build of Conky and then it changed from complaining about unexpected symbol to complaining about a Lua library. I checked it on OpenSUSE Tumbleweed and the problem exists there, too; So it's not an Arch issue.
Arch Details
Kernel: 5.7.12-arch1-1
Conky: 1.11.5-4
Lua: 5.4.0-2

OpenSUSE Details
Kernel: 5.7.11-1-default
Conky: 1.11.6-8.5
Lua: 5.1.5-15.6

**Comment by plikhari** [comment]
I would leave lua as ignore in your package manager config and stay with lua 5.3 till we have a solution. There is not going to be a tearing hurry in the industry to jump on the new 5.4  bandwagon.  A simple rebuild with new version may work but then it may not ...

conky for one needs so many things sorted - versions after 1.11.3 are not usable anyways !!!

It would be better those are sorted first ...

**Comment by IvoAndonov** [comment]
> I would leave lua as ignore in your package manager config and stay with lua 5.3 till we have a solution. There is not going to be a tearing hurry in the industry to jump on the new 5.4 bandwagon. A simple rebuild with new version may work but then it may not ...
> 
> conky for one needs so many things sorted - versions after 1.11.3 are not usable anyways !!!
> 
> It would be better those are sorted first ...

The downgrade package only shows versions from 5.3.5 and conky is looking probably for 5.3.0. So downgrading lua didn't work.

**Comment by AlexanderCurl** [comment]
Just install lua53 from the package repository, and done.
https://aur.archlinux.org/packages/conky-git#comment-759860

**Comment by palanthis** [comment]
Slapping together a custom set of versions is great for one or two users who go to the trouble of searching and finding this GH issue page. However, I would propose that getting Conky back into a working state with up-to-date dependencies, so that anyone using the above mentioned distros can also use it, would be a good thing.

**Comment by plikhari** [comment]
OK Here is the solution - simply install lua 5.4 and then recompile conky and install - I recompiled conky to 1.11.3 and it works like a charm.

conky performs as before... fantastic

**Comment by brndnmtthws** [comment]
Pinging @anthraxx

**Comment by Strykar** [comment]
I use Arch's community [conky](https://www.archlinux.org/packages/extra/x86_64/conky/) package, which is working fine after the [conky-nv-lua](https://aur.archlinux.org/packages/conky-lua-nv/) update.
Is a rebuild of `conky-git` all that is required, I'm unclear what the issue with `conky-git` is that doesn't affect the community package on Arch?

**Comment by oxhak** [comment]
none of the solutions here are fixing this issue, reinstalled conky, recompilied conky-git, conky cairo with or without lua53, same results.. 

> OK Here is the solution - simply install lua 5.4 and then recompile conky and install - I recompiled conky to 1.11.3 and it works like a charm.
> 

nope...

oxhak~: conky -c ~/.conky/statusbar2
conky: Syntax error (/home/oxhak/.conky/statusbar2:2: syntax error near 'no') while reading config file. 
conky: Assuming it's in old syntax and attempting conversion.
conky: [string "..."]:159: attempt to call a nil value (global 'loadstring')

**Comment by wright-p** [comment]
> None of the solutions above are fixing this issue, reinstalled conky, recompiled conky-git, conky-cairo, conky-nv-lua with or without lua53, same results..
> 
> oxhak~: conky -c ~/.conky/statusbar2
> conky: Syntax error (/home/oxhak/.conky/statusbar2:2: syntax error near 'no') while reading config file.
> conky: Assuming it's in old syntax and attempting conversion.
> conky: [string "..."]:159: attempt to call a nil value (global 'loadstring')

These seem to be config file issues.

`loadstring` has been deprecated in lua since version 5.2, it looks like they finally removed compatibility in 5.4.

**Comment by oxhak** [comment]
Just tried with the AppImage, works fine with a default config file, maybe I should try to rewrite my config.

**Comment by telmotrooper** [comment]
I'm on Arch and none of my configs work, but the default configuration (running command `conky` without params) works normally.

**Comment by telmotrooper** [comment]
Okay, this is what worked for me, download this script (https://github.com/brndnmtthws/conky/blob/master/extras/convert.lua), make it executable with `chmod +x convert.lua` and then run it against your configs, e.g. `./convert.lua system_info`, then your configs should work fine on Arch with updated `lua` and `conky`.

**Comment by plikhari** [comment]
If you are migrating to conky 1.10.x from an older versions - you will need to fine-tune  conky config after using convert.lua.

I have done evrything - install git, version in-between and it all works - you just need to install LUA 5.4 and then compile/build conky again. Arch Linux has AUR where you have various packages from users of Arch Linux - one of my packages is [conky-cairo](https://aur.archlinux.org/packages/conky-cairo/) - you may edit the PKGBUILD to any version you desire.

Please feel free to view/edit the PKGBUILD file. It works.

![Screenshot_2020-08-08_09-15-36](https://user-images.githubusercontent.com/14849928/89702163-a911f880-d95b-11ea-93e0-62452aacc06a.png)

**Comment by oxhak** [comment]
> Okay, **this is what worked for me on Arch**: download this script (https://github.com/brndnmtthws/conky/blob/master/extras/convert.lua), make it executable with `chmod +x convert.lua` and then run it against your configs, e.g. `./convert.lua system_info`, then your configs should work fine with updated `lua` and `conky` packages.
> 

Indeed I had tried this but I had made a mistake in the command and it gave me an error, I tried again this morning and now my configuration is correctly converted and everything works as before with the conky on Archlinux package. Thanks everyone.
