### ISSUE TITLE
how to show a conky over the top panel ubuntu 20.04

### ISSUE THREAD

**Issue by ochornolutskyi** [brndnmtthws/conky#993]
hello, sorry for my Ukrainian English. I have an ubuntu 20.04 with gnome. and my conky is minimalistic. but I have trouble with showing it on ubuntu panel, the conky is under the panel opacity and it is not readable. if ubuntu panel is transparent, the conky text has normal colour. so, I want to always show the normal colour of conky text. how I can find the way to fix it with the config? Or it has only one way of fixing with a gtk panel transparency? thank you

![1](https://user-images.githubusercontent.com/46054029/90267346-12af6c80-de5e-11ea-803b-c8875bb793b5.png)
![2](https://user-images.githubusercontent.com/46054029/90267350-15aa5d00-de5e-11ea-9fab-ff3d0d3c4d73.png)

**Comment by plikhari** [comment]
Yes with GTK panel transparency
