### ISSUE TITLE
[FreeBSD] lua conky_parse('${cpu}') gives different value than conky.text = [[${cpu}]]

### ISSUE THREAD

**Issue by madpilot78** [brndnmtthws/conky#996]
**Issue**

While experimenting with lua cairo bindings I tried making a graphic gauge for the cpu. I discovered, as reported in the subject, that `${cpu}` behaves different in lua than in the text section.

**Information**

This is happening On FreeBSD head with conky 1.11.6. I also found a report from another user for this issue here:

https://forums.freebsd.org/threads/problem-with-conky-and-lua-script.62763/

Changing the `cpu_avg_samples` value makes no difference.

Here is a minimal configuration showing the issue:

```lua
conky.config = {
    update_interval = 1,
    own_window = true,
    own_window_type = "normal",
    lua_load = "main.lua",
    lua_draw_hook_post = "main"
}

conky.text = [[
${cpu}
]]
```

This is the minimal lua script:

```lua
function conky_main ()
    if conky_window == nil then
        return
    end

    local cpu_perc = conky_parse('${cpu}')
    print(cpu_perc)
end
```

As you can see the values printed don't match. The lua printed value looks much more jumpy, and sometimes very random.

**Comment by madpilot78** [comment]
I will try to find some time to explore this issue, but I don't know conky internals, I'm not sure where to start looking. If someone could point me where in the source code the cpu load data is gathered and returned to the front end it would help me a lot investigate things.

Thanks in advance!

**Comment by tflori** [comment]
Intresting I just found out that on 1.11.5-2 (Arch) I get strange values from `conky_parse('${cpu cpu[1-16]}')` from time to time...
Sometimes it is always 0 - sometimes it is 178 - sometimes the value changes after some seconds to a more believable value - sometimes not...

I'm back to 1.11.3

**Comment by madpilot78** [comment]
Regarding this I took a look but I wasn't able to find my way in the source code myself.

If someone would point me at the right piece of code to look at, where the lua backend gets its data from, I could try again from there.

**Comment by madpilot78** [comment]
I just tested this one again.

The two values (the one in conky output and the one I get via lua) still don't match.

Only difference is now the value I get in lua is always 0.
